### ISSUE TITLE
Left sidebar?

### ISSUE THREAD

**Issue by r3df** [roots/sage#101]
Was wondering if there has been any consideration to having a left-sidebar for a 3-column layout?

**Comment by UnaOmnia** [comment]
For left sidebar, if you are using WordPress, just use PHP conditional statement, to actually rearrange the main and aside elements. As in:

Make a template called page-leftsidebar.php, and just copy what is in custom-template.php and change the template name to Left Sidebar Template etc. 

Then do a conditional statement like:
if(is_page_template('page-leftsidebar.php')){
<aside>etc</aside>
<main>etc</main>
} elseif( /** pick a condition **/ ){
// whatever you want
} else { // the default AKA right sidebar or full width templates, depending on your config.php settings
<main>etc</main>
<aside>etc</aside>
}
