### ISSUE TITLE
Header & Footer deprecated notice on Multisite

### ISSUE THREAD

**Issue by khromov** [roots/sage#1052]
Roots is not compatible with the signup page on:
site.com/wp-signup.php

The errors are:
```
Notice: Theme without header.php is deprecated since version 3.0 with no alternative available. Please include a header.php template in your theme. in /var/www/html/site/trunk/wp-includes/functions.php on line 3136
```

```
Notice: Theme without footer.php is deprecated since version 3.0 with no alternative available. Please include a footer.php template in your theme. in /var/www/html/site/trunk/wp-includes/functions.php on line 3136
```

I believe wp-signup.php works in its own mysterious ways and probably directly calls the header and footer templates. What can we do about this, because as of now the theme is not possible to use on a MultiSite because header and footer are not printed.

**Comment by retlehs** [comment]
also related: http://discourse.roots.io/t/search-filter-plugin-with-roots/2757

@Foxaii recently mentioned:

> maybe we should get the wrapper to include a logic file first.
> i.e a template devoid of any output, which will then load the wrapper, but can be used to setup functions specific to that template

**Comment by chrisSowerby** [comment]
I also have this problem when registering users using gravity forms +  gravity forms user registration.
After user activates by clicking link in email it takes them to a confirmation page on the site with 
Notice: Theme without header.php is deprecated since version 3.0 with no alternative available. Please include a header.php template in your theme. in /var/www/vhosts/price4me.co.uk/httpdocs/site/wp-includes/functions.php on line 3450

and same for footer

**Comment by QWp6t** [comment]
There's no way around it. `wp-signup.php` always calls `get_header()` directly.

```php
function get_header( $name = null ) {
	/**
	 * Fires before the header template file is loaded.
	 *
	 * The hook allows a specific header template file to be used in place of the
	 * default header template file. If your file is called header-new.php,
	 * you would specify the filename in the hook as get_header( 'new' ).
	 *
	 * @since 2.1.0
	 * @since 2.8.0 $name parameter added.
	 *
	 * @param string $name Name of the specific header file to use.
	 */
	do_action( 'get_header', $name );

	$templates = array();
	$name = (string) $name;
	if ( '' !== $name )
		$templates[] = "header-{$name}.php";

	$templates[] = 'header.php';

	// Backward compat code will be removed in a future release
	if ('' == locate_template($templates, true))
		load_template( ABSPATH . WPINC . '/theme-compat/header.php');
}
```

There's no way to hook into that to direct it to the correct file.

You'll have to add `header.php` and `footer.php` to avoid this warning.

**Comment by chrillep** [comment]
so basicly 

**header.php**
```
<?php
include('templates/head.php');
include('templates/header.php');
?>
```
**footer.php**
```
<?php
include('templates/footer.php');
?>
```

**Comment by chrisSowerby** [comment]
your the man.

**Comment by strarsis** [comment]
@chrillep: Just encountered the same issue in sage9. I added `header.php` and `footer.php` to theme root - but the message still appears. I also tried it with `header.php` and `footer.php` in `resources/views/` instead - which also doesn't help.

**Comment by greatislander** [comment]
[This](https://github.com/roots/sage/compare/master...greatislander:multisite-support) works. The files need to be in `/resources` so that they're at the same hierarchy as `index.php` and `functions.php`:

```
└── resources
    ├── footer.php
    ├── functions.php
    ├── header.php
    ├── index.php
    ├── screenshot.png
    └── style.css
```

**Comment by strarsis** [comment]
@greatislander: It works now! However, now the body classes are all missing, like .woocommerce and taxonomy slug - the styles don't apply anymore.
