### ISSUE TITLE
Error locating

### ISSUE THREAD

**Issue by alexandrule** [roots/sage#1133]
I did an installation how is written in Documentation, but I receive this error:

<code>
2014/08/20 13:51:08 [error] 24767#0: *54 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Error locating lib/utils.php for inclusion in /home/alex/work/wordpress/wp-content/themes/newtheme/functions.php on line 29" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost"
</code>

functions.php

``` php
<?php
/**
 * Roots includes
 *
 * The $roots_includes array determines the code library included in your theme.
 * Add or remove files to the array as needed. Supports child theme overrides.
 *
 * Please note that missing files will produce a fatal error.
 *
 * @link https://github.com/roots/roots/pull/1042
 */
$roots_includes = array(
  'lib/utils.php',           // Utility functions
  'lib/init.php',            // Initial theme setup and constants
  'lib/wrapper.php',         // Theme wrapper class
  'lib/sidebar.php',         // Sidebar class
  'lib/config.php',          // Configuration
  'lib/activation.php',      // Theme activation
  'lib/titles.php',          // Page titles
  'lib/nav.php',             // Custom nav modifications
  'lib/gallery.php',         // Custom [gallery] modifications
  'lib/comments.php',        // Custom comments modifications
  'lib/scripts.php',         // Scripts and stylesheets
  'lib/extras.php',          // Custom functions
);

foreach ($roots_includes as $file) {
  if (!$filepath = locate_template($file)) {
    trigger_error(sprintf(__('Error locating %s for inclusion', 'roots'), $file), E_USER_ERROR);
  }

  require_once $filepath;
}
unset($file, $filepath);
```

This happens only when is active my new theme.

**Comment by Phalconline** [comment]
Hi!
I have the similar problem on remote server, but localy all work perfect, in wp-engine service I have next errors:

With base code:
Fatal error: Error locating lib/utils.php for inclusion in /nas/wp/www/staging/anova/wp-content/themes/anova/functions.php on line 29

with this code:

```php
<?php
/**
 * Sage includes
 *
 * The $sage_includes array determines the code library included in your theme.
 * Add or remove files to the array as needed. Supports child theme overrides.
 *
 * Please note that missing files will produce a fatal error.
 *
 * @link https://github.com/roots/sage/pull/1042
 */
$sage_includes = [
    'lib/utils.php',                 // Utility functions
    'lib/init.php',                  // Initial theme setup and constants
    'lib/wrapper.php',               // Theme wrapper class
    'lib/conditional-tag-check.php', // ConditionalTagCheck class
    'lib/config.php',                // Configuration
    'lib/assets.php',                // Scripts and stylesheets
    'lib/titles.php',                // Page titles
    'lib/nav.php',                   // Custom nav modifications
    'lib/gallery.php',               // Custom [gallery] modifications
    'lib/extras.php',                // Custom functions
];

var_dump(TEMPLATEPATH);

foreach ($sage_includes as $file) {
    if (!$filepath = locate_template($file)) {
//        trigger_error(sprintf(__('Error locating %s for inclusion', 'sage'), $file), E_USER_ERROR);
    }

    $filepath = TEMPLATEPATH . '/' . $file;
    echo '<pre>';
    var_dump($filepath);
    echo '</pre>';
    require_once $filepath;
}
unset($file, $filepath);
```

string(49) "/nas/wp/www/staging/anova/wp-content/themes/anova"
string(63) "/nas/wp/www/staging/anova/wp-content/themes/anova/lib/utils.php"

Warning: require_once(/nas/wp/www/staging/anova/wp-content/themes/anova/lib/utils.php): failed to open stream: No such file or directory in /nas/wp/www/staging/anova/wp-content/themes/anova/functions.php on line 36

Fatal error: require_once(): Failed opening required '/nas/wp/www/staging/anova/wp-content/themes/anova/lib/utils.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/wp/www/staging/anova/wp-content/themes/anova/functions.php on line 36

 Can you help me?

**Comment by JulienMelissas** [comment]
@Phalconline - if you're on WP Engine you need to first make sure your server is running php 5.4 or greater. By default they're still on 5.3.*, but you can request a server with PHP 5.5

If that doesn't work, please go our [Discourse](https://discourse.roots.io/) for more troubleshooting as this isn't a bug.

**Comment by Phalconline** [comment]
Yeap, I'm in WP Engine, and I have php 5.5.9. Ok, tnks.
