### ISSUE TITLE
WP_ENV, File Order or Instructions Issue

### ISSUE THREAD

**Issue by aaronrutter** [roots/sage#1152]
This problem was also referenced in #1135 

When I installed, set WP_ENV to development in WP-CONFIG.PHP of the root wordpress directory as per instructions. Then I ran grunt dev which produced main.css but Wordpress was looking for main.min.css.

I noticed that WP_ENV was recently changed in reference to #1127 There was no change to the README.md

 Basically wp-content/theme/roots/lib/config.php is running before wp-config.php. A check if other variables from wp-config are set, or a change to the README would easily fix this.

**Comment by zackfair100** [comment]
@QWp6t thanks! this solved it for me!
