### ISSUE TITLE
Bug with built assets on Windows

### ISSUE THREAD

**Issue by CraigPearson** [roots/sage#1351]
This is a weird one, I have ran a build in gulp, ran a production etc however modernizr.js is not getting added to dist/scripts

The weird thing is that all modernizr classes get added to the body and modernizr is present on the page. Yet I get a 404 error on the asset request which is in the footer loaded before the jQuery CDN. And the asset is not present in theme folder.

I'm new to gulp but I haven't changed any configuration, am I missing something here?

**Comment by RainbowKpx** [comment]
Hi,
same here, i've seen that modernizr is included and minify in main.js, but we have an include from the assets.php (line 122), to turn off the error I've just comment this line.

I'm new in Sage so you might be wait for another person to confirm but it seem to be the right way to correct that problem.

Btw, sorry for my english.

Best regards.

**Comment by retlehs** [comment]
i just cloned this repo, ran `npm install`, ran `bower install`, and ran `gulp`:

```
➜  sage git:(master) ls dist/scripts
jquery-e5581654.js    main-0f58ea64.js      modernizr-b4a03e7f.js
```

@RainbowKpx modernizr is not being included in `main.js`.

if you have further support questions please ask over on https://discourse.roots.io/

**Comment by retlehs** [comment]
renamed title and reopened. relevant thread: https://discourse.roots.io/t/modernizr-added-to-dist-js-main-js-and-still-called-from-assets-php-as-dist-js-modernizr-js/2975

**Comment by austinpray** [comment]
It seems this is an issue with asset-builder and windows. I am currently working on a patch over at: https://github.com/austinpray/asset-builder/tree/windoze

I am also adding windows continuous integration to asset-builder to prevent windows regressions.
