### ISSUE TITLE
npm install, unmet dependencies problem

### ISSUE THREAD

**Issue by ltarasiewicz** [roots/sage#1357]
Hi,

First of all, thank you for the great work.

When I try to run npm install in the sage's root folder I get multiple warnings like these:
```
npm WARN unmet dependency /srv/www/tarasiewicz.local/current/web/app/themes/phpworker/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /srv/www/tarasiewicz.local/current/web/app/themes/phpworker/node_modules/wiredep/node_modules/bower-config/node_modules/optimist requires minimist@'~0.0.1' but will load
npm WARN unmet dependency /srv/www/tarasiewicz.local/current/web/app/themes/phpworker/node_modules/wiredep/node_modules/minimist,
npm WARN unmet dependency which is version 1.1.0
```

There are actually loads of these. Consequently, I cannot run any bowe command. They error out with:

```
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/www/tarasiewicz.local/current/web/app/themes/phpworker/node_modules/gulp-load-plugins/node_modules/multimatch/node_modules/minimatch/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

What might be the issue here? Am I missing something?

**Comment by drawcard** [comment]
I had this problem as well a while back, I'm trying to recall what the issue was but I think it was due to me running ```npm``` as sudo somewhere along the line, and it locked out some of my files when running as a user.

Try the following:
```npm cache clean```
```rm -rf node_modules/```
```npm install```

This will make NPM fetch all of the required dependencies again for Bower etc.

Also some people suggest [it might be your version of NPM is outdated](http://stackoverflow.com/a/24841274): running ```npm update npm -g``` may help.

**Comment by ltarasiewicz** [comment]
Drawcard's solution solves the problem. Thank you, drawcard.

**Comment by matthaliski** [comment]
Thanks @drawcard. Also worked for me.

**Comment by gtamborero** [comment]
Worked aswell!
