### ISSUE TITLE
Can't place path.source in subdirecotry

### ISSUE THREAD

**Issue by glennsjostrom** [roots/sage#1358]
In the Gulpfile I am trying to change my assets directory into "app/assets" instead of just "assets". I am setting path.source to "app/assets" but it does not work. It works for everything except "gulp styles". path.dist also works. Any idea why?

**Comment by austinpray** [comment]
I would change the path.source in the `assets/manifest.json`:

https://github.com/austinpray/asset-builder/blob/49089501f535a8245eb2eac694ea7efd8afd1de5/help/spec.md#examples

```
{
  "dependencies": {
    "main.js": {
      "files": [
        "scripts/main.js"
      ],
      "main": true
    },
    "main.css": {
      "files": [
        "styles/main.less"
      ],
      "main": true
    },
    "editor-style.css": {
      "files": [
        "styles/editor-style.less"
      ]
    },
    "jquery.js": {
      "bower": ["jquery"]
    },
    "modernizr.js": {
      "bower": ["modernizr"]
    }
  },
  "config": {
    "devUrl": "example.dev"
  },
  "paths": {
    "source": "change/me/assets/",
    "dist": "dist/"
  }
}
```
