### ISSUE TITLE
Custom Bower components directory

### ISSUE THREAD

**Issue by saulfautley** [roots/sage#1362]
It looks like `lib/assets.php` is trying to enqueue `dist/scripts/modernizr.js` although it doesn't exist. It does however seem like it's being included in `dist/scripts/main.js`, so enqueuing it is redundant anyway.

I've fixed this temporarily by commenting out the line `wp_enqueue_script('modernizr', ...` in `lib/assets.php` and modernizr seems to be triggering just fine without it.

**Comment by retlehs** [comment]
this was fixed with version 8.0.1, see https://github.com/roots/sage/issues/1351 and https://discourse.roots.io/t/modernizr-added-to-dist-js-main-js-and-still-called-from-assets-php-as-dist-js-modernizr-js/2975

**Comment by saulfautley** [comment]
I am using version 8.0.1. After some debugging I've discovered that the problem occurs because I've changed Bower's package directory in `.bowerrc` to `assets/vendor` -- somehow this is causing Modernizr and jQuery to be bundled with `main.js`. Changing it back to `bower_components` and rebuilding fixes it, but why is this happening in the first place?

**Comment by austinpray** [comment]
@saulfautley mainBowerFiles, which is used by asset-builder as a dependency, behaves a little weird in this situation and doesn't respect your bowerrc changes. I added an option to overcome this.

If you want to change the directory, in your gulpfile use asset-builder as such:
```js
var manifest = require('asset-builder')('./assets/manifest.json', {
  paths: {
   bowerDirectory: 'assets/vendor'
  }
});
```

**Comment by saulfautley** [comment]
@austinpray I've tried that but it doesn't seem to work. Looking through the code of asset-builder it seems that `bower_components` is hardcoded (`lib/buildGlobs.js:112`) and has no way of changing via options. I have manually changed this line to reflect my custom Bower directory and it works perfectly, even without specifying the `paths.bowerDirectory` option.

**Comment by austinpray** [comment]
@saulfautley oh yeah you are right. I manually check for bower_components to fix some corner case with jquery plugin naming. It definitely needs to be way more clever than that. I'll get around to fixing it but patches definitely welcome!

**Comment by retlehs** [comment]
closing this here since it's being addressed upstream https://github.com/austinpray/asset-builder/issues/22
