### ISSUE TITLE
NPM install in theme folder gives error 

### ISSUE THREAD

**Issue by anticCreations** [roots/sage#1368]
194706 error Windows_NT 6.1.7601
194707 error argv "C:\\programfiles\\nodejs\\\\node.exe" "C:\\programfiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
194708 error node v0.12.0
194709 error npm  v2.5.1
194710 error null == true

**Comment by retlehs** [comment]
this isn't the place for support. also, read through https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060

if you still run into issues after following those steps, start a thread on our discourse with more details (it looks like you provided an incomplete error log?)
