### ISSUE TITLE
Filtering the Wrapper 

### ISSUE THREAD

**Issue by giofilo** [roots/sage#1371]
Hi!

If I copy the function to filtering the wrapper as it is in the docs (https://roots.io/sage/docs/theme-wrapper/) in my extras.php file, it returns these errors.

<code>
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'sage_wrap_base_cpts' not found or invalid function name in /Users/giovanni/Dropbox/dev/www/wordpress/wp-includes/plugin.php on line 213
</code>

<code>
Warning: include(): Filename cannot be empty in /Users/giovanni/Dropbox/dev/www/wordpress/wp-includes/template-loader.php on line 74
</code>

<code>
Warning: include(): Failed opening '' for inclusion (include_path='.:/Applications/MAMP/bin/php/php5.5.18/lib/php') in /Users/giovanni/Dropbox/dev/www/wordpress/wp-includes/template-loader.php on line 74
</code>

I tried to rename the <code>sage/wrap_base</code> function to <code>sage/wrape</code> and it seems work now. But I'm not sure I did something clever or not :)

Thank you for your help!

**Comment by Foxaii** [comment]
That's not a fix sorry. You're just filtering a filter than doesn't exist. Try taking into account the namespace as below:
```php
add_filter('sage/wrap_base', __NAMESPACE__ . '\\sage_wrap_base_cpts'); // Add our function to the sage_wrap_base filter

function sage_wrap_base_cpts($templates) {
  $cpt = get_post_type(); // Get the current post type
  if ($cpt) {
     array_unshift($templates, 'base-' . $cpt . '.php'); // Shift the template to the front of the array
  }
  return $templates; // Return our modified array with base-$cpt.php at the front of the queue
}
```

Assuming that works, we'll just need to update the docs.

**Comment by giofilo** [comment]
@Foxaii thank you very much. I already changed the code and it works.
