### ISSUE TITLE
Issue when using gulp --production

### ISSUE THREAD

**Issue by webgurus** [roots/sage#1374]
Using `gulp --production` builds the files with custom hash in their file names but they don't get included in the theme, the /dits/main.js is included in the theme and it doesn't get updated.

**Comment by retlehs** [comment]
because your `WP_ENV` is set to `development`.

**Comment by retlehs** [comment]
ps. we've asked you multiple times to post over on https://discourse.roots.io/ instead of creating issues here. unless you're certain something is a bug (with proof), then post over on the forum.
