### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by con322** [roots/sage#1375]
I have been trying for a while to install sage and no success :( I am not knowledgeable of the terminal and commands etc.

Node v = v0.12.0
Bower = 1.3.12
Gulp = CLI version 3.8.11, Local version 3.8.11

Any help on why I am getting the error and commands to resolve it and get up and running with sage.

Currently I am getting this error when trying to run npm install:

    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
   
Then if I try sudo npm install I get the following (ps should I be using a pastebin?)

    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-    content/themes/duoglobal/node_modules/asset-builder/node_modules/main-bower-files requires     minimatch@'^1.0.0' but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/asset-builder/node_modules/minimatch,
    npm WARN unmet dependency which is version 2.0.1
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/node_modules/globule requires lodash@'~1.0.1' but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/browser-sync/node_modules/lodash,
    npm WARN unmet dependency which is version 3.5.0
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob requires graceful-fs@'~1.2.0'   but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs,
    npm WARN unmet dependency which is version 3.0.5
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/archive-type/node_modules/file-type/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/get-stdin,
    npm WARN unmet dependency which is version 3.0.2
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-  imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-  bin/node_modules/bin-build/node_modules/archive-type/node_modules/file-  type/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/get-stdin,
    npm WARN unmet dependency which is version 3.0.2
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-jshint/node_modules/jshint requires minimatch@'1.0.x' but will load
    npm WARN unmet dependency /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-jshint/node_modules/minimatch,
    npm WARN unmet dependency which is version 2.0.1
 
Then if I try use gulp I get

    -bash: gulp: command not found

Even though I use npm install -g gulp which install it globally right?

**Comment by swalkinshaw** [comment]
Not a Roots bug. Check our Discourse: https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060/4

Never run just `npm install` with `sudo`. Only ever use `sudo` for installing global packages if you have to.

**Comment by con322** [comment]
I have read that and used the following command
    
    npm cache clear && rm -rf node_modules && npm install 

However I get the following error

    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

    > gifsicle@2.0.1 postinstall /Applications/MAMP/htdocs/duoglobal/wp-    content/themes/duoglobal/node_modules/gulp-    imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
    > node lib/install.js

    module.js:338
    throw err;
          ^
    Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/duoglobal/wp-     content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-   fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

    > pngquant-bin@2.0.3 postinstall /Applications/MAMP/htdocs/duoglobal/wp-    content/themes/duoglobal/node_modules/gulp-     imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
    > node lib/install.js

    module.js:338
    throw err;
          ^
    Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/duoglobal/wp-    content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-    fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0

    > optipng-bin@2.0.4 postinstall /Applications/MAMP/htdocs/duoglobal/wp-  content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
    > node lib/install.js

    module.js:338
    throw err;
          ^
    Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/duoglobal/wp-  content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    npm WARN optional dep failed, continuing imagemin-pngquant@4.0.0

    > jpegtran-bin@2.0.2 postinstall /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
    > node lib/install.js

    module.js:338
    throw err;
          ^
    Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
    npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Applications/MAMP/htdocs/duoglobal/wp-content/themes/duoglobal/npm-debug.log

**Comment by dylan-k** [comment]
I am also getting similar errors when I try to run ``npm install`` and this is even after following [the instructions on Discourse](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) that @swalkinshaw linked to. I have also ensured that my environment meets the minimum requirements for the versions listed there.

It may be relevant to note that I'm on OSX version 10.7.5

After I run ``npm cache clean && rm -rf node_modules/ && npm install`` I get errors like:

```
npm ERR! Darwin 11.4.2
npm ERR! argv "node" "/Users/dylan/.nvm/versions/node/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.8.3

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 11.4.2
npm ERR! argv "node" "/Users/dylan/.nvm/versions/node/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.8.3

npm ERR! null == true
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
...
```

I read somewhere that if I use nvm to switch to using node 0.10 that it might help, but it didn't seem to.

Is there anything else I can try?

**Comment by austinpray** [comment]
Found this thread which is definitely related https://github.com/npm/npm/issues/7349
