### ISSUE TITLE
Sage\ConditionalTagCheck not iterating over arg arrays

### ISSUE THREAD

**Issue by saulfautley** [roots/sage#1376]
In `\Roots\Sage\Config\display_sidebars()` for example, if you specify the following:

```php
$conditionalCheck = new Sage\ConditionalTagCheck([
    ['is_page_template', ['template-custom1.php', 'template-custom2.php']],
]);
```

The arg array is simply being passed to the conditional tag function like this:

```php
is_page_template(['template-custom1.php', 'template-custom2.php']);
```

But since `is_page_template()` (and possibly others) only accepts a string, it should be calling it like this:

```php
is_page_template('template-custom1.php');
is_page_template('template-custom2.php');
```

**Comment by swalkinshaw** [comment]
It's not supposed to iterate over them.

The 2nd "args" argument get's passed through directly. You'd want to do:

```php
['is_page_template', 'template-custom1.php'],
['is_page_template', 'template-custom2.php']
```

**Comment by saulfautley** [comment]
Ok I see now. I was using a version of Sage before `lib/config.php` was updated with the new documentation and examples. Thanks for the clarification.
