### ISSUE TITLE
Latest stable Node.js version is 0.12.0

### ISSUE THREAD

**Issue by djmtype** [roots/sage#1385]
Is this a duplicate issue posted [here](https://github.com/roots/sage/issues/1361)? 

The latest stable node.js version is 0.12.0, installed as pkg binary or via terminal `npm install -g npm@latest`. I tried both. 

It seems Sage will not install its required packages running `npm install`. 
Is there a workaround? 

Error spewed out based on installing Node.js Mac pkg:
 
```
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /Users/scottrod/.npm/immutable/3.6.4
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/scottrod/.npm/immutable/3.6.4'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/scottrod/.npm/immutable/3.6.4']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/scottrod/.npm/immutable/3.6.4',
npm ERR!   parent: 'browser-sync' }
```

**Comment by mAAdhaTTah** [comment]
The error looks more like permissions issues rather than anything with Node.js. Check your perms on ~/.npm

**Comment by djmtype** [comment]
@mAAdhaTTah thanks. Yup, permissions (for some reason) on immutable and browser-sync were not to me as read/write.
