### ISSUE TITLE
Frontpage without navigation menu

### ISSUE THREAD

**Issue by tubia** [roots/sage#1395]
Hi,
I'm trying to customize the homepage removing the navbar that is actually called by `base.php` here:
```php
<?php
      do_action('get_header');
      get_template_part('templates/header');
    ?>
```

I would like to avoid to duplicate `base.php` as suggested in the docs. Any hints on the best path to achieve this?

Thank you :)

**Comment by JulienMelissas** [comment]
@tubia - this is not a Sage issue, please use our [Discourse forum](https://discourse.roots.io/) for support.

Close this up team.
