### ISSUE TITLE
Implement Timber support for theming

### ISSUE THREAD

**Issue by inverse** [roots/sage#1397]
Just stumbled across Timber and it looks like it could be a nice idea for Sage.

- http://upstatement.com/timber/

**Comment by QWp6t** [comment]
You are more than welcome to copy/paste the PHP template files into views for Twig/Timber (or any other template engine for that matter). But no we won't be making Timber a dependency of Sage anytime soon.

**Comment by austinpray** [comment]
@inverse can confirm that Timber works great with Sage. Used it on a couple projects and really enjoy it.

**Comment by retlehs** [comment]
fyi, we plan on adding an option for timber support with the sage yeoman generator

**Comment by tiborp** [comment]
I Like!

**Comment by KLVTZ** [comment]
@retlehs has the generator been added yet? Or is still a work in progress?
