### ISSUE TITLE
Sass integration incomplete

### ISSUE THREAD

**Issue by lamosty** [roots/sage#1404]
I went through the guide of how to switch from LESS to Sass but it's still not working. The style files has LESS syntax of variables, not Sass so gulp produces error. For example,

LESS:
```less
// Grid settings
@main-sm-columns:       @grid-columns;
@sidebar-sm-columns:    4;

// Colors
@brand-primary:         #27ae60;
```

Sass:
```sass
// Grid settings
$main-sm-columns:       $grid-columns;
$sidebar-sm-columns:    4;

// Colors
$brand-primary:         #27ae60;
```

**Comment by retlehs** [comment]
https://discourse.roots.io/t/regarding-the-grid-help-translating-less-to-sass/3253
