### ISSUE TITLE
Ability to exclude specific images from compression. Mac OSX Webkit SVG Issues

### ISSUE THREAD

**Issue by christianmagill** [roots/sage#1406]
I'm experiencing an issue where an SVG file displays as a solid black in Mac OS X (Chrome/Safari) after being "optimized". It would be nice to be able to exclude select images from optimization while still moving them for distribution.

**Comment by austinpray** [comment]
```js
gulp.task('images', function() {
  return gulp.src(globs.images)
    .pipe($.if(['!naughtyimage.svg'], $.imagemin({
      progressive: true,
      interlaced: true,
      svgoPlugins: [{removeUnknownsAndDefaults: false}]
    })))
    .pipe(gulp.dest(path.dist + 'images'));
});
```

Pretty sure that works

**Comment by retlehs** [comment]
please post over on discourse if what @austinpray said doesn't work
