### ISSUE TITLE
Follow Wordpress coding standards

### ISSUE THREAD

**Issue by tommica** [roots/sage#1411]
I've noticed that the theme uses PHP shorthands, and this is not recommended in the Wordpress coding standards documentation:
https://make.wordpress.org/core/handbook/coding-standards/php/#no-shorthand-php-tags

**Comment by Patabugen** [comment]
Was this closed because the single mentioned issue was fixed? Much of the code still does not adhere to the WordPress Coding Standards.

Roots brings excellent practice to so many areas of WordPress development and deployment it's a shame that it falls down in this (relatively simple) respect.

**Comment by swalkinshaw** [comment]
This was closed because the issue has been brought up many times. Example: https://github.com/roots/sage/pull/1507

**Comment by Patabugen** [comment]
That was only for short opening tags too, I'm asking about the whole coding
standard.

Digging through old issues and comments it seems that Roots wishes to use
PSR-2?

If Roots uses a different standard to WordPress, it'd be handy for it to be
advertised somewhere (like in the Intro).

**Comment by swalkinshaw** [comment]
See https://github.com/roots/guidelines.

TravisCI runs PHP CS and enforces our ruleset.

**Comment by Patabugen** [comment]
Right.

I presume someone had a conversation about it so I won't fight it (I'll just ignore it). But it seems silly to not only use a derivation of a standard (thus using something non-standard) but to use a different style from the parent project.

Now we're supposed to write WordPress style everywhere except in our theme where we use PSR-2?

I'd love WordPress to switch to PSR-2, but that's a decision for WP to make - as WP developers should we not be following their standards? (rhetorical question)

**Comment by swalkinshaw** [comment]
We have spent thousands of hours creating, maintaining, and supporting Roots' open source projects over a period of years. If there's something that makes that process just a little easier and more fun for us, we'll probably go with it. 

To put it simply: we don't like the WP coding standards so we choose to use our own which we do like. That is completely within our rights to do.

**Comment by JulienMelissas** [comment]
@Patabugen just to let you know - I had a developer that I was working with who preferred WordPress coding standards and was very adamant about it, so I made [something like a fork](https://github.com/Craftpeak/wp-starter-theme) of Sage (but really not all the same files and stuff so it's not a fork) with WordPress coding standards used throughout most of the project and it really didn't take me that long to do.

If it's that important to you, get ready for an hour of changing spaces to tabs, adding spaces around if statements and finding and replacing `<?= ` with `<?php echo `. Then publish that fork up on GitHub, keep it maintained by watching this project and keeping up with changes, and I'm sure a lot of people would appreciate it.

**Comment by Patabugen** [comment]
Thanks Julien, I actually hate the WP standards so I'm not going to go
through too much effort if the Sage team don't want it (I did actually
start a compliant fork before I discovered they'd made their own standards).

I'll just turn off the automatic linter for anything which involves Roots
(I think I can get SublimeLinter to ignore just the Roots directory
actually, but that's for a quieter day).

**Comment by QWp6t** [comment]
I think the fewer marching orders you take from WordPress, the better programmer you'll be.

Yoda statements? ROFL. Yeah, no thanks.

**Comment by aaemnnosttv** [comment]
I think the Yoda condition is a good idea when comparing a variable to something like a string literal.  By putting the literal before the variable in the comparison, it protects you from potentially creating more problems for yourself if you accidentally use a single `=` instead of a double.

**Comment by austinpray** [comment]
>It protects you from potentially creating more problems for yourself if you accidentally use a single = instead of a double.

Sounds like something that should be caught with tests and code reviews :wink:

**Comment by mAAdhaTTah** [comment]
Sure, you could do all that to check an assignment bug, or you could just write Yoda conditions and never have them in the first place.

**Comment by QWp6t** [comment]
That sounds like quite an inept problem to have. I think if you're worried about accidentally setting a variable, then you're probably not at a point where you should be setting code styles for half the internet.

**Comment by Patabugen** [comment]
I'd have to agree with @QWp6t , Code Styles are to make reading and writing code more consistent - as result of which is usually fewer bugs, but that's not the purpose of them.

I'll stop following WordPress's guidelines when I stop using WordPress. No project is perfect, WP sucks in it's choice of coding standard (and fails even harder in developers sticking to them) but I'll take that rubbish in exchange for the positives until I decided I'd prefer a better set of positives (I'm sure there's a platform with a wide arrange of platforms which aren't 99% awfully written.. out there somewhere).
