### ISSUE TITLE
Confused about deploying

### ISSUE THREAD

**Issue by simonh1000** [roots/sage#1412]
I've just started with Sage and am confused about what to deploy to a standard wordpress hosted environment (or to Openshift). There seem to be files in the root directory of the theme, in `templates` and in `assets`. I suspect I have missed something obvious in this otherwise very sophisticated system?

**Comment by JulienMelissas** [comment]
@simonh1000 - as is this isn't an issue with the repository, please post over at our [Discourse Forum](https://discourse.roots.io/), and I'll be able to answer your question over there.

Close this up team.
