### ISSUE TITLE
Is this possible to download old Roots theme versions?

### ISSUE THREAD

**Issue by monkeymonk** [roots/sage#1415]

**Comment by retlehs** [comment]
yes, see https://github.com/roots/sage/releases

also:

https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker

> Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/)).

**Comment by monkeymonk** [comment]
Thank you ! ...and sorry ! Σ(°Д° )
