### ISSUE TITLE
Sentence not being translated in comments.php

### ISSUE THREAD

**Issue by wsmbr** [roots/sage#1420]
For some reason, the following sentence in not being translated (at least for french translation).

**comments.php line 9**

```
<?php printf(_n('One Response to &ldquo;%2$s&rdquo;', '%1$s Responses to &ldquo;%2$s&rdquo;', get_comments_number(), 'comments title', 'sage'), number_format_i18n(get_comments_number()), '<span>' . get_the_title() . '</span>'); ?>
```

**Comment by retlehs** [comment]
there's fancy quotes in that code you pasted that doesn't exist in this repo. is that what your file looks like? someone reported recently that opening a file in textedit did the same thing for them.

**Comment by wsmbr** [comment]
Sorry but the fancy quotes was caused by the <code> tag in my comment below. Updated now.

**Comment by Foxaii** [comment]
The translate function is `_nx` in the repo, not `_n`. Which are you having trouble with?

**Comment by icamys** [comment]
The same issue with russian language

**Comment by joerimarquerinck** [comment]
Same issue with the Dutch translation. The string isn't even translated in the PO file for some reason.
