### ISSUE TITLE
Content sigle footer

### ISSUE THREAD

**Issue by santamartastudio** [roots/sage#1425]
In content-single.php we can use post pagination:

    <footer>
      <?php wp_link_pages(['before' => '<nav class="page-nav"><p>' . __('Pages:', 'sage'), 'after' => '</p></nav>']); ?>
    </footer>

But if you don't have it will draw the footer tag. Will not be better something like this?

		<?php if (wp_link_pages()) { ?>
		<footer>
		<?php } ?>

			<?php wp_link_pages(['before' => '<nav class="page-nav"><p>' . __('Pages:', 'sage'), 'after' => '</p></nav>']); ?>
		<?php if (wp_link_pages()) { ?>
		</footer>
		<?php } ?>

**Comment by Foxaii** [comment]
As a starter theme, our goal is to make our templates easy to adapt. Adding complexity, such as your conditional checks, takes away from this somewhat. The checks also become unnecessary if a theme has any other content inside the post's footer section (e.g. related posts, tags, categories, social media links).

So we'll pass this time to keep things simple. Thanks for the suggestion though.
