### ISSUE TITLE
Unable to install in WAMP on Windows

### ISSUE THREAD

**Issue by cyberwani** [roots/sage#1428]
I am using WAMP on windows. I installed Bedrock. It works fine. The I installed Sage theme and started process mentioned in theme documentation. But process get stuck. When I further check I found that it's creating folder structure which is leading path length too long. Due to which it';s not working.

**Comment by austinpray** [comment]
Personal support requests belong over at: https://discourse.roots.io/

https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker
