### ISSUE TITLE
Consider alternatives to regexing HTML

### ISSUE THREAD

**Issue by austinpray** [roots/sage#1435]
- https://github.com/roots/sage/blob/a17951579691376c6e097ce55f81df58ba54e80b/lib/nav.php#L47
- https://github.com/roots/sage/blob/a17951579691376c6e097ce55f81df58ba54e80b/lib/nav.php#L49

This is definitely pretty brittle. We should be using https://php.net/manual/en/book.dom.php here. Although I don't know enough about the community at large to know if this will cause problems for people. PHP Dom module is always enabled by default right? Need feedback.

**Comment by retlehs** [comment]
irrelevant if #1427 is merged.
