### ISSUE TITLE
Any reason to use uglify during development?

### ISSUE THREAD

**Issue by Jakeii** [roots/sage#1438]
Since removing from `jsTasks` development is much quicker for me, previously my compile time averaged around 5-6s when editing a js file, since disable disabling it now takes 100-200ms.

Perhaps skip uglifying when `--production` disabled? Or perhaps this uglify issue is specific to me?

**Comment by swalkinshaw** [comment]
I believe we did this to keep the dev workflow as close as possible to the production one. Uglify could break something and it's better to catch that in development also.

**Comment by austinpray** [comment]
The proper solution here would be to add caching and better incremental builds. Will look into this.

**Comment by Jakeii** [comment]
@swalkinshaw Shouldn't people be testing their production build before actually putting it in production anyway? There aren't a whole lot of things that can break with the default uglify options.

**Comment by swalkinshaw** [comment]
@Jakeii of course! There's lots of things people *should* do. Best way to ensure it is with automated processes though.

**Comment by retlehs** [comment]
#1433 related
