### ISSUE TITLE
Parse error on new install

### ISSUE THREAD

**Issue by wnrosenberg** [roots/sage#1441]
Using Sage latest version (c3d7d0afec951cd1c3e8c23a1bafbc63714ca590)
Using WP 4.2.1
Locally using PHP 5.4.30

Parse error: syntax error, unexpected '[' in /nas/wp/www/staging/ipgweb/wp-content/themes/ipg-sage/functions.php on line 12

Line 12: $sage_includes = [

**Comment by retlehs** [comment]
you're definitely not on php 5.4.

**Comment by wnrosenberg** [comment]
My bad, you're correct. I was looking at my WPEngine staging environment which is 5.3.2 :(

**Comment by JulienMelissas** [comment]
@wnrosenberg - get them to up it to 5.5, a simple support request and I've found they'll get it done in less than 24 hours, sometimes a lot quicker.
