### ISSUE TITLE
gulpfile code style

### ISSUE THREAD

**Issue by joemaller** [roots/sage#1443]
Does anyone have an opinion about migrating the gulpfile more towards the npm standard of explicitly including modules at the top of the file? 

I'd also like to move away from gulp-load-plugins, which saves a few keystrokes but ends up creating a lot of cognitive overhead in tracing through the code and understanding how the file works. I think readability would be increased quite a bit by dropping this. 

Space-aligning the require statements also feels very foreign to JavaScript.

**Comment by retlehs** [comment]
can you please create a discourse thread for this? https://discourse.roots.io/
