### ISSUE TITLE
Sage documentation syntax error

### ISSUE THREAD

**Issue by DylanSimowitz** [roots/sage#1444]
On the [theme sidebar page](https://roots.io/sage/docs/theme-sidebar/)

    [
      'is_404',
      'is_front_page',
      ['is_page_template', 'template-custom.php']
      ['is_page_template', 'page-contact.php']
      ['is_page_template', 'page-42.php']
    ]
should contain commas to separate each template

    [
      'is_404',
      'is_front_page',
      ['is_page_template', 'template-custom.php'],
      ['is_page_template', 'page-contact.php'],
      ['is_page_template', 'page-42.php']
    ]

**Comment by retlehs** [comment]
thanks, i've fixed it. 

fyi - at the bottom of every docs page is a link to [our discourse](http://discourse.roots.io/). please use that in the future to report issues like this
