### ISSUE TITLE
Compiled assets have incorrect file path

### ISSUE THREAD

**Issue by erikkowalski** [roots/sage#1449]
One a fresh install of 8.1.1 the file path to my bootstrap glyph icons is incorrect, here's an example of of what I'm getting in web inspector:

http://example.com/app/themes/sage/dist/styles/styles/fonts/bootstrap/glyphicons-halflings-regular.woff

I'm also getting the same problem with web fonts and image paths in my _global.less/scss files. I had add "../../" in front of the normal url ex:

src: url('../../../fonts/Aleo-Regular-webfont.eot');

usually the file path is src: url('../fonts/Aleo-Regular-webfont.eot');

**Comment by retlehs** [comment]
need to update https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L83 to point it to the correct spot

would really appreciate a PR to our assets/styles/common/_variables.scss file to fix this.

**Comment by erikkowalski** [comment]
Thanks for the quick response Ben, If that second comment is directed at me I'm not sure what you mean.

**Comment by retlehs** [comment]
see https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#pull-requests

you can also do this (see edit button near right):

![image](https://cloud.githubusercontent.com/assets/115911/7445826/66eca2cc-f188-11e4-9aca-5b0ea92ba65e.png)

**Comment by erikkowalski** [comment]
Thanks Ben, I'm still learning git as I go. fearlsgroove, beat me to the pull request. Gla

**Comment by fearlsgroove** [comment]
Hrm -- well the PR fixes the glyphicons issue, but not necessarily the issue with other fonts.

**Comment by erikkowalski** [comment]
self hosted fonts seem to be working fine with src: url('../../../fonts/webfont');

**Comment by erikkowalski** [comment]
But I guess that doesn't change the fact that escaping "styles/styles" twice is a hack, and the question still remains why "styles/styles' is in the path of asset links in the compiled main.scss file.

**Comment by willenglishiv** [comment]
I'm experiencing the same thing referencing images in my scss files, even after running gulp to move the images to dist folder.

**Comment by retlehs** [comment]
i think you guys are confusing yourselves.

fonts that are not bootstrap's glyphicons need to be referenced from css with `../fonts/`. from my reply on discourse just now:

> I'm really confused. 

> CSS is compiled to `dist/styles/`

> Images are compiled to `dist/images/`

> You would **never** need to do `../../../images/` in your CSS. I just tested the following in `_global.scss`:

```css
body {
  background: url(../images/example.png);
}
```

**nothing has changed at all regarding referencing assets. this is the same as it has been for years.**

**Comment by webfluence** [comment]
I'm experiencing this also, could it be a Windows thing?

As mentioned by @willenglishiv this is happening for images too.

**Comment by retlehs** [comment]
i don't understand how it could be a windows thing (guess it could be?) - look at the directory structure.

![image](https://cloud.githubusercontent.com/assets/115911/7453845/19e42cb0-f233-11e4-8e55-d34f69d2bab7.png)

if you reference `../../../` then you're going too far. from your stylesheet you should *only* need to go up one directory to reference assets from the fonts or images directories

**Comment by webfluence** [comment]
Yeah I know, this doesn't make sense - but it works.

Maybe the SASS compiler on Windows has a glitch?

**Comment by retlehs** [comment]
just wiped my node_modules directory and now experiencing the issue. digging now

**Comment by erikkowalski** [comment]
@webfluence I'm running Mac OS X 10.10.3, so its not Windows specific

**Comment by erikkowalski** [comment]
@retlehs Don't know if this helps but it seems like this popped up when the please gulp plugin was removed.

**Comment by austinpray** [comment]
:rage4:

**Comment by austinpray** [comment]
Everyone try this out: https://github.com/roots/sage/pull/1452

The issue was with the minification options. Definitely going to investigate turning off all the advanced options for minification. Clearly not worth it.

**Comment by erikkowalski** [comment]
Works, issue seems resolved.. does this change affect any other functionality?

Also any additional steps I should take before closing.

**Comment by austinpray** [comment]
@erikkowalski technically this needs to get merged for this to be resolved lol https://github.com/roots/sage/pull/1450

**Comment by erikkowalski** [comment]
Yes, thats what I thought. You just merged to master though.. correct?

**Comment by austinpray** [comment]
Yep! my fixes are in master and then I just called up @erikkowalski and he's gonna fix his stuff later.

**Comment by erikkowalski** [comment]
ok.. but you lost me on the second half

**Comment by austinpray** [comment]
Whoops, @ replied the wrong person lol. Fixed.

**Comment by erikkowalski** [comment]
got it, I thought so. Very relived to have this one resolve, I thought I was loosing it for little while when first  noticed this one. Thanks agin
