### ISSUE TITLE
compiled error?

### ISSUE THREAD

**Issue by iwillhappy1314** [roots/sage#1454]
I use sage 8.1.1 on my windows 8.1,

the font url:  `url(../fonts/iconfont.woff)`

after gulp build

it comes to: `url(styles/fonts/iconfont.woff)`

**Comment by austinpray** [comment]
Almost positive this is related to the minification options. 

Apply this patch: https://github.com/roots/sage/commit/cf928c85eb98c64dd719bee1d4c4d70539c29b1f
