### ISSUE TITLE
Update wp-h5bp-htaccess plugin

### ISSUE THREAD

**Issue by rslnk** [roots/sage#1463]
https://github.com/roots/wp-h5bp-htaccess/issues/15

**Comment by retlehs** [comment]
not sure what this issue is for? that functionality was removed from the starter theme in may 2013

**Comment by rslnk** [comment]
@retlehs Sorry, Ben! Wrong place. I was suppose to assign this to my project, but ended up creating issue in sage repository by mistake. My bad. I will be more carefull next time.
