### ISSUE TITLE
Sass files only compile with --production flag

### ISSUE THREAD

**Issue by thespotvin** [roots/sage#1474]
Hi there - I have a brand new install of Sage, everything installed and setup with no issues - but when I run `gulp` or `gulp watch` the css files are not compiled (hard refresh or BrowserSync). If I run `gulp --production` then all files are processed and compiled as expected.

When it fails it seems to fail silently. Gulp reports that the files have been processed - with `gulp watch` I see this:

```
[BS] Watching files...
[10:10:01] Starting 'wiredep'...
[10:10:02] Finished 'wiredep' after 238 ms
[10:10:02] Starting 'styles'...
[BS] 2 files changed (editor-style.css, main.css)
[10:10:07] Finished 'styles' after 5.29 s
```

I have tried updating some of the more relevant npm modules, and even removing all modules, clearing cache and starting from scratch. Any other ideas for troubleshooting?

**Comment by retlehs** [comment]
unable to reproduce - please post on our discourse if you can't figure it out and take a look at https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060
