### ISSUE TITLE
nav_walker?

### ISSUE THREAD

**Issue by lgt** [roots/sage#1475]
As I remember Roots has included a nav_walker. There is no more such a support  for bootstrap menus?

**Comment by Foxaii** [comment]
See #1427 and [here](https://discourse.roots.io/t/how-to-restore-the-bootstrap-nav-walkthrough/3657/).

In future please keep questions like this to the Discourse forum only.

**Comment by austinpray** [comment]
It's been removed: https://github.com/roots/sage/pull/1427
