### ISSUE TITLE
Use gulp-order to fix incorrectly ordered scripts and styles in minified bundle.

### ISSUE THREAD

**Issue by austinpray** [roots/sage#1476]
This is an old edgecase: https://discourse.roots.io/t/ordering-stylesheets-before-gulp-concat/3489/6

Asset-builder gives us the arrays in order. We need to drop these arrays into https://github.com/sirlantis/gulp-order

https://gist.github.com/austinpray/15d4514e93217a66e6d3#file-readme-md

https://github.com/dlmanning/gulp-sass/issues/236

**Comment by retlehs** [comment]
we won't be addressing this :warning:
