### ISSUE TITLE
Problems with npm installation

### ISSUE THREAD

**Issue by RokkGL** [roots/sage#1478]
Hi. I want to install sage starter theme into wordpress. I'm using git bash and xampp server. I think that i'm having problem with permissions. When i used npm install command, i got results:

Binary is fine; exiting.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path C:\Users\Rokas\AppData\Roaming\npm-cache\inherits\2.0.1\package\pa
ckage.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Users\Rokas\AppData\Roaming\npm-cache\inherits
\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\Rokas\AppData\Roaming\npm-cache\inhe
rits\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Rokas\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1
\\package\\package.json',
npm ERR!   parent: 'concat-stream' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\xampp\htdocs\wp\wp-content\themes\sage\npm-debug.log
/c/Program Files/nodejs/npm: line 14:  7644 Signal 112              (core dumped
) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

I tried to run git bash as Administrator, it did't help.

**Comment by retlehs** [comment]
https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker

> Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/)).

also: https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060
