### ISSUE TITLE
Dist folder?

### ISSUE THREAD

**Issue by lovablehack** [roots/sage#1479]
Hello

I am using Sage for WordPress. I'm unable to find the dist folder which has main.css for which due to the theme is not appearing properly? Am I missing something?

Ali Kazim
Frontend Developer

**Comment by MikeiLL** [comment]
If you cloned the repository the dist folder will be in the Sage directory, however untill you have installed node, gulp and bower and run npm install, bower install and gulp, none of the "assets" will have been compiled to the dist directory yet; it will be empty. Check out the Sage video if you can - also this question belongs more in the 'discourse' under the blog articles than as a github issue, i think.

**Comment by Foxaii** [comment]
@MikeiLL is correct. The dist folder won't exist until you first run `gulp`. The [readme](https://github.com/roots/sage/blob/master/README.md) and the [docs](https://roots.io/sage/docs/) on our site should help you through the process.

Any other questions should be addressed through [discourse](https://discourse.roots.io/).

**Comment by lovablehack** [comment]
Respected

I use windows operating system, is it possible to do on that? If yes, any
reference link of How?

**Comment by c2itllc** [comment]
>Any other questions should be addressed through [discourse](https://discourse.roots.io/).
