### ISSUE TITLE
Use wordpress' built-in version attribute for enqueued scripts/styles

### ISSUE THREAD

**Issue by purjon** [roots/sage#1481]
Instead of having gulp-rev renaming the assets you could create an asset manifest file like:

{ "path/to/file": "hash" }

And then have that hash included as the fourth argument (version) when enqueuing each file. Or is there a specific reason why you want to rename the files rather than appending the version as a url parameter?

**Comment by retlehs** [comment]
http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

**Comment by austinpray** [comment]
More specifically: http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.9

>We note one exception to this rule: since some applications have traditionally used GETs and HEADs with query URLs (those containing a "?" in the rel_path part) to perform operations with significant side effects, caches MUST NOT treat responses to such URIs as fresh unless the server provides an explicit expiration time. This specifically means that responses from HTTP/1.0 servers for such URIs SHOULD NOT be taken from a cache. See section 9.1.1 for related information.

What this means is that those query parameters can cause undefined behavior with browsers and proxys (think CDNs, nginx, caching layers like varnish). 

Where I have been personally bitten by this: AWS cloudfront only started supporting query strings in cached objects in May 2012. https://aws.amazon.com/blogs/aws/amazon-cloudfront-support-for-dynamic-content/
