### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dhuyvetter** [roots/sage#1490]
I just got sage from gitgub and afterter uploading and activating the theme I get this error:

Parse error: syntax error, unexpected '[' in /domain/wp-content/themes/sage/functions.php on line 12

**Comment by austinpray** [comment]
You have an old version of PHP https://github.com/roots/sage/tree/71c2e78b0e42c1a86adba8d4a30e1b6d9df17dff#requirements

**Comment by dhuyvetter** [comment]
My bad, I should have RTFM.
