### ISSUE TITLE
gulp-minify-css bug with background:inherit

### ISSUE THREAD

**Issue by coffeeneed** [roots/sage#1491]
When running gulp, this code snippet:

    .mm-menu > .mm-panel { background: inherit; }

minifies to

    .mm-menu > .mm-panel { background: inherit inherit/inherit inherit inherit inherit; }

This of course renders my markup invalid. Dunno if background:inherit it self is the problem or if it's in combination with chevrons. Probably the latter, imho.

gulp-minify-css running 1.1.0.

Also reported on Roots Discourse: https://discourse.roots.io/t/bug-with-minify-system-screws-up-background-inherit/4020

**Comment by austinpray** [comment]
This is https://github.com/jakubpawlowicz/clean-css/issues/563

It should be fixed by updating gulp-minify-css on your end. Our package.json depends on gulp-minify-css 1.x so you will get this by running `npm update`.

**Comment by coffeeneed** [comment]
This worked. Thank you. Case solved.

**Comment by austinpray** [comment]
Sweet!
