### ISSUE TITLE
browser sync problem

### ISSUE THREAD

**Issue by jajouka79** [roots/sage#1495]
Hello, I have a local domain bedrock.local, which I have defined in assets/manifest.json, however when I do gulp watch it opens localhost:3000, there is a reference to test.local in the terminal as its preparing:

[17:19:38] Starting 'watch'...
[17:19:38] Finished 'watch' after 24 ms
[BS] Proxying: http://bedrock.local
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.5:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.5:3001
 ------------------------------------

but in the browser that is automatically opened by the command its localhost:3000, and so are all the links in the document, is this correct? also localhost:3000/wp-admin doesn't work

thanks

**Comment by AdamWills** [comment]
This is a support issue, not an issue with the project. Head over to https://discourse.roots.io/

**Comment by swalkinshaw** [comment]
what @AdamWills said.
