### ISSUE TITLE
Better Soil integration

### ISSUE THREAD

**Issue by Gyroscopic** [roots/sage#1498]
Hi 

I just used soil for the first time on a project with Sage and was slightly confused as there seems to be missing documentation regarding what module is set by default and what is not.

Using discourse I found that in Sage, lib/config.php sets several modules on by default but for others you have to add code to lib/init.php. However init.php has no mention of this, so I propose that we add the following code to init.php to increase in-line documentation & overall understanding of what to do to get additional Soil modules working.
```
  /**
   * Additional SOIL modules can be activated here... Others are set by default in lib/config.php
   */
  //Google Analytics (see https://github.com/roots/soil/wiki/Google-Analytics)
  #add_theme_support('soil-google-analytics', 'UA-XXXXX-Y');

  //Move all JS to the footer
  #add_theme_support('soil-js-to-footer');

  //Disable trackbacks
  #add_theme_support('soil-disable-trackbacks');

  //Disable asset versioning
  #add_theme_support('soil-disable-asset-versioning');
```
I put this in my lib/init.php file after ```add_editor_style(Assets\asset_path('styles/editor-style.css'));``` inside the setup() function.

Not confident enough with git yet to produce a pull request, sorry.

Hope this helps someone.

**Comment by QWp6t** [comment]
You can add all of them to `lib/config.php`. You don't have to bounce between the two files. 

And it's all documented right here: https://github.com/roots/soil#modules

**Comment by Gyroscopic** [comment]
Thanks but I think that doc could be clearer, I read all that before I posted (and checked out discourse as stated). Currently is just says what to do not where, hence my additions - It would be good to get definitive instructions, whether thats on the plugin page or in Sage code (or both) .

**Comment by MikeiLL** [comment]
Seems to me like more documentation couldn’t hurt.
