### ISSUE TITLE
Migration to Bootstrap for SASS

### ISSUE THREAD

**Issue by rku4er** [roots/sage#1500]
When I install bower package that has Bootstrap as a dependency, Gulp generates ./dist/scripts/main.js with duplicated Bootstrap modules. Seems Bootstrap is concatenated with Bootstrap-Sass.

After research I found that easiest way is add:
<code> "bootstrap": { "ignore": [ "./dist/js/bootstrap.js" ] }, </code>

I'm not sure, Should I control these cases manually or it could be resolved with gulpfile.js?

Regards

**Comment by retlehs** [comment]
Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/))

**Comment by rku4er** [comment]
Thanks!
