### ISSUE TITLE
Duplicate Inclusion of jQuery

### ISSUE THREAD

**Issue by kevinfodness** [roots/sage#1502]
It appears that jQuery is being included twice - once as a dependency in WordPress when enqueuing the scripts in assets.php:

    wp_enqueue_script('sage_js', asset_path('scripts/main.js'), ['jquery'], null, true);

Once in the Bower/Gulp workflow in the minified JS file, as evidenced by the sourcemap: 

    {"version":3,"sources":["../bower_components/jquery/dist/jquery.js"

The double-inclusion of jQuery not only introduces unnecessary overhead, but causes JavaScript breakage in other areas - most notably, Gravity Forms. Commenting out the first line of the generated main.js fixes the issue, but an upstream fix should be applied to prevent Gulp from pulling in jQuery in the asset build when reading the Bower dependency tree.

**Comment by swalkinshaw** [comment]
Fixed in https://github.com/roots/sage/pull/1501.

Please update and confirm it fixes it for you as well.

**Comment by kalenjohnson** [comment]
Just found this yesterday. Not naming names though.
