### ISSUE TITLE
Editing JS file while "gulp watch" - nothing happens

### ISSUE THREAD

**Issue by kojilab** [roots/sage#1503]
Hi,

I'm editing assets/scripts/main.js while gulp is watching and my changes are not reflected in the distribution file. I tried 'gulp scripts' and same happened.

What do I need to do? Thanks

**Comment by retlehs** [comment]
Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/))

**Comment by kojilab** [comment]
If it's not working how is it a support request?

**Comment by kalenjohnson** [comment]
@kojilab It's a support request because you haven't posted any logs or any actual errors. It's also a support request because it is not an issue for anyone else, so as far as we know, not a bug with Sage.

**Comment by kojilab** [comment]
1. How can I know it's not an issue with anyone else?
2. If nothing happens when I do gulp watch after installing it and editing my main.js file, and am not seeing any error nor something about JS being minified in the console, how am i to assume it works?

Don't offer your framework if you're so uptight about this ticket.
