### ISSUE TITLE
Ensuring new CSS is loaded

### ISSUE THREAD

**Issue by gorkamolero** [roots/sage#1505]
Hey guys,

Great work on the starter theme. Love it and have been using it since discovery. One question about it:

How do you ensure new CSS is loaded? I always seem to have a problem with cache. Is this something that has a simple solution?

Thank you

**Comment by cjmosure** [comment]
You should post this at https://discourse.roots.io, or more specifically https://discourse.roots.io/c/sage

**Comment by gorkamolero** [comment]
Thank you Christopher, I'll do
