### ISSUE TITLE
the_excerpt() does not show 'Read more' if page break is done manually by <!--more-->

### ISSUE THREAD

**Issue by jashwant** [roots/sage#1509]
In `templates/content.php`, consider the following code,

```php
<div class="entry-summary">
    <?php the_excerpt(); ?>
</div>
```

`the_excerpt();` shows the `Read more` ( or `... Continued` in Sage ) correctly, if the content is more than the `excerpt_length`.

But, if a user manually inserts a `<!--more-->` tag inside the content, let's say after 10 words, it will show the 10 words only ( which is correct ), but it won't show the `Read more` ( or `... Continued` ) link.

A possible solution would be to search for `<!--more-->` tag and then conditionally show the either `the_content()` or the `the_excerpt()`.

```php
// Wordpress core uses the same regex to find the <!--more--> tag.
if (preg_match( '/<!--more(.*?)?-->/', $post->post_content, $matches)) {
  the_content(__('Read more', 'mytheme'));
}
else {
  the_excerpt();
}
```

However, I am not sure if it will cause issues to manually added `excerpts`.

**Comment by JBusch** [comment]
Having the same Problem

**Comment by retlehs** [comment]
not something we'd be looking to add to the theme by default, but others would find this helpful if you would share over at https://discourse.roots.io/

thanks!
