### ISSUE TITLE
'images' folder in 'dist' is not rebased in .css files

### ISSUE THREAD

**Issue by oleynikd** [roots/sage#1511]
Hi,

I've tried to search for answers but failed.

I'm using JS plugin ([swipebox](https://github.com/brutaldesign/swipebox)) that is managed with bower. Here's the bower.json overrides section:
```
"overrides": {
   "modernizr": {
      "main": "./modernizr.js"
   },
   "bootstrap": {
      "main": [
         "./less/bootstrap.less",
         "./js/transition.js",
         "./js/alert.js",
         "./js/button.js",
         "./js/carousel.js",
         "./js/collapse.js",
         "./js/dropdown.js",
         "./js/modal.js",
         "./js/tooltip.js",
         "./js/popover.js",
         "./js/scrollspy.js",
         "./js/tab.js",
         "./js/affix.js",
         "./fonts/glyphicons-halflings-regular.eot",
         "./fonts/glyphicons-halflings-regular.svg",
         "./fonts/glyphicons-halflings-regular.ttf",
         "./fonts/glyphicons-halflings-regular.woff",
         "./fonts/glyphicons-halflings-regular.woff2"
      ]
   },
   "swipebox": {
      "main": [
         "./src/js/jquery.swipebox.js",
         "./src/css/swipebox.css",
         "./src/img/**"
      ]
   }
}
```

### Question 1:
Not all files from `swipebox/src/img/` of plugin are copied to `dist/images/` There are 3 files:
![screenshot 2015-07-07 15 38 36](https://cloud.githubusercontent.com/assets/3976868/8546191/4bff43de-24be-11e5-96b7-092ba06a09ff.png)
But after gulp runs I get only 2 files in `dist/images/` :
![screenshot 2015-07-07 15 45 50](https://cloud.githubusercontent.com/assets/3976868/8546297/40885a44-24bf-11e5-91c2-12ac9ab81bd7.png)
So the question is **why? Where's `icons.svg` file?**

### Question 2:
What if other plugins have images with same filenames? How can I put different plugin's assets to different dist subfolders?

### Question 3:
Those copied images are not rebased in `swipebox.css` after 'compilation'
For ex. it was:
```
background-image: url(../img/icons.png);
```
and it is the same after `main.css` is created. **How to rebase them?**

Thanks in advance.

**Comment by QWp6t** [comment]
Since all of these are related to the `asset-builder` module, we'll likely have to wait for @austinpray to address this.

But to answer your questions more directly (and to the best of my knowledge).

1. Is `icons.svg` getting copied to `dist/fonts/`? What if you try specifying the [`images` property](https://github.com/austinpray/asset-builder/blob/master/help/spec.md#dependencies-serialization-)?
2. I don't know.
3. You could try using [scss/swipebox.scss](https://github.com/brutaldesign/swipebox/blob/master/scss/swipebox.scss) instead of the compiled css. I have limited experience with sass, so I'm not actually sure if it will rebase it for you, but it's worth a shot.

**Comment by oleynikd** [comment]
Hey @QWp6t Thanks for reply.

1. Yes it is copied to `fonts` folder but I'm not sure how to use `images` property for single dependency..?
2. :)
3. For some plugins sass is not an option so I'm looging for universal solution.

**Comment by QWp6t** [comment]
1. Oh, you're right. I was looking at it as a dependency instead of an override.
3. There isn't one. Overrides follow Bower.json specification.

http://bower.io/docs/creating-packages/#main
> **Image and font files may be used or referenced within the JS or Sass files, but are not main files as they are not entry-points.**
> 
> - Use source files with module exports and imports over pre-built distribution files.
> - Do not include minified files.
> - **Do not include assets files like images, fonts, audio, or video.**
> - Filenames should not be versioned (Bad: package.1.1.0.js; Good: package.js).
> - Globs like js/*.js are not allowed.

**Comment by oleynikd** [comment]
Dear @QWp6t thanks for your help.
Now I know how this should **not** be done..) But I still need help...
Anyone...please...

**Comment by austinpray** [comment]
@oleynikd 

>Not all files from swipebox/src/img/ of plugin are copied to dist/images/

change your assets/manifest.json to look like this https://gist.github.com/austinpray/9f11da29eeff1684431b#file-gistfile1-txt-L20-L26. [docs](https://github.com/austinpray/asset-builder/blob/master/help/spec.md#dependencies-serialization-)

>What if other plugins have images with same filenames? How can I put different plugin's assets to different dist subfolders?

Just copy the image from the plugin to your project's image folder and rename.

>Those copied images are not rebased in swipebox.css after 'compilation'

We don't do any rewriting of URLs or anything. Recommend trying and using the SCSS version and modifying the paths via variables or just override with regular CSS specificity. 

When you resolve this please contribute your solution back to https://github.com/austinpray/asset-builder/wiki/User-Contributed-Examples
