### ISSUE TITLE
new bower packages not include in main.js or anywhere

### ISSUE THREAD

**Issue by Kageetai** [roots/sage#1512]
Hi there,
I am trying to install a bower package to be used with the theme, so just usual and mentioned in the [docs](https://roots.io/sage/docs/theme-development/) I ran `bower install --save` but now the necessary are not added into the `main.js` like it says in the docs.
The package (https://github.com/IanLunn/jQuery-Parallax) has a main file declared in its own `bower.json` and everything but I just don't understand why the asset-builder or whatever's responsible for that is not processing the file...
Oh and I am running windows, just mentioning that because I read somewhere there are problems with the asset-builder under windows?

**Comment by JulienMelissas** [comment]
Personal support requests need to be made on the [Roots Discourse](https://discourse.roots.io/), please make a support thread there and close this out.

Thanks!
