### ISSUE TITLE
First npm install so takes time

### ISSUE THREAD

**Issue by isatrio** [roots/sage#1513]
Hi,

Sage is more better now, but takes time when first install the packages. Browser Sync is the problems I think. For just development phase I think it is not good, I know this feature was good but I need more fast start. I should waiting for 1-2 hours to finish the installation.

Is there any version without browser sync? Or maybe you need volunteer to create one? I'm happy to do it.

**Comment by austinpray** [comment]
Something is wrong on your end it it is literally taking 1-2 hours. For me:

```
npm install  117.19s user 32.58s system 132% cpu 1:52.83 total
```

You can definitely fork and remove browsersync, it's pretty loosely coupled with our project.

## remove the following

package.json

- https://github.com/roots/sage/blob/cd6095da82be2946a638a9651554db4da78e80e7/package.json#L31

gulpfile.js:

- https://github.com/roots/sage/blob/cd6095da82be2946a638a9651554db4da78e80e7/gulpfile.js#L4
- https://github.com/roots/sage/blob/cd6095da82be2946a638a9651554db4da78e80e7/gulpfile.js#L212
- https://github.com/roots/sage/blob/cd6095da82be2946a638a9651554db4da78e80e7/gulpfile.js#L225
- https://github.com/roots/sage/blob/cd6095da82be2946a638a9651554db4da78e80e7/gulpfile.js#L250-L257
