### ISSUE TITLE
How to add custom strings to translation

### ISSUE THREAD

**Issue by tubia** [roots/sage#1514]
Hi,
I would like to add my strings to the currently available theme translation in order to translate them. Is it possible?
What's the path to follow?
Thank you

**Comment by ptibbetts** [comment]
Hi @tubia,

You're more likely to get help with this if you start a new topic on [the forums](https://discourse.roots.io/c/sage).

The team use GitHub issues for bug reporting and pull requests and the forums for support requests like this.

**Comment by austinpray** [comment]
Thanks @ptibbetts

**Comment by tubia** [comment]
Hi @ptibbetts,
thank you for the explanation. I'll ask there.

P.s.: It would be great to have github SSO in the forums :)

**Comment by retlehs** [comment]
> P.s.: It would be great to have github SSO in the forums :)

@tubia done!
