### ISSUE TITLE
JavaScript Source maps "not used"

### ISSUE THREAD

**Issue by pablopaul** [roots/sage#1518]
Hey, 

any hints how to debug why JavaScript source maps are not "working" in my actual setup? 
The source maps get generated by gulp, in Chrome they are enabled (scss source maps are working…), the comment is present in the uglified dist js file, but Chrome does not apply the source map…

I am on Max OS X 10.10.4 and Chrome 43.0.2357.132.

Thanks

**Comment by Foxaii** [comment]
Please can you first take this kind of discussion to the [Roots Discourse forum](https://discourse.roots.io/). 

The issues tracker is for PRs, confirmed bugs and the occasional feature request as per our [Contributing Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md).

Thanks.
