### ISSUE TITLE
Watch task does not update prod files [workflow]

### ISSUE THREAD

**Issue by ricricucit** [roots/sage#1519]
Right now editing the _.scss files_ (or _JS files_) doesn't really get reflected in the browser while working, but if you run `gulp --production` i correctly see the modifications applied.

Shouldn't –the _watch task_– also run the `--production` task?
...or am i missing something about sage's workflow?

**Comment by bostondv** [comment]
+1

**Comment by austinpray** [comment]
So I just tried this and the current workflow is working. 

1. run `gulp watch`
2. change background color to blue in main.scss
3. styles task is triggered and completes, refresh page
4. background color is blue

and

1. run `gulp watch --production`
2. change background color to blue in main.scss
3. styles task is triggered and completes, refresh page
4. background color is blue

Have you looked at the actual output to see if any changes are landing in your `dist` folder? If the changes are landing in the dist folder but not making it to your browser it's probably a caching issue. The only difference between `gulp` and `gulp --production` is that production revs the assets and breaks the cache.

I need more information about your setup and your issue. I don't have enough information to reproduce.

**Comment by ricricucit** [comment]
Thanks!
I simply wasn't aware of the `watch --production` command (didn't check how the whole gulpfile.js was working)

So my suggestion is to simply add it to the list of **Available gulp commands** in the **_readme.MD_** file.

**Comment by austinpray** [comment]
Ok yes I agree that can be confusing.

Right now we have:

>
**Available gulp commands**
gulp — Compile and optimize the files in your assets directory
gulp watch — Compile assets when file changes are made
gulp --production — Compile assets for production (no source maps).

This should really be

>
**Available gulp commands**
gulp — Compile and optimize the files in your assets directory
gulp watch — Compile assets when file changes are made
**Available gulp flags**
--production — Run task in production mode. This disables source maps and turns on asset revving.

**Comment by ricricucit** [comment]
Yes, or since there are just a few commands, simple examples to those who aren't yet familiar with gulp and flags.

eg.

> **Available gulp commands**
> gulp — Compile and optimize the files in your assets directory
> gulp watch — Compile assets when file changes are made
> gulp watch --production — Compile and optimise assets for production (in the _dist_ folder) when file changes are made (no source maps)
> gulp --production — Compile assets for production (no source maps).

...and also (in case that's going to grow)

> **Available gulp _flags_**
> --production — Run task in production mode. This disables source maps and turns on asset revving.

**Comment by bostondv** [comment]
`gulp watch --production` works for me as well but without `--production` flag it does not. 

Styles and scripts are generated in the `dist` correctly without the revved file names (eg. main.css). But WordPress still looks for the revved file (eg. main-0c104ddc.css). 

`assets.json` also references the revved file names and seems to control what files WordPress loads. So if I manually remove the revs from assets.json it works. But shouldn't running `gulp watch` without a flag update assets.json accordingly so WordPress loads the non-revved files?

**Comment by kalenjohnson** [comment]
@bostondv does `gulp watch` work if you run `gulp` before, without the production flag?

**Comment by bostondv** [comment]
Ah... it does!
