### ISSUE TITLE
Unable to use CSS background-image

### ISSUE THREAD

**Issue by robabby** [roots/sage#1520]
Hey there, I am unsure if this is an issue with Wordpress, Sage, or both, but I am unable to successfully use CSS background-image to reference an image I am trying to use with my theme.  It keeps giving me a 404, even though I can see in the path printed out in Chrome Dev Tools is correct.

The code I have tried:
`background-image:url('../images/el_tracks.jpg');`
`background-image:url('/dist/images/el_tracks.jpg');`
`background-image:url('/wp-content/theme/sage/dist/images/el_tracks.jpg');`
`background-image:url('/wp-content/theme/sage/assets/images/el_tracks.jpg');`

I can see that the CSS is being minified into the dist/styles folder, and my image is in dist/images.

**Comment by retlehs** [comment]
Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/))
