### ISSUE TITLE
.jscs validateJSDoc depricated

### ISSUE THREAD

**Issue by chrisk2020** [roots/sage#1521]
I was having some issues with JSCS returning `Unsupported rule: validateJSDoc` it seems this rule has been depricated, but is still present in the .jscsrc file. I think simply updating to `jsDoc` fixes the issue. http://jscs.info/rule/jsDoc.html

**Comment by QWp6t** [comment]
You wanna submit a PR?

If not, we can update it ourselves. Just figured I'd give you the opportunity to take credit for the commit if you want.

**Comment by chrisk2020** [comment]
thanks - pull request created https://github.com/roots/sage/pull/1522
