### ISSUE TITLE
Theme activation error

### ISSUE THREAD

**Issue by jarc100** [roots/sage#1526]
When i activate my theme i get this two errors:

>Warning: include(): Filename cannot be empty in /nfs/c09/h03/mnt/189202/domains/disennio.com/html/wp-includes/template-loader.php on line 74

>Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/local/php-5.5.21/share/pear') in /nfs/c09/h03/mnt/189202/domains/disennio.com/html/wp-includes/template-loader.php on line 74

I've search but cant't find nothing about it. I hade PHP 5.3 but i upgrade it before do the deployment.

These are the files in my theme:

![image](https://cloud.githubusercontent.com/assets/617945/9238014/b8209028-4114-11e5-8c35-f531eb901585.png)

**Comment by retlehs** [comment]
this isn't the place for support - use https://discourse.roots.io

also, this isn't an issue with the theme. definitely an issue with your setup.

**Comment by QWp6t** [comment]
Looks like you removed `base.php`.
