### ISSUE TITLE
Fresh install gives "libsass bindings not found" error

### ISSUE THREAD

**Issue by ronnyandre** [roots/sage#1533]
I just installed Bedrock and Sage, went through the Node, NPM, Bower and Gulp install steps.

When I try to run `gulp watch` the first time, I get the following error message:

    /Users/username/Sites/fardalgard/web/app/themes/fardalgard/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
    Error: `libsass` bindings not found in /Users/username/Sites/fardalgard/web/app/themes/fardalgard/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/username/Sites/fardalgard/web/app/themes/fardalgard/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)

Tried reinstalling SASS with `npm install -g node-sass` without luck.

**Comment by retlehs** [comment]
please don't use github for support. see https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060 to help debug the issues you're running into on your machine.
