### ISSUE TITLE
Errors on trying to install npm

### ISSUE THREAD

**Issue by AndySimmers** [roots/sage#1534]
Hi there,

I am new to the Sage setup, and have been trying to get up and running.  I have installed  latest versions of Node, gulp and Bower, however get some fairly stinky looking error messages when I try to run the npm install.

I'm running Windows 7 - any advice on how I can untangle the issue would be much appreciated.

C:\Windows\system32>cd c:\xampp\htdocs\wp\wp-content\themes

c:\XAMPP\htdocs\WP\wp-content\themes>git clone https://github.com/roots/sage.git
 cch-new
Cloning into 'cch-new'...
remote: Counting objects: 7623, done.
remote: Total 7623 (delta 0), reused 0 (delta 0), pack-reused 7623
Receiving objects: 100% (7623/7623), 3.50 MiB | 704.00 KiB/s, done.
Resolving deltas: 100% (4473/4473), done.
Checking connectivity... done.

c:\XAMPP\htdocs\WP\wp-content\themes>cd /cch-new
The system cannot find the path specified.

c:\XAMPP\htdocs\WP\wp-content\themes>cd cch-new

c:\XAMPP\htdocs\WP\wp-content\themes\cch-new>npm install
/
> gifsicle@3.0.1 postinstall c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_m
odules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_m
odules\gifsicle
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_mod
ules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\node_modules\glob
-stream\node_modules\unique-stream\node_modules\through2-filter\index.js:9:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

> jpegtran-bin@3.0.4 postinstall c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\no
de_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\no
de_modules\jpegtran-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_mod
ules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\node_modules\glob
-stream\node_modules\unique-stream\node_modules\through2-filter\index.js:9:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0

> optipng-bin@3.0.2 postinstall c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\nod
e_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node
_modules\optipng-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_mod
ules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\node_modules\glob
-stream\node_modules\unique-stream\node_modules\through2-filter\index.js:9:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
-

> spawn-sync@1.0.13 postinstall c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\nod
e_modules\gulp-sass\node_modules\node-sass\node_modules\sass-graph\node_modules\
yargs\node_modules\os-locale\node_modules\exec-file-sync\node_modules\spawn-sync

> node postinstall

/
> node-sass@3.2.0 install c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_modu
les\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\
node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-14\binding.node

> node-sass@3.2.0 postinstall c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_
modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

` c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\node_modules\gulp-sass\node_modul
es\node-sass\vendor\win32-ia32-14\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\ANDY~1.SIM\AppData\Local\Temp\npm-1848
-10738ae0\registry.npmjs.org\browser-sync-ui\-\browser-sync-ui-0.5.15.tgz
npm ERR! Expected: c3a684313aaa379783231d826a5c6d8e3b5da128
npm ERR! Actual:   24249fb396912c845bece7f0fc8cfc8a7971f939
npm ERR! From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-
0.5.15.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\XAMPP\htdocs\WP\wp-content\themes\cch-new\npm-debug.log

**Comment by retlehs** [comment]
see https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060

also, please use roots discourse in the future for support instead of github issues

**Comment by AndySimmers** [comment]
thanks Ben, up and running now I sorted the Windows NPM file location issue
