### ISSUE TITLE
Installtion error, hard to found the mistake

### ISSUE THREAD

**Issue by webtuts4u** [roots/sage#1535]
I am new in roots sage theme. I am facing the uncertain error and not founding my mistake.
Too much googling and decide to create issue.

Error npm install
![npm install error](https://cloud.githubusercontent.com/assets/3891930/9583199/8a1052d2-5027-11e5-9b14-06e1f35e2857.png)

I am trying to reinstall all setup like node, gulp, bower. But no luck.
Hope for the best. Any body help me to fix this or suggest some thing to fix this.

Thanks

**Comment by retlehs** [comment]
see https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060

also, please use roots discourse in the future for support instead of github issues
