### ISSUE TITLE
Improve load times by loading JQuery from CDN

### ISSUE THREAD

**Issue by henrify** [roots/sage#1550]
While I can understand that bootstrap with its custom Sass builds and the need to reference (include/extend) it from Sage's styles can be tricky to make external, I cannot understand why you are not loading what seems to be stock standard JQuery from CDN? 

If this is indeed stock standard JQuery, please add build option and/or documentation how to load it from CDN. 95% of end users have CDN JQuery cached so this will save 100kb worth of page load time.

**Comment by austinpray** [comment]
We used to have this but removed it. It's now a roots/soil feature. https://github.com/roots/sage/pull/1301

**Comment by kalenjohnson** [comment]
Also, it is part of Sage by default, if you also have Soil installed:

https://github.com/roots/sage/blob/master/lib/config.php#L14

**Comment by henrify** [comment]
That's perfect, thanks for your fast replies.
