### ISSUE TITLE
DOM-based Routing and getting dimensions

### ISSUE THREAD

**Issue by johnteakdigital** [roots/sage#1551]
Having an issue with the `main.js` file. Trying to gather dimensions eg `.innerHeight()` once the page has loaded, but because the `UTIL` function is wrapped in `.ready()`it won't fire at the correct time. I've tried using `.load()` but anything I put in the handler gets skipped, thus I'm unable to gather dimensions of DOM objects. 

eg

```
...
var Sage = {
    // All pages
    'common': {
      init: function() {
       ...
      },
      finalize: function() {
        // JavaScript to be fired on all pages, after page specific JS is fired

        // My code
        thingWidth = $('#thing').innerWidth();
        console.log('thing width =' + thingWidth);
        //does not calculate correctly

        $('#thing').load( function(){
          // never fires
          thingWidth = $('#thing').innerWidth();
          console.log('thing width =' + thingWidth);
        });
        //end My code
     },
...
    };
...
// Load Events
  $(document).ready(UTIL.loadEvents);
...
```

**Comment by mAAdhaTTah** [comment]
`$('#thing')` is already loaded once the document is "ready", so the `load` callback will never fire. `$('#thing').innerWidth();` should just work within the `finalize` function fine. Are you seeing issues there?

**Comment by QWp6t** [comment]
[Not a bug](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker) or issue with Sage.

For personal support like this, please use [our community forum](https://discourse.roots.io/c/sage).

**Comment by johnteakdigital** [comment]
Sorry, I thought it was a bug, because it wasn't firing in finalize. But I'll move to the forum. Thanks
