### ISSUE TITLE
Reduce compile time of CSS bundles

### ISSUE THREAD

**Issue by aumo** [roots/sage#1552]
Currently, the whole styles are compiled twice:
- firstly as the `main.css` bundle
- secondly as the `editor-style.css` bundle because `main.scss` is imported in `editor-style.scss`.

Is there a justification or would it be enough to just concatenate, or include, the two files?

**Comment by JulienMelissas** [comment]
@aumo - thanks for bringing this up. I looked into it a little bit yesterday and hope to have a better solution soon.

I totally agree that it seems to be pretty redundant, but I personally like the fact that I can add editor-only overrides after my site styles, so I'm not sure I want to get rid of that functionality.

Anyways, know I'm looking into it more and will report back.

**Comment by JulienMelissas** [comment]
@aumo leave some thoughts here if you would please: https://github.com/roots/sage/pull/1560!

**Comment by retlehs** [comment]
closed by #1560
