### ISSUE TITLE
Bower Install fails

### ISSUE THREAD

**Issue by jjrchrds** [roots/sage#1561]
On MAC Yosemite v. 10.10.5
npm 3.3.5
bower 1.5.2

npm install works fine
bower install fails
gives a Module_Not_Found error, I globally installed one of the modules, but then it just failed on the next one.

Any assistance?

**Comment by PTiCA1** [comment]
To me this version everything works properly.
I had to first delete folders node_modules and bower_components

And then re-install.

**Comment by retlehs** [comment]
see https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060

please don't use github for support, head over to https://discourse.roots.io/
