### ISSUE TITLE
get_header found in base.php - Should this be relocated to the top of the file?

### ISSUE THREAD

**Issue by ryanlabelle** [roots/sage#1567]
I ran into an issue today with a plugin that calls the get_header hook, expecting that this was getting called at the very top of the page (before any output) but since it's down around line 18 it was causing some issues. I noticed that the [WP Codex found here](https://codex.wordpress.org/Plugin_API/Action_Reference/get_header) says: 

> Note: This hook is best to use to set up and execute code that doesn't get echo'd to the browser until later in the page load. Anything you echo will show up before any of the markup is displayed.

So, granted that the plugin shouldn't be outputting anything it would still be safe to assume that this hook is going to be one of the first things output on the page, no? 

Sage makes use of get_template_part('templates/head') vs the WordPress defaults (Twenty Fifteen theme) get_header() so I can see where the confusion is.

The [change log](https://github.com/roots/sage/blob/61022e07e71ee636949d79e1b3d4853391c4ec47/CHANGELOG.md) says this was added to support WooSidebars, is that still the case? Would it break anything to move this to the top of base.php?

Just some food for thought. Other plugins might be running into this issues as well. 

Best regards,
Ryan

**Comment by retlehs** [comment]
> I ran into an issue today with a plugin that calls the get_header hook, expecting that this was getting called at the very top of the page (before any output) but since it's down around line 18 it was causing some issues. 

what plugin?

what issues?

**Comment by ryanlabelle** [comment]
HI Ben! 

https://boxystudio.ticksy.com/ticket/563116

All the details are there. Cheers.

**Comment by retlehs** [comment]
we still don't know what plugin that is... need to know what the plugin is and need to see the plugin code.

**Comment by ryanlabelle** [comment]
ah yes, here you are:

[Booked - Appointment Booking for WordPress](http://codecanyon.net/item/booked-appointment-booking-for-wordpress/9466968)

It's a paid plugin, but 100% GPL so I think I can send you a copy if you need it.

**Comment by boxystudio** [comment]
@ryanlabelle: Yep, feel free to send him a copy for testing purposes. ;)

**Comment by ryanlabelle** [comment]
Thanks @boxystudio , @retlehs , what's the best way to send you a copy?

**Comment by retlehs** [comment]
while we could move the hook up, that plugin shouldn't be using the `get_header` hook for what it's doing. since this is an issue with a paid plugin doing weird things (:hankey: code), i'm closing this out.
