### ISSUE TITLE
Custom icon font gulp task

### ISSUE THREAD

**Issue by oxyc** [roots/sage#1568]
On one of my own projects I've set up a gulp task using:
- [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont)
- [gulp-iconfontcss](https://github.com/backflip/gulp-iconfont-css)

It looks for svg icons within `assets/icons` and then generates a sass file which you can include in your `main.scss`.

This way you can add your own icons as well as copy the [FontAwesome](https://github.com/encharm/Font-Awesome-SVG-PNG) ones you actually use to get a lightweight icon font.

Is this something you're interesting in adding to sage? If so I can polish it up and send over a pull request for further improvement.

Examples:
- [SASS template](https://github.com/generoi/sage/blob/genero/assets/icons.template.scss)
- [gulp task](https://github.com/generoi/sage/blob/cf6c3ef024062c84fc4755b3efc579c43aa1e7c1/gulpfile.js#L360:L375)

The gulp task still needs some polishing but it gives you an idea at least.

**Comment by ciromattia** [comment]
Not a "technical" comment, but I used to go with iconfonts until I came across [this article on CSS-Tricks](https://css-tricks.com/icon-fonts-vs-svg/) and it happens Sage works wonders with [automating SVG](https://github.com/roots/sage/pull/1492), so you could consider both to share your snippet in the [Roots discourse](https://discourse.roots.io) and maybe to switch to inline SVGs ;)

**Comment by oxyc** [comment]
@ciromattia sweet, thanks for the links! Too bad about the rusty `<use>` support but the solution suggested seems good enough
