### ISSUE TITLE
Edits to .scss files not showing up in main.scss

### ISSUE THREAD

**Issue by codyschuldt** [roots/sage#1574]
I'm just getting started using Sage and setting up a good workflow, so sorry if this is a dumb question.  I have everything set up great on one project, so I duplicated that project using DesktopServer and have run into one issue.  When I'm making changes to the partials (like _header.scss) and hit save, CodeKit gives me the message that main.scss was compiled, but my changes that I made to _header.scss aren't reflected when the Live Reload refreshes the browser.  I don't have this problem in the other project that I copied this one from, so that one's set up perfectly and this is a copy, so I don't understand where the disconnect is.  Everything else is working fine, but this is driving me crazy.

**Comment by retlehs** [comment]
couple things:

- please use https://discourse.roots.io/ for questions/support

- why are you using codekit and livereload? we won't support that - you'll need to use the gulp + bower + asset-builder + browsersync workflow that's included in sage. this is described in the README, in the docs, and in the book

see https://roots.io/sage/docs/theme-development-and-building/
