### ISSUE TITLE
Bootstrap javascript doesn't inject

### ISSUE THREAD

**Issue by orggue** [roots/sage#1580]
I'm trying to add some javascript files from the default bootstrap-sass folder in bower_components, for example the bootstrap collapse.js but there is no way to inject this files. bootstrap is injected properly because of the main.scss file.
```sass
@import "../../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
```

**Comment by QWp6t** [comment]
They're all specified right here: https://github.com/roots/sage/blob/master/bower.json#L12-L35

But this isn't the place to ask for support. The issue tracker is for reporting bugs or requesting features. For support, use the forums. https://discourse.roots.io/
