### ISSUE TITLE
Can't activate theme.

### ISSUE THREAD

**Issue by amreed8** [roots/sage#1581]
Greetings,

When I test in my localhost, the theme activates.
When I upload to my hosting company, I cannot activate.

Wonderful theme that combines B3 and WP.

Thank you.

**Comment by swalkinshaw** [comment]
Sage [requires PHP 5.4](https://github.com/roots/sage#requirements). My only guess is that your hosting company might be using 5.3 by default still. You can contact them and get them to confirm + see if they can update it.

But beyond that we can't provide much help without any more details. Please also use https://discourse.roots.io/ for personal support.
