### ISSUE TITLE
Installing on Wordpress Issue

### ISSUE THREAD

**Issue by LunarDevelopment** [roots/sage#1585]
Hello! 

I'm new to wordpress and after I upload my theme from localhost worpress (working fine) to the live wordpress via the wordpress "themes" -> "upload" option I get the following error: 

Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme install failed.

Obviously if this were a normal site I'd just ensure the html tags were looking for the minified --production file names but I don't know how to do this with wordpress yet. 

Is there an easy way of compiling the roots files into a zip that wordpress accepts?

Lewis

**Comment by QWp6t** [comment]
Out of the box Sage can be zipped up and installed on WordPress no problem (failure install dependencies and compile assets notwithstanding). It sounds like you removed style.css from the root directory of Sage.

This is the file WordPress wants: https://github.com/roots/sage/blob/master/style.css
