### ISSUE TITLE
No Page Template Option in the Page Edit Panel

### ISSUE THREAD

**Issue by fred-pedro** [roots/sage#1586]
Is there something needed to be done to display the Page Template section in the Page Edit Panel? I can't see the drop-down where you can select the Page Templates. I can only see the Parent and Order options of the Page Attributes.

**Comment by QWp6t** [comment]
It means you deleted the custom template file.

Simply create another template file, and it will show back up.

For future reference, use https://discourse.roots.io/ for support questions like this one.
