### ISSUE TITLE
What is tinymce.scss for?

### ISSUE THREAD

**Issue by henrikra** [roots/sage#1600]
Hello and thanks for the great starter theme! Can you tell me where tinymce.scss file is for?

**Comment by QWp6t** [comment]
The example code we have in it sets the padding for the "visual editor" in the WordPress admin panel. The "visual editor" is powered by TinyMCE, hence the name of the scss file.

**Comment by Foxaii** [comment]
Please keep questions like this to the [Discourse Forum](https://discourse.roots.io/) in future. Thanks.
