### ISSUE TITLE
Depreciated NPM Modules

### ISSUE THREAD

**Issue by BrandonShutter** [roots/sage#1601]
Fresh Install of sage and running into some depreciated modules:

```npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.```
```npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0```
```npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm```

**Comment by QWp6t** [comment]
Only `gulp-minify-css` is a Sage dependency. Since we're redoing our asset pipeline in Sage 9, it shouldn't be an issue to swap it out. Thanks for the heads up.

I don't think we can do anything about the other two. Feel free to report upstream if you want.

**Comment by BrandonShutter** [comment]
👍
