### ISSUE TITLE
exclude certain css and js from bootstrap

### ISSUE THREAD

**Issue by v3nt** [roots/sage#1604]
We're creating a really light site and we don't need most of Bootstrap's feature's and function. How can we exclude these from the final .css & .js files to make it lighter?

**Comment by scottstreit** [comment]
@V3nt,

This should help you.

https://github.com/purifycss/purifycss

**Comment by retlehs** [comment]
as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/

this question is already covered in a lot of different areas: on our forums, in the gulp/bower screencast, in the sage book, and even on a blog post on our site. 

please search next time.
