### ISSUE TITLE
Add gulp-newer to check for modified files

### ISSUE THREAD

**Issue by mahammedzkhan** [roots/sage#1605]
https://www.npmjs.com/package/gulp-newer

This would be useful especially for the `imagemin` gulp task because minifying images takes some time. It will only run on the images newer then the ones in the `dist` folder. Can be used for the other tasks as well but mostly it's the `imagemin` task which takes a lot of time.

**Comment by retlehs** [comment]
open to a PR, but sage 8 is really just in maintenance mode right now as we're focused on sage 9.
