### ISSUE TITLE
Version composer.json?

### ISSUE THREAD

**Issue by ekandreas** [roots/sage#1606]
It's not possible to install roots/sage via composer with create-project as there is no version in composer.json?
```bash
composer create-project roots/sage web/app/themes/your-theme-name-here
```
get's message:
```
[InvalidArgumentException]
  Could not find package roots/sage with stability stable.
```
No manipulations to Bedrock composer.json done...

**Comment by aguimaraes** [comment]
+1 here

**Comment by QWp6t** [comment]
It's because there haven't been any tagged releases of Sage since Composer.json was introduced. Once we tag a release (i.e., mark a stable version), it will work.

https://github.com/roots/sage/pull/1599#issuecomment-174588450

**Comment by ekandreas** [comment]
So version 8.4.0 isn't stable enough? Features, tests, what's missing?

**Comment by ekandreas** [comment]
Then the documentation should be updated since the command described isn't working :-)

**Comment by QWp6t** [comment]
The docs are fine.

https://roots.io/sage/docs/theme-installation/

You're looking at the README.md in the development branch, which, again, hasn't been marked as stable. I'm not sure what's blocking a new tagged release, but the only thing that differs between the current development (master) branch and the latest tagged (8.4.0) release is the addition of composer.json.
