### ISSUE TITLE
Modularize javascript

### ISSUE THREAD

**Issue by PabloMarch** [roots/sage#1611]
Hello guys,

More than an issue is a question. My wordpress theme is start growing and there are many js functionality that is share between pages, I've been using the body class to initialize scripts as sage currently does but in this way I've had to call my modules in each page because I couldn't assign new classes to the body from my template part (ex: module-gallery), to solve this I've create a new function into UTIL :

```
  loadComponents: function() {
    var $component = $('[data-component]');

    // Fire a component instead a page
    $.each($component.data(), function(i, classnm) {
      this.fire(classnm.replace(/-/g, '_'));
      this.fire(classnm, 'finalize');
    });
  }
```
I assign a 'data-component' to each module and check whether it exists on page, this way I can call components instead of pages but the problem now is that I've had to create each component into a jQuery plugin because I couldn't find a way to move my code outside of the main.js and It starts getting too big and hard to maintain for that reason I've decided to restructure my sage scripts to use browserify. Please let me know if there is another way to modularize the current code and avoid changes on the template config.

Thanks!
Marchena

**Comment by blitz999** [comment]
This topic is being discussed here: https://discourse.roots.io/t/add-isotope-just-in-one-page/5699/8

**Comment by retlehs** [comment]
as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/
