### ISSUE TITLE
vendor/autoload not working in sage/function

### ISSUE THREAD

**Issue by eshimischi** [roots/sage#1613]
sage/functions.php#L29 whats it for? it doesn't work or perhaps i missed something?

**Comment by retlehs** [comment]
the sage 9 branch, yes? you need to run `composer install` first. it's for [autoloading files](https://github.com/roots/sage/blob/4edb695d7717c34fee88036b419cdd6f1036eac6/composer.json#L26-L36)

as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/

**Comment by eshimischi** [comment]
@retlehs yeah Sage 9! i thought about but avoid the composer install, thanks for the tip! Very nice project btw, long live!
