### ISSUE TITLE
Font Awesome doesn't work with "gulp watch"

### ISSUE THREAD

**Issue by henrikra** [roots/sage#1615]
I installed Font Awesome correctly with bower and added overrides to bower.json. This is minor bug and I will report it.

If I just run `gulp` and refresh the site myself the icons work. When I run `gulp watch` the icon won't show.

**Comment by cdrlee** [comment]
Font Awesome works well for me.

"font-awesome": {
"dependencies": {
    "bootstrap-sass": "3.3.6",
    "font-awesome": "fontawesome#~4.5.0"
  },

      "main": [
        "./scss/font-awesome.scss",
        "./fonts/*"
      ]
    }

**Comment by retlehs** [comment]
as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/
