### ISSUE TITLE
Use gulp-cssnano only in production

### ISSUE THREAD

**Issue by costidima** [roots/sage#1622]
Why don't you use gulp-cssnano only when '--production' arg is used so we don't have to minify the styles on 'watch' task. It takes 6-7 additional seconds on 'styles' task when we use gulp-cssnano

**Comment by retlehs** [comment]
for parity between dev and prod, which has been discussed a bunch if you search gh issues/our discourse. we're also no longer making any changes to sage 8 as we're now focused on making changes to the front-end workflow in sage 9
