### ISSUE TITLE
display_sidebar conditional: is_page_template() requires the name of the subfolder

### ISSUE THREAD

**Issue by ptrckvzn** [roots/sage#1624]
In Sage 9 : the display_sidebar conditional should be updated to include the templates folder since he template-custom.php has been move to templates/template-custom.php.. See my [commit](https://github.com/ptrckvzn/sage/commit/efb28452f7f1915f772d53db38fff195785ee984).

See : [Page template in subdirectory](https://developer.wordpress.org/reference/functions/is_page_template/)

Should I make a pull request?

**Comment by retlehs** [comment]
yes please! nice catch

**Comment by QWp6t** [comment]
Have you actually tested this? I think because of the way we load the templates, that's not actually correct. I predict that it would be unnecessary to specify the `templates/` folder here. Before making a PR, feel free to actually test it if you haven't already.

**Comment by nusserstudios** [comment]
You don't have to, I've always moved my template-custom.php to templates/ and WordPress always picks it up. So QWp6t is correct.

**Comment by ptrckvzn** [comment]
I noticed my template wasn't loading and added `tempates/` and it worked. I think the change might not be needed in the `app/filters.php`. I just noticed in `composer.json` my theme use the files in `src/*`. I will test if src/filters.php needs the folder and report back here.

**Comment by ptrckvzn** [comment]
I just tested this with the latest sage-9 branch. The template-custom.php loads the sidebar even though it is listed in the display_sidebar filter. It works as expected (no sidebar) when I put the directory. "templates/template-custom.php". I am doing a PR, but feel free to test on your side to.
