### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by codyme** [roots/sage#1636]
Hi there
I know github might not be the best place to ask this, but I couldn't find any contact forms or other way of direct communication on the Roots website.... so..... please excuse me for asking this here.
I was wondering if I can use this theme for commercial purposes? what sort of licence does this theme have? I couldn't find this anywhere either.... please advise. thanks.

**Comment by retlehs** [comment]
our projects are MIT licensed

https://github.com/roots/sage/blob/master/LICENSE.md

https://tldrlegal.com/license/mit-license

**Comment by codyme** [comment]
thanks
