### ISSUE TITLE
Nested shortcodes

### ISSUE THREAD

**Issue by dhyegofernando** [roots/sage#1637]
Hi, first of all I know which my problem is not at all related to the **sage** project but I know that your advanced *wordpress* knowledge can help me to get through that.

p.s. I've been creating my shortcodes upon sage scaffolding.

I built two shortcodes for nested using:

```html
[outdoor]
  [outdoor_item title="My title 1" color="orange"]<strong>The</strong> 1st Content[/outdoor]
  [outdoor_item title="My title 2" color="blue"]<strong>The</strong> 2nd Content[/outdoor]
  [outdoor_item title="My title 3" color="green"]<strong>The</strong> 3rd Content[/outdoor]
  [outdoor_item title="My title 4" color="red"]<strong>The</strong> 4th Content[/outdoor]
[/outdoor]
```

After lots of hours searching something in stackoverflow and google I figured it out that I had to apply `do_shortcode()` in my RAW `outdoor` shortcontent content... something like this:

```php
add_shortcode('outdoor', function($atts, $content, $tag) {
   return '<div class="outdoor">' . do_shortcode($content) . '</div>';
});
```

and then my problem comes out... **the function `do_shortcode()` renders ONLY my first `outdoor_item` and ignores every `outdoor_item` else**. It outputs something like this:

```html
<div class="outdoor">
  <div class="outdoor-item" style="background-color: orange">
    <h1>My title 1</h1>
    <div class="outdoor-item-content">
      <strong>The</strong> 1st Content
    </div>
  </div>
</div>
```

p.s. I've tried `do_shortcode()`, `apply_filters('the_content', $content)` and even `wp_reset_postdata()` after each `outdoor_item` call.

WHAT ELSE COULD I DO? :(

**Comment by austinpray** [comment]
>Hi, first of all I know which my problem is not at all related to the sage project

https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Questions like this belong on https://discourse.roots.io

**Comment by QWp6t** [comment]
Use `[/outdoor_item]`.

And next time please post on our forum or StackOverflow or something. This issue tracker is for people who are interested in aiding with (or at least monitoring) the development of Sage.

If you have a project you're working on and you want our help, the proper place to ask us is right here: https://roots.io/services/
