### ISSUE TITLE
Parse error on fresh install

### ISSUE THREAD

**Issue by jaakk** [roots/sage#1638]
**Setup:**
Sage latest version (Sage 8.4.2)
WP latest version 4.5.1
MediaTemple (gs) Grid-Service PHP 5.5.31

**Parse error: syntax error, unexpected '[' in /…/wp-content/themes/sage-master/functions.php on line 12**

Just installed the Sage theme from github .zip download without any further modifications.

**Comment by swalkinshaw** [comment]
If MediaTemple is telling you it's running PHP 5.5 then they are lying 😢 

That error means PHP doesn't recognize the short array syntax which was added in 5.4: http://php.net/manual/en/migration54.new-features.php

**Comment by jaakk** [comment]
Interesting! My **<?php phpinfo(); ?>** in MediaTemple is printing "PHP Version **5.5.31**" 
![screenshot 2016-04-27 00 18 25](https://cloud.githubusercontent.com/assets/248971/14834599/f0f7d5ae-0c0d-11e6-9f68-0cc5cde0a6a5.png)

**Comment by Foxaii** [comment]
Check if Media Temple can configure different versions of PHP on a per site basis. It cannot be anything else.

**Comment by blitz999** [comment]
MT can be self-configured up to 5.6+ - check the kb. I've had issues with Sage 8 and this version on MT. You can update to 5.6, which stopped some other errors and may help here.
