### ISSUE TITLE
Conflicting autoprefixers?

### ISSUE THREAD

**Issue by Nocklas** [roots/sage#1639]
Since we're using autoprefixer, shouldn't we add autoprefixer: false by default to cssNano since it will remove prefixes for IE etc. if we add them to the browsers list of autoprefixer?

The part of the gulp-file I'm talking about:
`.pipe(autoprefixer, {
      browsers: [
        'last 2 versions',
        'android 4',
        'opera 12'
      ]
    })
    .pipe(cssNano, {
      safe: true
    })`

**Comment by marcelo2605** [comment]
I had a problem with this today. The default autoprefixer browser list do not add prefix to `justify-content`, and Safari 8 need this. 

So I edit this part to: `.pipe(autoprefixer, {browsers: ['last 2 versions', 'safari 8', 'android 4', 'opera 12'] })`.

But cssNano run autoprefixer too, and by default do not include prefix to `justify-content`. So what autoprefixer add, cssNano remove.

The solution was to disable autoprefixer in cssNano, as suggested above by @Nocklas.

**Comment by retlehs** [comment]
closing as we're not focused on sage 8, but would be open to a PR if someone cares enough about it
