### ISSUE TITLE
Update docs to reflect that sage 8 does not currently support node 6

### ISSUE THREAD

**Issue by aried3r** [roots/sage#1641]
It's actually not sage itself that doesn't support it, but some dependencies, like [node-sass](https://github.com/sass/node-sass/issues/1484) (also [this](https://github.com/sass/node-sass/pull/1506#issuecomment-215943430) are not compatible with node 6 yet, also graceful-fs.

Until this is fixed, or Sage 9 is released, which changes a lot of things, I'd recommend putting
*Node >= 0.12.x, < 6.x*
into the documentation.

**Comment by ciromattia** [comment]
This is not actually true.
I'm using sage 8 with an updated node, and despite I had to mess in updating my -g packages, at the moment it works, though giving quite a bunch of node warnings in running gulp (I think the main offender here is node-sass and its dependencies)

**Comment by aried3r** [comment]
That's great to hear!
Do you mind sharing the steps you needed to take to get it running? Since it doesn't seem to work out of the box.

My main problem was (even after rebuilding node-sass) that `main.scss` was not being compiled to `main.css`, only throwing lots of JS stack traces.
Thus my site was left unstyled.

**Comment by ciromattia** [comment]
You have to ```rm -rf node_modules/*``` and then ```npm install``` again, because libsass needs new bindings.
Also, my package.json is now:
```
"devDependencies": {
    "asset-builder": "^1.1.0",
    "browser-sync": "^2.8.2",
    "del": "~2.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "~3.1",
    "gulp-changed": "^1.3.0",
    "gulp-concat": "^2.6.0",
    "gulp-cssnano": "^2.1.0",
    "gulp-flatten": "~0.2",
    "gulp-if": "~2.0",
    "gulp-imagemin": "^2.3.0",
    "gulp-inject": "^4.0.0",
    "gulp-jshint": "^2.0.0",
    "gulp-less": "^3.0.3",
    "gulp-plumber": "^1.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "~7.0",
    "gulp-sass": "^2.0.1",
    "gulp-sourcemaps": "*",
    "gulp-svg2png": "~1.0",
    "gulp-svgmin": "^1.2.0",
    "gulp-svgstore": "~6.0",
    "gulp-uglify": "^1.2.0",
    "imagemin-pngcrush": "^4.1.0",
    "jshint": "^2.9.2",
    "jshint-stylish": "^2.0.1",
    "lazypipe": "^1.0.1",
    "merge-stream": "^1.0.0",
    "minimist": "^1.1.3",
    "run-sequence": "^1.1.2",
    "traverse": "^0.6.6",
    "wiredep": "~4.0.0"
  }
```
(svg stuff is for SVG sprites)
IIRC I have updated also a bunch of global packages, you can check your mileage with ```npm -g outdated```.
