### ISSUE TITLE
Issue with Gulp pipeline and sass package

### ISSUE THREAD

**Issue by lkhedlund** [roots/sage#1646]
I originally brought this up as an issue with the package owers, but it seems to be a problem with the way the gulpfile builds nested packages, so it might be something on the Sage end. Here's my issue submission with the package:

[gulp build fails on line 40 of bower_components/bootstrap-material-design/scss/_variables.scss](https://github.com/FezVrasta/bootstrap-material-design/issues/995#issuecomment-217579412)
---

**What is the current behavior?**
Gulp build cannot read nested packages.

**What is the expected or desired behavior?**
That it will be able to read nested structures.

---

## Bug report

**Please provide steps to reproduce, including full log output:**
Details provided on original issue report: [gulp build fails on line 40 of bower_components/bootstrap-material-design/scss/_variables.scss](https://github.com/FezVrasta/bootstrap-material-design/issues/995#issuecomment-217579412)

**Please describe your local environment:**

WordPress version: 4.5

OS: Windows 10

NPM/Node version: 3.8.3

Bower version: 1.7.9

**Where did the bug happen? Development or remote servers?**

Development

**Comment by retlehs** [comment]
how are you trying to include bootstrap-material-design? their `bower.json` file includes already compiled css files, no sass:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/bower.json#L9

**Comment by lkhedlund** [comment]
Hi @retlehs, I would like to include it with a bower install so I can continue to use Sass variables for adjustments and better manage my dependencies. Here's the command I ended up with, based on their suggestions: `bower install FezVrasta/bootstrap-material-design# v4-dev --save`

**Comment by blitz999** [comment]
Is that v4 bootstrap? That might be why, you are likely using two different versions. v4 is still Alpha and has different classes/placeholders etc. Have you removed the Sage Bootstrap?

Also, not scientific (I can't see the error log), but we had similar issues on some bower installed kits. Sometimes running install node and bower again seems to make things work a second time around. TBH, it's not hard to import the material aspects onto the Sage installed bootstrap. It's really weighty on the user though - all that double drop shadow stuff.

**Comment by lkhedlund** [comment]
@blitz999 I did completely remove Sage's Bootstrap 3 to allow for a Bootstrap 4 total takeover. The compiling broke somewhere in the middle. 

I will definitely try your reinstall just to make sure.

I think you're both probably on to something with just including the compiled material css. I would have liked to manage the package through the normal channels to ensure consistent updates, but since both v4 and Material are alpha, I should expect a few hiccups.

**Comment by blitz999** [comment]
BTW, you can use the bower installed scss by using overrides in the manifest and @import bower component scss files by hand into main.scss - top of file. Usually kit variables first in SASS.

**Comment by retlehs** [comment]
please use the roots discourse for further support

**Comment by lkhedlund** [comment]
Thanks @blitz999. I'll try that.
