### ISSUE TITLE
Having trouble npm install

### ISSUE THREAD

**Issue by benag** [roots/sage#1647]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

X when doing npm install I get an error: code ELIFECYCLE when install node-sass
using ubuntu 14 node 5.0.0

**What is the expected or desired behavior?**

X npm install should install lib

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X clone and run npm install on ubuntu 14

**Please describe your local environment:**

WordPress version:  4.4.2

OS: ubuntu 14

NPM/Node version: 5.0

**Where did the bug happen? Development or remote servers?**

local host

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by retlehs** [comment]
![image](https://cloud.githubusercontent.com/assets/115911/15183034/037e6632-1755-11e6-8614-1035a470ed84.png)
