### ISSUE TITLE
Does gulp --production works?

### ISSUE THREAD

**Issue by hijoncon** [roots/sage#1654]
Hey guys great job in this framework.  Does gulp --production works? Just noticed that when I run `gulp --production` looks like the doesn't change the output in the network.  Also what is the purpose of `dist`?

**Comment by hijoncon** [comment]
Nevermind, figured out 👍

**Comment by retlehs** [comment]
in the future please don't use github for personal support requests, use https://discourse.roots.io/

**Comment by hijoncon** [comment]
Ok. Thanks for the link. I am very new in your starter theme and I really love it. Thanks again!
