### ISSUE TITLE
Autogenerate language file

### ISSUE THREAD

**Issue by schrapel** [roots/sage#1672]
I am not sure how language files are being dealt with in v9 but I came across a neat gulp package so we don't have to manually create a po file. I'm sure there is something similar without gulp

https://www.npmjs.com/package/gulp-wp-pot

**Comment by retlehs** [comment]
we removed the pot file intentionally and will likely keep it outside this repo, but would be open to something that would autogenerate it for the https://github.com/roots/sage-translations repo

(can also be convinced to bring it back into this repo)

**Comment by retlehs** [comment]
closing this issue but we're open to more discussion on this if anyone has something to say. please holler via https://discourse.roots.io/
