### ISSUE TITLE
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by mav1283** [roots/sage#1674]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

I recently installed sage as a i'm trying to learn theme development ( i'm a newbie by the way ) but i'm confuse with the instructions (specifically where) to install this:  npm install -g npm@latest   so i just typed that code on my cmd prompt, C:\users\myname\  _npm install -g npm@latest_

and i got 5 npm WARN

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0 Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0 Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Please describe your local environment:**

WordPress version: 4.5.3

OS: Windows 10

NPM/Node version: v4.4.5

**Where did the bug happen? Development or remote servers?**

inside my sage theme i just typed this: npm install   and i got this:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                                           to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o                                                          n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                                          . Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade                                                           to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher                                                           to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o                                                          n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                                          . Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! fetch failed https://registry.npmjs.org/buffer-to-vinyl/-/buffer-to-vin                                                          yl-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu                                                          s code 400
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global jshint@2.9.2 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

Please help, i'm a beginner in wordpress, not the techy expert but i do strictly follow instructions when installing something.. i'm just tryin to learn theme development, newbie here.

**Comment by retlehs** [comment]
> - [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
