### ISSUE TITLE
[Sage 9] Wrapper disregards templates from plugins

### ISSUE THREAD

**Issue by emzo** [roots/sage#1675]
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

The theme wrapper seems to disregard templates coming from plugins such as WooCommerce.

![screencapture-woocommerce-local-shop-1467802439159](https://cloud.githubusercontent.com/assets/148775/16615715/8886209e-4370-11e6-9ef2-7c641a7c43b8.png)

**What is the expected or desired behavior?**

Sage should load templates coming from plugins as it did in previous versions.

![screencapture-woocommerce-local-shop-1467802493693](https://cloud.githubusercontent.com/assets/148775/16615722/8fb1d17e-4370-11e6-8e42-4ee8b17b863a.png)

---

## Bug report

**Please provide steps to reproduce, including full log output:**

With the Sage 9 theme and WooCommerce installed, visiting any WooCommerce page where WooCommerce attempts to use a template it supplies results in a PHP warning and the template is not loaded by the theme wrapper. See log output below: 

```
Warning: include(): Filename cannot be empty in /Users/emyr/Sites/woocommerce/wp-content/themes/sage/templates/layouts/base.php on line 17

Warning: include(): Failed opening '' for inclusion (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Users/emyr/Sites/woocommerce/wp-content/themes/sage/templates/layouts/base.php on line 17
```

**Please describe your local environment:**

WordPress version: 4.5.3

OS: Mac OS X El Capitan 10.11.5

NPM/Node version: 3.10.3/v5.10.1

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

- https://discourse.roots.io/t/single-template-filter-from-plugins/6637 This thread suggests a fix for the issue reported here.
- https://discourse.roots.io/t/sage-9-woocommerce/7108

**Comment by allanchau** [comment]
You can modify the sage wrapper to look in a different folder if it cannot find the template.
`
public function getTemplate()
    {
        $template = apply_filters('sage/unwrap_' . $this->slug, $this->template) ?: $this->template;
        return locate_template($template) ?: locate_template('woocommerce/' . $template);
    }
`

**Comment by emzo** [comment]
Thanks @allanchau. However, correct me if I'm wrong here, but I don't think your code above fixes the issue I reported - it will not go looking for templates in the plugins directory.

Taking WooCommerce as an example here, it defines it's own function [`wc_get_template_part()`](https://github.com/woothemes/woocommerce/blob/2.6.2/includes/wc-core-functions.php#L151) (to use instead of the WordPress core [`get_template_part()`](https://developer.wordpress.org/reference/functions/get_template_part/) which first looks for template partials in the theme's root directory `/themes/my-theme/`, then in the theme's `/themes/my-theme/woocommerce/` directory, and if it doesn't find on there, it falls back to the templates provided by WooCommerce itself which are in the `/plugins/woocommerce/templates/` directory. **This all seems to work fine under Sage 9**.

However, the problem lies with the main WooCommerce templates (not the template partials), i.e. `single-product.php`, `archive-product.php`, `taxonomy-product_cat.php` and `taxonomy-product_tag.php`.

WooCommerce [filters the `template_include` hook](https://github.com/woothemes/woocommerce/blob/2.6.2/includes/class-wc-template-loader.php#L41) to make WordPress fall back and look for these templates in the `/plugins/woocommerce/templates/` directory if it can't find them within the theme.

This is where the problem lies. It seems that Sage 9 stops WooCommerce from looking in the plugins directory altogether, and expects to find them in the theme directory, which end up with Sage trying to [`include()` a non-existent template](https://github.com/roots/sage/blob/sage-9/templates/layouts/base.php#L17) in the template wrapper, and breaks the WooCommerce fallback mechanism.

**Comment by QWp6t** [comment]
Wrapper now wraps templates loaded from plugins.

https://github.com/roots/sage/commit/4435d52d01e1598f0bf2f4b7c27feda5c8060412

If on the other hand you would rather it not wrap a template loaded from a plugin, then change the filter at the bottom of `src/filters.php`.
