### ISSUE TITLE
[Sage-9][docs] Using images/ directory

### ISSUE THREAD

**Issue by jmarceli** [roots/sage#1677]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Feature Request

There should be some info (e.g. inside README or docs) which will guide users how to include images from `assets/images/` directory in their webpack builds as described in https://discourse.roots.io/t/what-should-we-put-in-assets-images/6852.

**Comment by retlehs** [comment]
thanks, added to sage 9 docs at https://github.com/roots/docs/commit/3b94c48e528f39fe8b7319ca599a919fb3f75541
