### ISSUE TITLE
[Sage 9] - Better support 12 factors

### ISSUE THREAD

**Issue by lpirola** [roots/sage#1691]
## With few changes we could deploy sage 9 with bedrock in a heroku without worries

- This is a feature request

**What is the current behavior?**

When you run ```npm install``` and everything goes fine, the following command is auto executed: ```composer install```.

**What is the expected or desired behavior?**

Remove dependencies between PHP and Node package management. With this done, the theme will be capable to be used with containers.

## Feature Request

**Please provide use cases for changing the current behavior:**

When deploying this theme in heroku containers you could use [multi buildpack](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)

**Comment by QWp6t** [comment]
I completely agree. I didn't even realize that was happening. I'll take care of that this week.

**Comment by retlehs** [comment]
fixed in 4d58f88166b5c1efd78f15ef5f1fbb2ca5f2e344
