### ISSUE TITLE
wp_link_pages() only first page can wraped by base.php, other pages only dispaly with single.php

### ISSUE THREAD

**Issue by thailandjerry** [roots/sage#1692]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Bug report

wp_link_pages() only first page can wraped by base.php, other pages only dispaly with single.php

(delete this section if not applicable)

**Please describe your local environment:**

WordPress version: 4.5.3

**Comment by QWp6t** [comment]
Sage 8 or 9?

**Comment by thailandjerry** [comment]
Sage 8.4.2

**Comment by QWp6t** [comment]
Our focus at the moment is on Sage 9. Feel free to take this issue to [the forums](https://discourse.roots.io/c/sage) where you might be able to find someone who has had a similar problem. I don't think this is a bug with Sage 8, though. I'm thinking that Sage 8 is mature enough that we would have noticed it before now.
