### ISSUE TITLE
Live Reload too slow

### ISSUE THREAD

**Issue by asifsaho** [roots/sage#1693]
Sage live reload seems too slow, taking about 5 seconds to inject updated CSS file, can you give me suggestion regarding this?

**Comment by ptibbetts** [comment]
Hey @asifsaho, 

The team use GitHub issues for tracking bugs, you'll be better off asking on https://discourse.roots.io/c/sage

**Comment by asifsaho** [comment]
Alright @ptibbetts I'm gonna ask at right place.
