### ISSUE TITLE
Images are put in fonts dir after build

### ISSUE THREAD

**Issue by robbens** [roots/sage#1694]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

After running `npm run build`, the images I've selected in the config.json end up in `dist/fonts` looking like `fonts/credit-cards_7a2eb09f.svg`. The random string is somehow generated.

Seems like it only affects svg files. Even though other formats gets the random string as well.

**What is the expected or desired behavior?**

The images should be placed inside `dist/images` without the generated string.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

**config.json**
```
{
  "context": "assets",
  "entry": {
    "main": [
      "./scripts/main.js",
      "./styles/main.scss",
      "./images/credit-cards.svg"
    ],
    "customizer": [
      "./scripts/customizer.js"
    ]
  },
  "output": {
    "path": "dist",
    "publicPath": "/app/themes/sage-9/dist/"
  },
  "devUrl": "http://sage.dev",
  "devPort": 3000
}
```

**Please describe your local environment:**

WordPress version: 4.6

OS: OS X 10.11.6

NPM/Node version: NPM: 3.10.3 / Node: 6.4.0

**Where did the bug happen? Development or remote servers?**

Development and production

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

**Comment by ptrckvzn** [comment]
Currently, the webpack loader that processes .svg moves them in the fonts/ folder ([here](https://github.com/roots/sage/commit/4d58f88166b5c1efd78f15ef5f1fbb2ca5f2e344#diff-11e9f7f953edc64ba14b0cc350ae7b9dR144)).

I'm curious about the reason for not leaving `[path]` in the images and fonts loader.

**Comment by QWp6t** [comment]
> I'm curious about the reason for not leaving `[path]` in the images and fonts loader filename.
See: https://discourse.roots.io/t/how-to-correctly-install-font-awesome-in-sage-9/7059/3
And my response: https://discourse.roots.io/t/how-to-correctly-install-font-awesome-in-sage-9/7059/5

The issue he describes was happening with font-awesome as well. The font files were being copied to `dist/_/node_modules/font-awesome/...`. Do you know of a better way to resolve this issue?

**Comment by ptrckvzn** [comment]
I tried a few things but couldn't find a good solution.

As it is now, I see a problem with hard-coding images/ in webpack.config.js : it's removes the subfolder structure and it adds a hash to the filename. Those images won't be reached by `App\asset_path('images/cat.jpg')`. If you remove the hash, it will work with asset_path, but any duplicate filename won't work (images/folder-a/cat.jpg and images/folder-b/cat.jpg -> dist/images/cat.jpg)

Using [path][name].[ext] results in _/node_modules/... the output folder is not very clean but it works. Maybe a different loaders for node_modules packages? With a different context it would remove _/node_modules.

```
{
        test: /\.woff(2)?(\?.*)?$/,
        loader: 'url?' + qs.stringify({
          limit: 10000,
          mimetype: "application/font-woff",
          name: "[path][name].[ext]",
          context: './node_modules'
        })
}
```

**Comment by ptrckvzn** [comment]
@robbens this has been [fix](https://github.com/roots/sage/pull/1697). If you update your sage files. Your assets will be moved to the corresponding path in dist/ (assets/images -> dist/images).
