### ISSUE TITLE
Node.js version support documentation/enforcement is broken

### ISSUE THREAD

**Issue by CharlieHawker** [roots/sage#1695]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**
The documentation notes that node version 0.12.x is required for Sage, yet the engines constraint in `package.json` is for `>= 0.12.0`. 

This does not throw errors if a new version of node is used. `gulp` command fails if using node 6.4.0 for example, but really you should not be able to get this far.

**What is the expected or desired behavior?**
Amend package.json to use correct `node-semver` syntax to enforce 0.12.x:

```
...
"engines": {
    "node": ">= 0.12.x",
    ...
  },
...
```

**Comment by ntwb** [comment]
This is now NodeJS 4.x on the `sage-9` branch:
https://github.com/roots/sage/blob/sage-9/package.json#L26-L28
```js
  "engines": {
    "node": ">=4"
  },
```
