### ISSUE TITLE
New gulp command [feature request]

### ISSUE THREAD

**Issue by tullsta** [roots/sage#1698]
## Submit a feature request or bug report

- [X] This is a feature request
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When theme is done and ready to deploy we run "gulp --production" command. 

**What is the expected or desired behavior?**

Can you add extra gulp command (like gulp --deploy), that takes all nessesary files and compress it into ZIP theme file? It should be without any .git, .json, .config files, node modules and so on. 
I see on Discourse https://discourse.roots.io/c/sage, that many people don't know what they can delete without affecting theme apperance.

**Comment by QWp6t** [comment]
You can remove all of the dot-files before deployment. You can also remove the assets directory, node_modules, bower_components, all of the json, xml, and .md files in the theme's root directory.

As for adding a --deploy parameter and compressing the theme into a zip, this has been asked a couple times already. We're not likely to go in that direction at the moment, certainly not for Sage 8. At some point, we might reconsider it for Sage 9 or later versions.
