### ISSUE TITLE
Add support for Laravel Blade

### ISSUE THREAD

**Issue by QWp6t** [roots/sage#1699]
I've come up with a couple ways to implement this, but I'm still undecided on the approach I'm going to take and I haven't fully investigated whether there are any pitfalls. Definitely need to do more testing and research, but it only took me about 10 minutes to get it working so I anticipate it being fairly straightforward.

**Comment by nathanielks** [comment]
```
@section('comment')
    @each('lists.awesome-item', $reasons_quap_is_awesome, 'reason')
@endsection
```
_Renders:_
1. Quap is awesome because: he thinks outside of the box
1. Quap is awesome because: he's kindler and gentler
1. Quap is awesome because: he contributes to FOSS
