### ISSUE TITLE
bootlint complains that <main class="main"> in base.php not allowed as an immediate child of .row

### ISSUE THREAD

**Issue by WebDragon** [roots/sage#1704]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [X ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

base.php:
   `<div class="wrap container" role="document">
      <div class="content row">
        <main class="main">
`
-- bootlint.com complains: E013 Line 113, Column 9:Only columns (`.col-*-*`) may be children of `.row`s more details https://github.com/twbs/bootlint/wiki/E013

**What is the expected or desired behavior?**
decide whether to either patch bootlint to recognize this from sage, or avoid making `<main>` a direct child of .row without also (possibly) adding a class such as col-lg-12 to main

**Comment by QWp6t** [comment]
That's a limitation with bootlint. 

`.main` is a column: https://github.com/roots/sage/blob/master/assets/styles/components/_grid.scss
