### ISSUE TITLE
Sage 9 with Typography.com fonts

### ISSUE THREAD

**Issue by joneslloyd** [roots/sage#1708]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

**What is the current behavior?**

Our Sage 9 site uses Typography.com fonts. When the font pack is put into 'Production' mode, for launching the site, Typography.com gives you a `.ZIP` file which is a random string. You're instructed to extract this, and put the folder into an externally accessible directory on your web server, and tell them the link.

e.g.,
- Download `30682.zip`
- Extract, so it's now a folder called `30682`, containing various files with font file extensions and `.css` extensions
- Place this folder on to your web server, ie, `http://mysite.com/wp-content/themes/mytheme/dist/fonts/30682/`
- Paste this URL into your Typography.com project
- ????
- PROFIT!!

However, in-keeping with the Sage 9 workflow, When I place the `30682` folder into `/mytheme/assets/fonts/`, and then run `npm run build:production`, the folder isn't then copied into its equivalent directory in the `dist` folder.

Typography.com only allow you to specify the parent folder (ie, `http://mysite.com/wp-content/themes/mytheme/dist/fonts/`), not the end folder in which the font files / `.css` files will reside, so it's not simply a case of changing the directory at Typography.com so that their files be in the `dist/fonts/` folder like the other fonts.

The 'solution' on this thread isn't ideal: https://discourse.roots.io/t/is-roots-incompatible-with-typography-com/5774/7 as it assumes that `assets` is living on the server, which isn't always the case.

**What is the expected or desired behavior?**

Placing a generated Typography.com font folder into `/assets/fonts/` should see it compiled to `/dist/fonts/` upon running `npm run build:production`

**Comment by QWp6t** [comment]
One of your entry points needs to actually use the font as a resource, i.e., you need to pull the fonts in through your CSS. There are numerous ways to do this: by adding their CSS file to your main entry point, by requiring it within your SCSS, or by creating an entirely new entry point in webpack config.

Alternatively, you can use copy-webpack-plugin to copy arbitrary files and folders.

**Comment by membla** [comment]
@joneslloyd
You can simply remove the flatten command from the fonts gulp task:

`    .pipe(flatten())
`

And the directory structure will be kept intact when copying from assets/fonts to dist/fonts. Not sure about the rationale behind flattening the structure here but yes, it conflicts with the way typography.com requires you to host the fonts.

**Comment by joneslloyd** [comment]
Nice! Thanks a lot!
