### ISSUE TITLE
Npm start - broken after latest updates

### ISSUE THREAD

**Issue by derkjn** [roots/sage#1717]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When running `npm start`, the process fails with the following errors:
```
/assets/build/webpack.plugin.browsersync.js:32                   
this.compiler.plugin('compilation', () => this.watcher.notify('Rebuilding...'));                                                                          ^                                                                                                                         

TypeError: Cannot read property 'plugin' of undefined

```

**What is the expected or desired behavior?**

The scripts should run correctly

---

## Bug report

**Please provide steps to reproduce, including full log output:**

On a fresh installation of the scripts this morning, after running `npm install`, I ran `npm start` and it crashes.

**Please describe your local environment:**

WordPress version: 4.6.1

OS: OSX 10.11.6

NPM/Node version: 
node: v.4.3.1
npm: 3.10.7

**Where did the bug happen? Development or remote servers?**

development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by QWp6t** [comment]
Fix was simple. I double-checked it to be sure. It should work now. Sorry about that.
