### ISSUE TITLE
[idea] Silencing Webpack output

### ISSUE THREAD

**Issue by drawcard** [roots/sage#1719]
## Submit a feature request or bug report
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

Currently, Webpack spits out a heap of information when running 'npm start' and it's a bit overwhelming, especially as asset counts grow for a project. Plus, BrowserSync connection information gets lots in the mix. I would like to propose building in the option to disable the superfluous information (maybe making it a default, and toggling it off if desired.) 

**Other relevant information:**

Ideas for implementing this can be found here: http://stackoverflow.com/a/31933551

This solution is ideal as it allows error messages to pass through, while suppressing everything else.

**Comment by derkjn** [comment]
I had a play around the current configuration files and turns out, this would be extremely easy.
Following the stackoverflow post, I simply added `{noInfo: true}` to the current `webpack.plugin.browsersync.js` `middleware` function.
Don't know if this will get approved for sage or not but definitely nice to have a cleaner output!

**Comment by drawcard** [comment]
Cool. I thought it would be pretty simple to do. Might be worthy of a PR!

**Comment by mrobit** [comment]
Webpack output in the command line can get ridiculous, especially if you cmd+click on the URL browser-sync outputs in the terminal when the server command is started. +1 from me.

**Comment by drawcard** [comment]
It's especially a pain when you're trying to catch an error in a SCSS file for example, but it all whizzes past too quickly to read it in the console. 

I've found a [better solution](https://github.com/webpack/webpack/issues/1191#issuecomment-228602750) that just supresses the chunk information, but still gives you useful stats on the watched files. It also still outputs errors and warnings, eg deprecation messages from SASS. It's not as noisy as before but it's still useful. I'm about to submit a PR with the change 👍 

![image](https://cloud.githubusercontent.com/assets/1435638/19501135/97c35492-95ea-11e6-8503-09edd5c07dca.png)

**Comment by retlehs** [comment]
closed by #1751

**Comment by drawcard** [comment]
Thanks!
