### ISSUE TITLE
Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by craigmdennis** [roots/sage#1720]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

After a fresh `npm install`, Webpack complains about configurations objects that don't match the API schema.

**What is the expected or desired behaviour?**

No errors out of the box

---

## Bug report

Ran `npm start` as well as `npm run build` with the same errors.

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'enforceExtensions'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
 - configuration.entry['files'] should be one of these:
   string | [string]
   The entry point for one output file.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { rules?, loaders?, noParse?, unknownContextRequest?, unknownContextRegExp?, unknownContextRecursive?, unknownContextCritical?, exprContextRequest?, exprContextRegExp?, exprContextRecursive?, exprContextCritical?, wrappedContextRegExp?, wrappedContextRecursive?, wrappedContextCritical? }
   Options affecting the normal modules (`NormalModuleFactory`).
```

OS: OSX El Capitan

NPM/Node version: 3.10.3/6.5.0

**Comment by derkjn** [comment]
Webpack has just release `beta.23` which brings breaking changes to the configuration structure.
I'd suggest to stick with `beta.22` for the time being.

**Comment by QWp6t** [comment]
We specify beta 22 in package.json. Use that.

**Comment by craigmdennis** [comment]
As far as I can tell, you specify anything _above_ `"webpack": "^2.1.0-beta.22"` rather than forcing an absolute version (by removing the `^`) which would solve this issue in the short term.

**Comment by QWp6t** [comment]
Oh, you're absolutely right. I forgot I did that.

If you want credit for it, feel free to submit a PR, otherwise I'll go ahead and handle it later today.

**Comment by craigmdennis** [comment]
👍  PR submitted

**Comment by rjksn** [comment]
Guessing this still wasn't implemented in the latest alpha—as I just deleted the ^.

Thanks craigmdennis!

**Comment by Guyana345** [comment]
can some one help me here: this is the error i'm getting

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.loaders[0] has an unknown property 'text'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
