### ISSUE TITLE
svn2png Library introduced breaking changes for node<5

### ISSUE THREAD

**Issue by derkjn** [roots/sage#1722]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

This is not exactly a bug but more of a warning. The current setup specifies `node >=4.5`.
When running a fresh install, `svn2png` with a version greater than `3.1.0` will be downloaded, which will only work on node 5 or 6, as noted [here](https://github.com/domenic/svg2png) and [here](https://github.com/domenic/svg2png/issues/59)
This will result in error when running `npm run start`, `npm run build` and `npm run build:production`

**What is the expected or desired behavior?**

The version of this plugin should be either manually specified in `package.json` to point to `3.1.0` to support `node 4` or bump node version to `>=5`

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Run a fresh install with an `svg` logo in your assets and `node < 5`. Then run `npm run build`.

**Please describe your local environment:**

WordPress version: 4.6.1

OS: OSX 10.11.6

NPM/Node version: 
node: v.4.3.1
npm: 3.10.7

**Where did the bug happen? Development or remote servers?**

development

**Comment by QWp6t** [comment]
I'm confused. Does this have anything to do with Sage? As far as I can tell, `svg2png` isn't one of our dependencies or even a dependency of one of our dependencies.

Node 4.5.0 is the most recent LTS version, which I think is a compelling reason to continue supporting it.

**Comment by derkjn** [comment]
It's a dependency of `imagemin-webpack-plugin` which will be automatically pulled when installing sage. I'm happy to keep the LTS of node, but if you don't force this dependency to be `3.1.0` it will not build the bundles.

**Comment by QWp6t** [comment]
I'm still confused. It doesn't appear to be a [dependency of `imagemin-webpack-plugin`](https://github.com/Klathmon/imagemin-webpack-plugin/blob/master/package.json#L30-L39).

`npm ls | grep svg2png` also yields zero results on fresh install of latest Sage alpha.

I'm pretty sure you got your wires crossed here, bud.
