### ISSUE TITLE
Latest webpack breaks npm build

### ISSUE THREAD

**Issue by michalkopanski** [roots/sage#1723]
Summary from answer on [SO](http://stackoverflow.com/a/39601224):

Yesterday, `webpack` released `2.1.0-beta.23` which is not compatible with `angular-cli 1.0.0-beta.14` so, due to the caret (`^`), deployed versions of `angular-cli 1.0.0-beta.14` have stopped working. To address this problem, `angular-cli 1.0.0-beta.15` was released yesterday with a fixed `webpack: 2.1.0-beta.22` dependency -- note the lack of the `^` -- thus avoiding the breaking upgrade to webpack. See https://github.com/angular/angular-cli/issues/2234 for details.

---

## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

`npm run build` fails with the following error:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'enforceExtensions'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           enforceExtensions: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
```

**What is the expected or desired behavior?**

`npm run build` should be successful.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Clone sage, and follow install instructions. Webpack will throw an error when attempting to build.

**Please describe your local environment:**

WordPress version: All versions

OSX: 10.11.6

NPM/Node version:

- npm: 3.7.3
- node: v5.8.0

**Where did the bug happen? Development or remote servers?**

Development.

---

## Proposed fix

As described in [this github comment](https://github.com/angular/angular-cli/issues/2234#issuecomment-248173309), pinning the `webpack` version to `v2.1.0-beta.22` fixes this issue and results in successful builds.

**Comment by eshimischi** [comment]
First of all, its not a bug but new features of webpack2 [https://github.com/webpack/webpack/issues/3018](this webpack issues)

**Comment by michalkopanski** [comment]
@eshimischi I appreciate your comment, but if the latest clone of this repo is not building properly, then in my humble opinion, it is in fact a bug.

Obviously there are several ways this can be addressed by the developer, so I'm not suggesting that a change in the configuration is not the best way to fix it, but at a minimum, a clean clone of this repo should be building successfully, regardless of what introduced the change.

I've used the proposed fix mentioned above to get it building, for those of you that run into this issue, and consider it a blocker.

**Comment by eshimischi** [comment]
@michalkopanski yes, i understand. I have the same issue with PostCss via new webpack2.1.beta24, doing an experiments whole day today [this comment](https://github.com/webpack/webpack/issues/3018#issuecomment-248624214) and asked about help

**Comment by QWp6t** [comment]
This already been addressed.

https://github.com/roots/sage/blob/master/package.json#L72

https://github.com/roots/sage/pull/1721

Please use search next time.

**Comment by strarsis** [comment]
Yes, when I install the packages using `npm` I get this issue, when I install with `yarn`, building works fine.
