### ISSUE TITLE
Custom template body class

### ISSUE THREAD

**Issue by cleverinx** [roots/sage#1724]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Body classes on custom template pages are appended strangely, and `page-template-templates `is repeated twice.

`<body class="page page-id-47 page-template page-template-templates page-template-template-migration page-template-templatestemplate-migration-php sample-page">`

I created a custom template called template-migration.php and assigned it to a few pages. When I visit those pages, the body class is as noted above. The main issue is with the lack of spacing here: `page-template-templatestemplate-migration-php`

**What is the expected or desired behavior?**

The ideal output of the above should be:
`page-template-templates template-migration-php`

or just

`template-migration-php` (without page-template-templates, don't see why that's required/duplicated)

---

## Bug report

**Please provide steps to reproduce, including full log output:**

To reproduce, create a new page template, assign it to a page, and view the body classes in the source.

**Please describe your local environment:**

WordPress version: 4.6.1

OS: OSX El Capitan 10.11.6

NPM/Node version: 3.10.8/v6.4.0

**Where did the bug happen? Development or remote servers?**

Development

---

**Comment by nickknissen** [comment]
This is technically not a bug. It's default wordpress behavior. See [body_class function](https://core.trac.wordpress.org/browser/tags/4.6.1/src/wp-includes/post-template.php#L675)

It is possible to 'body_class' filter to clean up the classes.
```php
add_filter('body_class', function (array $classes) {
  // Add post/page slug if not present
  if (is_single() || is_page() && !is_front_page()) {
    if (!in_array(basename(get_permalink()), $classes)) {
      $classes[] = basename(get_permalink());
    }
  }
  $templateSlug = get_page_template_slug();
  $classToAdd = sanitize_html_class( str_replace( '.', '-', explode('/', $templateSlug)[1]));
  $classToRemove = 'page-template-' . 'templates'. $classToAdd;
  $clases[] = $classToAdd;
  $classes = array_diff($classes, [$classToRemove]);
  return $classes;
});
```
