### ISSUE TITLE
sage activation error 500

### ISSUE THREAD

**Issue by felixyorke** [roots/sage#1725]
Hi, i downloaded the latest version of sage and after uploading the entire folder in the themes folder in my e wordpress i started with activation... but after activation i had an error 500. in wp-config. I put on "TRUE" the WP_DEBUG, and i found an error on src/helpers.php on line 27... how can i fix this problem?

**Comment by retlehs** [comment]
2 things:

1. don't clear out the issue template that was in place when you went to create this issue. it's there for a reason... not for you to ignore and delete.
2. if you had followed the steps in the template, you would understand that this is a personal support request that shouldn't be posted here
