### ISSUE TITLE
sage activation error 500

### ISSUE THREAD

**Issue by felixyorke** [roots/sage#1726]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

error 500

**What is the expected or desired behavior?**

a complete activation of the theme

---

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: 4.6.1

OS: linux

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

 remote servers

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

Hi, i downloaded the latest version of sage and after uploading the entire folder in the themes folder in my e wordpress i started with activation... but after activation i had an error 500. in wp-config. I put on "TRUE" the WP_DEBUG, and i found an error on src/helpers.php on line 27... how can i fix this problem?

**Comment by retlehs** [comment]
did you actually read my comment? https://github.com/roots/sage/issues/1725#issuecomment-249199527

> **if you had followed the steps in the template, you would understand that this is a personal support request that shouldn't be posted here**

if you continue to make issues for support requests we'll have to restrict you from the repository since we don't need everyone watching this repo getting notifications for this shit.
