### ISSUE TITLE
browserSync follows my previous updates

### ISSUE THREAD

**Issue by eness** [roots/sage#1728]
I have just downloaded Sage starter kit and playing around with it. Everytging is working as expected and documented. But there is a problem with browserSync module.

I have created a new custom.scss file in assets/ and imported it inside main.scss file. I run 'watch' task from Gulp. Now I do tests by changing body background color from custom.scss : 

```body { background: red !important; }```

The problem is when I do any modification from my custom.scss file, browserSync processes the request and says "Injecting main.css" in my browser. But the change does not effect on the page. When I do a new modification, now the previous modification has been effected on the page. This is my problem. Example :

set bg color to "blue" : no changes
set bg color to "red" : bg color becomes blue (from previous update)
set bg color to "pink" : bg color becomes red (from previous update)
.. and so on

I haven't changed anything inside gulpfile.js so I don't think to paste it here as it untouched original version from the source.

I'm running these tools under Windows 10 and using PhpStorm as IDE and Chrome for browser.

**Comment by retlehs** [comment]
2 things:

1. don't clear out the issue template that was in place when you went to create this issue. it's there for a reason... not for you to ignore and delete.
2. use https://discourse.roots.io/ for personal support requests, not this issue tracker.

**Comment by jmarceli** [comment]
Hey,
It seems to be a common bug not a personal support request. I'm also having this issue on OS X Yosemite. I'm using Sage 9 branch for a while and this problem seems to be connected with latest 9.0.0-alpha.3 version.

**Comment by mdaliyan** [comment]
I don't know why I can't see `gulpfile.js` in this repo. but i install sage from command line and I have gulpfile.js there.

every time I create new project I goto gulpfile.js and change this:
`
rev: argv.production,
`
to this:
``
rev: !argv.production,
``

this enables revisions on development and disables it on production

**Comment by jmarceli** [comment]
This repo is now following Sage 9 branch so Gulp is replaced with Webpack. If you want to use Gulp refer to the Sage 8 branch: https://github.com/roots/sage/tree/sage-8.

**Comment by v3nt** [comment]
how & where can we configure browserSync in sage 9? ie stop autoload, show the badge / notifications etc?

**Comment by jmarceli** [comment]
Here: https://github.com/roots/sage/blob/master/assets/build/webpack.plugin.browsersync.js#L35

**Comment by v3nt** [comment]
ah ha! thanks. I've been wondering how we configure these packages without grunt / gulp files.

I added 
    open: false,

to config.js and
    line 37: open: this.options.open,

to webpack.plugin.browsersync.js

**Comment by jmarceli** [comment]
It's better to add:
```
browserSyncOptions: {
  open: false
}
```
to the `config.json` and leave `webpack.plugin.browsersync.js` unchanged.

**Comment by v3nt** [comment]
OK thanks. Looking at assets/config.json i'm not sure where that would go?

```
{
  "entry": {
    "main": [
      "./scripts/main.js",
      "./styles/main.scss"
    ],
    "customizer": [
      "./scripts/customizer.js"
    ]
  },
  "watch": [
    "templates/**/*.php",
    "src/**/*.php"
  ],
  "publicPath": "/wp-content/themes/ampc-sage-9-theme",
  "devUrl": "http://ampcdev.jynk.net",
  "proxyUrl": "http://localhost:4000",
  "cacheBusting": "[name]_[hash:8]"
}

```

**Comment by retlehs** [comment]
> how & where can we configure browserSync in sage 9?

as mentioned in my first reply:

> use https://discourse.roots.io/ for personal support requests, not this issue tracker.
