### ISSUE TITLE
NPM Start missing from 8.5.0

### ISSUE THREAD

**Issue by milosvujnovic** [roots/sage#1734]
Hi guys,

Used the latest stable 8 version lately (several times) - and seems like that the "npm start" command isn't included in the package.json's scripts -- can anybody else confirm this?

To replicate this issue, just download the latest 8 version, run npm install and then try **npm start** :)
I usually just paste the **"start": "npm run build -s -- --watch"** from the current master repo.

Not sure if I'm doing something wrong, but it's working -- in any case, just wanted to let you know regarding this.

Cheers!

**Please describe your local environment:**

WordPress version: 4.6.1
NPM/Node version: 

sage: '8.5.0',
npm: '2.15.8',
ares: '1.10.1-DEV',
http_parser: '2.5.2',
icu: '56.1',
modules: '46',
node: '4.4.7',
openssl: '1.0.2h',
uv: '1.8.0',
v8: '4.5.103.36',
zlib: '1.2.8'

OS: Windows 7

**Where did the bug happen? Development or remote servers?**
Local/development.

**Comment by retlehs** [comment]
sage 8 doesn't use `npm start`, that's sage 9. please don't use github issues for personal support requests, use https://discourse.roots.io/.
