### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found in

### ISSUE THREAD

**Issue by brandonpowell** [roots/sage#1735]
Hello Guys,

Whenever I upload my WordPress theme to my web hosting server I get this error message about a Fatal Error. 

I just finish my theme on my local computer on WordPress know trying to test out on a web hosting server and also using a WordPress builder theme called sage by roots.io

Here the repo: https://github.com/brandonpowell/pixelcity/blob/master/src/helpers.php

`Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found in /Users/brandonpowell/sites/valet/demo/web/app/themes/pixelcity/src/helpers.php:27 Stack trace: #0 /Users/brandonpowell/sites/valet/demo/web/app/themes/pixelcity/src/setup.php(71): App\asset_path('styles/main.css') #1 /Users/brandonpowell/sites/valet/demo/web/wp/wp-includes/plugin.php(524): App\{closure}('') #2 /Users/brandonpowell/sites/valet/demo/web/wp/wp-settings.php(395): do_action('after_setup_the...') #3 /Users/brandonpowell/sites/valet/demo/web/wp-config.php(9): require_once('/Users/brandonp...') #4 /Users/brandonpowell/sites/valet/demo/web/wp/wp-load.php(44): require_once('/Users/brandonp...') #5 /Users/brandonpowell/sites/valet/demo/web/wp/wp-admin/admin.php(31): require_once('/Users/brandonp...') #6 /Users/brandonpowell/sites/valet/demo/web/wp/wp-admin/themes.php(10): require_once('/Users/brandonp...') #7 /Users/brandonpowell/.composer/vendor/laravel/valet/server.php(106): require('/Users/brandonp...') #8 {main} thrown in /Users/brandonpowell/sites/valet/demo/web/app/themes/pixelcity/src/helpers.php on line 27`

**Comment by retlehs** [comment]
hello @brandonpowell 

you created this issue a little while [after you already made a thread on discourse](https://discourse.roots.io/t/not-let-me-upload-theme-issue-with-helpers-php/7848/1), which was the appropriate place to ask your question

please don't use github issues for personal support request (which is noted in our contributing guidelines as well as the issue template that you cleared out when creating this issue)
