### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found

### ISSUE THREAD

**Issue by gouravcoder** [roots/sage#1736]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

I just started playing with sage and cloned the repo and install npm packages... i activated this theme in the wordpress admin
Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found

**What is the expected or desired behavior?**

It should run without any glitch.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

`
( ! ) Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found in C:\wamp64\www\wordpress\wp-content\themes\mensa\src\helpers.php on line 27
( ! ) Error: Class 'Roots\Sage\Assets\JsonManifest' not found in C:\wamp64\www\wordpress\wp-content\themes\mensa\src\helpers.php on line 27
Call Stack
#	Time	Memory	Function	Location
1	0.0015	364216	{main}( )	...\index.php:0
2	0.0601	366272	require( 'C:\wamp64\www\wordpress\wp-blog-header.php' )	...\index.php:17
3	0.0605	381664	require_once( 'C:\wamp64\www\wordpress\wp-load.php' )	...\wp-blog-header.php:13
4	0.0608	394152	require_once( 'C:\wamp64\www\wordpress\wp-config.php' )	...\wp-load.php:39
5	0.0644	478920	require_once( 'C:\wamp64\www\wordpress\wp-settings.php' )	...\wp-config.php:89
6	0.4694	16997880	do_action( )	...\wp-settings.php:395
7	0.4694	16998632	App\{closure}( )	...\plugin.php:524
8	0.4702	17001776	App\asset_path( )	...\setup.php:67
`

**Please describe your local environment:**

WordPress version: 4.6.1

OS: Windows 10

NPM/Node version: NPM - 3.8.9, Node - 6.2.0

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by retlehs** [comment]
you didn't follow the installation instructions which say to use `composer create-project`, so run `composer install`.

**Comment by gouravcoder** [comment]
oh my bad... thanks
