### ISSUE TITLE
Have any sample project build with Sage?

### ISSUE THREAD

**Issue by vanloc0301** [roots/sage#1746]
I newbie `Wordpress`, I usually create `HTML/CSS` theme base on `PSD` file.

I want to know more about `Sage` through by example.

So, have any sample project( a big site like the theme in `ThemeForest` using `Sage`)? Thanks.

**Comment by scherii** [comment]
Please use https://discourse.roots.io/.

[Sage's GitHub issues deal with code-related issues only.](https://github.com/roots/sage/blob/master/.github/ISSUE_TEMPLATE.md)
