### ISSUE TITLE
template_include runs thrice

### ISSUE THREAD

**Issue by ians88** [roots/sage#1749]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Somehow Sage redirects/refreshes 2 times on a request. After checking we found every file is loaded 3 times upon request. We figured this has to be a redirect/refresh bug? 

**What is the expected or desired behavior?**

It should return the desired request once

---

**Please provide steps to reproduce, including full log output:**

Change the `template_include` filter in `filters.php`
```
/**
 * Use theme wrapper
 */
add_filter('template_include', function ($main) {
    
    error_log($main .' - ' . time() . "\r\n", 3, get_template_directory() . '/error_log.txt');

    if (!is_string($main) && !(is_object($main) && method_exists($main, '__toString'))) {
        return $main;
    }
    return ((new Template(new Wrapper($main)))->layout());
}, 109);
```
Check the log. My output (with a clean 9.0.0. alpha3 install) is: 
```
/wp-content/themes/sage/templates/page.php - 1478275457
/wp-content/themes/sage/templates/404.php - 1478275457
/wp-content/themes/sage/templates/404.php - 1478275457
```

**Please describe your local environment:**

WordPress version: latest

OS: Windows

NPM/Node version: 3.3.6

**Where did the bug happen? Development or remote servers?**

Development

**Comment by QWp6t** [comment]
I was unable to reproduce this error. I followed your steps to confirm, and it only had a single line.

It doesn't sound like a theme issue. It sounds like an issue with the load order of files in wp-config.php and your root index.php file (not index.php in the theme).

If you can give me steps to reproduce, I'll revisit this issue.
