### ISSUE TITLE
Bootstrap loader issue

### ISSUE THREAD

**Issue by pafra87** [roots/sage#1750]
Hello,

I have installed roots sage for my WP website. But I got this error message when I was trying to run `npm run build`

`92% chunk asset optimizationError: "/usr/local/lib/node_modules/bootstrap/dist/js/bootstrap.js" is not in the SourceMap.`

Can you please help? Thanks a lot!

**Comment by eshimischi** [comment]
@pafra87 You should install it globally with `npm install -g bootstrap`
