### ISSUE TITLE
Bootstrap as a real option?

### ISSUE THREAD

**Issue by enguerranws** [roots/sage#1752]
Hi,

I used your theme starter and it makes lot of things faster. However, I regret the fact that Bootstrap is not considered as a real option: it's installed by default, and the basic Sass contains a lot of Bootstrap mixins, which makes things not so fast when we don't need Bootstrap at all (we need to remove Bootstrap from Bower deps and remove all Bootstrap mixins in Scss files).

This is not an issue but a question/improvment: do you plan to make Bootstrap really optional on Sage init? I mean something like `composer create-project roots/sage your-theme-name 8.5.0 --no-bootstrap`?

**Comment by mdaliyan** [comment]
I agree. I use different frameworks for each project. But some sass styles in sage use bootstrap variables. I believe sage should not be dependant on any framework.

**Comment by jmarceli** [comment]
Totally agree. Removing Bootstrap is not so hard but it would be even easier if it was optional.

**Comment by raramente** [comment]
I kinda like the Bootstrap there. It ends up being a good example on how to use npm as a replacement of bower and the correct way to integrate node_modules into the the theme.

On sage 8, I had a few problems with bower and the bootstrap example was great to get me started into the workflow.

However I also agree core features shouldn't be dependent on it and it should be simple and fast to remove. It also might diverge newcomers from sage just because they prefer foundation, other frameworks or the good old hard work.

**Comment by PascaleBeier** [comment]
I'm sure opinions divide on this topic.

This is more like question to the roots team as this is kind of a project philosophy-esque question.
Considering Sage's past I'm pretty sure they would stick to bootstrap though.

**Comment by enguerranws** [comment]
Well, the topic is not about using/loving Bootstrap or not. It's just that it should be considered as an option, as it's not a need, it's at most an helpful tool.

**Comment by retlehs** [comment]
please don't use github as a place for discussion ➡️ https://discourse.roots.io/ 

> which makes things not so fast when we don't need Bootstrap at all (we need to remove Bootstrap from Bower deps and remove all Bootstrap mixins in Scss files).

typically people don't complain about removing bootstrap being tedious. it's pretty simple and shouldn't take long

**Comment by enguerranws** [comment]
Nobody said it's tedious, it's just not a real option right now: it's
installed, and we have to remove it manually.

Sorry for using github as a discussion platform, I didn't know about
discourse.roots.io.

**Comment by enguerranws** [comment]
Moved the subject here : https://discourse.roots.io/t/bootstrap-as-a-real-option/8115
