### ISSUE TITLE
[feature request] Use modernizr-loader

### ISSUE THREAD

**Issue by jmarceli** [roots/sage#1753]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Feature Request

**Please provide use cases for changing the current behavior:**

Modernizr-loader (https://github.com/peerigon/modernizr-loader) compiles only the part of the modernizr library which you are actually using, so there is no need to write your own test just to check one small thing (like flexbox support or touchevents).

**Other relevant information:**

I've checked the https://github.com/roots/sage/pull/1541 but I see no drawback of using modernizr-loader in opposite to using entire modernizr package with bower (as metioned in the linked PR). Anyone who doesn't need feature detection would simply leave `.modernizrrc` unchanged and won't `import 'modernizr'` in JS files.

I would be happy to provide PR if you are interested in such feature.

**Comment by derkjn** [comment]
I followed a different path on this. I used `customizr` combined with a `modernizr.config.json` file that I can change per project. This generates a custom build `modernizr` module that I can import in webpack, avoiding all the unnecessary modules.

I guess either way works anyway, I'd be happy to have this build in in sage!

**Comment by retlehs** [comment]
not looking to re-implement modernizr, thanks though
