### ISSUE TITLE
Sage 9.0.0-alpha.3 - npm start dont make dist & linebreak error

### ISSUE THREAD

**Issue by MaxSwinkels** [roots/sage#1754]
Hey,

I'v a problems using the new sage 9 alpha. theme

When i run 'npm start' after installing it everything works fine but the script dont build the dist folder. Only while using 'npm run build' he create the dist folder and shows the actual style.

Is there anyone with the same problem or can someone help me with this?

Thank you in advance

Max

**Comment by jmarceli** [comment]
Not generating `dist/` directory is perfectly OK in a development environment (as far as I know webpack store files in memory to speed up building process).
I don't know anything about your line break problems but for personal issues you should use https://discourse.roots.io/ forum.
