### ISSUE TITLE
[feature] ngrok tunnel

### ISSUE THREAD

**Issue by jmarceli** [roots/sage#1756]
How about adding ngrok support?
So just with `npm run ngrok` you will be able to show your work to someone outside your local network under generic address like `https://asdf90sdf.ngrok.io` (for more info see https://ngrok.com/).
I may make PR if you are interested in this feature.

**Comment by eshimischi** [comment]
@jmarceli what for? it has the practical value?

**Comment by jmarceli** [comment]
Very useful if you're working remotely and want to get some feedback showing your current working progress.

**Comment by austinpray** [comment]
You have to pay for ngrok HTTPS right?

**Comment by scherii** [comment]
https://ngrok.com/product#pricing
Seems so.

**Comment by ntwb** [comment]
There's the "Free Plan" just below the paid plans...

**Comment by jmarceli** [comment]
ngrok is **FREE** unless you need specific address e.g. https//fancyurl.ngrok.io, example of free address may be https://afldsjf87a.ngrok.io.

**Comment by austinpray** [comment]
Yeah y'all haven't tried to use ngrok with an HTTPS origin. 

I pay for ngrok (worth it) and pretty much the only reason I do that is to get TLS origins. 

The reason I bring the whole monetized aspect up in this discussion: in 2016 the default Roots recommendation is to run HTTPS in dev. You are running HTTPS in prod, so you must run HTTPS on dev. So if we recommend this and then include this command by default: users who do not pay for ngrok will get a "please upgrade" message. Although I personally am happy to pay ngrok for their useful service: I can't include this in the codebase.

**Comment by jmarceli** [comment]
FYI I've just checked that there is no "please upgrade" message even if you use free address. The only limitation is connections number which shouldn't be a problem if you just expose your site to one person.
