### ISSUE TITLE
 Failed at the sage@9.0.0-alpha.4 start script 'webpack --hide-modules --watch --config assets/build/webpack.config.js'.

### ISSUE THREAD

**Issue by marcelo2605** [roots/sage#1757]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

`npm start` not run

---

## Bug report

`npm start`

```
> sage@9.0.0-alpha.4 start M:\sites\wordpress\public\wp-content\themes\tema
> webpack --hide-modules --watch --config assets/build/webpack.config.js

Webpack is watching the files…

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Marcelo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! sage@9.0.0-alpha.4 start: `webpack --hide-modules --watch --config assets/build/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sage@9.0.0-alpha.4 start script 'webpack --hide-modules --watch --config assets/build/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --hide-modules --watch --config assets/build/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     M:\sites\wordpress\public\wp-content\themes\tema\npm-debug.log
```

WordPress version: 4.6.1

OS: Windows 10

NPM/Node version: 4.0.2/6.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

---

**Comment by miclap** [comment]
I had similar problem. Try the following:

1. Delete node_modules folder: ```rimraf node_modules```
2. Open Node.js command prompt as admin
3. Run ```npm install```

In my case ```npm start``` is working properly now.

**Comment by sebgrizzly** [comment]
Same here, @miclap suggestion didn't solve the issue

**Comment by mrperceval** [comment]
I had the same problem, stopping at `Webpack is watching the files…`. Then I remembered that there was a problem with `eslint-plugin-import` not installing properly due to a version confilct. This fixed it for me:

1. `npm install eslint-plugin-import@^1.16.0 --save-dev`
2. `rm -r node_modules`
3. `npm install`

**Comment by retlehs** [comment]
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
