### ISSUE TITLE
[Feature]: TypeScript Support

### ISSUE THREAD

**Issue by hijoncon** [roots/sage#1758]
## Feature Request

**Please provide use cases for changing the current behavior:**

Hey guys, Is there a chance to add TypeScript?

**Comment by QWp6t** [comment]
We have no plans of adding it at this time, but you're certainly free to add it to your own projects.

**Comment by pfalomorblab** [comment]
@QWp6t since sage 10 can we consider that roots now supports typescript?

**Comment by retlehs** [comment]
@pfalomorblab yep! but it's best to use https://discourse.roots.io/ for support or questions since closed issues from 2016 might not be looked at again
