### ISSUE TITLE
 Optimize config gets skipped when running `npm run build:production`

### ISSUE THREAD

**Issue by geschwendt** [roots/sage#1761]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Bug report

I believe there is a typo loading in the optimization config.

It looks like the optimization setting is only defined on the `enabled` property in `config.js` and is never assigned to `env`.

This line, https://github.com/roots/sage/blob/master/assets/build/webpack.config.js#L175, 
should probably be something like `if (config.enabled.optimize) {`.

¯\\\_(ツ)\_/¯

**Comment by QWp6t** [comment]
🤔

Looks like you're right.

Feel free to submit PR if you want. Otherwise I'll tackle it this weekend.
