### ISSUE TITLE
[SUGGESTION] Disable the Plugin and Theme Editor by default 

### ISSUE THREAD

**Issue by mycaravam** [roots/sage#1763]
Would it be smart to disable the Plugin and Theme Editor by default?

`define('DISALLOW_FILE_EDIT',true);`

Just for obvious security reasons and lack of use.

**Comment by raramente** [comment]
Hello I think this is done on bedrock. (https://roots.io/bedrock/).

Either way, IMO this is something for the bootstrap of the Wordpress installation it self and not for the theme.
