### ISSUE TITLE
Theme requires activation to work

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1768]
select 'live preview' on sage via wp-admin prior to activation. error shown in the customizer:

```php
Warning: include(web/app/themes/./index.php): failed to open stream: No such file or directory in web/wp/wp-includes/template-loader.php on line 74

Warning: include(): Failed opening 'web/app/themes/./index.php' for inclusion (include_path='.:') in web/wp/wp-includes/template-loader.php on line 74
```

**Comment by retlehs** [comment]
updated title as we're going to be changing some things around to get sage 9 working w/o theme activation.

different scenario where it causes issues: https://discourse.roots.io/t/failed-to-open-stream-wp-includes-template-loader-php/8298/13?u=benword

**Comment by QWp6t** [comment]
As far as I can tell, the customizer live preview issue cannot be *fully* resolved without a WordPress plugin, something that can hook in before template constants are defined on line 392 of wp-settings.php. The theme activation requirement is easily fixed, however.
