### ISSUE TITLE
Views outside of $viewPaths are not loaded properly

### ISSUE THREAD

**Issue by QWp6t** [roots/sage#1769]
This can be resolved in `src/lib/Sage/Template/FileViewFinder`. The most straightforward way would probably be to overwrite the `findInPaths()` method to check if the path is absolute or relative. Issues might arise if it's intended to be a relative path, but it has a leading slash, as in the case of custom templates. My most recent commits to modify `BladeProvider::normalizeViewPath()` to account for custom templates probably exacerbates this issue. So that would have to be reworked as well. We might consider checking that if it's an absolute path, that the path exists within the document root or something.

The Symfony `Filesystem` class has methods we can use to fix it (`isAbsolutePath()` and possibly `makePathRelative()`).

The illuminate `Filesystem` class does not extend the Symfony one, to be clear.

We could merge the two and make it part of the container with something like...

```php
<?php

namespace Roots\Sage;

class Filesystem extends \Illuminate\Filesystem\Filesystem
{
    public function __call($method, $parameters)
    {
        if (method_exists($symfonyFilesystem = new \Symfony\Component\Filesystem\Filesystem(), $method)) {
            return call_user_func_array([$symfonyFilesystem, $method], $parameters);
        }
        return parent::__call($method, $parameters);
    }
}
```

Or we could just poach the method from the Symfony class.

Our implementation should still keep everything decoupled, possibly write a new contract if necessary. 

(If this hasn't been resolved by next weekend, I'll tackle it myself.)

**Comment by adrienhobbs** [comment]
I'm experiencing this same issue with a fresh install. Can't load the index, as the view cannot be 
found.

However when using Bedrock, this issue doesn't occur.

> Fatal error: Uncaught InvalidArgumentException: 'View [home.vagrant.Code.dev.pops.wp-content.themes.pops.index] not found.' in /home/vagrant/Code/dev/pops/wp-content/themes/pops/vendor/illuminate/view/FileViewFinder.php:137

Is there a fix to get this working without Bedrock currently?

**Comment by askz** [comment]
Hi,
I just had the same issue, cannot load index with fresh bedrock then sage install.

The simplest way I found is to create uploads/cache/compiled folder then set right permissions.
