### ISSUE TITLE
Make theme available for translation

### ISSUE THREAD

**Issue by hambos22** [roots/sage#1770]
I think sage 9 missing the code to make the theme available for translation. I couldn't find any relevant code for loading the text domain

[https://github.com/roots/sage/blob/master/src/setup.php#L63](url)

`load_theme_textdomain('sage', get_template_directory() . '/lang');`

**Comment by ciromattia** [comment]
It has already been addressed in https://github.com/roots/sage/issues/1672
TL;DR it makes no sense to have a language template on a starter theme.
I usually add the line by myself and generate/update .pot/.po files with POEdit.

**Comment by hambos22** [comment]
Oh! I didn't see the #1672 . I'm closing it. Thanks :)
