### ISSUE TITLE
gulp --production: Potentially unhandled rejection [2] 'layouts/tinymce.less' wasn't found.

### ISSUE THREAD

**Issue by cnyyk** [roots/sage#1776]
## Submit a bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**
gulp --production for theme test.

**What is the expected or desired behavior?**

- [X] gulp error with: Potentially unhandled rejection [2] 'layouts/tinymce.less' wasn't found.
Actually, it should be tinymce.scss. 
If comment the last line in main.scss, will show posts.less not found.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**
1. composer create-project roots/sage sage842 8.4.2
2. yarn
3. bower install
- [X] 4. gulp --production

<img width="928" alt="qq20161217-0 2x" src="https://cloud.githubusercontent.com/assets/275233/21287977/6d8e75c0-c4b2-11e6-8680-2b5fd8f18931.png">

**Please describe your local environment:**

WordPress version: 
- [X] 4.7

OS: 
- [X] macOS 10.12.2

NPM/Node version:
- [X] node: v7.2.1
- [X] npm: 3.10.9
- [X] yarn: 0.17.10

**Where did the bug happen? Development or remote servers?**
- [X] Local Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

- [X] Yes, one issue related but not solved:
https://discourse.roots.io/t/gulp-issue-potentially-unhandled-rejection-2-error-enoent-open/3456

**Comment by greatislander** [comment]
See https://github.com/roots/sage/issues/1648 — have you updated `gulp-if` as per https://github.com/roots/sage/commit/2d3f25b3b6a97380164a4097673379f3cc868775?

**Comment by QWp6t** [comment]
I'm thinking this was fixed with Sage 8.5.0. 

If you still have the issue in the latest stable version of Sage, then post here and we'll revisit this issue.

**Comment by cnyyk** [comment]
Solved with 8.5.0 package.json.

Thank you all.
