### ISSUE TITLE
Invalid CSS causes task styles to crash.

### ISSUE THREAD

**Issue by myurtsev** [roots/sage#1783]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

After saving a .scss file task styles crashes with the error; invalid css and refers to the line where css is invalid.

**What is the expected or desired behavior?**

trigger 'plumber' to avoid crashing the gulp task so the developer can go and fix the specific line in the editor.
---

## Bug report

**Please describe your local environment:**

WordPress version: 4.7

OS: Mac OS Sierrra

NPM/Node version: v6.9.1

**Where did the bug happen? Development or remote servers?**

Development; gulp task watch

Sage 8.5.0

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

something with enabling the failstyletask perhaps?

**Comment by retlehs** [comment]
see #1779 for the fix

related thread: https://discourse.roots.io/t/jshint-crashing-gulp-when-a-javascript-error-occurs/6783/8
