### ISSUE TITLE
Add Filter for Custom Blade Directives

### ISSUE THREAD

**Issue by Log1x** [roots/sage#1785]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Allowing custom directives for blade without extending or modifying the core code of Sage.

**Other relevant information:**

I got this idea from [wp-blade](https://github.com/tormjens/wp-blade). You can see an example of how they implement it [here](http://blade.tormorten.no/extending/actions/#add-directives).

They also have a few default directives (although not a fan of their naming conventions) that may be useful to add into Sage's core to simplify things such as the repeated need to `@while(have_posts()) @php(the_post()) [...] @endwhile`

Such as the ability to do:

```
@posts
    @include('partials.content-page')
@endposts
```

Additional information on extending Blade can be seen on the Laravel docs [here](https://laravel.com/docs/5.3/blade#extending-blade).

Thought it might be a decent addition. If any objections, feel free to close this.

Thanks a ton! Loving Sage 9 so far and can't wait to see whats in store for the full release.

**Comment by swalkinshaw** [comment]
You can just add your own action on `after_setup_theme` like this:

```php
add_action('after_setup_theme', function () {
    sage('blade')->compiler()->directive('customDirective', function ($arg) {
        return 'htm';
    });
}, 20);
```

So I'd say a more specific filter/action isn't needed.

In terms of adding more directives by default, we specifically want to avoid those. We prefer the Blade integration to be the thinest layer possible.

**Comment by Log1x** [comment]
Ahhh. Didn't know you could call compiler with sage('blade') -- that's much cleaner than a filter. Thanks!
