### ISSUE TITLE
Feature Request: Routing

### ISSUE THREAD

**Issue by bonmagazine** [roots/sage#1788]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

There is no routing in WordPress. Let's say we have a website for the Foo Bar, `www.foo-bar.com`. The Foo Bar puts on black metal concerts and poetry sessions, so we have a Custom Post Type called `Events`. If we want to collect all upcoming Events in `www.foo-bar.com/upcoming`, the current workflow is:

- create a blank page in the WP backend called "Upcoming"
- create a page template for this page: `page-upcoming.php`
- create a function that queries all Events CPT with a future date

There are a few problems with this:

- the 'routing' of our website is stored in the database, which means we have to remember to create those 'routing' pages on staging and live when we deploy
- there's a risk users will delete these blank 'routing' pages and break the website. (It happens. A lot).
- having to use the backend and leave my beloved development environment kills my mojo

**What is the expected or desired behavior?**

I've been using [Timber](http://timber.github.io/timber) a lot, and its killer feature is [Routing](http://timber.github.io/timber/#routing). In Timber, I have a file called `routes.php` with the following deliciousness: 

```php
Routes::map('upcoming', function($params){
  $archive_args = array(
    'post_type' => array('events'),
    'posts_per_page' => -1,
    'order' => 'ASC',
    'orderby'  => 'meta_value',
    'meta_key' => 'start_date',
    'meta_query' => array(
      array(
        'key'   => 'start_date',
        'compare' => '>=',
        'value'   => current_time('Ymd')
      )
    )
  );
  Routes::load('upcoming.php', $params, $archive_args);
});
```

That's it. Now on the `upcoming.php` page I just loop through `$posts` and go enjoy my free time to read bad poetry. 

---

## Feature Request

Now that Sage 9 has Blade templates, it would be great if it matched Timber's features by also offering routing. The current workflow for custom routes as described above is brittle and perilous, prone to disasters of all kinds. Timber-style routing would improve developer morale by 300% and cut development time by at least 6 minutes.

If enough interest is generated, I would be happy to attempt a pull request to fix this crucial feature.

**Comment by eshimischi** [comment]
https://github.com/Brain-WP/Cortex

**Comment by QWp6t** [comment]
We have discussed this a few times and determined that it's outside the scope of Sage. We do provide a filter that you can use to inject data, or you can always hook into template_include (or any of the hierarchy filters) to pass a specified file to Blade.

You can actually accomplish what you're mentioning by using an events archive which you can specify to show up when a user hits the `/upcoming` path.

There's a lengthy blog post on the Roots website that covers how to accomplish routing using WordPress's own internal functions. He ultimately builds a small router and its API is similar to what you posted. Feel free to check it out.

https://roots.io/routing-wp-requests/

The author of that blog post is also the creator of Cortex, which @eshimischi has linked above.
