### ISSUE TITLE
Rename 'clean' task

### ISSUE THREAD

**Issue by psorensen** [roots/sage#1797]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

## Feature Request

**Please provide use cases for changing the current behavior:**

Most tasks can be started even when excluding the 'run' command. i.e. `yarn build`, `yarn start`

However, `yarn clean` and `yarn run clean` are very different. Running `yarn clean` is not recommended: (From the [docs](https://yarnpkg.com/en/docs/cli/clean))

Running `yarn clean` can lead to other tasks, such as `yarn build:production`, to not work properly. 
> Note: This command is considered for advanced use cases only. Unless you are experiencing issues with the amount of files that are installed as part of node_modules it is not recommended to use this command. It uses a heuristic to identify files that may not be needed from a distributed package and may not be entirely safe.

Making this change may prevent some support headaches down the line.

**Other relevant information:**

[Related discussion](https://discourse.roots.io/t/yarn-build-production-errors-svgo/8503/8?u=psorensen)

**Comment by QWp6t** [comment]
With npm, you have to use `npm run x` for everything except `npm start` and `npm test`. I assumed yarn would be the same. Interesting. 

But yeah, if that's the case, then we should consider renaming the task. Any suggestions?

**Comment by psorensen** [comment]
- distclean
- distrm
- rmdist
- cleandist
- cleanup

**Comment by BenOvermyer** [comment]
I like psorensen's solution. Very clear about what it does.
