### ISSUE TITLE
Importing Blade View engine into roots

### ISSUE THREAD

**Issue by torabian** [roots/sage#1801]
- [X] This is a feature request

Last week I was working on a custom starter theme named gallant by myself, my aim was to add these features:

- Create a good react boilerplate for WordPress ( Universal apps )
- Added blade view engine instead of using get_template_part to use more features shipped by laravel.

Now I think to add these features in this repository, do you think it's a good idea to add commit them?

**Comment by torabian** [comment]
That's ridiculous, I saw now it's implemented first item years ago!!!

**Comment by kalenjohnson** [comment]
😕
