### ISSUE TITLE
Adding super-wordpress strongly-typed classes

### ISSUE THREAD

**Issue by torabian** [roots/sage#1802]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Currently the WordPress posts are accessible through normal loop:

```php
if (have_posts()) {
  while(have_posts()) {
      get_the_title();
  }
}
```

**What is the expected or desired behavior?**

I was working on multiple project that they have more complicated types ( custom post types ), like hotels, tours, and places.
I decided to add strongly-typed models for my custom post types.

```php
$posts = Sage\Pages\Single::GetPosts();
foreach ($posts as $post) {
   // Post is actually now instanceof Post class:
   $post->GetTitle();
   $post->GetThumbnail()->GetUrl();
}

class Hotel extends Sage\Pages\Post {
  public function GetStars() {
     return 5;
  }
  public function GetLocation(): GeoLocation {
     // Find location by map or other methods and return a GeoLocation object.
  }
}

```
Now, I am working on [https://github.com/torabian/gallant/blob/master/src/Pages.php](https://github.com/torabian/gallant/blob/master/src/Pages.php) and it describes the definition of WP posts.

---
  
## Feature Request
**Please provide use cases for changing the current behavior:**

When using these set of classes, the expected data is ready before going to render pages. It can be compared with one-directional-flow of data, Also helps better typing for custom projects and modular project development.

**Other relevant information:**

X

**Comment by eshimischi** [comment]
I think all these is just a "sugar". Its better to work around WP-API in Wordpress + React/Vue nowadays, for example [deliciousbrains](https://deliciousbrains.com/creating-a-wordpress-theme-using-the-rest-api-and-vue-js/)

**Comment by QWp6t** [comment]
We won't be adding something like this to Sage since we don't want Sage to become a framework. This is better suited as a WordPress plugin or composer library anyway.
