### ISSUE TITLE
[Bug] Beta 1: Problems with watcher (SCSS & PHP)

### ISSUE THREAD

**Issue by emilsgulbis** [roots/sage#1804]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues/1803)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Bug report

**Steps**

1. `composer create-project roots/sage my-theme dev-master`
2. `npm install`
3. edited config.json
4. `yarn run start`

Opens localhost:3000 but with console errors:
`Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/app/themes/my-theme/dist/a8794502c051d1cd8213.hot-update.json`
`Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/app/themes/my-theme/dist/styles/main.css`

Also terminal prints - https://discourse.roots.io/t/sage9-not-inserting-styles-in-browsersync/8525/7?u=emilsgulbis
No PHP files edited, but watcher called.

**Please describe your local environment:**

WordPress version: 4.7

OS: macOS Sierra

NPM/Node version: 4.0.5 / 7.4.0

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/sage9-not-inserting-styles-in-browsersync/8525/7

**Comment by emilsgulbis** [comment]
Not working for me. 
Just created new sage theme and run `yarn run start` and no css was loaded (404 error on console) and same after styling update & browsersync refresh.

`yarn run build` works as expected and have no 404 errors on css files.

**Comment by giacomoalonzi** [comment]
after alpha1, I always had this problem.

**Comment by retlehs** [comment]
a copy of my reply to @emilsgulbis [from discourse](https://discourse.roots.io/t/sage9-not-inserting-styles-in-browsersync/8525/15):

@emilsgulbis I noticed that when you open your console at the start of the BS session that you're missing the error I mention at the top of https://github.com/roots/sage/pull/1806

```
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_2__util_Router__[false] is not a constructor
    at Object.<anonymous> (main.js:23)
    at Object.<anonymous> (main.js:27)
    at __webpack_require__ (bootstrap f2d9dd8…:659)
    at fn (bootstrap f2d9dd8…:83)
    at Object.<anonymous> (tether.js:1811)
    at __webpack_require__ (bootstrap f2d9dd8…:659)
    at bootstrap f2d9dd8…:708
    at bootstrap f2d9dd8…:708
```

Can you remove your `node_modules` folder, make sure `yarn.lock` is the same as what's on the Sage repo, and re-run `yarn`?

@giacomoalonzi did you try [making this change](https://github.com/roots/sage/commit/417ce46654d72405cfa0e46b94fd30b98c0093c0) and then following the instructions at the top of #1806?

please keep the support back-and-forth on the discourse thread for this specific issue:

https://discourse.roots.io/t/sage9-not-inserting-styles-in-browsersync/8525

**Comment by giacomoalonzi** [comment]
@retlehs Not yet, i'm going to try new beta in the next days, i'll let you know

**Comment by retlehs** [comment]
> please keep the support back-and-forth on the discourse thread for this specific issue:

i'm locking this issue. please use the discourse topic for discussion:

https://discourse.roots.io/t/sage-9-beta-1-not-inserting-styles-in-browsersync/8525

**Comment by retlehs** [comment]
fixed in beta 2
