### ISSUE TITLE
Font Awesome not added to package.json

### ISSUE THREAD

**Issue by runofthemill** [roots/sage#1818]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When running through the Sage install options, entering `y` at the `Add Font Awesome?` prompt does not end up adding font-awesome to `package.json`.

**What is the expected or desired behavior?**

It should be added to `package.json`

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. In theme directory, `composer create-project roots/sage your-theme-name dev-master`
2. Use defaults for all prompts, except `Add Font Awesome?`
3. Type `y` at `Add Font Awesome?` prompt 

I noticed the styles were correctly added to `main.scss` and `_variables.scss` so the script is running, the first part just isn't working :(

**Please describe your local environment:**

WordPress version: `4.7.1`

OS: `10.12.2`

NPM/Node version: 

```
$ npm -v
4.0.5

$ node -v
v7.4.0
```

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by drawcard** [comment]
For the time being, adding it manually via Yarn works:

```
yarn add font-awesome
yarn run build
```

**Comment by greatislander** [comment]
@runofthemill @drawcard https://github.com/roots/sage/pull/1819 should fix it.
