### ISSUE TITLE
Recommended screenshot image size

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1825]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

X Example screenshot has an image size of 880px x 660px.

**What is the expected or desired behavior?**

X [According to WordPress Codex](https://codex.wordpress.org/Theme_Development#Screenshot) the recommended image size for the screenshot image is 1200x900 (px).
It would be helpful when the (empty) example screenshot image has this size, too.

**Comment by retlehs** [comment]
thanks for reporting. this would be a good first PR for someone :eyes:

**Comment by psorensen** [comment]
You can do it!
