### ISSUE TITLE
Enable CSS build when watching

### ISSUE THREAD

**Issue by nicooprat** [roots/sage#1826]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

With the `--watch` flag, webpack doesn't create `dist/styles` directory nor compile styles. 

**What is the expected or desired behavior?**

Always build files, being watching them or not.

**Please describe your local environment:**

WordPress version: 4,7

OS: Mac El Capitan

NPM/Node version: 7

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

* Need to commit built files (I know, I know).
* Can't afford a continuous integration/deployment process. 
* Don't want to run `yarn build:production` before every commit.

Plus (not a big deal) there're always a 404 at first load for the `main.css` missing file, and a brief "flash of no style" before the CSS gets injected in development env.

**Other relevant information:**

Removing [this line](https://github.com/roots/sage/blob/master/assets/build/webpack.config.js#L130) makes Webpack building the CSS file even when watching, but then changes aren't live-reloaded. Just read a lot of threads about this and it seems hard/impossible to have hot-reloading + files written. Any idea? Am I missing something obvious here?

Thanks.

**Comment by retlehs** [comment]
the files are served from memory during a browsersync session, they will always 404 until a build

styles are automatically injected into the BS session during development. if that's not what you're seeing then you likely have a configuration issue with `assets/config.json`

please use https://discourse.roots.io/ for personal support requests

**Comment by nicooprat** [comment]
Got it working by using https://github.com/gajus/write-file-webpack-plugin.

1. `yarn add write-file-webpack-plugin --dev`
2. Edit `assets/build/webpack.confi.watch.js`:

````js
const webpack = require('webpack');
const BrowserSyncPlugin = require('browsersync-webpack-plugin');
const WriteFilePlugin = require('write-file-webpack-plugin');

const config = require('./config');

module.exports = {
  devServer: {
    outputPath: config.paths.dist
  },
  output: {
    pathinfo: true,
    publicPath: config.proxyUrl + config.publicPath,
  },
  devtool: '#cheap-module-source-map',
  stats: false,
  plugins: [
    new WriteFilePlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new BrowserSyncPlugin({
      target: config.devUrl,
      proxyUrl: config.proxyUrl,
      watch: config.watch,
      delay: 500,
    }),
  ],
};
````

I think it could be an interesting (and not complicated to add) option to have in Sage. I guess I'm not the only one in my situation: I'm building websites which will potentially by deployed on cheap servers where I can't have a proper build environments (can't install node for example) ; so compiling assets on the server is not an option. I must build & commit them locally, but having to run `yarn run build` before each commit/deploy is annoying and error/forget prone.

So I guess it's still a feature request and not really a bug or misunderstanding :)

**Comment by quangthien27** [comment]
@nicooprat 's fix also works for sage 9

**Comment by dylanjameswagner** [comment]
This does not work for me. Can I clarify that the `// Force CSS update` code goes into the theme's `/resources/assets/scripts/main.js`?

@nicooprat 
Should this be overwriting the `main.css` file content on compile from running `yarn start`?

**Comment by nicooprat** [comment]
@dylanjameswagner It's a bit old in my memory, but yes it should be in your `main.js` or any other JS file that is loaded by Webpack. The `main.css` content should indeed be replaced, does this work? Your browser might still load its cached version regardless the `?` date parameter appended in the stylesheet URL. You can try to open the devtools and disable cache to avoid this.
