### ISSUE TITLE
get_posts() with Blade

### ISSUE THREAD

**Issue by Log1x** [roots/sage#1829]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

`get_posts($args)` always returns the current post instead of the `$args` passed.

**What is the expected or desired behavior?**

For it to return posts relevant to the `$args` passed.

---

## Bug report

Well, I figure I'd be the one to bring this up since I created the original issue concerning `$post` with Blade.

Due to WordPress being a little retarded, `setup_postdata($post);` **must** be called with a variable called `$post`. With that being the case, the current implementation of 

```
add_action('the_post', function ($post) {
    sage('blade')->share('post', $post);
});
```

overrides any `foreach` statement such as `foreach ($myposts as $post) : setup_postdata($post);` and causes it to not work as intended.

While this isn't really an issue and I just did a `WP_Query` instead, I thought I would bring this to light in case there's a fix for it.

Otherwise, I feel like it should just be noted in the official documentation and left alone.

---

**Comment by QWp6t** [comment]
```php
foreach ($myposts as $mypost) : setup_postdata($mypost);
```

Ideally you'd be doing this before your templates are loaded, though. This type of logic doesn't belong in a template, but we do still make it possible. You can always grab `$GLOBALS['post']` if you want, but that's pretty ugly.

Regardless, this isn't a bug with Sage. It's a scoping issue. Just grab the global variable if you need to.

Also note: https://github.com/roots/sage/blob/master/src/setup.php#L94
