### ISSUE TITLE
eslint / console log

### ISSUE THREAD

**Issue by samburgers** [roots/sage#1837]
## Submit a feature request or bug report

- [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X ] This is a feature request
- [ ] This is a bug report
- [ X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

`console.log('foo')` results in build errors

**What is the expected or desired behavior?**

`console.log('foo')` should simply log to console without error

---

## Feature Request

add this to `.eslintrc` file

```
  "rules": {
    "no-console":0
}
```

**Comment by QWp6t** [comment]
We want it to fail if there is console output. If we ever have a need for console output, we can use `eslint-disable-line no-console` or something similar.

You're certainly free to set that rule on your own, though.

**Comment by samburgers** [comment]
fair enough, thanks.
