### ISSUE TITLE
Wrong dist-path in WP 4.7.2

### ISSUE THREAD

**Issue by ad-on-is** [roots/sage#1838]
WordPress tries to include the dist-files from within the templates directory, instead of the theme root directory. Fresh installation of WP and sage 8.5.0.

gulp output
`wp-content/themes/mytheme/dist/styles/main.css`

WP HTML-output
`wp-content/themes/mytheme/templates/dist/styles/main.css`

If I debug the get_template_directory_uri() in lib/assets.php I get
`wp-content/themes/mytehem/templates`

What's wrong here?

**Comment by ad-on-is** [comment]
Nevermind, the issue is gone... somehow!?

**Comment by retlehs** [comment]
when you created this issue you cleared out the entire issue template, including the part where you were supposed to mark that this wasn't a personal support request

please don't do that, and please use https://discourse.roots.io/ for support in the future.
