### ISSUE TITLE
Update to Laravel Blade 5.4

### ISSUE THREAD

**Issue by Log1x** [roots/sage#1841]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Feature Request

**Please provide use cases for changing the current behavior:**

I'd like to see if we can update Blade to 5.4 that got released on January 24th.

The most notable change is the use of [`@component` and `@slot`](https://laravel.com/docs/5.4/blade#components-and-slots).

An example usage of this is to create `templates/components/alert.blade.php` with:

```
<div class="alert alert-warning">
  {{ $slot }}
</div>
```

and then call upon it inside of our views for example:

```
@component('components.alert')
  {{ __('Sorry, no results were found.', 'sage') }}
@endcomponent
```

Also coming with 5.4 is [Laravel Mix](https://laravel-news.com/laravel-elixir-to-laravel-mix) (previously known as Elixir) which now uses Webpack instead of Gulp. Might be worth a glance for ideas to even further optimize Sage's use of Webpack. [Here's](https://laravel-news.com/laravel-5-4) a breakdown of the changes courtesy of Laravel News.

Thanks in advance.

**Comment by Log1x** [comment]
It looks like changing `composer.json` to use `~5.4.0` for `illuminate/view` and `illuminate/config` did the trick, but I had to manually clear `uploads/cache` -- not sure how you guys want to handle situations like that so I'm going to wait for you guys instead of submitting a pull request.

**Comment by kaisermann** [comment]
Did the same thing with my `composer.json` and everything is still working for me

**Comment by samrap** [comment]
Can confirm the same works for me 👍

**Comment by LeoColomb** [comment]
@Log1x Did you succeed to use Blade components within latest Sage?

**Comment by Log1x** [comment]
@LeoColomb yeah they work good.

Here's an example of an `alert.blade.php`

```
<div class="alert {{ $type or 'warning' }}">
  @if (isset($title))
    <h4>{{ $title }}</h4>
  @endif
  {{ $slot }}
</div>

```
