### ISSUE TITLE
Unexpected Token {

### ISSUE THREAD

**Issue by djoks** [roots/sage#1843]
Hello I recently started using sage again after a long time and a lot of things seem to have changed for me. I had to install yarn but when I tried running the command yarn run build I got:
```
λ yarn run build
yarn run v0.20.3
$ webpack --progress --config assets/build/webpack.config.js
F:\www\xxxxxx\wp-content\themes\23022017\node_modules\copy-globs-webpack-plugin\index.js:101
const { promisify } = __webpack_require__(0);
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (F:\www\xxxxxx\wp-content\themes\23022017\assets\build\webpack.config.js:10:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Now I have already successfully run the following commands in my terminal:
```
composer self-update
composer update
npm install
yarn
```

OS: Windows 10
NodeJS: 4.8.0

**Comment by lekkerduidelijk** [comment]
NodeJS 7.6.0 is current. I think you should try upgrading.

**Comment by djoks** [comment]
Okay, reason I didn't was when I was running npm install I saw it say it needed NodeJS version >= 4.3.0 <= 5.0.0 or does that not matter?

**Comment by QWp6t** [comment]
That's probably some other dependency giving you that warning, but it should be safe to update beyond 5.x.

Our requirements are listed right here: https://github.com/roots/sage#requirements
And here: https://github.com/roots/sage/blob/master/package.json#L30

**Comment by djoks** [comment]
Thank you, you were right, it was my NodeJS version. It works now.

**Comment by nickkos101** [comment]
Can you please inform us what you did to fix it...I've upgraded and downgraded my node...my NPM everything nothing is fixing this issue for me i have the same exact message.

**Comment by djoks** [comment]
I did like I was asked to do, I upgraded my nodejs version that's all.
