### ISSUE TITLE
 blank lines appearing in the output html on every single page

### ISSUE THREAD

**Issue by maharjanrams** [roots/sage#1844]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

 blank lines appearing in the output html on every single page. 

**What is the expected or desired behavior?**

no blank lines

---

## Bug report

**Please provide steps to reproduce, including full log output:**

View source the page

**Please describe your local environment:**

WordPress version: Sage 8.5.1 with Latest wordpress

OS: MAC

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by retlehs** [comment]
are you talking about the first blank line? this doesn't exist anymore in sage 9

**Comment by maharjanrams** [comment]
I am using Sage 8.5.1, is there a  way to fix it?
