### ISSUE TITLE
Pass variables along the blade asset directive

### ISSUE THREAD

**Issue by malamoet** [roots/sage#1845]
Hi,

I'm using the blade asset directive for image path rendering. When passing a plain string everything works just fine. But when passing a variable the result isn't really as expected:

**Static example:**
this line of code (with the @asset() directive)
`<img src="@asset('images/stoel.png')" alt="Stoel" class="c-product__image">`
results in
`<img src="//192.168.1.4:3000/app/themes/my-theme/dist/images/stoel.png" alt="Stoel" class="c-product__image">`

**Dynamic example:**
```
<?php
  $products = [
    1 => [
      'image' => 'images/stoel.png',
      'title' => 'Stoel laag bruin',
    ]
  ]
?>
```
the image tag in the code look like this (when iterating over the products array)
`<img src="@asset(<?php echo $product['image']; ?>)" alt="" class="c-product__image">`
results in
`<img src="//192.168.1.4:3000/app/themes/my-theme/dist/(images/stoel.png)" alt="Stoel" class="c-product__image">`

So as you can see, for some reason '(' and ')' are added to the resource string which off course results in a missing non existing resource...

Am I doing something wrong here?

Thanks in advance,
Thomas

**Comment by lekkerduidelijk** [comment]
`@asset` is a custom Blade helper. Check the src folder in Sage. You can't use `<?php` directly in there.

**Comment by malamoet** [comment]
Thx for the quick reply.

So how can variables be passed with the @asset() helper in the blade views? Or is this not possible at all?

**Comment by lekkerduidelijk** [comment]
`$image = 'images/foo.jpg';` with `<img src='@asset($image)'>` should work.

**Comment by malamoet** [comment]
@lekkerduidelijk Makes sense, but after trying this it still doesn't renders the correct output. It seems like the php variable isn't getting parsed and is printed as plain text...

In my .blade.php file i've got this:
```
@php
 $image = 'images/foo.jpg';
@endphp
<img src="@asset($image)" alt="Stoel" class="c-product__image">
```

Renders to this:
`<img src="//192.168.1.4:3000/app/themes/my-theme/dist/$image" alt="Stoel" class="c-product__image">`

**Comment by QWp6t** [comment]
This is deliberate behavior on the part of the `@asset()` directive.

I was thinking users might get confused as to whether they should wrap the string in quotes, i.e., `@asset(images/foo.jpg)` vs `@asset('images/foo.jpg')` so I deliberately made it able to handle both. Looks like a downside is that it doesn't properly render variables. lol oops.

The solution is to remove `trim()` from this line:

https://github.com/roots/sage/blob/master/src/setup.php#L149

```php
return '<?= App\\asset_path($asset); ?>';
```

You guys are free to submit a PR with that change if you want, otherwise I'll tackle it next time I'm working on Sage. Thanks for bringing it to my attention. Sorry for the confusion.

**Comment by malamoet** [comment]
Thanks for the clarification.

So what you're saying is to replace the following line (setup.php):
`return '<?= App\\asset_path(\''.trim($asset, '\'"').'\'); ?>';`
with
`return asset_path($asset);`

Is that correct?

After doing this the variable ($image) is still unparsed and outputed as a plain string...
`src="//192.168.1.4:3000/app/themes/my-theme/dist/$image"`

**Comment by QWp6t** [comment]
My bad. This should work.

```php
return "<?= App\\asset_path('{$asset}'); ?>";
```

If that doesn't work, let me know and I'll actually test it and figure it out.

**Comment by malamoet** [comment]
@QWp6t I'm sorry but still no success...

I've adjusted the asset directive with the line from your latest comment and now I'm getting the following error:

> Parse error: syntax error, unexpected 'image' (T_STRING), expecting ',' or ')'

In my Blade view I have the following:

`<img src="@asset($realization['image'])" alt="{!! $realization['title'] !!}" class="c-realization__image">`

I've tried fixing it myself but i'm a bit of a novice when it comes to php...

Could you take a closer look please?

Thanks in advance
