### ISSUE TITLE
Fatal error: Call to undefined function App\template() 

### ISSUE THREAD

**Issue by myurtsev** [roots/sage#1848]
Hi guys, at a single (custom type) page I get the following error; Fatal error: Call to undefined function App\template(). Refering to line; `<?php include App\template()->main(); ?>` in base.php

any ideas why and how to fix it? 

Working on Sage 8.5.0, MAC OS Sierra

**Comment by retlehs** [comment]
please don't clear out the issue template when creating a new issue. head over here:

https://discourse.roots.io/
