### ISSUE TITLE
Browsersync session not injecting updates from Blade templates

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1859]
as of #1817, changes to blade templates in a browsersync session should be injected. this is not working for all users. updating the `delay` [as suggested](https://github.com/roots/sage/issues/1816#issuecomment-274986730) does not resolve the issue

related thread: https://discourse.roots.io/t/watching-blade-files-in-sage-9-beta-2/8816

**Comment by QWp6t** [comment]
If you remove bs-htmlinjector (or whatever it is), does that cause the page to reload when making changes to php files?

**Comment by QWp6t** [comment]
Let's continue discussion in the PR

https://github.com/roots/sage/pull/1862

**Comment by apintocr** [comment]
I think we should recheck this, I just created a new project using the latest sources from here and got exactly the same issue (using https)

**Comment by jfatomix** [comment]
We're also seeing this issue. As above, page doesn't refresh after making changes to PHP or blade files, changing the delay setting for Browersync has no effect. Style & script assets inject fine.

**Comment by thisprojectworks** [comment]
I have the exactly same issue: Page doesn't refresh after making changes to PHP or blade files, changing the delay setting for Browersync has no effect. Style & script assets inject fine.

**Comment by w-biggs** [comment]
I'm having exactly this issue as well. I can't seem to find any solution to this at all...

**Comment by retlehs** [comment]
the solution to this problem should be a properly configured theme (`devUrl` and `publicPath` in `resources/assets/config.json`)

if you need further help, please visit https://discourse.roots.io/

**Comment by w-biggs** [comment]
The problem is that those two are perfectly configured. Just blade files won't update.

**Comment by retlehs** [comment]
another problem is using github for support — all replies trigger notifications to people watching this project. this is a bug that has been solved and not popped up for quite some time, so please visit https://discourse.roots.io/ for further help
