### ISSUE TITLE
S3 Uploads is not compatible with compiled blades

### ISSUE THREAD

**Issue by andrewklau** [roots/sage#1863]
I'm not sure if this should be a config change or document change, but the new Laravel blade `view.compiled` config will conflict with plugins like s3-uploads as it'll try to reach out to S3 for the compiled file.

The quick fix would be not to store it in the uploads folder but I'm not sure how relevant that is to everyone.

**Comment by apintocr** [comment]
Similar issue with _Tailor_ https://discourse.roots.io/t/sage-9-beta-2-tailor-editor-giving-view-error/9003

**Comment by retlehs** [comment]
@andrewklau you can configure the path of the compiled blade files to move them outside of the uploads directory, open `src/setup.php` and see `config` ... `view.compiled`

**Comment by andrewklau** [comment]
@apintocr I don't believe this is the same issue

@retlehs Yeah that's what I did, I was just opening this issue to get some awareness, perhaps something that may want to get documented or breadcrumbed for anyone else that gets caught.

**Comment by QWp6t** [comment]
Next update will have a simpler config system, which should make it more obvious for developers what's going on.
