### ISSUE TITLE
Problems with interchange and Foundation

### ISSUE THREAD

**Issue by alexkerber** [roots/sage#1865]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

interchange only works when I run yarn run build not yarn start. It complains about foundation-mq. What I can see is that it enables this into the header with a metatag. Works fully when I include  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.css"> in head.blade.php.

**What is the expected or desired behavior?**

Should view right image for right breakpoint (I'm using it for backgrounds and images)

---

## Bug report

**Please describe your local environment:**
Latest Sage (9 beta v2), Bedrock and Trellis

WordPress version: 4.7.3

OS: MacOS 10.12.3 (16D32)

NPM/Node version: 4.1.2 / 7.7.3

**Where did the bug happen? Development or remote servers?**

Development locally

**Comment by JulienMelissas** [comment]
>It complains about foundation-mq.

We're gonna need a lot more information about this if this is actually a "bug report" and not just a personal request please!

**Comment by alexkerber** [comment]
It's hard no errors at all in the console log. Works perfect when I import a CDN from Foundation 6 … so this might be an even deeper issue. What I do for now is use the cdn until I'm done with the site and before deployment just delete this line.

**Comment by deJong** [comment]
Foundation puts a meta tag into head like: ”small=0em&medium=40em&large=64em&xlarge=75em&xxlarge=90em";

It then reads those queries in util.mediaQuery.js and uses it to enable js breakpoints.
The _init function of Foundation.MediaQuery does the following:
var extractedStyles = $('.foundation-mq').css('font-family');

The meta tag is empty at the time util.mediaQuery.js initializes. As alexkerber said: this only happens with yarn start.

Related Discourse topic:
https://discourse.roots.io/t/sage-9-and-foundation-mediaquery/8686

**Comment by alexkerber** [comment]
Run it with the computer IP address instead of the localhost works!

**Comment by wgroenewold** [comment]
Is it an option to detect if there are any vars set before util.mediaQuery.js initializes? That woud circumvent the problem I guess.

**Comment by alexkerber** [comment]
@wgroenewold include it somewhere? Tell me more. This "bug" starts gets frustrating ;-)

**Comment by jayarnielsen** [comment]
I'm building a theme with beta3 and foundation, and can confirm that Foundation's javascript components do not work when using yarn start, but do work when using yarn build. So far I've run into issues getting sticky and equalizer to function when using yarn start.

**Comment by QWp6t** [comment]
The media query stuff seems to work fine on my end, but I'm definitely having trouble with sticky and equalizer. I think this is an issue on their end, though.

I'm thinking it it's because the JS gets loaded before the CSS, which presumably would also make their plugins incompatible with lazy-loaded CSS, but I'm not sure.

Loading Foundation CSS from a CDN resolves the issue for me, which lends a little credence to my theory.

At any rate, I don't think this is something that we can resolve in Sage without a hack that specifically targets Foundation. The good news is that we can implement such a hack in https://github.com/roots/sage-installer if anyone comes up with a workaround.

**Comment by campaignupgrade** [comment]
@QWp6t ever find a better hack for this issue? 

I can load Foundation from a CDN but then some settings are overridden, or I can add `jQuery(window).on('load', () => Foundation.MediaQuery._init());` to main.js and some styles are still broken, but I can't seem to get full functionality under `yarn start`.
