### ISSUE TITLE
Imagemin-SVGO is throwing error in Gulp

### ISSUE THREAD

**Issue by schutzsmith** [roots/sage#1866]
**What is the current behavior?**

Imagemin-SVGO has been updated to 5.2.1 and now throws error breaking Gulp. More at https://github.com/imagemin/imagemin/issues/237

**What is the expected or desired behavior?**

Gulp commands previously were working fine.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Install new Sage 8.x theme. Run npm install, bower install, then run any gulp command.

**Please describe your local environment:**

WordPress version: latest

OS: 10.11.6

NPM/Node version: 3.10.8

**Where did the bug happen? Development or remote servers?**

Dev

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by JulienMelissas** [comment]
Have you tried updating node? https://github.com/imagemin/imagemin/issues/237#issuecomment-290368841

**Comment by S8nsick66** [comment]
I couldn't upgrade Node so I edited package.json in the theme folder:

    "gulp-imagemin": "^2.4.0",
