### ISSUE TITLE
Tailor Builder Fatal Error

### ISSUE THREAD

**Issue by apintocr** [roots/sage#1872]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When using the Tailor Builder Plugin a Fatal Error appears.
```
! ) Fatal error: Uncaught InvalidArgumentException: View [] not found.
    in /(...)/mytheme/vendor/illuminate/view/FileViewFinder.php on line 137
( ! ) InvalidArgumentException: View [] not found.
    in /(...)/mytheme/vendor/illuminate/view/FileViewFinder.php on line 137
```
*Sometimes* the live editor opens, *sometimes* it's stuck at loading.

**What is the expected or desired behavior?**

The live editor should open without any error.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

- Install and Activate Tailor
- Open a Page and select *Edit with Tailor*
- Fatal Error appears on the left.
![image](https://cloud.githubusercontent.com/assets/1459530/24696606/efc69034-19e1-11e7-87a2-8d07006261c8.png)

```
( ! ) Fatal error: Uncaught InvalidArgumentException: View [] not found.
    in /srv/www/mysite/current/web/app/themes/mytheme/vendor/illuminate/view/FileViewFinder.php on line 137
( ! ) InvalidArgumentException: View [] not found.
    in /srv/www/mysite/current/web/app/themes/mytheme/vendor/illuminate/view/FileViewFinder.php on line 137
Call Stack
#	Time	Memory	Function	Location
1	0.2014	355872	{main}( )	.../index.php:0
2	0.2048	357824	require( '/srv/www/mysite/current/web/wp/wp-blog-header.php' )	.../index.php:5
3	1.6093	39370536	require_once( '/srv/www/mysite/current/web/wp/wp-includes/template-loader.php' )	.../wp-blog-header.php:19
4	1.6192	39561168	apply_filters( )	.../template-loader.php:73
5	1.6192	39561568	WP_Hook->apply_filters( )	.../plugin.php:203
6	1.7115	40885184	App\{closure}( )	.../class-wp-hook.php:298
7	1.7146	40912320	App\template( )	.../filters.php:57
8	1.7147	40912320	Roots\Sage\Template\Blade->render( )	.../helpers.php:57
9	1.7147	40912320	Roots\Sage\Template\Blade->make( )	.../Blade.php:51
10	1.7147	40912696	Roots\Sage\Template\Blade->__call( )	.../Blade.php:51
11	1.7147	40913072	call_user_func_array:{/srv/www/mysite/current/web/app/themes/mytheme/src/lib/Sage/Template/Blade.php:127} ( )	.../Blade.php:127
12	1.7147	40913496	Illuminate\View\Factory->make( )	.../Blade.php:127
13	1.7155	40916336	Illuminate\View\FileViewFinder->find( )	.../Factory.php:128
14	1.7155	40916336	Illuminate\View\FileViewFinder->findInPaths( )	.../FileViewFinder.php:79
```
**Please describe your local environment:**

WordPress version: 4.7.3

OS: Ubuntu 16.04 (Trellis)

**Where did the bug happen? Development or remote servers?**

Development Server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/sage-9-beta-2-tailor-editor-giving-view-error/9003

---

**Other relevant information:**

- Posted same [issue report](https://github.com/andrew-worsfold/tailor/issues/109) at Tailor Repository

**Comment by apintocr** [comment]
I'm open to help debug/fix, but I do need some help finding the root cause of the issue.

**Comment by QWp6t** [comment]
Fixed with this refactor: https://github.com/roots/sage/pull/1919/commits/1a8dce9b092e8bbe1d1921c43eb3691f3399b0a7

(still hasn't been merged)

If you wanna fix it on your end, then in filters.php, swap out the template_include filter for this:

```php
/**
 * Render page using Blade
 */
add_filter('template_include', function ($template) {
    $data = collect(get_body_class())->reduce(function ($data, $class) use ($template) {
        return apply_filters("sage/template/{$class}/data", $data, $template);
    }, []);
    if ($template) {
        echo template($template, $data);
        return get_stylesheet_directory().'/index.php';
    }
    return $template;
}, PHP_INT_MAX);
```
