### ISSUE TITLE
CSS not injected on external URL

### ISSUE THREAD

**Issue by nicooprat** [roots/sage#1874]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Using external URL on another machine (same network), eg `192.168.1.4:3000`, CSS is not getting injected. 

**What is the expected or desired behavior?**

CSS should be refresh as it is on local URL, eg `localhost:3000`.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

* Install fresh Sage theme, activate, start server. 
* Open one tab with the local URL, another with the external URL given by BrowserSync.
* Make a CSS change, save.

CSS is refreshed on the local tab, not on the external one. 

Notes:

* the BrowserSync notification works.
* No error in console. 
* The local URI **does** work on the same machine though. 
* Tried with another Mac, Windows, IE, iPhone... Same issue everywhere.
* Changes in JS & Blade templates are injected correctly

**Please describe your local environment:**

WordPress version: 4.7.3

OS: Mac OS El Capitan (Chrome latest)

NPM/Node version: 7.4.0

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Didn't find anything.

Thanks in advance!

**Comment by retlehs** [comment]
just tested this out and was unable to reproduce
