### ISSUE TITLE
Translation tools aren't picking up strings in templates

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1875]
it looks like translatable strings, such as https://github.com/roots/sage/blob/bea1b34322d38c04a16f373170154051244c4982/resources/views/index.blade.php#L8, aren't been picked up by translation tools

if you swap `{{  }}` with `<?php ?>` then the strings are detected

```diff
- {{ __('Sorry, no results were found.', 'sage') }}
+ <?php __('Sorry, no results were found.', 'sage'); ?>
```

discourse thread: https://discourse.roots.io/t/localization-of-blade-templates/9331

tools:

* https://github.com/rasmusbe/wp-pot
* https://develop.svn.wordpress.org/trunk/tools/i18n/ (`makepot.php`)
* poedit

**Comment by apintocr** [comment]
For PoEdit (1.x and 2.x) following this guide should work.
http://framework.themosis.com/docs/master/blade/

I do not think this issue should be resolved on Sage level but rather on the translation tools themselves.

**Comment by nicooprat** [comment]
Thanks, but PoEdit still  can't find any string if not within a `<?php ?>` block:

````php
// wp-content/themes/sage/templates/test.blade.php
<?php __('test'); ?> // works
{{__('test2')}} // doesn't work
@php(_e('test3')) // doesn't work
````

I also tried these tools: 
* https://github.com/rasmusbe/wp-pot
* https://github.com/rasmusbe/wp-pot-cli

without luck, the generated .pot files are always empty. Too bad because it could be great to have a command to generate `.pot` files, like `yarn run localize`.

Just stumbled upon a PHP solution, https://github.com/xinax/laravel-gettext. Did anyone tried to integrate something like this?

By the way, looks like the WPML team doesn't plan to do anything more to support Blade templates: https://wpml.org/forums/topic/string-translation-in-blade-template-engine/

Thanks.

**Comment by apintocr** [comment]
@nicooprat I'm using PoEdit, WPML and Sage 9 Bladeand following the guide above it works.

**Comment by nicooprat** [comment]
Thanks for your feedback. Here's my config:

![capture d ecran 2017-04-11 a 14 26 18](https://cloud.githubusercontent.com/assets/645641/24909120/e335e442-1ec2-11e7-9e34-2b8a70f93b68.png)
![capture d ecran 2017-04-11 a 09 58 32](https://cloud.githubusercontent.com/assets/645641/24909123/e33a99c4-1ec2-11e7-9d11-37fed4aad4fa.png)
![capture d ecran 2017-04-11 a 09 59 42](https://cloud.githubusercontent.com/assets/645641/24909122/e3370462-1ec2-11e7-900d-c8d6d0200942.png)
![capture d ecran 2017-04-11 a 09 58 39](https://cloud.githubusercontent.com/assets/645641/24909121/e336617e-1ec2-11e7-8525-048315d2f28b.png)

(Btw, I agree that's not sth to be managed by Sage *theme*, but its *tooling*, either with PHP or JS)

**Comment by apintocr** [comment]
I'm using the exact same config and it works.
I only have a slight difference, I'm using the theme root folder and I've added exclusions for vendor/node_modules/(...)

Currently I'm on PoEdit 2.0, but the same config worked on previous versions.

Try removing the *.scout.php, leave only *.blade.php

**Comment by nicooprat** [comment]
Unfortunately removing `*.scout.php` didn't solve it.

Also tried the configuration you recommend, no change.

I just did it all over again, by creating a fresh new `.po` file in the theme root directory with PoEdit, no luck either. :(

Do we agree that the goal is to avoid using `<?php ?>` blocks, like in my screenshot above?

When you say that it's working with WPML, do you mean that you scan the theme with PoEdit, leave translations empty, and then fill them with the WPML String Translation plugin?

Thanks for your time.

**Comment by lekkerduidelijk** [comment]
I'm using Poedit 2 (macOS) with the Blade extractor settings in a Multilingual Press (multisite) setup. Poedit works like a charm with the `{{ __('String','namespace') }}` definitions. I've created a `.pot` file first. 

Make sure you include the load textdomain method and define your lang folder.

**Comment by Kimers** [comment]
It seems I'm only able to make this work for either php or blade, not both at once.

**Comment by wgroenewold** [comment]
Is it possible to ship a config file for PoEdit bundled with Sage?

**Comment by ptrckvzn** [comment]
I think it works well with xgettext on the command line using this in the theme folder (replace \<textdomain\> and \<theme\>. It picks up both *.php and *.blade.php.

`$ find ./resources ./app -iname "*.php" | xargs xgettext --language=Python --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=<textdomain> -k__ -k_e -k_n -k_x -k_ex -k_nx -kesc_attr__ -kesc_attr_e -kesc_attr_x -kesc_html__ -kesc_html_e -kesc_html_x -k_n_noop -k_nx_noop -o resources/languages/<theme>.pot`

**Comment by nicooprat** [comment]
Ok this one seems to work! Hooray :) So here's the workflow:

1. Add strings in blade files like `__('string', 'domain')`
1. In the terminal, go to the theme root folder & execute the command above (don't forget to replace two terms as mentioned)
1. I recommend placing all localization (.pot .mo .po) files in `THEME_FOLDER/lang` (they're easily found by Wordpress here). 
1. Open the generated .pot file with PoEdit, select "create new translation", and save .mo & .po files in the `lang` folder with the correct name syntax, eg. `fr_FR` or `en_US`.
1. Translate some strings and save, .mo files should be generated automatically by PoEdit.
1. When adding/removing translations in templates, run the command again, then in PoEdit go to "Catalog > Update from a POT file" and select the .pot file.

If you're using WPML, in the "Theme & plugin localization" tab, you should see the table for each lang with the corresponding "The file exists" in front of it:

![capture-d ecran-2017-05-31-a-14 50 30](https://cloud.githubusercontent.com/assets/645641/26632498/b0b80a70-4610-11e7-983f-a4560fde9a09.jpg)

You can also add the terminal command to your package.json file and then run `yarn run pot`: 

````json
{
  "name": "sage",
  ...
  "scripts": {
    ...
    "pot": "find ./templates -iname \"*.php\" | xargs xgettext --language=Python --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=<domain> -k__ -k_e -k_n -k_x -k_ex -k_nx -kesc_attr__ -kesc_attr_e -kesc_attr_x -kesc_html__ -kesc_html_e -kesc_html_x -k_n_noop -k_nx_noop -o ./lang/<domain>.pot"
  },
}
````

Many thanks.

**Comment by QWp6t** [comment]
Closing this since it's now a documentation issue.

**Comment by thomascharbit** [comment]
I believe this is still an issue as it won't pick `__()` between quotes (in HTML attributes)
So @lekkerduidelijk comment is still valid from what i tested.
See https://stackoverflow.com/a/34249157/632487

**Comment by thomascharbit** [comment]
So best solution seems to compile blade templates and run xgettext on it.
To do this i guess https://github.com/alwaysblank/blade-generate would help!

**Comment by dsturm** [comment]
Thanks @nicooprat´s! I've modified the [terminal command](https://github.com/roots/sage/issues/1875#issuecomment-305179782) to match the current directory structure and parsing .php and .blade.php in separate commands, since it gave me warnings on php files:

```json
{
  "name": "sage",
  ...
  "scripts": {
    ...
    "pot": "mkdir -p ./resources/lang && find ./resources ./app -iname \"*.php\" | xargs xgettext --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -o resources/lang/sage.pot && find ./resources -iname '*.blade.php' | xargs xgettext --language=Python --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -j -o resources/lang/sage.pot"
  },
}
```

**Comment by andyinabox** [comment]
I was getting an error when the pot file wasn't exist. Fixed by adding

```
touch ./resources/lang/sage.pot
```

**Comment by apintocr** [comment]
@dsturm I cannot seem to make your command work.

Am I missing anything?

**Comment by dsturm** [comment]
@apintocr Hmmm - do you get any error message? What system are you using? Any files created?

**Comment by apintocr** [comment]
@dsturm I'm using Windows and Ubuntu. Obviously it is not working on Windows ;)

On ubuntu, it returns:
`xgettext: no input file given`

But the file is there.

**Comment by PMS72** [comment]
Hi,

For all Polylang (Pro) users: I am using this plugin for theme translation: https://wordpress.org/plugins/theme-translation-for-polylang/

I've used it before for Timber/Twig projects and now for the first time for a Sage/Laravel project. You can use `{{ pll__('String to translate') }}` (note the missing text domain, the plugin will add it for you) and your strings will automatically appear in Languages > String translation. No need to worry about .po, .mo or .pot files.

**Comment by retlehs** [comment]
for anyone coming here in the future: https://roots.io/sage/docs/theme-localization/

for updates/improvements, please submit a PR to the docs or open a discussion on roots discourse

**Comment by sandrowuermli** [comment]
@dsturm @apintocr
Got an error too:
```sh
$ yarn pot
yarn run v1.5.1
$ mkdir -p ./resources/lang && find ./resources ./app -iname "*.php" | xargs xgettext --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -o resources/lang/sage.pot && find ./resources -iname '*.blade.php' | xargs xgettext --language=Python --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -j -o resources/lang/sage.pot
xargs: xgettext: No such file or directory
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
Arguments: -c mkdir -p ./resources/lang && find ./resources ./app -iname \"*.php\" | xargs xgettext --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -o resources/lang/sage.pot && find ./resources -iname '*.blade.php' | xargs xgettext --language=Python --add-comments=TRANSLATORS --force-po --from-code=UTF-8 --default-domain=de_DE -k__ -k_e -k_n:1,2 -k_x:1,2c -k_ex:1,2c -k_nx:4c,12 -kesc_attr__ -kesc_attr_e -kesc_attr_x:1,2c -kesc_html__ -kesc_html_e -kesc_html_x:1,2c -k_n_noop:1,2 -k_nx_noop:3c,1,2, -k__ngettext_noop:1,2 -j -o resources/lang/sage.pot
Directory: /Users/sandro/Sites/Hostpoint/madbox.ch/web/app/themes/madbox
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/sandro/Sites/Hostpoint/madbox.ch/web/app/themes/madbox/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by retlehs** [comment]
please read the error message you provided:

> xargs: xgettext: No such file or directory

i'm locking this because we prefer to use roots discourse for conversations & support. every reply on here notifies everyone who is watching the repo
