### ISSUE TITLE
Anonymous functions on filters/hooks

### ISSUE THREAD

**Issue by timersys** [roots/sage#1882]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x ] This is a feature request
- [ ] This is a bug report
- [ x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Theme use anonymous function on hooks which are hard to remove

**What is the expected or desired behavior?**

Theme using normal function that user can remove.

---

**Please describe your local environment:**

WordPress version: 4.7.3

OS: n/a

NPM/Node version: 6

**Where did the bug happen? Development or remote servers?**

Anyplace

## Feature Request

**Please provide use cases for changing the current behavior:**
So I have a plugin that includes custom templates which don't run on blade engine. The problem is that sage is using anonymous functions on hooks and filters make other developers complicate to work with.
I do use closures myself on hooks that I'm almost certain that others don't need to remove. On this particular case the template_include filter is not a good choice as in order to play with it we need to find workarounds that not always work as intended. 
Eg: http://stackoverflow.com/questions/31240432/anonymous-functions-in-wordpress-hooks
https://wordpress.stackexchange.com/questions/137688/remove-actions-filters-added-via-anonymous-functions

ps: Thanks for the nice work. I really liked the theme.

**Comment by QWp6t** [comment]
Just edit the filter if necessary. It's really that simple. Everything in admin.php, filters.php, helpers.php, and setup.php are intended to be edited by developers. Sage is a starter theme, after all.
