### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by schrapel** [roots/sage#1887]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

- When running `npm run start` `http://localhost:3000` loads fine without JS/CSS
- If a file is updated browser sync detects the change and triggers a build which is returned back as built
- HMR is missing from the console 
- Console contains `Uncaught SyntaxError: Unexpected token <`
- `yarn run build` works fine

**What is the expected or desired behavior?**

HMR compiles the SCSS/JS and injects into the browser

## Bug report

**Please provide steps to reproduce, including full log output:**

1. git clone repo
2. update `publicPath` and `devUrl`
3. make some changes to the scss
4. run `yarn run start`

**Please describe your local environment:**

WordPress version: 4.7.4

OS: 10.12.2

NPM/Node version: 3.10.10/v6.9.5 - I also tried the latest version and latest LTS

**Where did the bug happen? Development or remote servers?**

Development

**Comment by wgroenewold** [comment]
I found this ticket in the Yarn thread. Is all webpack stuff up to date?

https://github.com/yarnpkg/yarn/issues/857

**Comment by schrapel** [comment]
I reinstalled yarn, restarted my machine and removed node_modules. Still happens from a fresh clone of this repo. Pretty sure it's a weird edge case that is not effecting other people

**Comment by schrapel** [comment]
I tried this on another machine and it worked fine. Then nuked nvm, npm, yarn and after that it worked again on a fresh install of the repo. Closing this
