### ISSUE TITLE
body_class causing issues with page layout for specific page slugs

### ISSUE THREAD

**Issue by Smyczek** [roots/sage#1889]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

This is not actually a very important bug, but in some situations can be problematic. The issue occurs when I add a page with a title for example "sidebar" or "container" or "h1" etc. Function body_class() from extras.php file adding page slug as a class to the body and this causing that CSS styles relating to the same class breaking the whole page layout.

**What is the expected or desired behavior?**

I think this function should return slug with some prefix to prevent this behavior. For example:
post_type-page-slug 

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Create a new page
2. Add a title, for example: sidebar
3. Publish the page

**Please describe your local environment:**

WordPress version: 4.7.4

OS: OSX

**Where did the bug happen? Development or remote servers?**

Development

**Comment by derkjn** [comment]
More than a bug, this feels to me like a different approach in writing your css. You can just be more specific when targeting these classes, for instance use `body.container` instead of just `.container`.

**Comment by QWp6t** [comment]
There's not a reliable way to ensure that the body class attribute won't inadvertently contain a class declared in your css absent of element specificity.

**Comment by Smyczek** [comment]
> More than a bug, this feels to me like a different approach in writing your css. You can just be more specific when targeting these classes, for instance use body.container instead of just .container.
I didn't write any line of mine own css code yet. I just installed a clear theme and playing with it a little bit when I came across this issue. 

> There's not a reliable way to ensure that the body class attribute won't inadvertently contain a class declared in your css absent of element specificity.
Of course, isn't possible cover all classes declared by a developer in their css code. But for example `.container` it is a pure Bootstrap class. Even more `.sidebar` it is your own class declared in `_grid.scss`. I am sure it is possible to cover all Bootstrap classes or your own classes. Just small modification mentioned `body_class()` function will solve this issue. Btw. Of course in my own css code, I can be more specific but many developers use pure Bootstrap in their plugins. What then?

**Comment by derkjn** [comment]
I didn't mean you wrote a wrong css, I meant that knowing you might end up having those classes in your body, you have to manually target `body.container` and reset the properties you get from bootstrap. An example could be
```
body.container{
  margin: 0;
  padding: 0;
  width: 100%;
}
```
It still feels to me that it's easier and cleaner to add this exception rule more than adding a prefix to all body classes and having to prefix my whole stylesheet.
