### ISSUE TITLE
Error: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by linuxbastard** [roots/sage#1893]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

composer finished. Went through and created folders and cloned files from dev-master. After setup questions, running "yarn" produces the error message

**What is the expected or desired behavior?**

Yarn will run and install dependencies

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Run composer
Finish setup questions
Run yarn
linuxbastard@BakulawDev:~/websites/serenecommunities.dev/public_html/wp-content/themes/serene-sage$ yarn
ERROR: There are no scenarios; must have at least one.

**Please describe your local environment:**

WordPress version: 4.7.4

OS: Ubuntu 16.04

NPM/Node version: 4.2.0/7.10.0

**Where did the bug happen? Development or remote servers?**

local dev server (not VM/Vagrant)

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

**Comment by linuxbastard** [comment]
Sorry guys, was running the wrong yarn.

**Comment by crouti** [comment]
I have the same problem, what does it mean, the wrong yarn ? I am on ubuntu and `yarn --version` says:

`0.27`

what should i do ?

**Comment by knowler** [comment]
Upgrade Yarn:

https://roots.io/getting-started/docs/ubuntu-linux-development-environment-sage/
https://yarnpkg.com/en/docs/install#debian-stable

Please use [Roots Discourse](https://discourse.roots.io/) for further support.
