### ISSUE TITLE
[reproducible] watch doesn't work for javascript/scss files

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1896]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

webpack watch doesn't work for javascript/scss files.

**What is the expected or desired behavior?**

webpack watches javascript/scss files and recompile when these source files have been modified.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

### Reproducing the issue 
(https://github.com/roots/sage#theme-installation):
````
$ composer create-project roots/sage test-watch dev-master

Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? > Roots\Sage\PostCreateProject::updateHeaders
Define theme headers. Press enter key for default.
Theme Name [Sage Starter Theme]:
Theme URI [https://roots.io/sage/]:
Theme Description [Sage is a WordPress starter theme.]:
Theme Version [9.0.0-beta.3]:
Theme Author [Roots]:
Theme Author URI [https://roots.io/]:
> Roots\Sage\PostCreateProject::selectFramework
Select a CSS framework (Default: Bootstrap)
  [0] Bootstrap
  [1] Foundation
  [2] None
> 2
> Roots\Sage\PostCreateProject::addFontAwesome
Add Font Awesome? [y,N]?
> Roots\Sage\PostCreateProject::buildOptions
Configure build settings. Press enter key for default.
Path to theme directory (eg. /wp-content/themes/sage) [/app/themes/test-watch]:
Local development URL of WP site [http://example.dev]:
````
````
$ cd test-watch/
$ (nvm use v6)
$ yarn install
$ yarn run start
````
(Optionally clean up the `dist/` folder)

Modify files in `resources/assets/styles/` or `resources/assets/scripts/`.
Notice that webpack doesn't recompile, also notice that 
nothing changed in dist/ folder / that there is still no dist/ folder.

Optionally invoke `yarn run build` and notice that now the files in `dist/` folder have 
been updated / dist/ folder together with these files has been created.

**Please describe your local environment:**

WordPress version: (not applicable)

OS: Ubuntu 16.04.2 LTS

NPM/Node version: v6.10.3

**Where did the bug happen? Development or remote servers?**

Development/workstation

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/webpack-watch-doesnt-work-for-scss-js/9587

**Comment by retlehs** [comment]
as already mentioned to you on discourse, this is not a current bug and you're probably dealing with a configuration issue. please don't use github for personal support requests.
