### ISSUE TITLE
Missing trailing comma Sage 9

### ISSUE THREAD

**Issue by 9585999** [roots/sage#1898]
Hi, if use `yarn test` I have this

![img 2017-05-21 12 56 44](https://cloud.githubusercontent.com/assets/16165904/26282945/5c7e04de-3e25-11e7-8e5a-f339d8cf84a6.PNG)

Perhaps you need to put the missing commas?

**Comment by QWp6t** [comment]
You should add those commas or remove/change the rule in eslint.
