### ISSUE TITLE
CSS framework selection needs to no longer fully clear out files

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1905]
as of #1885 (stylelint addition) we can no longer fully clear out files after someone has selected a CSS framework besides bootstrap

https://github.com/roots/sage/blob/65169986b71a02c73ddd3efe05383783bfbed202/app/lib/Sage/PostCreateProject.php#L43-L48

these files need to still maintain the newly added comments at the top

discourse thread: https://discourse.roots.io/t/yarn-build-failed-because-of-a-stylelint-error/9792

**Comment by samrap** [comment]
I'll try and take a look at this.
