### ISSUE TITLE
Disabling cache

### ISSUE THREAD

**Issue by kmrsfrnc** [roots/sage#1909]
Hello, 
When deploying to wpengine the themes cache is messing up the sites template. Since wpengine has caching I would like to disable the themes cache if possible. Where can I do this?
Thanks!

**Comment by kmrsfrnc** [comment]
Seems like the caching is done by Blade. I found a couple of hacky ways to disable it but not sure where to implement it in Sage. Any help would be appreciated.

**Comment by retlehs** [comment]
please don't clear out the issue template when creating a new issue. head over to https://discourse.roots.io/ where sage 9 and wpengine is already being discussed

**Comment by Coop920** [comment]
@kmrsfrnc what did you end up doing?  Thanks

**Comment by dsturm** [comment]
Hej @Coop920,

please don't ask for support on GitHub - especially in eight year old, closed issues.

As @retlehs already said (right above), head over to [Roots Discourse](https://discourse.roots.io/search?q=Wpengine%20Cache).

Cheers
