### ISSUE TITLE
Add webpack cache-loader for improved build performance

### ISSUE THREAD

**Issue by oxyc** [roots/sage#1922]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Using the new webpack cache loader provides significant performance improvements on subsequent builds. By caching the buble and extracttext rules I get these results:

command | before | after
---|----|---
yarn run build | 16s | 10s
yarn run build:production | 29s | 17s

_source: https://gist.github.com/oxyc/f9c28d7f84e8c3c31dbf8da4015beec2_

```diff
diff --git a/resources/assets/build/webpack.config.js b/resources/assets/build/webpack.config.js
index 1cb7f5a..4c63f0c 100644
--- a/resources/assets/build/webpack.config.js
+++ b/resources/assets/build/webpack.config.js
@@ -51,8 +51,10 @@ let webpackConfig = {
       {
         test: /\.js$/,
         exclude: [/(node_modules|bower_components)(?![/|\\](bootstrap|foundation-sites))/],
-        loader: 'buble',
-        options: { objectAssign: 'Object.assign' },
+        use: [
+          'cache',
+          { loader: 'buble', options: { objectAssign: 'Object.assign' } },
+        ],
       },
       {
         test: /\.css$/,
@@ -60,6 +62,7 @@ let webpackConfig = {
         use: ExtractTextPlugin.extract({
           fallback: 'style',
           use: [
+            'cache',
             { loader: 'css', options: { sourceMap: config.enabled.sourceMaps } },
             {
               loader: 'postcss', options: {
@@ -76,6 +79,7 @@ let webpackConfig = {
         use: ExtractTextPlugin.extract({
           fallback: 'style',
           use: [
+            'cache',
             { loader: 'css', options: { sourceMap: config.enabled.sourceMaps } },
             {
               loader: 'postcss', options: {
```

**Other relevant information:**

Cache invalidation is an issue. Some improvements in https://github.com/webpack-contrib/cache-loader/pull/9 but still not all that is needed.

**Comment by QWp6t** [comment]
Went ahead and added it. 

https://github.com/roots/sage/pull/1919/commits/48dd684b1014a47d1dfc9137c809bb31530cf17b

Thanks for the suggestion.
