### ISSUE TITLE
failed yarn run build on copy-globs-webpack-plugin\index.js:179

### ISSUE THREAD

**Issue by bebjakub** [roots/sage#1925]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

I can't successfully execute command yarn run build

**What is the expected or desired behavior?**

Executed yarn run build

---

## Bug report

**Please provide steps to reproduce, including full log output:**

 **composer create-project roots/sage** test-theme dev-master

Updated **resources/assets/config.json** to:

`"publicPath": "/wp-content/themes/test-theme",
  "devUrl": "http://localhost/wordpress",
  "proxyUrl": "http://localhost:3000/wordpress",`

**yarn**

**yarn run build**

```
C:\xampp\htdocs\wordpress\wp-content\themes\test-theme>yarn run build
yarn run v0.27.5
$ webpack --progress --config resources/assets/build/webpack.config.js
C:\xampp\htdocs\wordpress\wp-content\themes\test-theme\node_modules\copy-globs-webpack-plugin\index.js:179
                        constructor(relativeFrom, output = '[path][name].[ext]', context = process.cwd()) {
                                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\xampp\htdocs\wordpress\wp-content\themes\test-theme\resources\assets\build\webpack.config.js:10:25
)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Please describe your local environment:**

WordPress version: 4.8

OS: Win 7 64x

NPM/Node version: 5.3.0

**Where did the bug happen? Development or remote servers?**

Development/localhost

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by QWp6t** [comment]
Looks like you need to update node.js to at least 6.9.0
