### ISSUE TITLE
When the same form is used more than once on the page

### ISSUE THREAD

**Issue by alenb** [roots/sage#1926]
## Bug report

**Please provide steps to reproduce, including full log output:**

Create a form. Add a drop-down and text input to this form. Add a `show` conditional to the text input field that's tied to an option on the drop-down. Then add the form via `do_shortcode` on a page twice or more times.

You will notice only one form will load while all others will be hidden away.

**Please describe your local environment:**

WordPress version: 4.8

OS: Mac OS X Sierra

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Not that I'm aware of.

**Comment by QWp6t** [comment]
I'm confused as to what this has to do with Sage.

**Comment by alenb** [comment]
Apologies, posted to the wrong project
