### ISSUE TITLE
Add style lint task

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1928]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Feature Request

It would be great if a `style-lint` task is added so it can be directly invoked using yarn/npm run.

**Comment by QWp6t** [comment]
Already implemented this a month ago.

https://github.com/roots/sage/commit/093d1f724d648bb823926ded701eac4a464be787#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R85

**Comment by strarsis** [comment]
@QWp6t: Oh, then composer create-project somehow pulled a stale version (dev-master was used though). Thanks.
