### ISSUE TITLE
Composer installation - no setup, TTY mode error on Windows

### ISSUE THREAD

**Issue by webwingscz** [roots/sage#1929]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

**What is the current behavior?**

When I used composer **today** with dev-master (locally, on server,... windows/linux):
`composer create-project roots/sage your-theme-name dev-master`

**On Windows, I get error:**
TTY mode is not supported on Windows platform

**On Linux, it is fine, but missing the configuration (Theme name, devUrl,...)**

I am writing this, because yesterday I made same thing and it worked, today I get these 2 kinds of behavior on any device.

**What is the expected or desired behavior?**

To download files, install and come throught the setup as it was working before.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Just run composer on Windows, or Linux with basic example from Readme

**Please describe your local environment:**

WordPress version: 4.8

OS: PHP 7.1, Windows 10 / PHP 5.6 CentOS 7

NPM/Node version: 5.3.0 / v6.10.2

**Where did the bug happen? Development or remote servers?**

Development and remote server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Not found

**Other relevant information:**

Worked properly yesterday

**Comment by Shirkit** [comment]
Ok, I'm new to Sage and I tried installing it on my environment as well. I got the output below. I just followed the installation instructions. I'm running:

Windows 10.1
PHP 7.1.7
Node 7.6.0
NPM 4.1.2
Local build.

```
E:\Trabalho\ShirkitTheme>composer create-project roots/sage sage-master dev-master
Installing roots/sage (dev-master 8691074b29c4c09dae40f0f0c33dc2b51d9292e2)
  - Installing roots/sage (dev-master master): Cloning master from cache
Created project in sage-master
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 26 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.3.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)
  - Installing illuminate/contracts (v5.4.27): Downloading (100%)
  - Installing doctrine/inflector (v1.1.0): Downloading (100%)
  - Installing illuminate/support (v5.4.27): Downloading (100%)
  - Installing illuminate/container (v5.4.27): Downloading (100%)
  - Installing illuminate/events (v5.4.27): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing symfony/debug (v3.3.4): Downloading (100%)
  - Installing symfony/finder (v3.3.4): Downloading (100%)
  - Installing illuminate/filesystem (v5.4.27): Downloading (100%)
  - Installing illuminate/view (v5.4.27): Downloading (100%)
  - Installing illuminate/config (v5.4.27): Downloading (100%)
  - Installing roots/sage-lib (9.0.0-beta.3): Downloading (100%)
  - Installing symfony/yaml (v3.3.4): Downloading (100%)
  - Installing hassankhan/config (0.10.0): Downloading (100%)
  - Installing brain/hierarchy (2.3.0): Downloading (100%)
  - Installing soberwp/controller (dev-master e9358ff): Cloning e9358ff900 from cache
  - Installing symfony/polyfill-mbstring (v1.4.0): Downloading (100%)
  - Installing symfony/translation (v3.3.4): Downloading (100%)
  - Installing nesbot/carbon (1.22.1): Downloading (100%)
  - Installing symfony/process (v3.3.4): Downloading (100%)
  - Installing symfony/console (v3.3.4): Downloading (100%)
  - Installing illuminate/console (v5.4.27): Downloading (100%)
  - Installing roots/sage-installer (1.1.0): Downloading (100%)
  - Installing squizlabs/php_codesniffer (2.9.1): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.2).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
symfony/translation suggests installing symfony/config ()
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (~6.0).)
illuminate/console suggests installing mtdowling/cron-expression (Required to use scheduling component (~1.0).)
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
> Roots\Sage\Installer\ComposerScript::postCreateProject
Script Roots\Sage\Installer\ComposerScript::postCreateProject handling the post-create-project-cmd event terminated with an exception


  [Symfony\Component\Process\Exception\RuntimeException]
  TTY mode is not supported on Windows platform.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by Eldavid** [comment]
+1

**Comment by QWp6t** [comment]
This issue belongs in https://github.com/roots/sage-installer, but I kinda already addressed it. Windows users will be shown a warning in a future version of sage-installer. Basically, you should still be able to manually run the following:

```
sage meta
sage config
sage preset
```

And that will do the same as composer's post-create-project event.

**Comment by Shirkit** [comment]
Ok, so how exactly you want us to run those commands? "sage" is not on PATH, nor do I see a GULP file to run, and COMPOSER says "sage" is not a defined command. What exactly I was supposed to run? I should download sage-installer?

BTW, "sage-isntaller" is being detected as a virus by Windows Defender as seen here: http://imgur.com/p2k4aw1

**Comment by QWp6t** [comment]
if `vendor/bin` isn't in your path, then you can use...

```
php vendor/bin/sage meta
php vendor/bin/sage config
php vendor/bin/sage preset
```

Again, discussion of this issue belongs in https://github.com/roots/sage-installer so if you wanna report a bug or request a feature, that's the repo to do it in. If you need support, feel free to post on discourse, ezpz
