### ISSUE TITLE
(s)CSS ERROR

### ISSUE THREAD

**Issue by martijnbrands** [roots/sage#1930]
After the full installation of the sage theme, yarn run start, I add some CSS to _global.scss and save it. If I go to my localhost:3000 I get the following error on the screen (black overlay).

ERROR in 
resources/assets/styles/common/_global.scss
 1:4   ✖  Expected single space before "{"     block-opening-brace-space-before
 2:2   ✖  Expected indentation of 2 spaces     indentation                     
 2:13  ✖  Expected single space after ":"      declaration-colon-space-after   
          with a single-line declaration                                       
 3:1   ✖  Unexpected missing end-of-source     no-missing-end-of-source-newline
          newline

**Comment by retlehs** [comment]
please don't clear out the issue template when creating a new issue. please don't post personal support requests on github (as noted in the issue template that you cleared out).

please also simply read the error message as it is very specific and tells you what to fix.
