### ISSUE TITLE
[Feature] webpack config being able to process either sass or scss 

### ISSUE THREAD

**Issue by ramjamx** [roots/sage#1931]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Feature Request

**Feature request: Use whatever extension is setup in config.json**

Nowadays you need to change line 77 on webpack.config.js in order to change from scss to sass.
No matter if you specify in config.json sass as the extension of the main style file. 
It would be great if you can use it whatever you want and only set it up only on config.json

It's also necessary to edit line 177  for sass lint messages
```
      syntax: 'sass',
```

**Comment by webstractions** [comment]
+1 on this. 

Using several Laravel Framework modules already. Maybe use Jeffrey Way's [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) which provides an API for defining basic webpack build steps. You can even _mix_ two or three style types together if you wish (LESS, SCSS, Stylus). 

This repository works well with stand-alone projects too, not just Laravel projects. I am using it for a custom WordPress theme that I am working on, and it is fantastic.

**Comment by Log1x** [comment]
#2172
