### ISSUE TITLE
Last merge makes 7 the minimum PHP version

### ISSUE THREAD

**Issue by kaisermann** [roots/sage#1933]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Composer won't install if the dev/host machine doesn't have at least PHP 7. The [`illuminate/support` is the "culprit"](https://github.com/illuminate/support/commit/ae3ac8d3076006bf1d0109355f706591891c1e23#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L17). 
 
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
  - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
  - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
Problem 2
  - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
  - illuminate/support v5.4.27 requires doctrine/inflector ~1.0 -> satisfiable by doctrine/inflector[v1.2.0].
  - Installation request for illuminate/support v5.4.27 -> satisfiable by illuminate/support[v5.4.27].
```

**What is the expected or desired behavior?**

Should it still work with PHP 5.6? Or should the readme be updated?

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Just have php 5.6 and try to `composer install` on the theme.

**Please describe your local environment:**

WordPress version: 4.8

OS: MacOS

NPM/Node version: X

PHP Version: 5.6

**Where did the bug happen? Development or remote servers?**

Remote server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Nope

**Comment by greatislander** [comment]
Would need a README update and https://github.com/roots/sage/blob/master/composer.json#L32 should be bumped too. If the intention is to drop 5.6 support.
