### ISSUE TITLE
extra configuration in composer.json

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1940]
Related discussion: https://github.com/Log1x/blade-svg-sage/issues/2#issuecomment-320776970

Some extra paths that facilitate installation/integration of 
MU plugins for the theme would be a nice addition.

**Comment by retlehs** [comment]
don't try and require plugins from the theme 🙀 from the issue you linked, you wrote:

> It works if I require it for the site instead for the theme (site/) -

this is the way you should do it

**Comment by strarsis** [comment]
@retlehs: Thanks! Though now I doubt whether I should really use a plugin for SVG support in sage theme. Maybe a composer package is better because it is low level and can be just bundled with the theme?

**Comment by Log1x** [comment]
lol I actually recommend using Bedrock as well as give an example if you were to want to do it in your theme `composer.json`-- but I'm just curious, why is it so frowned upon to use the theme's `composer.json` for theme-related dependencies that aren't crucial to the Bedrock stack? I won't lie, I've done it before as it made streamlining clients theme setups outside of Bedrock vastly more straight forward and have never had any issues.
