### ISSUE TITLE
Sage 8.5.2 bootstrap.js:1414 Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)

### ISSUE THREAD

**Issue by skwalgit** [roots/sage#1947]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**
bower_components/popper.js/index.1 is installed

Throwing JS error:

bootstrap.js:1414 Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
    at bootstrap.js:1414
    at bootstrap.js:1819
    at bootstrap.js:3828

**What is the expected or desired behavior?**

bower_components/popper.js/index.js should be installed in the bower_components directory.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

npm install
bower install
gulp

**Please describe your local environment:**

WordPress version: 4.8.1

OS: X

NPM/Node version: 3.10.8 / v6.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by MWDelaney** [comment]
Could this be related to #1946 ?

**Comment by retlehs** [comment]
sorry, should be good now

**Comment by etiennejcharles** [comment]
Still happening to me as we speak, someone reported a ticket not more than 4 hours ago. 
https://github.com/FezVrasta/popper.js/issues/491

I'm getting the same error mentionned above, 
Is there a temporary workaround around this ?

**Comment by etiennejcharles** [comment]
<img width="879" alt="solution" src="https://user-images.githubusercontent.com/2872476/32803742-8954ee1a-c952-11e7-86d9-192a5d01931c.png">

My solution was reverted those lines in the bower.json file, in order to download some version from unpkg.com

**Comment by aingham** [comment]
@etiennejcharles Did you  keep both sets of lines (marked green and blue) or just one of them? This is relevant to my situation I think.

**Comment by etiennejcharles** [comment]
I kept both ;) Hope you found a workaround ;)

**Comment by aingham** [comment]
@etiennejcharles Yes - all working thanks.
