### ISSUE TITLE
required to choose version of popper.js because version required differs from Bootstrap4 version

### ISSUE THREAD

**Issue by tofraser** [roots/sage#1952]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

While installing bower, I receive the following error requiring resolution:

> bower resolution    Unsuitable resolution declared for popper.js: e-tag:W/"13b6b-1
> 
> Unable to find a suitable version for popper.js, please choose one by typing one of the numbers below:
>     1) popper.js#* which resolved to e-tag:W/"13ed8-1 and is required by sage
>     2) popper.js#^1.11.0 which resolved to 1.12.2 and is required by bootstrap#4.0.0-beta

if the wrong version is chosen (!2), scripts throw "Uncaught Error: Bootstrap dropdown require Popper.js"

**What is the expected or desired behavior?**

I would expect the version of popper to match the version required by bootstrap#4.0.0-beta

---

## Bug report

**Please provide steps to reproduce, including full log output:**

install bower

**Please describe your local environment:**

WordPress version: NA

OS: MacOS version 10.12.5

NPM/Node version: 3.10.6/v6.2.1

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

**Comment by retlehs** [comment]
caused by popper.js update [as i suspected](https://github.com/roots/sage/pull/1944#issuecomment-322079339) :(

select #1 for now and it will update your `bower.json` with the new e-tag

**Comment by FezVrasta** [comment]
Popper.js is now available through Bower

**Comment by FezVrasta** [comment]
It will not last forever, I plan to get rid of Bower completely in v2 (this release isn't yet planned).

Consider to migrate to a modern dependencies manager system. Even Bower is suggesting people to move to npm/yarn.

**Comment by retlehs** [comment]
@FezVrasta sage 9 (`master` branch) dropped bower a while ago. this is for supporting the sage 8 branch
