### ISSUE TITLE
Autoload JS files from /scripts/autoload/ doesn't work with import "./autoload/**/*" from main.js

### ISSUE THREAD

**Issue by mtx-z** [roots/sage#1956]
## Submit a feature request or bug report

- [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Files from `resources/scripts/autoload/` are not being loaded by the `import "./autoload/**/*"` from main.js

**What is the expected or desired behavior?**

All files from resources/scripts/autoload/ should be loaded

---

## Bug report

**Please provide steps to reproduce, including full log output:**
`import "./autoload/**/*"` from` main.js` seems not to load files under `/autoload/`.
Setting `import "./autoload/*"` fix the issue. 
I think it's a directory/subdirectory finding problem.

**Please describe your local environment:**
 Windows 8.1/Wamp64 Apache, Node 6.112, npm 3.10.10, Yarn 0.27.5
Trying to add a new yarn package by creating a new /autoload/ file to import my dependency.

**Where did the bug happen? Development or remote servers?**
Dev local

**Comment by retlehs** [comment]
> What is the expected or desired behavior?

> All files from resources/scripts/autoload/ should be loaded

please provide more information on exactly what you have changed in the default sage install

**Comment by mtx-z** [comment]
Well, I just wanted to install the jQuery `Flickity `Gallery so : 

1. `yarn add flickity`
2. added SASS import into `main.scss`
3. created new file _flickity.js in autoload/ with `import 'flickity/dist/flickity.pkgd.min'`;

On build, flickity is not compiled if i dont edit import `"./autoload/**/*"` as described.

**Comment by kaisermann** [comment]
You don't need to put the flickity file in the autoload directory. Just `import 'flickity'` on your `main.js` (or any other included js file)!

**Comment by mtx-z** [comment]
Ah OK. So the /autoload/ is only used for package installed when deploying trough composer? 
I thought it was there for Js vendors. 

Thanks a lot!

**Comment by kaisermann** [comment]
I use it for vendors that do not support a 'import' call (sometime it happens... [example](https://github.com/lokesh/color-thief))

**Comment by mtx-z** [comment]
Ah OK, cause bootstrap was defaulty imported here in a /autoload/ file with a classic import. 
Thanks a lot for your help and your explanations.

**Comment by GenericUK** [comment]
I am using autoload for symlinks to js files installed in node_modules ()example: I am using Materialize-css. I noticed `yarn build` will not detect if files have changed in autoload directories (scripts and styles), to trigger build to include any changes you need to renew the modified date of main.js (open and save)
