### ISSUE TITLE
\App\config('theme') not populated

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1957]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

`\App\config('theme')` not populated with information, like 'dir' (array key).

**What is the expected or desired behavior?**

`\App\config('theme')` containing information, including 'dir' (array key).

---

## Bug report

**Please provide steps to reproduce, including full log output:**

```php
var_dump(\App\config('theme'));
````
`(null)`

**Please describe your local environment:**

WordPress version: 4.8.1

**Where did the bug happen? Development or remote servers?**

Development. (Was noticed in a `build:production` build.)

Related GitHub issue: https://github.com/Log1x/blade-svg-sage/issues/7

**Comment by Log1x** [comment]
`\App\config('theme')['dir']` works if you are using dev-master of Sage 9 using [sage-lib](https://github.com/roots/sage-lib).

`var_dump(\App\config('theme'));`

![Screenshot](https://log1x.com/screenshots/2017-08-22_14-38-40_X7qc0.png)

**Comment by QWp6t** [comment]
@Log1x You should also be able to use `\App\config('theme.dir')`.

Here's an example of where we use similar syntax: https://github.com/roots/sage/blob/master/app/setup.php#L107
