### ISSUE TITLE
Passing php data to Js

### ISSUE THREAD

**Issue by bdebever** [roots/sage#1966]
Hi there, 

I was trying to pass data with an exchanger to my js files but it doesn't seem to work. 

I am using the latest version of Sage with ES6, router.js, etc. 
What would you recommend to achieve such thing? For instance having an exchanger of data available for all js files? 

Thanks.

**Comment by QWp6t** [comment]
Feel free to ask on discourse.roots.io or stackoverflow or something. This section for posting bug reports or requesting features related to Sage.

**Comment by ciromattia** [comment]
@QWp6t is right, btw take a look at `wp_localize_script()`, like: 

```
wp_localize_script('sage/main.js', 'lang', [
    'current_lang' => ICL_LANGUAGE_CODE,
    'sun' => _x('Sun', 'day of week', 'aba'),
    ...
]);
```
