### ISSUE TITLE
Docs incorrect for correct deployment for Sage9

### ISSUE THREAD

**Issue by jascination** [roots/sage#1967]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x ] This is a bug report
- [x ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

The docs mention running `gulp` to build for production, while the readme says to run `yarn build:production`. Neither build anything that can be zipped up and installed in a WP site - docs should be clearer on how to actually deploy here!

**What is the expected or desired behavior?**

A `/dist/` folder that can be zipped and installed in a Wordpress site, or at least instructions on how to make on.

The folder structure that the Sage install process creates is also very different from a regular Wordpress theme folder (no PHP files in the root directory...) and the build process gives an error that `The package could not be installed. The theme is missing the style.css stylesheet.`.

**Comment by retlehs** [comment]
sage 9 docs don't mention gulp. sage 9 readme links to the sage 9 docs

https://github.com/roots/sage#documentation

**Comment by jascination** [comment]
Yes, which link to https://github.com/roots/docs/blob/sage-9/sage/theme-deployment.md, which link to this post from 2 years ago: http://austinpray.com/ops/2015/01/15/build-steps-and-deployment.html

And regardless, the specific mention of `gulp` vs `yarn` isn't the issue here - it's the the instructions don't properly explain how to deploy a theme to wordpress at all. How do I get my files into a format that can actually be installed in Wordpress?

**Comment by retlehs** [comment]
please don't use github for support...
