### ISSUE TITLE
Cannot see admin bar

### ISSUE THREAD

**Issue by philippebarbosa** [roots/sage#1968]
Hi,
just installed Sage 8 for my new website.
I cannot see the admin bar while i'm logged.
Looked in functions to find if anything force the bar to be hidden, did not find anything.
Anyone could help me, please ?

Thanks a lot ! Have a nice day :)

**Comment by kalenjohnson** [comment]
Please use https://discourse.roots.io/ for problem solving. However like you mentioned, nothing in Sage hides the admin bar, so sounds like a plugin or something else.

**Comment by philippebarbosa** [comment]
Sorry for the wrong processs :/
Tried with default wp theme, the same, so yes Sage isn't guilty ;)
Thanks for your help
