### ISSUE TITLE
`isset` not functioning properly in asset manifest

### ISSUE THREAD

**Issue by andrewmartin** [roots/sage#1969]
## Submit a feature request or bug report

- [ x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ x ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ x ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

My site is not loading in the proper (asset revved, minified) file.

**What is the expected or desired behavior?**

My site should load in the properly asset revved file (in production)

---

## Bug report

**Please provide steps to reproduce, including full log output:**

I discovered the issue was in `vendor/roots/sage-lib/Assets` on line 31:

```
public function get($asset)
    {
        return isset($this->manifest[$asset]) ? $this->manifest[$asset] : $asset;
    }
```

That `isset` call is not actually working. `$this-manifest[$asset]` is actually present, but for some reason `isset` is saying it's not.

**Please describe your local environment:**

WordPress version: 8.2
OS: X: Latest
NPM/Node version: 7+

**Where did the bug happen? Development or remote servers?**

Remote

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

NO

**Comment by retlehs** [comment]
i already replied to the discourse thread you created https://discourse.roots.io/t/production-variable-sage-9-wp-env-gone/10473/2?u=benword

**Comment by andrewmartin** [comment]
@retlehs 

I already ran `yarn run build:production`. That's why I'm saying there is a bug with this feature, because it wasn't loading in my minified files.

Please re-read my bug report more carefully. I'm generating a proper manifest in webpack with asset revved files, but the WordPres theme is not sourcing them.

**Comment by retlehs** [comment]
yeah, this isn't a bug. you can post more on discourse if you need further support

**Comment by kalenjohnson** [comment]
@andrewmartin I'm really not sure why that would fix your problem. `isset()` returns true if the array key is there. Doing `if($this->manifest[$asset])` is the same thing, except if the array key is not there, a notice will be thrown.

I'm honestly not sure why that would work for you but the original code does not. But this isn't an issue for anyone else. I would ask what PHP version you're running, but I really doubt that has any bearing on this.

**Comment by andrewmartin** [comment]
@kalenjohnson I'm familiar with what `isset` does, and it's confusing to me as well. I'm using PHP `7.1.6`.

**Comment by retlehs** [comment]
locking this as every message is notifying over 600 people... discourse is the place for back and forth.
