### ISSUE TITLE
Hangs on cloning

### ISSUE THREAD

**Issue by strarsis** [roots/sage#1971]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

`composer create-project roots/sage <theme name> dev-master` 
hangs during cloning master until Ctrl+c (^C) is hit.
````
$ composer create-project roots/sage the-theme dev-master
No composer.json in current directory, do you want to use the one at [...]/site? [Y,n]? n
Installing roots/sage (dev-master b4421be2696bd6021a11eb6893bb6fbb8a949d15)
- Installing roots/sage (dev-master master):
^CCloning master
````

**What is the expected or desired behavior?**

`composer create-project roots/sage <theme name> dev-master`  runs through correctly.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

WSL (Bash on Windows).
In (new) empty directory.
Run `composer create-project roots/sage <theme name> dev-master`.
Wait for a long time (nothing happens, hangs).
Hit `Ctrl+c`.

**Please describe your local environment:**

OS: WSL

**Where did the bug happen? Development or remote servers?**

Development

**Comment by webstractions** [comment]
`No composer.json in current directory, do you want to use the one at [...]/site? [Y,n]? n`

Try answering **Y** to that question. Pretty sure you will need a composer.json file.

**Comment by strarsis** [comment]
@webstractions: The composer.json file in questions belongs to a bedrock site in a higher up directory.
It works well after using the Ctrl+c workaround so a composer.json doesn't seem to be required by sage installation.

**Comment by webstractions** [comment]
@strarsis Okie dokie. Didn't realize it was a Bedrock install. Nevermind ;)

**Comment by retlehs** [comment]
what version of composer are you using? what directory did you run that command from? i'm unable to reproduce

**Comment by strarsis** [comment]
@retlehs: Sorry, lost track on this issue :)

`Composer version 1.4.2 2017-05-17 08:17:52`
On Bash on Windows/WSL

I use directory `~/src/test` for easily reproducible testing:
````
$ mkdir -p ~/src/test
$ cd $_
$ composer create-project roots/sage the-theme dev-master
(Hangs as described above)
````

**Comment by kalenjohnson** [comment]
```
# kalen @ DESKTOP-RJ1U90F in ~ [8:40:13]
$ rm -rf src

# kalen @ DESKTOP-RJ1U90F in ~ [8:40:17]
$ mkdir -p ~/src/test

# kalen @ DESKTOP-RJ1U90F in ~ [8:40:20]
$ cd $_

# kalen @ DESKTOP-RJ1U90F in ~/src/test [8:40:22]
$ composer create-project roots/sage the-theme dev-master
Installing roots/sage (dev-master 5c4c50071664299706fb6eac38aac0f9284e3d11)
  - Installing roots/sage (dev-master master): Cloning master from cache
Created project in the-theme
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 26 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.4.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)
  - Installing illuminate/contracts (v5.4.27): Downloading (100%)
  - Installing doctrine/inflector (v1.2.0): Downloading (100%)
  - Installing illuminate/support (v5.4.27): Downloading (100%)
  - Installing illuminate/container (v5.4.27): Downloading (100%)
  - Installing illuminate/events (v5.4.27): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing symfony/debug (v3.3.6): Downloading (100%)
  - Installing symfony/finder (v3.3.6): Downloading (100%)
  - Installing illuminate/filesystem (v5.4.27): Downloading (100%)
  - Installing illuminate/view (v5.4.27): Downloading (100%)
  - Installing illuminate/config (v5.4.27): Downloading (100%)
  - Installing roots/sage-lib (9.0.0-beta.4): Downloading (100%)
  - Installing symfony/yaml (v3.3.6): Downloading (100%)
  - Installing hassankhan/config (0.10.0): Downloading (100%)
  - Installing brain/hierarchy (2.3.0): Downloading (100%)
  - Installing soberwp/controller (9.0.0-beta.4): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.5.0): Downloading (100%)
  - Installing symfony/translation (v3.3.6): Downloading (100%)
  - Installing nesbot/carbon (1.22.1): Downloading (100%)
  - Installing symfony/process (v3.3.6): Downloading (100%)
  - Installing symfony/console (v3.3.6): Downloading (100%)
  - Installing illuminate/console (v5.4.27): Downloading (100%)
  - Installing roots/sage-installer (1.3.1): Downloading (100%)
  - Installing squizlabs/php_codesniffer (2.9.1): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.2).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
symfony/translation suggests installing symfony/config ()
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (~6.0).)
illuminate/console suggests installing mtdowling/cron-expression (Required to use scheduling component (~1.0).)
Generating autoload files
```

Only thing I can think of that's happened to me to make me think Composer was hanging was my IDE was listening for xdebug, I have xdebug set to always run, and it had caught Composer and was just sitting there.

**Comment by Log1x** [comment]
I use WSL daily on the latest fall creators update and have never had Composer hang.

Only issue right now is with yarn as seen [here](https://github.com/Microsoft/WSL/issues/2448) and is temporarily fixable with [this](https://github.com/Log1x/dotfiles/blob/master/home/.zsh/wsl.zsh#L1).
