### ISSUE TITLE
‘yarn start' don't chaging the styles on the fly

### ISSUE THREAD

**Issue by kirylpl** [roots/sage#1972]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

‘yarn start" don't updating styles in browser.
Browsersync detects changes but doesn’t update.

**What is the expected or desired behavior?**

 Applying styles during yarn start watching process.

---

## Bug report

**Please describe your local environment:**

WordPress version: 4.8.1

OS: Ubuntu 16.04

NPM/Node version: v6.11.3

**Where did the bug happen? Development or remote servers?**

Dev

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/sage-9-beta-4-browser-sync-doesnt-update-the-styles/10364/8

![screenshot from 2017-09-29 13-27-38](https://user-images.githubusercontent.com/3589618/31012332-165c1994-a51a-11e7-8d5e-5fd94c5ef04d.png)

**Comment by retlehs** [comment]
most of the threads on discourse related to this end up being solved once the values of your config are properly set

we prefer to avoid going back and forth here on github for support as there are hundreds of people that are getting emails every time a comment is made on here. please use https://discourse.roots.io/ — thank you

**Comment by kirylpl** [comment]
@retlehs edited path worked, thank you.
