### ISSUE TITLE
Sage 8/Sage 9-beta.4, Bootstrap 4 Beta & Autoprefixer Problem

### ISSUE THREAD

**Issue by weilinzung** [roots/sage#1975]
**Sage 8.5.3**

on latest version or 3.1.1 of `gulp-autoprefixer` & `bootstrap 4 beta` is missing `-webkit-flex-wrap: wrap` after compiled.

Also `display: -webkit-box;` is not correct, should be `display: -webkit-flex;`.

issue related: https://github.com/postcss/autoprefixer/issues/917

I tested on all IOS devices.
thanks!

**Comment by weilinzung** [comment]
Also just test with `Sage 9.0.0-beta.4` also have same issue.

```
.row {
  display: flex;
  flex-wrap: wrap;
  margin-right: ($grid-gutter-width / -2);
  margin-left:  ($grid-gutter-width / -2);
}
```

**Output CSS:** 
```
.row {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
}
```

**Expected output CSS should be:**
```
.row {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px
}
```

**Comment by weilinzung** [comment]
More info about autoprefixer with the Sage asset build problem:

All IOS mobile & tablet devices have this issue.

**markup:**
```
<div class="row">
      <div class="col-lg-6">
        @include('partials.page-header')
      </div>
      <div class="col-lg-6">
        @include('partials.content-page')
      </div>
  </div>
```

Screenshot:
http://oi68.tinypic.com/m8nx2b.jpg

**Comment by retlehs** [comment]
that screenshot shows iOS 7, pretty old

you can change autoprefixer support for older browsers here: https://github.com/roots/sage/blob/8.5.3/gulpfile.js#L108

**Comment by weilinzung** [comment]
Thanks, @retlehs. I did that already with`last 4 versions`, but it is not working.
Also try to add `Safari` or `iOS` to browsers array which said it is not available.

According Bootstrap Frameworks, it should support IOS7, but after compiled with Sage which is not working properly :  https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/
https://blog.prototypr.io/what-you-need-to-know-about-the-latest-bootstrap-4-beta-bc750ef2b9ae#5e85

still give me this output:
```
.row {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
}
```

**Comment by roots-ladybug** [comment]
Hi @weilinzung,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
