### ISSUE TITLE
Build failure when including a node_module in main.scss

### ISSUE THREAD

**Issue by SunnyJohal** [roots/sage#1977]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When I am including a node module in main.scss that references another installed module the build fails (I was attempting to install Material Design Web Components).

**What is the expected or desired behavior?**
Any module that is called should be able to include other installed in the node_modules folder if required.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. After theme setup install material components: `yarn add material-components-web`

1. In `resources/assets/styles/main.scss` reference the sass file by adding the following line: `@import "~material-components-web/material-components-web";`  

1. Run `yarn start` and the build will fail

**Please describe your local environment:**

WordPress version: 4.8.2

OS: MAC OS High Sierra 10.13

NPM/Node version: NPM: 5.4.2 | Node: 8.1.2

**Where did the bug happen? Development or remote servers?**

Dev server locally

---

**Other relevant information:**

X

**Comment by retlehs** [comment]
looks like you'll need to modify the webpack config, see https://github.com/material-components/material-components-web/issues/351

please use https://discourse.roots.io/ for further support
