### ISSUE TITLE
'Yarn start' - browser crashes on visiting development address

### ISSUE THREAD

**Issue by BramDecuypere** [roots/sage#1978]
## Submit a feature request or bug report

- [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

DISCLAIMER: I am a developer trying to get into PHP and this boilerplate makes use of all my favorite tools after working with node.js/spring mvc/webpack/react/angular4/... So maybe some of my issues are general PHP questions, not related to this project. If so, I'm sorry... But I believe these problems will occur on anyone coming from anyone diving into PHP with this background.

**What is the current behavior?**

After:
1. composer create-project roots/sage boiler 9.0.0-beta.4
2. yarn install && composer install

I expect `yarn start` to start the project and give me a workable output. When I navigate to http://localhost:3000 (developing) chrome crashes and does not provide anything visible.

**What is the expected or desired behavior?**

A bear boilerplate that displays in the browser where I can start from.

---

**Please describe your local environment:**

WordPress version: X

OS: El Capitan 10.11.6

NPM/Node version: 
node: v8.7.0
npm:  v5.4.2

**Where did the bug happen? Development or remote servers?**

Development

** PHP version **
PHP 7.1.10 (cli) (built: Oct  6 2017 01:07:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by SunnyJohal** [comment]
Are you running MAMP on your mac? Is your WordPress install in a subdirectory?

**Comment by derkjn** [comment]
Also, have you configured your `resources/assets/config.json` to point to your local domain?
