### ISSUE TITLE
Boostrap 4 js doesn't compile

### ISSUE THREAD

**Issue by tavo379** [roots/sage#1988]
module.exports = {
  STATIC_PATH: __dirname,
};

is the error that my console  show, so i use boostrap for a carousel, the carousel works, in a moment  the carousel is no working anymore.

**Comment by retlehs** [comment]
please don't clear out the issue template, it's there for a reason. part of that reason is so that you don't use github issues for personal support requests and instead post on https://discourse.roots.io/
