### ISSUE TITLE
Address or document 404 on stylesheet during development

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1989]
i believe that the only place we've talked about how it's currently expected that there is a 404 on `main.css` during local dev is on roots discourse. it's not on the docs or the readme

related discourse threads:

https://discourse.roots.io/t/consequences-of-absent-main-css-with-yarn-start-sage-9/10755
https://discourse.roots.io/t/sage-9-main-css-404-on-devurl/9799

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)

**Comment by retlehs** [comment]
forgot @QWp6t already reported this here: https://github.com/roots/docs/issues/52

leaving open here as well to mention in README

**Comment by MWDelaney** [comment]
I can update the README for the short term but should we investigate writing out to a file?

**Comment by a-barbieri** [comment]
I understood why CSS is not persisted on file system and it's ok, but one downside is that **CSS might be loaded after** `jQuery(document).ready()`. 

I came out with a workaround which works on local development and doesn't affect production. More [details here](https://discourse.roots.io/t/looks-like-doc-ready-fires-before-css-has-been-applied-how-can-i-avoid-it/14382/3?u=a-barbieri).

Mine is clearly a patch, but I wonder a similar fix should be added by default to avoid frustration with the current webpack/browsersync config.

**Comment by sandrowuermli** [comment]
I thought i'll copy & paste my 'dirty' workaround:

**setup.php**

```php
/**
 * Theme assets
 */
add_action( 'wp_enqueue_scripts', function() {
    if ( asset_exist( 'styles/main.css' ) ) {
        wp_register_style( 'sage/main.css', asset_path( 'styles/main.css' ), false, asset_version( 'styles/main.css' ) );
        wp_enqueue_style( 'sage/main.css' );
    }

    if ( asset_exist( 'scripts/main.js' ) ) {
        wp_register_script( 'sage/main.js', asset_path( 'scripts/main.js' ), [ 'jquery' ], asset_version( 'scripts/main.js' ), true );
        wp_enqueue_script( 'sage/main.js' );
    }
}, 100 ); // Theme assets
```

**helpers.php**
```php

/**
 * Checks if asset exist.
 *
 * @param string $asset Full file path of the asset.
 *
 * @return bool
 */
function asset_exist( $asset ) {
    if ( file_exists( asset_file( $asset ) ) )
        return true;

    return false;
}

/**
 * Retrieve full path to asset file
 *
 * @example /Users/username/Sites/test.ch/web/app/themes/themefolder/dist/styles/main.css
 *
 * @param string $asset Filename including subfolder after 'dist/' like 'styles/main.css'
 *
 * @return string
 */
function asset_file( $asset ) {
    $asset_file     = sage( 'assets' )->get( $asset );
    $asset_filepath = str_replace( 'resources', '', get_stylesheet_directory() ) . "dist/{$asset_file}";

    return $asset_filepath;
}

/**
 * Returns dynamic version, based on file modified date.
 *
 * @param string $asset Filename including subfolder like 'styles/main.css'
 *
 * @return bool|int Modified date as UNIX Timestamp. False if file not exist.
 */
function asset_version( $asset ) {
    $asset_file     = sage( 'assets' )->get( $asset );
    $asset_filepath = get_stylesheet_directory() . "/../dist/{$asset_file}";

    if ( file_exists( $asset_filepath ) )
        return filemtime( $asset_filepath );

    return false;
}
```

**Comment by Log1x** [comment]
This is resolved in Sage 10.
