### ISSUE TITLE
Bootstrap incorrect peer dependency popper.js

### ISSUE THREAD

**Issue by TheSycamore** [roots/sage#1997]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

After running "yarn && yarn build" I get the following error:
```
[4/5] Linking dependencies...
warning " > bootstrap@4.0.0-beta.2" has incorrect peer dependency "popper.js@^1.12.3".
[---------------------------------------------------------------------------------------------------------------------------------------] 0/1237
Killed
```

**What is the expected or desired behavior?**

To run yarn and have the dependencies installed without an error.

---

## Bug report

```
composer create-project roots/sage mytheme dev-master
cd mytheme
yarn && yarn build
```

**Please describe your local environment:**

WordPress version: 4.9
OS: Ubuntu 16.04
NPM: 5.5.1
Node: v8.9.1

**Where did the bug happen? Development or remote servers?**

remote server

**Similar Issue:**
Here is a similar issue someone experienced trying to install dependencies using bower:
https://github.com/roots/sage/issues/1952

**Comment by slackday** [comment]
I noticed this resolves if you update to `bootstrap@4.0.0` and `popper.js@1.2.9`

Please look at https://github.com/twbs/bootstrap/releases if you are effected by breaking changes between `bootstrap@4.0.0-beta.2` and `bootstrap@4.0.0`
