### ISSUE TITLE
Relative url's in css remain localhost from network access

### ISSUE THREAD

**Issue by GenericUK** [roots/sage#2002]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

`yarn run start` Browsersync 
Relative url's in css remain localhost from network access.

Example: **url(/wp-content/themes/my-theme/dist/fonts/My-font.otf)**
Link remains local when accessed externally from network: 
`http://localhost:3000/wp-content/themes/my-theme/dist/fonts/My-font.otf` 

**What is the expected or desired behavior?**

Links should be accessible from the network
Example: `http://192.168.1.1:3000/wp-content/themes/my-theme/dist/fonts/My-font.otf`

---

## Workaround

Change proxyUrl to `"proxyUrl": "http://192.168.1.1:3000",` in resources/assets/config.json

**Please describe your local environment:**

WordPress version: 4.9

OS: Linux

NPM/Node version: v8.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Comment by Hillsrion** [comment]
I got the same problem here, but with Mac env, and Node 9

**Comment by nicooprat** [comment]
I found a workaround.

1. Add two `devDependencies`: `eventsource-polyfill` & `es6-promise-promise`
2. Create a file somewhere, like `scripts/util/fixBSHMR.js`:

```js
/*global __webpack_require__ b:true*/
if(__webpack_require__)
  __webpack_require__.p = __webpack_require__.p.replace('localhost', window.location.hostname)
```

3. Add these lines [here](https://github.com/roots/sage/blob/master/resources/assets/build/util/addHotMiddleware.js#L13):

```js 
results[name].unshift('./scripts/util/fixBSHMR.js');
results[name].unshift('eventsource-polyfill');
results[name].unshift('es6-promise-promise');
```

I believe that's all. This way Hot Module Replacement works again through networks, and polyfills make it work on IE.

**Comment by eriteric** [comment]
> I believe that's all. This way Hot Module Replacement works again through networks, and polyfills make it work on IE.

i tried this workaround but couldn't get it to build.
```
fixBSHMR.js
  1:30  error  'b' is defined but never used  no-unused-vars
```

**Comment by nicooprat** [comment]
I can't remember exactly why I needed this line, but you could try to remove it:

```
/*global __webpack_require__ b:true*/
```

If it doesn't work, try to disable this ESlint rule: https://eslint.org/docs/rules/no-unused-vars

**Comment by eriteric** [comment]
> If it doesn't work, try to disable this ESlint rule: https://eslint.org/docs/rules/no-unused-vars

that works, awesome thanks. Fonts now displaying on external devices. 
I ended up doing an inline eslint disable, here's the code so anyone can copy/paste:

```
/* eslint-disable no-unused-vars */
/*global __webpack_require__ b:true*/
/* eslint-enable no-unused-vars */
if(__webpack_require__)
  __webpack_require__.p = __webpack_require__.p.replace('localhost', window.location.hostname)

```
