### ISSUE TITLE
Where is the Default Template in Sage9 ?

### ISSUE THREAD

**Issue by Itemshopp** [roots/sage#2004]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

I maybe need some glasses but I can't find the Default Template in Sage9. Anywhere. 
I suppose it is on any blade files but I can't find any. with this markdown : 

{{--
  Template Name: Default Template
--}}

Do you have any idea ?
Thanks for your informations, for new glasses maybe ?

**Comment by alwaysblank** [comment]
This seems like a personal support request, not a bug report, so you might want to try asking over in the Discourse forum: https://discourse.roots.io/c/sage
