### ISSUE TITLE
Issues with FancyBox

### ISSUE THREAD

**Issue by burhandodhy** [roots/sage#2005]
Hi,

I added the Fancybox via Bower but I'm facing two different issue. 

1) Gulp put all images including fancybox in `dist\images\` while fancybox is looking for images in `dist\scripts`  folder. Is there any way to change the images path ?

2) After task completion Fancybox CSS in on the top of `main.css` but I want fancybox CSS before my CSS not on the top.

**Comment by retlehs** [comment]
please don't clear out the issue template, it's there for a reason. part of that reason is so that you don't use github issues for personal support requests and instead post on https://discourse.roots.io/
