### ISSUE TITLE
how can write widget with the blade in sage 9

### ISSUE THREAD

**Issue by AhmedAbdelazizRabea** [roots/sage#2010]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

how can write widget with the blade in sage 9
my widget folder in sage 9
framework -> widget -> widget.php

I need to change this widget to be by the blade

**Comment by JulienMelissas** [comment]
As this is a personal support request and not a bug, please ask this on Discourse: https://discourse.roots.io/
