### ISSUE TITLE
Scroll-linked positioning effect in admin area

### ISSUE THREAD

**Issue by kirylpl** [roots/sage#2016]
## Submit a feature request or bug report

- [* ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [- ] This is a feature request
- [* ] This is a bug report
- [* ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [* ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [*] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

In WP backend admin panel, when editing post's by clicking on the text area in Visual mode - there is height updating dynamically for iframe id="content_ifr" 
Other themes (non sage-based) works good.

---

**Please describe your local environment:**

WordPress version: 4.9.2

OS: Ubuntu 16.04

NPM/Node version: Production

**Where did the bug happen? Development or remote servers?**

Remote prod. server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/html-100-height-and-visual-editor/10396/3
https://discourse.roots.io/t/sage-9-visual-editor-issue/10812/3

**Comment by Hillsrion** [comment]
I think I got the same problem as you, and I ended up commenting this line in `app/setup.php`
`add_editor_style(asset_path('styles/main.css'));`

Hope it helps.
