### ISSUE TITLE
Customising the webpack setup, errors and separation of concerns

### ISSUE THREAD

**Issue by Pushplaybang** [roots/sage#2018]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When using a custom webpack assets pipeline, there is a non-descript error and no documentation regarding the specifics of the current webpack implementation.

```
Uncaught SyntaxError: Unexpected token <
http://wp.yudu.local/ line 1
```

**What is the expected or desired behavior?**

firstly, useful error checks and handling to make advanced customisations more approachable, and potentially a greater degree of decoupling between the assets pipeline and the theme.

### Why?

While the existing web pack config is pretty great for getting going quickly, and developers who haven't worked with web pack before, I expect that I'm not alone in building more advanced asset pipelines, or arriving with a custom web pack setup.  In my specific use case, here are some examples:

 - critical CSS & JS per page
 - code splitting
 - separate bundling of a React app that gets loaded only on one specific page

I believe a cleaner separation of concerns between assets and the theme would be the ideal solution but would settle for clear documentation on how to swap out the webpack config.   I'd even been keen to help out with this, but am too new to sage to jump in just yet.

---

## Bug report

Given a custom build of my assets on a fresh install of sage, that create the same dist directory files/folder structure, the following error on initial page load:

```
Uncaught SyntaxError: Unexpected token <
http://wp.yudu.local/ line 1
```

Using sage's web pack config,l and running yarn && yarn build . on the exact same install all works correctly.  Having had a look around, my suspicion is that its related to the manifest stuff, but not certain.

**Please describe your local environment:**

The environment is irrelevant as sage installed in the default manner works correctly, customisation of sage creates the error.

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

I've added a topic regarding my specific issue, though I do believe this is a concern that we should consider more generally:

https://discourse.roots.io/t/advanced-webpack-customisation/11445

---

## Feature Request

1. Better Error Handling
2. Documentation on Customising the assets pipeline

**Comment by Pushplaybang** [comment]
late nights, and bad paths.  Custom web pack now working beautifully.

Would still like more docs on the specifics of the default web pack install though.

**Comment by QWp6t** [comment]
https://github.com/roots/docs/blob/sage-9/sage/theme-development-and-building.md#theme-assets

**Comment by Pushplaybang** [comment]
@QWp6t  - thanks but that's a little thin at the moment.

**Comment by QWp6t** [comment]
If you feel that docs are inadequate, you're invited to start an issue (or PR) in that repo outlining what you think should be added to improve them. Or just buy [Ben's book](https://roots.io/books/theme-development-with-sage/) when it gets updated for Sage 9.
