### ISSUE TITLE
Maintenance Page Support

### ISSUE THREAD

**Issue by RyoIkarashi** [roots/sage#2023]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Sage doesn't support wordpress maintenance page.
Even if I create a template for maintenance page like `maintenance.blade.php` in views folder, the maintenance page with the template doesn't appear.
Also `webpack` does not handle assets for maintenance page at all.

**What is the expected or desired behavior?**

`maintenance.blade.php` file optionally can be created and rendered like other templates.
`webpack` also can handle assets for `maintenance.blade.php` file.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: X

OS: X

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by alwaysblank** [comment]
Does WordPress offer support for a maintenance page template outside of Blade? I wasn't able to find one on the [template heirarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/). Since Sage just hooks into the existing template heirarchy to select Blades, it would need an existing template to hook into.

**Comment by kalenjohnson** [comment]
A quick search also shows that if you want to modify the maintenance page, it doesn't even go in the theme directory, it goes in the uploads directory https://www.seedprod.com/how-to-create-custom-maintenance-mode-page-wordpress/
