### ISSUE TITLE
Where to put the language files?

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2029]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
---

**What is the current behavior?**

There is no documentation about where to place the language files for sage9 theme, 
notably the language files for sage9 base theme from https://github.com/roots/sage-translations .

Following paths have been tried, relative to the theme directory but no translations were picked up:
- `./lang/`
- `./langs/`
- `./language/`
- `./languages/`
- `./resources/lang/`
- `./resources/langs/`
- `./resources/language/`
- `./resources/languages/`

In this example, the de_DE / de_DE_formal *.mo files have been downloaded 
from the sage-translation repository and placed into the folder.

**What is the expected or desired behavior?**

An addition to documentation about the proper directory for language files for sage9 based themes.

Related discourse discussion: https://discourse.roots.io/t/install-sage9-language-files/10638

**Comment by retlehs** [comment]
there's a docs repo where we accept both issues and actual contributions to documentation

https://github.com/roots/docs/issues/96
