### ISSUE TITLE
Activating Sage theme with WP CLI

### ISSUE THREAD

**Issue by jasperrooduijn** [roots/sage#2030]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x ] This is a bug report
- [ x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
---

**What is the current behavior?**

Activating the theme with WP CLI using `wp activate sage` command gives the error `Error: Stylesheet is missing.` Probably because the style.css file is in the resources folder.

**What is the expected or desired behavior?**

Activitating the theme with WP CLI should be possible.

---

**Comment by QWp6t** [comment]
What happens if you try `wp activate sage/resources`?

x-ref: https://github.com/roots/sage/issues/1938

**Comment by jasperrooduijn** [comment]
@QWp6t Great! That works. I did not think about that option! Thats for the quick support.

**Comment by QWp6t** [comment]
Awesome. Glad to hear that worked. We'll add that to docs.
