### ISSUE TITLE
BrowserSync Not Watching Changes in Docker for Windows

### ISSUE THREAD

**Issue by distributev** [roots/sage#2038]
## Submit a feature request or bug report

- [x] This is a bug report

---

**What is the current behavior?**

BrowserSync Not Watching Changes in Docker for Windows

https://discourse.roots.io/t/browsersync-not-watching-changes-in-docker-for-windows/11275

**What is the expected or desired behavior?**

BrowserSync is expected to see the changes

**Comment by QWp6t** [comment]
The thread you linked seems to have the solution. Feel free to reopen this issue if that solution doesn't work.

https://discourse.roots.io/t/browsersync-not-watching-changes-in-docker-for-windows/11275/2

**Comment by distributev** [comment]
Yes but the solution implies hacking internal sage configuration files. Maybe this can work out of the box with Sage.
