### ISSUE TITLE
Title filters

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2039]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Bug report
`App::title()` is filtered by 'unusual' filters, hence some plugins 
(like [wp-typography](https://github.com/mundschenk-at/wp-typography)) don't treat the title strings differently.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

For more details concerning the filters, see https://github.com/mundschenk-at/wp-typography/issues/204

**Comment by retlehs** [comment]
there is nothing unusual in here: https://github.com/roots/sage/blob/e00eaf7e8fd8a5e63716ff31b5f0fc006171a8c4/resources/controllers/App.php

 the github issue you linked is talking about `wp_title` which is for your `<title>` and not your `<h1>`

please don't use github for personal support requests
[please](https://github.com/roots/sage/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3Astrarsis+)
[please](https://github.com/roots/trellis/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3Astrarsis+)

**Comment by QWp6t** [comment]
Yeah, the dude in the issue you linked explained it well: https://github.com/mundschenk-at/wp-typography/issues/204

> Apparently the call to `App::title()` does not use any of the standard WordPress filter hooks for the document title (`wp_title`, `wp_title_parts`, `document_title_parts`). Instead, **it appears to use the `the_title` hook intended for printing the post title as a heading.**

In case you missed that:

> Instead, it appears to use the `the_title` hook **intended for printing the post title as a heading.**
