### ISSUE TITLE
[Feature] Support dynamic requires (imports) in DOM-Router.

### ISSUE THREAD

**Issue by vkryukov76** [roots/sage#2041]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

DOM-Router is very useful pattern.

But it has one small flaw - all routes always bundled into one file that loads on every page, even when most routes will never be fired.

Webpack has a great feature called [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports).  

Unfortunately current implementation of DOM-Router works only with regular modules, not the dynamic ones.

Dynamic approach to routes can help to split some heavy routes into separate chunks that loads on-demand through only one trigger - a classname of body tag.

I already  made some changes in DOM-Router class to support `require.ensure`d and `import()`ed modules (not supported in current sage's build system now).

https://github.com/vkryukov76/sage/commit/9b41139

If upstream and community will find it useful I will be glad to submit a PR.

**Comment by Log1x** [comment]
#2190
