### ISSUE TITLE
[README] composer create

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2045]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

The instructions in [README](https://github.com/roots/sage#theme-installation) of this repository seems to be outdated.
`````
$ composer create-project roots/sage <project-name> dev-master
Could not find package roots/sage with version dev-master in a version installable using your PHP version 7.0.25.
`````

After sage9 became stable, the dev-master somehow changed probably?

**Comment by alwaysblank** [comment]
The README you linked to explicitly states that Sage requires PHP 7.1.3 or better:

![image](https://user-images.githubusercontent.com/23412884/37663364-491b8c6a-2c16-11e8-8cd8-769f9d1fd361.png)

You are attempting to install on PHP 7.0.25, which is not supported. Your version of PHP is outdated, not the instructions.
