### ISSUE TITLE
package.json doesn't seem to be updated by 

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2047]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
---

**What is the current behavior?**
`package.json` is not updated accordingly to input in interactive 
`composer create-project roots/sage [...]` session.

**What is the expected or desired behavior?**
`package.json` fields use the previously enterred information.

**Please describe your local environment:**
OS: WSL (Bash on Windows)
Node version: v.8.10.0
Yarn version: 1.5.1

**Reproducing the bug:**
1. Create new sage project using `composer create-project roots/sage test`
2. Interactively provide the information, e.g. theme version, author, etc
3. After confirmation and finish of generation, inspect the `package.json`.
Note that the fields in `package.json`, that can make use of the provided information don't use them, e.g. the `version`, `author` or `homepage` fields are still using default values (from this repository).

**Comment by retlehs** [comment]
possibly same as https://github.com/roots/sage-installer/issues/15? if not, needs to be addressed in that repo regardless
