### ISSUE TITLE
[Sage 9] Infinite auto reload

### ISSUE THREAD

**Issue by alancpazetto** [roots/sage#2052]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When edit a JS the auto reload causes infinite loop in browser.

**What is the expected or desired behavior?**

When edit a JS, the auto reload reload browser normally.

---

## Bug report

When edit a JS the auto reload causes infinite loop in browser.

**Please provide steps to reproduce, including full log output:**

- Create new project
- Active Theme
- Configure devUrl
- Start server: yarn run start
- Open home.js
- Edit and save
- See browser

**Please describe your local environment:**

WordPress version: 1.7.9

OS: MacOSX High Sierra

NPM/Node version: Node 8.2.1 NPM 5.3.0

**Where did the bug happen? Development or remote servers?**

Localhost

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No.

**Comment by alancpazetto** [comment]
My MAMP is configured in port 80, so I've configure my devUrl with **http://localhost**
```
{
  "entry": {
    "main": [
      "./scripts/main.js",
      "./styles/main.scss"
    ],
    "customizer": [
      "./scripts/customizer.js"
    ]
  },
  "publicPath": "/app/themes/sage",
  "devUrl": "http://localhost/sandbox/sage9",
  "proxyUrl": "http://localhost:3000",
  "cacheBusting": "[name]_[hash:8]",
  "watch": [
    "app/**/*.php",
    "config/**/*.php",
    "resources/views/**/*.php"
  ]
}
```

**Comment by retlehs** [comment]
please don't use github for personal support requests, use https://discourse.roots.io/
