### ISSUE TITLE
yarn start on vagrant doesn't detect scss file change?

### ISSUE THREAD

**Issue by firescript** [roots/sage#2057]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

On a fresh install of bedrock + sage on to my homestead vagrant box, I ssh to the template and run `yarn && yarn` build and it works.. Then I go to run `yarn start` and it just does one successful compile when i first ran `yarn start` but nothing happens after that. If i modify and save main.js or main.scss it doesnt trigger the build process.

i dont want to use browsersync since i'm in vagrant, i'm fine with just reloading the page - not sure if that has anything to do with it? Also i know that in your docs you say to use outside of vagrant. Is this the reason it does not compile?

**What is the expected or desired behavior?**

it compiles on change of file - 

---

## Bug report

**Please provide steps to reproduce, including full log output:**

fresh install on homestead vagrant. 

**Please describe your local environment:**

WordPress version: 4.9.5

OS: vagrant 2.0.2 homestead

NPM/Node version: 5.8

**Where did the bug happen? Development or remote servers?**

homestead vagrant box

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

i didnt see one.

**Comment by retlehs** [comment]
**please use https://discourse.roots.io/ for personal support requests**

> i dont want to use browsersync since i'm in vagrant

if you don't want to use browsersync then you would need to run a normal build every time you wanted it to compile updates

ps. don't run the build scripts from your vagrant box, you need to run them from your host machine
