### ISSUE TITLE
Make PHP Templating Engine optional

### ISSUE THREAD

**Issue by landwire** [roots/sage#2064]
## Submit a feature request or bug report

- [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ x] This is a feature request
- [ ] This is a bug report
- [ x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Feature Request

**Please provide use cases for changing the current behavior:**

Like many people I would like to use twig instead of blade with Sage. Would it be possible to add these options during the theme setup dialog? I guess equivalent to the Front End Framework dialog...

1. use blade
2. use twig
3. use none (which lets you set-up your own and removes all the blade related stuff)

I am not too familiar with Sage, so cannot tell if that is easy to implement the twig option. But at least the option not to use a templating language should be available. I do not want all the clutter that comes with blade, if I am not going to use it.

Thanks,
Sascha

**Comment by QWp6t** [comment]
[Blade compiler](https://github.com/laravel/framework/blob/5.6/src/Illuminate/View/Compilers/BladeCompiler.php) is technically optional if you rename your template files from `.blade.php` to `.php`. At that point your files will still be picked up by the view service provider and passed to the [php engine](https://github.com/laravel/framework/blob/5.5/src/Illuminate/View/Engines/PhpEngine.php).

At the moment we have no plans of adding a Twig compiler. As an alternative to Sage, there's a framework by htmlBurger called [wpemerge](https://wpemerge.com/) that will simultaneously support Blade and Twig, but I can't attest to its implementation or quality as I haven't personally used it yet.
