### ISSUE TITLE
Browsersync HTML injector not designed for PHP, causes unintended side effects

### ISSUE THREAD

**Issue by knowler** [roots/sage#2069]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Since the [Browsersync HTML injector plugin](https://github.com/shakyShane/html-injector) was not designed for Blade, let alone PHP, there can be some undesired effects when changing the markup of a looped item. A full reload is required to generate the correct markup.

**What is the expected or desired behavior?**

One would expect that the markup to display correctly as it was changed 

---

## Bug report

**Please provide steps to reproduce, including full log output:**

I was able to reproduce this for Patric on Discourse following his description of his setup (Valet, WP installed via WP-CLI).

Here is a gif demonstrating how to reproduce this error in a freshly installed Sage setup:

![bs-html-injector-issue](https://user-images.githubusercontent.com/6908001/39953900-5f51c708-5572-11e8-810d-0b5ecbcf8791.gif)

This is the HTML generated by that final state in the gif:

```html
<main class="row my-4">
  <div class="col-3">
    <div class="p-3 bg-primary text-white">
      <div class="p-3">
        <h5>apple</h5>
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="p-3 bg-primary text-white">
      <h5>pear</h5>
    </div>
  </div>
  <div class="p-3">
    <div class="p-3 bg-primary text-white">
      <h5>banana</h5>
    </div>
  </div>
</main>
```

**Please describe your local environment:**

WordPress version: 4.9.5

OS: macOS 10.13.4

NPM/Node version: 5.6.0/v9.8.0

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Start here: https://discourse.roots.io/t/sage-9-browsersync-not-updating-right/10648/10?u=knowler

**Comment by QWp6t** [comment]
Full reloads do in fact occur under the hood.

https://github.com/shakyShane/html-injector/blob/master/index.js#L236-L253


Did you try throttling BrowserSync?

**Comment by knowler** [comment]
@QWp6t I’m able to get it do a full reload if I save the file twice, which makes sense give that block of code you shared. I am unable to get a full reload to occur from modifications to PHP (that affects markup — i.e. anything in a Blade template or updating an object value in a controller).

I enabled debugging for Browsersync by setting `logLevel: 'debug'` and then since `bs-html-injector` is using [`debug`](https://github.com/visionmedia/debug), I prepended `DEBUG=bs-html-injector` to the `start` script.

Here's an example of the console output if I’m only modifying the classes of existing markup:

```
[Browsersync] Browser Connected: Firefox, version: 59.0
[BS] [HTML Injector] Stashing: http://localhost:3000/
  bs-html-injector Responding to file change event HTML Injector +0ms
[BS] [HTML Injector] Cache items: 1
  bs-html-injector requesting http://localhost:3000/ +0ms
  bs-html-injector 3 tasks returned +46ms
  bs-html-injector Task: TAG: DIV, INDEX: 3 +0ms
  bs-html-injector Task: TAG: DIV, INDEX: 5 +1ms
  bs-html-injector Task: TAG: DIV, INDEX: 7 +0ms
  bs-html-injector Responding to file change event HTML Injector +6s
[BS] [HTML Injector] Cache items: 1
  bs-html-injector requesting http://localhost:3000/ +1ms
  bs-html-injector 3 tasks returned +38ms
  bs-html-injector Task: TAG: DIV, INDEX: 3 +0ms
  bs-html-injector Task: TAG: DIV, INDEX: 5 +1ms
  bs-html-injector Task: TAG: DIV, INDEX: 7 +0ms
  bs-html-injector Responding to file change event HTML Injector +6s
[BS] [HTML Injector] Cache items: 1
  bs-html-injector requesting http://localhost:3000/ +1ms
  bs-html-injector 3 tasks returned +42ms
  bs-html-injector Task: TAG: DIV, INDEX: 3 +0ms
  bs-html-injector Task: TAG: DIV, INDEX: 5 +0ms
  bs-html-injector Task: TAG: DIV, INDEX: 7 +0ms
```

(That was 3 modifications to the file.)

As soon as a change to the structure of the markup within a foreach loop occurs the first change outputs:

```
[BS] [HTML Injector] Cache items: 1
  bs-html-injector requesting http://localhost:3000/ +1ms
  bs-html-injector 1 tasks returned +53ms
  bs-html-injector Task: TAG: DIV, INDEX: 3 +0ms
```

Subsequent changes output:

```
[BS] [HTML Injector] Cache items: 1
  bs-html-injector requesting http://localhost:3000/ +0ms
  bs-html-injector 3 tasks returned +51ms
  bs-html-injector Task: TAG: DIV, INDEX: 4 +0ms
  bs-html-injector Task: TAG: DIV, INDEX: 7 +1ms
  bs-html-injector Task: TAG: DIV, INDEX: 10 +0ms
```

#### Re:throttling

I tried a few settings for `reloadThrottle`, but the issue persists.
