### ISSUE TITLE
Postcss's control comments not working on production

### ISSUE THREAD

**Issue by Roywcm** [roots/sage#2077]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Postcss provides a functionality to disable specific autoprefix behavior with Control Comments. 
This is working perfect when using the yarn start command, but not with the yarn build:production command.

**What is the expected or desired behavior?**

Disable autoprefixing for rules with postcss control comments on production compiling.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. add a rule that normaly will be auto prefixed with the control comment above. e.g.
```
image {
    /* autoprefixer: off */
    clip-path: url(#imagemask);
  }
```

2. Run `yarn start`: now it's working, without prefix
3. Run `yarn build:production`; Now it's not working with prefix.

**Please describe your local environment:**

WordPress version: 4.9.6

OS: OSX

NPM/Node version: 5.6.0/v8.8.1

**Where did the bug happen? Development or remote servers?**

Development

**Comment by knowler** [comment]
Could be related:

https://discourse.roots.io/t/removing-unused-css-with-purgecss-uncss/11586/13?u=knowler

**Comment by knowler** [comment]
@Roywcm I just made a PR (#2078) to provide a better solution for this. Check it out to see my findings in regards to this issue.
