### ISSUE TITLE
Something happened between Sage 9.0.0 and 9.0.1

### ISSUE THREAD

**Issue by durbanski** [roots/sage#2079]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Really can't debug this so hopefully someone can help my with it.

In my previous project based on Sage (9.0.0) I used https://jonsuh.com/hamburgers/

I'm adding file: `autoload/_hamburgers.scss` with following:

`@import "~hamburgers/_sass/hamburgers/hamburgers"`

when running:

`yarn run build:production`

all is working fine.

When I will use Sage 9.0.1 and do the same, only bootstrap is compiled and added to final css (like something breaked within hamburgers.scss)

This is not working only with production flag. In any other case it works fine.

No errors, no warnings or anything is thrown during this.

**What is the expected or desired behavior?**

To build all assets with success.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Install fresh sage 9.0.1 (with bootstrap)
2. Install hamburgers by `yarn add hamburgers`
3. Add file `autoload/_hamburgers.scss` with content as specified above.
4. Add any style to main.scss after autoload (like body background red).
5. Run `yarn run build:production`

**Please describe your local environment:**

WordPress version: 4.9.6

OS: macOS Sierra 10.12.6

NPM/Node version: NPM 6.0.6 / Node 8.9.1

**Where did the bug happen? Development or remote servers?**

Both

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by knowler** [comment]
Does `yarn lint:styles` pass?

**Comment by durbanski** [comment]
Yup.

```
yarn lint:styles
yarn run v1.3.2
$ stylelint "resources/assets/styles/**/*.{css,sass,scss,sss,less}"
✨  Done in 1.13s.
```

**Comment by koentjuh1** [comment]
@import "~hamburgers/_sass/hamburgers/hamburgers.scss";

**Comment by garrettw** [comment]
@koentjuh1 The [docs](https://jonsuh.com/hamburgers/#sass) say the '.scss' extension isn't needed.

**Comment by knowler** [comment]
I think for now this would be better as a support request on [Discourse](https://discourse.roots.io) as the ambiguity of the error/issue ("Something happened between Sage 9.0.0 and 9.0.1") requires a lot of back and forth for testing which notifies everyone who is watching Sage.

In my testing I was encountering the same issue — no styles after a production build — with the given instructions, however, I tested it in both 9.0.1 and 9.0.0 and received the same results. This leads me to believe it’s an issue of configuration and not a bug with Sage itself.

There is an official community contributed [guide for setting up Hamburgers in Sage 9](https://roots.io/guides/how-to-use-hamburgers-in-sage/) which I do know works as I’ve setup my last few projects using it (even my personal fork of Sage which is on 9.0.1).

**Comment by knowler** [comment]
This solves the issue: https://github.com/roots/sage/issues/2017#issuecomment-361054297

**Comment by durbanski** [comment]
Thanks @knowler for pointing this out. I'm closing this issue, as it's not an issue actually.
It works.
