### ISSUE TITLE
build:production ImageminPlugin fails on Windows [FIXED]

### ISSUE THREAD

**Issue by mtx-z** [roots/sage#2087]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**Bug**

Running `yarn run build:production` on Windows fail because of `ImageminPlugin()` in `resources/assets/build/webpack.config.optimize.js`.

**What is the expected or desired behavior?**

`yarn run build:production` should produce optimized images in `/dist/` folder

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Running `yarn run build:production` on Windows fail because of `ImageminPlugin()` in `resources/assets/build/webpack.config.optimize.js`.

Error is : `asset optimizationError: Le chemin d'accès spécifié est introuvable` (path not found). Running `npm run build:production --verbose` does not provide any useful additionnal info.

- Commenting all `new ImageminPlugin()` block in `webpack.config.optimize.js` fix the issue, and `build:production` succeed
- removing all images file from `resources/assets/images` fixes the issue, and `build:production` succeed
- `yarn run build` works as it does not optimize images

**Resolution**
- As seen on [discourse](https://discourse.roots.io/t/yarn-build-production-failing-asset-optimizationerror-write-epipe/12219/2), I tried to install [windows version of libpng](http://gnuwin32.sourceforge.net/packages/libpng.htm), it not worked at all
- As seen on [imagemin Github](https://github.com/imagemin/imagemin/issues/199) I tried running : 
  - `npm install gulp-imagemin imagemin-jpegtran imagemin-pngquant pngquant-bin`
  - `yarn install`
- That fixed the issue, and `yarn run build:production` was able to process my images correctly
- Not sure what are required packages in the command, I would say that only `imagemin-jpegtran imagemin-pngquant pngquant-bin` are required.

**Please describe your local environment:**

WordPress version: 4.9.7, Sage 9.0.1

OS: Windows 10 Pro 64, PHP 7.1, Nginx (Laragon)

NPM/Node version: 8.11.1

**Where did the bug happen? Development or remote servers?**

Local (Laragon) Windows 10

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/yarn-build-production-failing-asset-optimizationerror-write-epipe/12219/2

---

**Comment by alwaysblank** [comment]
It seems like you solved this issue, so I'm going to close it. If you feel Sage would benefit from a PR to address your solution, please feel free to submit one.
