### ISSUE TITLE
Controller data not available in searchForm partial

### ISSUE THREAD

**Issue by NuruddinBadawi** [roots/sage#2105]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Bug report

the staps ..
install new Sage theme --->  remove all posts from admin  ---> and see the error in the home page.

this section will execute:
```
 @if (!have_posts())
    <div class="alert alert-warning">
      {{ __('Sorry, no results were found.', 'sage') }}
    </div>
    {!! get_search_form() !!}
  @endif
```
**the error is `Undefined variables...`** 

The error in my opinion is:
because the variables not passed to the "formSearch" partial page as well.

the data injected here
```
add_filter('sage/template/app/data', function ($data) {
    return $data + [
        'sf_action' => esc_url(home_url('/')),
        'sf_screen_reader_text' => _x('Search for:', 'label', 'sage'),
        'sf_placeholder' => esc_attr_x('Search &hellip;', 'placeholder', 'sage'),
        'sf_current_query' => get_search_query(),
        'sf_submit_text' => esc_attr_x('Search', 'submit button', 'sage'),
    ];
});

```

but "formSearch" use this data but he can't access the data above.

**Please describe your local environment:**

WordPress version: latest

OS: macOsx

NPM/Node version: 6.4.0/ 10.0.0

**Where did the bug happen? Development or remote servers?**

Development

**Comment by mmirus** [comment]
Also reported in #2101 and referenced on Discourse [here](https://discourse.roots.io/t/ask-about-passing-data-to-the-view/13499).

As reported, the controller data for the searchForm partial defined at https://github.com/roots/sage/blob/master/app/filters.php#L95 is available within templates but not within that partial.

One possible solution would be this:

```php
/**
 * Render WordPress searchform using Blade
 */
add_filter('get_search_form', function () {
    $data = collect(get_body_class())->reduce(function ($data, $class) {
        return apply_filters("sage/template/{$class}/data", $data, 'partials.searchform');
    }, []);

    return template('partials.searchform', $data);
});
```

But we can probably come up with something cleaner.
