### ISSUE TITLE
Webpack crashes on new tailwind project

### ISSUE THREAD

**Issue by gandalfar** [roots/sage#2113]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

## Bug report

I've created a new roots.io project and selected `tailwind` as CSS toolkit, when running `yarn build`, it crashes

```
➜ yarn build
yarn run v1.9.4
$ webpack --progress --config resources/assets/build/webpack.config.js
/Users/gandalf/hacking/projectname/wp-content/themes/projectname/resources/assets/build/webpack.config.preset.js:19
    )
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at module.exports.err (/Users/gandalf/hacking/projectname/wp-content/themes/projectname/resources/assets/build/util/desire.js:13:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The problem is that `projectname/resources/assets/build/webpack.config.preset.js:19` has one `,` too much on line 19:

```
/** Add cssnano when optimizing */
config.enabled.optimize
  ? postcssPlugins.push(
      require('cssnano')({
        preset: ['default', { discardComments: { removeAll: true } }],
      }),     <---- this comma here should be removed
    )
  : false;
```

Removing it fixes the build, but it would be great if it worked out of the box.

X

**Please describe your local environment:**

WordPress version: 4.9.8

OS: macOS 10.13.6

NPM/Node version: 5.8.0 / v6.14.1

**Where did the bug happen? Development or remote servers?**

Local development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

None

**Comment by roots-ladybug** [comment]
Hi @gandalfar,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by gandalfar** [comment]
I'll open new issue. Thanks.

**Comment by knowler** [comment]
No, keep this in one issue, I'll reopen it. Just edit your original post.

**Comment by gandalfar** [comment]
I've updated the issue. I'll try to reproduce it on a different node env.

**Comment by gandalfar** [comment]
Please go ahead if you think this will make webpack not crash for other users.

I can't reproduce this issue in any other environment as I never get tailwind option anymore by following installation instructions. But that's a probably a different issue.

**Comment by mmirus** [comment]
Hi @gandalfar,

Node 6.9 is the minimum version for Sage 9. Do you still get this error using 6.9 or newer?

**Comment by gandalfar** [comment]
But I'm using - `v6.14.1`?

**Comment by mmirus** [comment]
Wow, that's what I get for replying to issues before fully waking up. My mistake!

**Comment by gandalfar** [comment]
@mmirus thanks for the PR. 

I don't think I should open an issue because on those environments PHP is 7.0.31 (and project requires 7.1) and that's probably why I don't get tailwind option. Sorry for the false alert.
