### ISSUE TITLE
Sage 9.0.2 load wrong controller for template specified frontpage

### ISSUE THREAD

**Issue by IronGhost63** [roots/sage#2115]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

If you set homepage display (`Settings > Reading`) to static page, and selected page is specified with custom template (let's say template-custom.blade.php), Sage 9.0.2 load `FrontPage` controller instead of `TemplateCustom` controller

**What is the expected or desired behavior?**

If custom template is set to static home page, load controller for specified template instead of `FrontPage`

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Create a page and set custom template (for example: template-custom.blade.php)
2. Go to `Settings > Reading` and set `Your homepage displays` to A static page, and select created page from step one as Homepage
3. in `template-custom.blade.php` try display data from `TemplateCustom` controller.

_data from `TemplateCustom` will not appear, instead, if you move methods to `FrontPage` data will appear correctly_

**Please describe your local environment:**

WordPress version: 4.9.8

OS: Mac OS

NPM/Node version: 8.11.3

**Where did the bug happen? Development or remote servers?**

Development (but likely to happen on production as well)

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

none

**Comment by MWDelaney** [comment]
This issue is more appropriately filed with Controller [here](https://github.com/soberwp/controller). As I understand it, this is the intended behavior. You could work around this with Traits in Controller, but that's a more project-specific recommendation.

**Comment by darrenjacoby** [comment]
Please create issues for Controller on https://github.com/soberwp/controller/issues

**Comment by IronGhost63** [comment]
@darrenjacoby The problem is Sage 9 loaded `template-custom.blade.php` not `front-page.blade.php` I don't care if it should be `template-custom.blade.php` or `front-page.blade.php` that should take the priority. but Controller should be the same, not `FrontPage.php` with `template-blade.php`

Btw, I will create issue on `soberwp/controller` thanks for suggestion
