### ISSUE TITLE
Unexpected action/filter execution order

### ISSUE THREAD

**Issue by kimhf** [roots/sage#2116]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Some notable actions, filters and events are being executed in the following order:

1. data collected from controllers
2. wp_enqueue_scripts (action)
3. the_content (filter) on main query
4. wp_head (action)
5. get_header (action)
6. get_footer (action)
7. wp_footer (action)

**What is the expected or desired behavior?**

The actions and filters being executed in the following order:

1. get_header (action)
2. wp_head (action)
3. wp_enqueue_scripts (action)
4. data collected from controllers
5. the_content (filter) on main query
6. get_footer (action)
7. wp_footer (action)

---

## Bug report

Plugin authors often expect the execution order to be the same on every theme for these key actions and filters.

One example would be Jetpack setting up a the_content filter during get_header. The result is the filter is not applied to the main content loop for a Sage theme.

We also might use template tags in controllers, so 3. party filters should be set up before collecting the data.

**Please provide steps to reproduce, including full log output:**

The issue was tracked by logging the execution order via priority 0 hooks on tracked actions.

**Please describe your local environment:**

WordPress version: 4.9.8

OS: Windows 10

NPM/Node version: 8.11.3

**Where did the bug happen? Development or remote servers?**

On all sites with incompatible plugins.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

This issue can be hard to notice, but is related to the issues with wp_enqueue_scripts that is fixed in the template() function. My suggestion would be to replace that fix with something covering more actions/filters to increased compatibility with more plugins.

**Comment by garrettw** [comment]
I can confirm that OP's expected behavior is accurate as per http://rachievee.com/the-wordpress-hooks-firing-sequence/
