### ISSUE TITLE
[Feature] Dart-Sass implementation for webpack build

### ISSUE THREAD

**Issue by mscalessio** [roots/sage#2128]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Feature Request

This is a simple [dart-sass](https://github.com/sass/dart-sass) implementation for webpack request.
I've updated `sass-loader` to 7.1 version in order to use this implementation.
And I've already made the necessary changes and open a pull-request.

Please consider this upgrade in the next release.
Thanks

**Comment by Log1x** [comment]
#2172 (Mix uses dart-sass by default)

**Comment by trainoasis** [comment]
@mscalessio this hasnt been added then in Sage 9?  Were you able to do this without any issues there? For example these: https://github.com/roots/sage/pull/2129#issuecomment-849627338 ?
