### ISSUE TITLE
Build Vendor Fonts cache busting

### ISSUE THREAD

**Issue by auban** [roots/sage#2130]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums
---

**What is the current behavior?**

File: /resources/assets/build/webpack.config.js
Line: 118
If build assets not production the output vendor fonts add cache busting on each font files.

---

## Bug report

Replace: name: `${config.cacheBusting}.[ext]`,
With:  name: `${assetsFilenames}.[ext]`,

**Please provide steps to reproduce, including full log output:**

- Build asset not production

**Where did the bug happen? Development or remote servers?**

Development 

---

**Comment by Kreativschnittstelle** [comment]
Yes, I second that one!

**Comment by Log1x** [comment]
#2172
