### ISSUE TITLE
Embed template customization is not working

### ISSUE THREAD

**Issue by paradox37** [roots/sage#2142]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Customizing embed templates does not work. For example, I created embed-content.blade.php in the views folder and it does not have any effect.

**What is the expected or desired behavior?**

It should allow customizing embed templates, which works with default WP. Those files include embed.php, embed-404.php, embed-content.php, header-embed.php, footer-embed.php.

---

## Bug report

Create two posts. Paste first post link to second post content. Create embed-content.php in views folder and try to customize it.

**Please describe your local environment:**

WordPress version: 4.9.8

OS: Windows 10

NPM/Node version: 8.9.1

**Other relevant information:**

Using Sage 9.06 + Bedrock 1.8.12

**Comment by mmirus** [comment]
Thanks for reporting this, @paradox37! I just created a PR to resolve this issue.
