### ISSUE TITLE
[Sage 9] Polyfill needed for CustomEvent (IE <=11)

### ISSUE THREAD

**Issue by jcarignan** [roots/sage#2147]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

CustomEvent is used by resources/assets/scripts/util/Router.js, no polyfill is added and fails in IE<=11.

**What is the expected or desired behavior?**

The polyfill from https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent should be added in order to execute code from resources/assets/scripts/routes/ for IE<=11.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Naviguate to https://roots-example-project.com/ using IE11 with Developer Tools opened.

**Comment by retlehs** [comment]
we're aware of this and it's not a bug

https://github.com/roots/sage/pull/2080#issuecomment-439496848

i'll add a note to the docs

**Comment by jcarignan** [comment]
Alright thanks for confirming!

**Comment by jtuds** [comment]
Needing a polyfill for this wasn't the case in version 9.0.5 but is in version 9.0.7. Surely this isn't a minor change? It breaks all IE11 Javascript functionality. What is the reason for this not having a fallback baked into the version or at least not a minor change?

**Comment by retlehs** [comment]
> What is the reason for this not having a fallback 

ie11 accounts for 2.26% of global web traffic. i'm not sure it makes sense to include a polyfill out of the box for that

**Comment by jtuds** [comment]
Yeh I don't disagree with that. My concern is that people are now already using Sage with IE11 without this issue and could do a minor upgrade but have all of their functionality break

**Comment by maguijo** [comment]
> > What is the reason for this not having a fallback
> 
> ie11 accounts for 2.26% of global web traffic. i'm not sure it makes sense to include a polyfill out of the box for that

It makes sense when your client is part of the 2.26% still using IE 11!

**Comment by dsturm** [comment]
> > > What is the reason for this not having a fallback
> 
> > 
> 
> > ie11 accounts for 2.26% of global web traffic. i'm not sure it makes sense to include a polyfill out of the box for that
> 
> 
> 
> It makes sense when your client is part of the 2.26% still using IE 11! 

As much as I know the "problem" of having such a client, I think it's time to move on and spend no more efforts on supporting IE (out of the box) at all. It's not the task of a framework like Sage. Instead, we as a developing community should clear the way for new and better technology. Also, [WordPress is officially aiming to drop support sooner or later](https://make.wordpress.org/core/2020/03/27/guidelines-for-ancient-browser-support-ie/).

**Comment by maguijo** [comment]
> > > > What is the reason for this not having a fallback
> > 
> > 
> > > 
> > 
> > 
> > > ie11 accounts for 2.26% of global web traffic. i'm not sure it makes sense to include a polyfill out of the box for that
> > 
> > 
> > It makes sense when your client is part of the 2.26% still using IE 11!
> 
> As much as I know the "problem" of having such a client, I think it's time to move on and spend no more efforts on supporting IE (out of the box) at all. It's not the task of a framework like Sage. Instead, we as a developing community should clear the way for new and better technology. Also, [WordPress is officially aiming to drop support sooner or later](https://make.wordpress.org/core/2020/03/27/guidelines-for-ancient-browser-support-ie/).

That's all fine and dandy for Wordpress but Microsoft has said they'll continue to support IE 11 for the life of Windows 10. However if the framework doesn't want to support IE anymore then it's up to the developer to install a polyfill which is what I did for this situation as there's no convincing this client that he needs to use Edge instead. Polyfills cost extra though...a LOT extra. 🤣

**Comment by jtuds** [comment]
Again, I agree with the sentiment behind not supporting an old browser however I'd like to highlight my original point. This functionality worked in 9.0.5 but not in 9.0.7. Can this really be considered a minor upgrade with that being the case? Shouldn't the upgrade be bumped or IE11 supported still?
