### ISSUE TITLE
Incorrect production asset paths when 2+ levels deep 

### ISSUE THREAD

**Issue by codepuncher** [roots/sage#2148]
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Given the following file structure:

```
# sage/resources/assets
├── scripts
│   └── tinymce
│       └── button.js
├── styles
│   └── tinymce
│       └── button.scss
└── config.json
```

We will get these results within `sage/dist/assets.json`:
`yarn build`: `scripts/tinymce/button.js`
`yarn build:production`: `tinymce/button.js`

As a result, your CSS and JS files in subdirectories will never be loaded on production environments as the key is incorrect e.g. `asset_path('scripts/tinymce/button.js')` only works without `:production` flag.

**What is the expected or desired behavior?**

We should get identical results regardless of which script is run:
`yarn build`: `scripts/tinymce/button.js`
`yarn build:production`: `scripts/tinymce/button.js`

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Install fresh copies of Bedrock + Sage
2. Add a Javascript or SCSS file to a new directory in either `scripts` or `styles` (e.g. `sage/resources/assets/scripts/plugins/hello.js`)
3. Enqueue in `sage/app/setup.php` and add to `sage/resources/assets/config.json`
    ```
    # sage/app/setup.php
    wp_enqueue_script('sage/misc/plugins/hello.js', asset_path('scripts/misc/plugins/hello.js'), ['jquery'], null, true);
    ```
    ```
    # sage/resources/assets/config.json
    "misc/plugins/hello": [
      "./scripts/plugins/hello.js"
    ]
    ```
4. Run `yarn build:production`

**Please describe your local environment:**

WordPress version: any (tested on 4.9.8 and 5.0.3)

OS: Ubuntu Linux 18.04, Linux Mint 19

NPM/Node version: NPM 6.4.1, Node 11

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/cant-load-production-assets-located-in-sub-directory/14666

**Comment by Log1x** [comment]
Sage 9 (especially it's build system) will not be receiving any future updates. This should be resolved in 10 as per #2172 – but feel free to make a new issue (or an issue upstream to Mix) if this continues to be a problem in the future.
