### ISSUE TITLE
Node v11.9.0 Dependency Issue?

### ISSUE THREAD

**Issue by brandontamm** [roots/sage#2151]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

**What is the current behavior?**

Fresh installation of node container with:
Node v11.9.0
Yarn v1.13.0

When trying to use Sage's documented Yarn commands, I receive dependency errors

**What is the expected or desired behavior?**

Yarn should have installed all dependencies with no errors.
---

## Bug report

**Please provide steps to reproduce, including full log output:**

develop@3ae0d923d729:/var/www/html/site/web/app/themes/site# npm install --allow-root && yarn install --allow-root && yarn && yarn start
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of webpack@^1.13.2 || ^2.7.0 || ^3.11.0 || ^4.4.0 but none is installed. You must install peer dependencies yourself.
npm ERR! Cannot read property '0' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-05T15_22_44_839Z-debug.log
develop@3ae0d923d729:/var/www/html/site/web/app/themes/site# node -v
v11.9.0
develop@3ae0d923d729:/var/www/html/site/web/app/themes/site# yarn -v
1.13.0

**Please describe your local environment:**

WordPress version: 5.0.3
Node v11.9.0
Yarn v1.13.0

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

**Comment by MWDelaney** [comment]
Please post a topic on https://discourse.roots.io for support requests like this. Before posting, please review our [Getting Started documentation](https://roots.io/getting-started/docs/development-environment-recommendations/) which differs from your methods a little and is our recommended process for setting up a development environment for Roots in general and Sage specifically.
