### ISSUE TITLE
upgrade node-sass t 4.11.0

### ISSUE THREAD

**Issue by vahidalvandi** [roots/sage#2156]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

X

**What is the expected or desired behavior?**

hi i have error in install sass when in update node to v11 and change packge.json to 4.11.0 it work fine

---

## Bug report

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: X

OS: X

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by garrettw** [comment]
you could at least try to fill it out properly... 🙄

**Comment by vahidalvandi** [comment]
i use last version ,

**Comment by MWDelaney** [comment]
We recommend using the Node LTS release (8.9.0 at the time of this writing) and using `nvm` to switch between Node versions as required by your projects.

See [our "Getting Started" docs](https://roots.io/getting-started/docs/development-environment-recommendations/) for complete details on our recommended development environment.
