### ISSUE TITLE
remove eslint for easy develop

### ISSUE THREAD

**Issue by vahidalvandi** [roots/sage#2157]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

X

**What is the expected or desired behavior?**

if you remove eslint in webpack.config.js we can develop scss easy and fast
remove this for dont have error in new line , empty space ,....
```
    new StyleLintPlugin({
      failOnError: !config.enabled.watcher,
      syntax: 'scss',
    }),
```

---

## Bug report

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: X

OS: X

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by MWDelaney** [comment]
Code hygiene and coding standards are extremely important to the Roots team. We institute these tools to help our users write better, more supportable code. We will not be removing eslint or stylelint from Sage.
