### ISSUE TITLE
[8.6.0] Cant install asset-builder, repo doesnt exist

### ISSUE THREAD

**Issue by justlevine** [roots/sage#2158]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Installing asset-builder in using the package.json from 8.6.0 fails.
Id assume this is because @mmirus doesnt have a public repository called asset-builder (?)

---

## Bug report
```
12 verbose node v8.11.1
13 verbose npm  v5.6.0
14 error Error while executing:
14 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/mmirus/asset-builder.git
14 error
14 error Host key verification failed.
14 error fatal: Could not read from remote repository.
14 error
14 error Please make sure you have the correct access rights
14 error and the repository exists.
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]

```
**Please provide steps to reproduce, including full log output:**

Download the package.json, run either `npm install` or `npm install asset-builder` 

**Please describe your local environment:**

WordPress version: 5.1

OS: Windows 10

NPM/Node version: 5.6.0/8.11.1

**Comment by mmirus** [comment]
Hm, I thought I removed all references to my fork - maybe I missed something. It should be installing from https://www.npmjs.com/package/asset-builder, which points back to https://github.com/austinpray/asset-builder.

I'll take a closer look at this tomorrow.

**Comment by justlevine** [comment]
@mmirus no need. 
Somehow I accidentally pulled the old package.json, but the one in the main 8.6.0 tag does point to the normal one @ v2.0.0.

I tried checking out the tag again and I got the correct package file, so Im not even sure how to reproduce...

Marking this as closed.
