### ISSUE TITLE
Images added to assets/images while BrowserSync are not copied to dist folder

### ISSUE THREAD

**Issue by mchruszczycki** [roots/sage#2162]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

While adding new images to `assets/images` it causes Browsersync to refresh but images are not copied to `dist` folder.
I'm not able to get them using `@asset` blade directive, until I restart the whole watch process. 

**Expected behavior:** Copy images to `dist` folder immediately after adding them to `assets/images`

**Actual behavior:** Need to restart watch process

## Versions

Sage 9.0.7
macOS Mojave 10.14.3 (18D109)
Node 10.15.3
npm 6.4.1
yarn 1.15.2

## Additional information

Similar to: https://github.com/roots/sage/issues/1794
Found new post on discourse here: https://discourse.roots.io/t/webpack-watch-images-in-assets-images-not-copied-to-dist/8487/4

**Comment by Log1x** [comment]
This will be addressed in Sage 10 with the switch to Mix.
