### ISSUE TITLE
Sage is not compatible with PHP 7.3

### ISSUE THREAD

**Issue by williamscotholmes** [roots/sage#2164]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Sage is not compatible with PHP 7.3.

As seen here:

https://discourse.roots.io/t/error-on-installing-sage-with-composer-on-mac/14951

## Steps to reproduce

1. install php 7.3 + WordPress + Sage theme
2. try and run composer install
3. Error:                                                                                            
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  

**Expected behavior:** the install works

**Actual behavior:** See error message

**Reproduces how often:** 100%

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mmirus** [comment]
I'm unable to reproduce this with PHP 7.3.2 in WSL.

What version of WordPress are you installing? I haven't seen this error related to Sage, but I've encountered it with either WP core or a plugin, can't remember which.

Could you share the full output in case there's anything useful in it? Pretty sure there are no `switch` statements in Sage itself, which means it can't be the direct origin of this error.

**Comment by codepuncher** [comment]
You're getting this error because you're running an outdated version of Composer.
Source: https://github.com/composer/composer/issues/7783

**Comment by williamscotholmes** [comment]
Thanks, that was indeed the case, the fix was to install composer again https://getcomposer.org/download/ and then make the new working version available globally: sudo mv composer.phar /usr/local/bin/composer

**Comment by garrettw** [comment]
In the future you could probably just do `sudo composer self-update`.
