### ISSUE TITLE
#hidden-source-map not working for JS

### ISSUE THREAD

**Issue by tillkruss** [roots/sage#2165]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When using `#hidden-source-map` instead of `#source-map`, only the source map for Sass files is produced, but not for JavaScript files.

## Steps to reproduce

Open `webpack.config.js`.

Change `devtool: (config.enabled.sourceMaps ? '#source-map' : undefined)` to `devtool: (config.enabled.sourceMaps ? '#source-map' : '#hidden-source-map')`

Rung `npm run build:production`

**Expected behavior:** See source maps for .js files.

**Actual behavior:** Only seeing source maps for .css files.

**Reproduces how often:** 100%

## Versions

macOS 10.14.4 and Sage 9.0.9

**Comment by tillkruss** [comment]
In fact, even using setting `sourceMaps: true`, I still don't get source maps for JavaScript when running `npm run build:production`.

**Comment by tillkruss** [comment]
Adding `sourceMap: true` in `webpack.config.optimize.js` fixes it:

```js
new UglifyJsPlugin({
  sourceMap: config.enabled.sourceMaps,
  uglifyOptions: {
    ecma: 5,
    compress: {
      warnings: true,
      drop_console: true,
    },
  },
}),
```

Should this be a PR?

**Comment by Log1x** [comment]
Thanks for this solution– but Sage 9 will not be receiving any updates as Sage 10 nears release.
