### ISSUE TITLE
Using unsupported (EOL) BrowserSync webpack plugin

### ISSUE THREAD

**Issue by mallardduck** [roots/sage#2169]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The current webpack plugin being for browsersync is no longer supported by its developer and has been archived on GitHub.

See here: https://github.com/QWp6t/browsersync-webpack-plugin

If using an unsupported project isn't enough reason to consider a change there are some lacking features. For instance the BrowserSync package supports a callback as the second value of the `init()` method. The current package doesn't allow implementing that though and being unsupported/EOL there's no change of it.

## Steps to reproduce

1. Look in the package.json
2. Review the repo: https://github.com/QWp6t/browsersync-webpack-plugin

**Expected behavior:** The project should use packages/tools that are supported and current.

**Actual behavior:** The project is using a package that is no longer supported.

**Reproduces how often:** Every day since July 18, 2017 (officially abandoned Nov 12, 2018)

## Versions

N/A

## Additional information

There are a handful of ways this could be improved. Maybe roots could fork the package to add the missing functionality and keep dependencies updated. Or maybe there is another package that's more actively updated to switch to.

**Comment by knowler** [comment]
That plugin was made by @QWp6t who is a lead developer for Sage, so in a sense it's already a first-party package. I believe it was archived because he's begun to focus on [Sage 10](https://github.com/roots/sage/tree/10.0.0-dev) instead which has a different solution for Browsersync.

**Comment by mallardduck** [comment]
Oh, I wasn't aware of that - any of it really. Sounds more than reasonable enough!
With an effort being placed on Sage 10 and that accounting for this 'issue' I think this can be marked resolved. Unless you wanted to keep it around for transparency and close it when Sage 10 is released.

Either way seems good to me with this new info in mind.
