### ISSUE TITLE
Move the 'cleanup /dist directory' process to 'right after compilation finishes'

### ISSUE THREAD

**Issue by jofrysutanto** [roots/sage#2181]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

For people running `yarn build` and/or `yarn build:production` as part of their deployment script, this prevents missing assets while assets are being bundled.

## Motivation

At the moment we are seeing (taking example of our current deployment pipeline):
- We git push our code to our staging/production
- Our deployment script run `yarn build:production` # or `yarn build`
- `/dist` directory is cleaned
- During the compilation process visitors will encounter missing assets
- Asset bundling finishes,
- New `dist/` directory generated 
- Business as usual

proposed sequence:
- We git push our code to our staging/production
- Our deployment script run `yarn build:production` # or `yarn build`
- Asset bundling finishes,
- `/dist` directory is cleaned
- ~During the compilation process visitors will encounter missing assets~ Can be avoided
- New `dist/` directory generated 
- Business as usual

We are not entirely sure if this is intentionally done due to certain limitation of the Clean plugin, but this change would certainly be beneficial for people like us who couldn't setup zero-downtime deployment.

**Comment by Log1x** [comment]
It's unlikely that any changes will be made to Sage 9 as Sage 10 is nearing a beta release of which solves 98% of the open issues right now.

**Comment by jofrysutanto** [comment]
Fair enough, guess we'll consider switching to laravel mix (by referring to current Sage 10's setup) or sit tight for Sage 10 release.
