### ISSUE TITLE
I can't use url(data-*)

### ISSUE THREAD

**Issue by tillkruss** [roots/sage#2199]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

We can't seem to use `content: url(data-image);` in any way shape or form (variables, unquote, etc).

We always encounter the same error:

```
This relative module was not found:
```

## Steps to reproduce

Add this to any Sass file:

```sass
&::after {
    content: url(attr(data-image));
}
```

**Expected behavior:**

For the CSS loader to not try to lookup the url as a module.

**Actual behavior:**

```
This relative module was not found:

* ./attr(data-image in ./node_modules/cache-loader/dist/cjs.js!./node_modules/css-loader?{"sourceMap":true}!./node_modules/postcss-loader/lib?{"config":{"path":"...","ctx":{...}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"sourceComments":true}!./node_modules/import-glob!./resources/assets/styles/main.scss
```

**Reproduces how often:** 100%

## Versions

Sage 9.0.9

**Comment by Log1x** [comment]
Using `attr()` within `url()` is not possible in the current spec of CSS. It has been proposed as a possible feature [in the future](https://www.w3.org/TR/css-values-3/#attr-notation) but is not possible without JavaScript and is in no way related to Sage.
