### ISSUE TITLE
yarn build production has stopped working globally

### ISSUE THREAD

**Issue by TheYaXxE** [roots/sage#2202]
I'm been working on a project the last few months, but suddenly i can no longer run `yarn build production`. The other day I had no problem, so it seems like it occurred from one day to the other.

This is the error I get:
```
This dependency was not found:

* production in multi ./scripts/main.js ./styles/main.scss production

To install it, you can run: npm install --save production
                    Asset     Size  Chunks                    Chunk Names
          scripts/main.js  1.02 MB       0  [emitted]  [big]  main
    scripts/customizer.js  3.25 kB       1  [emitted]         customizer
          styles/main.css   500 kB       0  [emitted]  [big]  main
      scripts/main.js.map  1.21 MB       0  [emitted]         main
      styles/main.css.map   743 kB       0  [emitted]         main
scripts/customizer.js.map  3.08 kB       1  [emitted]         customizer
     images/logo-temp.png  5.83 kB          [emitted]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've tried to run the npm command as suggested, but that do not work either. I've also tried to reinstall all of the dependencies and create a new clean sage project, but that's all the same: It cannot build to production. `yarn run start` works perfectly.

Anyone knows how to fix this?

**Comment by knowler** [comment]
It’s `yarn build:production` with a colon.
