### ISSUE TITLE
Upgrade node-sass to 4.12.0

### ISSUE THREAD

**Issue by mquellhorst** [roots/sage#2213]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Running yarn in a fresh install results in an error for node-sass.
Upgrade to node-sass 4.12.0 fixes the issue.

**Expected behavior:**

Finish yarn without errors

**Actual behavior:**

Results in error:
`
/Users/username/.node-gyp/12.4.0/include/node/v8.h:2995:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/username/Development/sage/application/wp-content/themes/hartwerk/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/Users/username/Development/sage/application/wp-content/themes/hartwerk/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/username/Development/hartwerk/application/wp-content/themes/sage/node_modules/node-sass
gyp ERR! node -v v12.4.0`

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

## Versions

sage 9.0.9
mac with osx 10.14.5
node v12.4.0

**Comment by retlehs** [comment]
looks like sage 9 still works fine with the latest node LTS (version 10)

we weren’t planning on making more commits to sage 9 but this is probably something that we should work in.. preferably after sage 10 (#2138) gets merged into the master branch (when it gets its first alpha tag)

anyone running into this right now - either update node-sass or use [nvm](https://github.com/nvm-sh/nvm) to install node 8, 9, or 10 to build sage 9 without issues

**Comment by pfalomorblab** [comment]
@retlehs [node 12 is now the LTS](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.14.1) and as mentioned in https://roots.io/sage/docs/theme-installation/ sage support node >=8 - that's false for v12 since this is still an issue.

Please help merge this one https://github.com/roots/sage/pull/2367

**Comment by zarausto** [comment]
> @retlehs [node 12 is now the LTS](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.14.1) and as mentioned in https://roots.io/sage/docs/theme-installation/ sage support node >=8 - that's false for v12 since this is still an issue.
> 
> Please help merge this one #2367

Thank you, took me ages to figure it out.
I'm using NVM now with Node v10.19.0 and everything's working.
