### ISSUE TITLE
Fix Laravel Mix source maps

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2266]
https://github.com/roots/sage/pull/2197/commits/a524006214018cefcefdfdf3d26dab564f9f7681 needs to make it into the 10 dev branch since #2197 won’t be part of the first alpha release

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)

**Comment by knowler** [comment]
Resolved in #2268 👍
