### ISSUE TITLE
theme_file_uri sage hooks interfere with add_editor_style

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2363]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Sage uses a filter hook that strips the filename from result of `add_editor_style(...)` (https://github.com/roots/sage/blob/fd2a94fa1b8fa5b4767b5f0f825ec364564d0efa/resources/functions.php#L82).

The global `$editor_styles` is used with `get_theme_file_path(...)` in the Gutenberg editor (`edit-form-blocks.php`). `get_theme_file_path(...)` searches for files in stylehsheet directory ('./resources' for sage9 theme), it doesn't work with an URL, like `asset_path(...)` returns.
```php
add_editor_style(asset_path('styles/main.css'));
````
will not work with Gutenberg editor.
But also passing the relative path `../dist/styles/main.css` instead of the URL `asset_path(...)` returns, doesn't work because that filter hook in sage will strip the file name `main.css` from it and the `is_file` check fails.

## Steps to reproduce

1. `add_editor_style( asset_path('styles/main.css') );` is already used in `setup.php`
2. Open Gutenberg editor, notice that the main.css styles are not loaded there
3. Debug `asset_path('styles/main.css')` result, notce that it returns an URL.
4. Debug `get_theme_file_path(...)` with what `asset_path('styles/main.css')` returns, notice that it doesn't work with URIs.
5. Debug `get_theme_file_path(...)` with a path relative to sage9 theme root (`./resources`), notice that the filename from result is missing.

**Expected behavior:**
That the example with `add_editor_style` also works with Gutenberg.
That the filter hook doesn't interfere with `get_theme_file_path(...)`.

**Actual behavior:**
Doesn't work with Gutenberg editor.
Inteferes with `get_theme_file_path(...)`.

## Versions
9.0.9

**Comment by tazeverywhere** [comment]
Should be using https://developer.wordpress.org/block-editor/developers/themes/theme-support/#enqueuing-the-editor-style

But adding `add_theme_support( 'editor-styles'); ` dosn't help.

**Comment by strarsis** [comment]
It is possible to use a full URL, apparently the server-side Gutenberg code downloads the theme stylesheet via HTTP(S), see https://github.com/WordPress/gutenberg/issues/19262.

**Comment by sebastianpopp** [comment]
In some scenarios, the server-side download doesn't work (e.g. a local environment with self-signed certs or a password-protected staging environment). This is not a great fix, but it works for now:
```php
$editor_style = ltrim(str_replace(get_theme_file_uri(), '', asset_path('styles/main.css')), '/');
add_filter('theme_file_path', function ($path, $file) use ($editor_style) {
    if ($file === $editor_style) {
        return get_theme_file_path() . '/' . $file;
    }
    return $path;
}, 20, 2);
add_editor_style($editor_style);
```

**Comment by strarsis** [comment]
@sebastianpopp: You may find this workaround interesting that rewrites the enqueued style URLs so e.g. a Docker container can download the files (which happens on server-side) from the HTTP (e.g. nginx) container:
https://github.com/WordPress/gutenberg/issues/19262#issuecomment-568047719
