### ISSUE TITLE
Custom JS loading in admin but not executing

### ISSUE THREAD

**Issue by nbyloff** [roots/sage#2379]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Installed the current 10.0.0-dev branch and tried to add some custom JS on page load but in the most recent alpha version of 10.X, my admin JS code isn't working.

## Steps to reproduce
1. Create a file at `resources/assets/scripts/admin.js`
````
console.log('loaded');

$(document).ready(() => {
   console.log('Hello world');
});

````
2. In `setup.php`, add the following:
````
add_action('admin_enqueue_scripts', function() {
    wp_enqueue_script('demo-admin-js', asset('scripts/admin.js')->uri(), ['jquery']);
}, 100);
````

3. Update `webpack.mix.js` to add a line for our `admin.js`
````
mix.js('resources/assets/scripts/app.js', 'scripts')
   .js('resources/assets/scripts/customizer.js', 'scripts')
   .js('resources/assets/scripts/admin.js', 'scripts')
   .blocks('resources/assets/scripts/editor.js', 'scripts')
   .extract();
````

4. Run `yarn build`

5. Login to WP Admin

**Expected behavior:** [What you expect to happen]
Message print to the console (the actual JS code to execute)

**Actual behavior:** [What actually happens]
Nothing printed; code isn't executed

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

## Versions
10.0.0-alpha.1: TBA

## Additional information

I built a site from the 10.0.0-dev branch about 4 months ago. This exact process works in that version.

**Comment by Log1x** [comment]
It needs the manifest (as well as potentially vendor) enqueued with it like seen on the frontend script enqueue.

**Comment by nbyloff** [comment]
@Log1x Fair enough. I just changed my admin enqueue to this, still doesn't execute. Sorry if I am missing the obvious, but there's been a handful of changes not in the documentation yet. Figured it was a bug since this works in an older version of 10.X.

````
/**
 * Theme admin assets
 */
add_action('admin_enqueue_scripts', function() {
    wp_add_inline_script('sage/vendor', asset('scripts/manifest.js')->contents(), 'before');
	wp_enqueue_script('tkf-admin-js', asset('scripts/admin.js')->uri(), ['jquery']);
}, 0);

````

**Comment by Log1x** [comment]
```
/**
 * Register the admin assets.
 *
 * @return void
 */
add_action('admin_enqueue_scripts', function () {
    wp_enqueue_script('sage/admin.js', asset('scripts/admin.js')->uri(), ['jquery'], null, true);
    wp_add_inline_script('sage/admin.js', asset('scripts/manifest.js')->contents(), 'before');
}, 100);
```

**Comment by nbyloff** [comment]
Hmm. I didn't change the config except to add the admin.js file. Yes it uses extract, here's the entire file:

````
const mix = require('laravel-mix');
            require('laravel-mix-wp-blocks');
            require('laravel-mix-purgecss');
            require('laravel-mix-copy-watched');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Sage application. By default, we are compiling the Sass file
 | for your application, as well as bundling up your JS files.
 |
 */

mix.setPublicPath('./dist')
   .browserSync('www.rootsdemo.test');

mix.sass('resources/assets/styles/app.scss', 'styles')
   .sass('resources/assets/styles/editor.scss', 'styles')
   .purgeCss();

mix.js('resources/assets/scripts/app.js', 'scripts')
   .js('resources/assets/scripts/customizer.js', 'scripts')
   .js('resources/assets/scripts/admin.js', 'scripts')
   .blocks('resources/assets/scripts/editor.js', 'scripts')
   .extract();

mix.copyWatched('resources/assets/images/**', 'dist/images')
   .copyWatched('resources/assets/fonts/**', 'dist/fonts');

mix.autoload({
  jquery: ['$', 'window.jQuery'],
});

mix.options({
  processCssUrls: false,
});

mix.sourceMaps(false, 'source-map')
   .version();

````

**Comment by Log1x** [comment]
You should definitely have a `manifest.js` and `vendor.js` in your `dist/scripts` folder then.

**Comment by nbyloff** [comment]
You're right, they are there. And my admin.js file loads. I can navigate to it in the firefox console and view the contents of the file. However the code doesn't actually execute. I disabled all plugins too, so not sure why this doesn't happen.
