### ISSUE TITLE
Functions.php Problem

### ISSUE THREAD

**Issue by agaertner-zz** [roots/sage#239]
Hi There

I upload the files to folder roots and active the theme in admin area. Right after activitation I get following error:

Fatal error: require_once() [function.require]: Failed opening required '' (include_path='.:/usr/share/php') in /home/httpd/docs/siteramt/wp-content/themes/roots/functions.php on line 5.

same on backend and frontend.

I use the latest wordpress version today.

Any ideas? I head not problems with other themens.

Thanks

Al

**Comment by sirhaffy** [comment]
Yes please, tell us what you did.
