### ISSUE TITLE
Upgrade to version 4.4.1 lts of bootstrap

### ISSUE THREAD

**Issue by zkmark** [roots/sage#2397]
* [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x ] This request isn't a duplicate of an existing request
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

##Versions
9.0.9

## Summary

Will they upgrade to version 4.4.1 lts of bootstrap?
https://blog.getbootstrap.com/2019/07/24/lts-plan/

**Comment by retlehs** [comment]
tracking here: #2466
