### ISSUE TITLE
Consider upgrading node-sass

### ISSUE THREAD

**Issue by eduardoarandah** [roots/sage#2408]
Consider upgrading node-sass to 4.12 because it's not longer compatible with recent node versions. 

## Description

I bumped into this error when building with CircleCI PHP default image (uses node v12)
`yarn` command fails:

![image](https://user-images.githubusercontent.com/4065733/75313921-f4a86e00-5823-11ea-8b6c-132813f0c184.png)

Here's supported versions:
https://www.npmjs.com/package/node-sass

I made the change in package.json and v.12 works fine. 

## Steps to reproduce

```
sudo service docker start
docker pull circleci/php:7.3-node-browsers
docker run -it circleci/php:7.3-node-browsers /bin/bash
git clone git@github.com:roots/sage.git && cd sage
yarn
```

**Comment by w3bdesign** [comment]
https://github.com/roots/sage/pull/2416
