### ISSUE TITLE
node-sass fails with node v12

### ISSUE THREAD

**Issue by eduardoarandah** [roots/sage#2411]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

yarn command fails in node v12

I bumped into this when building with CircleCi )default php image uses v12)

![image](https://user-images.githubusercontent.com/4065733/75374227-797da100-5891-11ea-916f-7fe356845af2.png)

## Steps to reproduce

You can check locally with docker:

```
sudo service docker start
docker pull circleci/php:7.3-node-browsers
docker run -it circleci/php:7.3-node-browsers /bin/bash
git clone git@github.com:roots/sage.git && cd sage
yarn
```

**now change node-sass version in package.json to version 12** and run `yarn` again, it will work

**Expected behavior:** [What you expect to happen]

yarn to install node_modules

**Actual behavior:** [What actually happens]

Error with node-sass

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

## Versions

Docker image: circleci/php:7.3-node-browsers
Node V12
node-sass ~4.9.4

## Additional information

Check this compatibility chart [https://www.npmjs.com/package/node-sass](https://www.npmjs.com/package/node-sass)

**Comment by alonsoJS** [comment]
A quick workaround is:

- Remove `node_modules` folder
- Remove `package-lock.json` or `yarn.lock`
- Remove `node-sass` dependency from `package.json` file
- Run `yarn | yarn install | npm install` in the console
- Run `yarn add node-sass` or `npm install node-sass`

This will make your project work as expected before the fix is submitted.

**Comment by chrish-d** [comment]
@alonsoJS this fixed the problem for me. Is there any scope to get this fixed in the official version? Took a bit of digging before I eventually found this fix.

**Comment by w3bdesign** [comment]
See https://github.com/roots/sage/pull/2416

**Comment by retlehs** [comment]
tracking here: #2466

**Comment by trainoasis** [comment]
> A quick workaround is:
> 
> * Remove `node_modules` folder
> * Remove `package-lock.json` or `yarn.lock`
> * Remove `node-sass` dependency from `package.json` file
> * Run `yarn | yarn install | npm install` in the console
> * Run `yarn add node-sass` or `npm install node-sass`
> 
> This will make your project work as expected before the fix is submitted.

I get 

`Module build failed: Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.`
