### ISSUE TITLE
Found 55 vulnerabilities (28 low, 11 moderate, 16 high)   run `npm audit fix` to fix them, or `npm audit` for details

### ISSUE THREAD

**Issue by w3bdesign** [roots/sage#2423]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

After running npm install I get this:

```
Found 55 vulnerabilities (28 low, 11 moderate, 16 high) run `npm audit fix` to fix them, or `npm audit` for details
```

## Steps to reproduce

1. Create a Sage project
2. npm install
3. npm audit

**Expected behavior:** [What you expect to happen]

I expect no vulnerabilities.

**Actual behavior:** [What actually happens]

See above.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### 9.0.9: February 13th, 2019
* Update to Bootstrap 4.3.1 ([#2153](https://github.com/roots/sage/pull/2153))

**Comment by retlehs** [comment]
tracking here: #2466
