### ISSUE TITLE
[10.0.0-dev] Assets aren't versioned

### ISSUE THREAD

**Issue by hybridvision** [roots/sage#2454]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Hello Roots team!

I've been using Sage 10 for a few months now on quite a large project and as it nears completion, I've noticed that assets don't seem to be versioned even though `mix.version()` is on and I am seeing the hashed query strings in the generated `dist/mix-manifest.json` file.

Unless I'm missing something obvious, I assume files should be versioned when using the `Roots\asset()` helper function?

## Steps to reproduce

1. Reference an asset using the helper function (eg. `asset('styles/app.css')->uri()` or just `asset('styles/app.css')`
2. Check to see output from this function - it should contain the versioned querystring (eg. `styles/app.css?id=d797e3949596db483406`)

**Expected behavior:** I expect the hashed querystring ID to be present.

**Actual behavior:** No querystring is appended to the asset URI.

**Reproduces how often:** This happens all the time, whether in development or production mode (`yarn start` / `yarn build` / `yarn build:production`)

## Versions

* Mac OS 10.14.6
* PHP 7.3.13
* Node v13.12.0
* Sage 10.0.0-alpha.1

## Additional information

I know that Sage 10 is still in alpha and I have a modified version that uses Stylus + Tailwind CSS + PurgeCSS but I've been pretty careful with my changes and updates so I don't think anything I've done has affected the versioning.

Any pointers to things I can check or test would be appreciated :)

**Comment by Log1x** [comment]
Is your `manifest` in `assets.php` set to use `mix-manifest.json`?

**Comment by hybridvision** [comment]
Ah, that was it! So simple... Thank you Brandon!

I was missing this update https://github.com/roots/sage/commit/41e4f6d2972a8e984d00b9e910f97384e05d51c5 and it looks like there are a few others that I will need to merge in later. It's the price of using an alpha release but so far Sage 10 has been really nice to use 👍
