### ISSUE TITLE
https://roots-example-project.com/ has an invalid SSL certificate

### ISSUE THREAD

**Issue by Joshfindit** [roots/sage#2461]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Firefox refuses to browse to the example site due to the way it's SSL is configured

 
## Steps to reproduce

1. Browse to https://roots-example-project.com/ from FireFox

**Expected behavior:** [What you expect to happen]
- To be able to browse to the site
- To be able to remove the `s` and browse to the un-secure site

**Actual behavior:** [What actually happens]
```
Firefox Developer Edition detected a potential security threat and did not continue to roots-example-project.com because this website requires a secure connection.

What can you do about it?

roots-example-project.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox Developer Edition can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it.

If you are on a corporate network or using anti-virus software, you can reach out to the support teams for assistance. You can also notify the website’s administrator about the problem.
```
**Reproduces how often:** 100%

## Versions

N/A

## Additional information

LetsEncrypt should be a good solution to this as opposed to "Fake LE Root X1"

**Comment by retlehs** [comment]
oops, this is good now :)
