### ISSUE TITLE
Template modifications are not injected on reload

### ISSUE THREAD

**Issue by AmphiBee** [roots/sage#2470]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Template modifications are not taken into account with laravel mix in watch mode.

## Steps to reproduce

1. I installed Sage 10.
2. I launch development mode with `yarn start`.
3. I modify one of the files in resources /views/.
4. The page is reloaded but the modifications made in the html code do not go back

**Expected behavior:** Template modification should be injected at page reload

**Actual behavior:** No template modification added.

**Reproduces how often:** 100%

## Versions

Latest sage 10-dev-master

## Additional information

**Environment:** lando (docker) with wordpress recipe (php 7.3, nginx, mariadb). Bedrock install.
The page reload is done if I add a get parameter in the url (eg localhost:8080?v=2)
I tried various configuration (watch: true on browserSync)

**Comment by lhilton** [comment]
@AmphiBee have you found any solution to this error?

**Comment by Log1x** [comment]
This should be fixed on the latest version.

**Comment by zarausto** [comment]
I was having the same scenario. I've mange to **fix it** by realizing that opcache was enabled in my localhost.
So, if you are on a development environment make sure to disable opcache or downsize the time revalidate in revalidate_freq to 0.

Ways to fix it:

1. On .htaccess include this if Apache is configured to to manage php_flag inside .htaccess: php_flag opcache.enable Off
2. You can also disable in php.ini: opcache.enable=0 or opcache.revalidate_freq=0

Hope it helps.
