### ISSUE TITLE
async/await not working

### ISSUE THREAD

**Issue by oxyc** [roots/sage#2474]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Using async/await throws the following error after `npm run build`:

> Uncaught TypeError: Cannot read property 'mark' of undefined

## Steps to reproduce

1. Add the following to `app.js`

    ```js
    async function asyncCall() {
      console.log('foo');
    }
    asyncCall();
    ```

2. Run `npm run build`
3. Open developer tools in the browser and notice nothing is logged and error is thrown.

**Expected behavior:**

`@babel/runtime/regenerator` should get imported by webpack and then used by the babel internals.

If I remove editor.js from the build, the runtime is included in dist/app.js and everything works.

**Actual behavior:** [What actually happens]

`@babel/runtime/regenerator` is not imported correctly.

The runtime is ~included in dist/vendor.js~ and not used in app.js for whatever reason.

**Reproduces how often:** 100%

## Versions

- master
- macOS 10.15.3

## Additional information

This is quite similar to https://github.com/roots/sage/issues/2370 but im not sure why the runtime isnt picked up from vendor. Not well versed in webpack internals

**Comment by oxyc** [comment]
Seems this could be the cause https://github.com/jeffbski/redux-logic/issues/10#issuecomment-382855798 https://stackoverflow.com/questions/39690582/getting-webpack-multi-vendor-error-cannot-resolve-module-babel-runtime#comment66731010_39690582

**Comment by oxyc** [comment]
Okay I tracked it down to https://github.com/WordPress/gutenberg/blob/dd9f4544330be4aa32beb96c13a9ad9268c7e573/packages/dependency-extraction-webpack-plugin/util.js#L65

Adding `wp-polyfill` as a dependency to vendor.js fixes the problem.

I'd rather not enqueue wp-polyfill on the frontend so another fix would be for `laravel-mix-wp-blocks` to override `@wordpress/dependency-extraction-webpack-plugin`.

```js
    return new WordPressDependencyExtraction({
      requestToExternal(request) {
        if (request === '@babel/runtime/regenerator') {
          return null;
        }
      },
    })
```

@kellymears what do you think, should `laravel-mix-wp-blocks` expose the config to laravel mix so sage can configure it downstream, or should it be a flag or a default?

**Comment by Log1x** [comment]
Fixed in laravel-mix-wp-blocks

**Comment by oxyc** [comment]
For future reference if someone lands here. To use async functions you need to disable regenerator when using `mix.block()`:

```js
mix.block('resources/assets/scripts/blocks.js', 'scripts', {
  disableRegenerator: true,
})
```
