### ISSUE TITLE
Options get skipped during theme installation

### ISSUE THREAD

**Issue by wassim** [roots/sage#2482]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

> During theme installation you will have options to update style.css theme headers, select a CSS framework, and configure Browsersync.

The installer automatically exit after the first question. Whether I type Y/n or simply hit enter button.

> Generating optimized autoload files
> Roots\Acorn\ComposerScripts::postAutoloadDump
> Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]?
> exit...

## Steps to reproduce

1. `composer create-project roots/sage theme-name dev-master`
2. answer first question

**Expected behavior:** Get all theme options during installation

**Actual behavior:** Options get skipped except the first one

## Versions

Sage 10

**Comment by network-rail** [comment]
I got exactly the same

**Comment by catgofire** [comment]
@wassim There is currently not an installer for Sage 10 like there was for Sage 9. I hope they add one, as it was a super nice feature, but for now you have to manually edit that stuff yourself. See these topics:

https://discourse.roots.io/t/sage-10-and-tailwind-css/18324
https://discourse.roots.io/t/sage-10-cli-installer-and-settings-up-the-theme/18367

**Comment by knowler** [comment]
Going to close this, because what @catgofire said is true. I _think_ there might be a Sage 10 installer in the works (probably Node based), but I could be wrong.
