### ISSUE TITLE
Blade php shorthand was re-introduced with Sage 10

### ISSUE THREAD

**Issue by dawidurbanski** [roots/sage#2491]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In sage 9 we had php blade shorthand used in many places (`@php(something())`), but at some point after someone correctly pointed out ([here](https://github.com/roots/sage/issues/2012)) this shorthand was deprecated by blade and it was later removed by [this](https://github.com/roots/sage/pull/2042) and [this](https://github.com/roots/sage/pull/2060), in favour of long form (`@php something() @endphp`).

With the following PR the same shorthand we re-introduced in many places:

https://github.com/roots/sage/pull/2122

To be more precise in these files:

https://github.com/roots/sage/pull/2138/files#diff-e09897fbdd2918deee752b67af496219
https://github.com/roots/sage/pull/2138/files#diff-247464e8a323304ef08b46558bf5a2fd
https://github.com/roots/sage/pull/2138/files#diff-8de5e7d2e658d0e8e22455127ff569ee
https://github.com/roots/sage/pull/2138/files#diff-21503203223292a031e9846d62475cac
https://github.com/roots/sage/pull/2138/files#diff-d9a6166239d8c4c0f303cf92c0c84d14
https://github.com/roots/sage/pull/2138/files#diff-fc43d41c4d0653820b99f0692689c9f5
https://github.com/roots/sage/pull/2138/files#diff-858c467c85fc822ba60439c4048bb48a
https://github.com/roots/sage/pull/2138/files#diff-523bdef1518642d82293490b410cd7a8
https://github.com/roots/sage/pull/2138/files#diff-3d83f5734433c59ae117ffd70ecf88fe
https://github.com/roots/sage/pull/2138/files#diff-e6c6583e10bcc9c6232d75a18c415dca
https://github.com/roots/sage/pull/2138/files#diff-ace29c022ecb3da4003716240b6da8fb
https://github.com/roots/sage/pull/2138/files#diff-b537a90068d54375cfcc450b389a4980

Did something change in this shorthand matter from Laravel side that I'm not aware of?

From what I see they don't even mention this syntax at all in the docs any more: https://laravel.com/docs/7.x/blade#php

## Steps to reproduce

1. Just go to the code.

**Expected behavior:** No `@php` shorthand in the codebase

**Actual behavior:** The shorthand is all over the place

**Reproduces how often:** 100%

## Versions

10.0.0-alpha.1

**Comment by QWp6t** [comment]
@Log1x had some reasoning for it but I don't remember what it was. I'll let him explain it.

**Comment by Log1x** [comment]
I explain my reasoning in the second bullet under enhancements on #2171
