### ISSUE TITLE
SCSS Cannot parse selector although it gets parsed

### ISSUE THREAD

**Issue by mortensassi** [roots/sage#2497]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x ] This request isn't a duplicate of an existing issue
* [x ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

You can write padding or margin rules in SCSS like this:

```scss
padding: {
   left: 1rem;
   right: 1rem;
   bottom: 5rem;
}
```

but the webpack `start` task runs it complains with a warning

```
resources/assets/styles/components/_nav.scss
 64:5  ✖  Cannot parse selector   parseError
 64:5  ✖  Cannot parse selector   parseError
```

and when i inspect the browser the padding gets set correctly

## Steps to reproduce

1. Write some SASS like in the example above
2. Save the file
3. Check the console and the browser inspector window

**Expected behavior:** No warning should be printed

**Actual behavior:** A warning gets printed

**Reproduces how often:**  -

## Versions

9.0.9

**Comment by retlehs** [comment]
this is gonna be a #wontfix for sage 9, but if this is actually supported by sass and not-supported in sage 10 please let us know
