### ISSUE TITLE
Sage10 infinite loop with bbPress and inheritance of templates

### ISSUE THREAD

**Issue by trajche** [roots/sage#2506]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

This is a bug with one of the Auttomatic's main plugins bbPress (https://bbpress.org/). When using Sage10 the site pages for the bbPress forums end up in an infinite loop.

I believe this is an issue with other plugins that I have yet to test. If it's not planned to support the default way these plugins have functioned so far, what would be the steps to be able to inherit their templates while using Sage10?

## Steps to reproduce

1. Install Sage10
2. Install bbPress
3. Craete a 'test' forum
4. Click 'view' for the test forum

**Expected behavior:**

bbPress templates should render the bbPress content or a white page should show up when overwriting the bbPress template in `resources/bbpress/bbpress.php`.

**Actual behavior:**

Infinite loop on the page until PHP times out.

**Reproduces how often:**

100%

## Versions

- Sage 10.0.0-beta.1
- WordPress 5.4.2
- Nginx via Valet
- macOS Mojave

**Comment by retlehs** [comment]
similar to woocommerce (see `sage-woocommerce` package examples: https://github.com/ptrckvzn/sage-woocommerce/tree/sage-10, https://github.com/ouun/stage-woocommerce), bbpress support in sage 10 will need to be a separate extension

**Comment by Log1x** [comment]
Please see the above packages and/or open a thread on Discourse. This is not something that can be fixed in Sage core right now.
