### ISSUE TITLE
Sage 10 with() $data in View Composers error

### ISSUE THREAD

**Issue by gpsugy** [roots/sage#2510]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Sage 10 is in development, but based on the docs, https://roots.io/working-with-composers-in-sage-10/, a View Composer seems like it should be able to use the `with()` method with the `$data` variable without issue. Whenever a View Composer is created, however, where the `with()` declaration of the Composer contains the variables `$data` and/or `$view` (i.e. `public function with($data, $view)`), the following error occurs:

`Too few arguments to function App\View\Composers\MyComposer::with(), 0 passed in /Users/[myuser]/[my-project]/src/[project]/web/app/themes/[folder]/vendor/roots/acorn/src/Acorn/View/Composer.php on line 70 and exactly 2 expected (View: /Users/[myuser]/[my-project]/src/[project]/web/app/themes/[folder]/resources/views/example.blade.php) (View: /Users/[myuser]/[my-project]/src/[project]/web/app/themes/[folder]/resources/views/example.blade.php) (View: /Users/[myuser]/[my-project]/src/[project]/web/app/themes/[folder]/resources/views/example.blade.php)
`
A fix seems to have been made in Sep 2019 after Acorn had a refactor, but this seems to be a newer issue.

## Steps to reproduce

1. Create a Composer file as taken from the examples in the docs linked above.
2. In the `with()` declaration, add the parameters `$data` and `$view`
3. The error described above occurs when loading the page

**Expected behavior:** No error

**Actual behavior:** The code breaks, and the error described above occurs

**Reproduces how often:** 100%

## Versions

Sage: 10.0.0-alpha.1
"php": "^7.2.5"
"roots/acorn": "^1.0.1"

OS: macOS 10.15.5

**Comment by gpsugy** [comment]
Was not aware that the checklist for the contributing guidelines needed to be included in the post, but I did indeed go through those steps. Requesting to re-open this ticket.

**Comment by Log1x** [comment]
You no longer have to pass `$data` or `$view` – they are now properties (`$this->data` and `$this->view`)
