### ISSUE TITLE
Sage 10 - Vendor.js 404 error

### ISSUE THREAD

**Issue by smeedijzer-internet** [roots/sage#2513]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Removing Bootstrap results in an 404 error that vendor.js can not be found. Vendor.js is not build in production.

## Steps to reproduce

1. Remove: import 'bootstrap'; from app.js
2. yarn build:production

**Expected behavior:** [What you expect to happen]

Maybe conditional load vendor.js?

**Actual behavior:** [What actually happens]

The wp_enqueue_scripts action in app/setup.php still has it as a dependency and results in a 404.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

## Versions

master
macOS 10.15.5

## Additional information

None

**Comment by Log1x** [comment]
vendor.js is generated by `.extract()` in the mix manifest. If you were going to remove it, you would more or less take it upon yourself to then remove it from `after_setup_theme`

**Comment by strarsis** [comment]
Hm, when no vendor/libraries are used in the theme scripts, Laravel mix doesn't generate a `vendor.js` at all.

**Comment by frankstallone** [comment]
Yep, this was happenening to me too before I started writing any JS for this most recent project. When `app.js` is empty `vender.js` 404s.

**Comment by strarsis** [comment]
And just commenting out/removing the vendor scripts enqueue will result in the main app script not running as it relies on the manifest json that needs vendor as dependency. So when commenting it out, be sure to comment it out as dependency, too.

**Comment by Dioniggio** [comment]
> 
> 
> Yep, this was happenening to me too before I started writing any JS for this most recent project. When `app.js` is empty `vender.js` 404s.

Same issue here!

**Comment by tirins008** [comment]
Same here, just to test it out I imported Alpinejs in app.js and then the build generated vendor.js

**Comment by eduardoarandah** [comment]
I'd like to draw attention to this issue. 

Wordpress 5.8 makes heavy use of JS in the backend. 

When vendor doesn't exist, wordpress responds with a redirection. 

![image](https://user-images.githubusercontent.com/4065733/127600021-550d519a-8c5e-470b-98ea-f64f94d40fc9.png)

then javascript stops execution and page displays blank 

check: /wp-admin/widgets.php

![image](https://user-images.githubusercontent.com/4065733/127600131-628467e6-cb43-4871-a178-d83038a4db82.png)

## Temporary solution

**webpack.mix.js**

remove `.extract()`

## setup.php

change this:

```
    wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), ['jquery'], null, true);
    wp_enqueue_script('sage/app.js', asset('scripts/app.js')->uri(), ['sage/vendor.js'], null, true);
    wp_add_inline_script('sage/vendor.js', asset('scripts/manifest.js')->contents(), 'before');

```

to this:

```
wp_enqueue_script('sage/app.js', asset('scripts/app.js')->uri(), ['jquery'], null, true);

```

change this:

```
    if ($manifest = asset('scripts/manifest.asset.php')->load()) {
        wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), ...array_values($manifest));
        wp_enqueue_script('sage/editor.js', asset('scripts/editor.js')->uri(), ['sage/vendor.js'], null, true);
        wp_add_inline_script('sage/vendor.js', asset('scripts/manifest.js')->contents(), 'before');
    }

```

to this:

``` 
        wp_enqueue_script('sage/editor.js', asset('scripts/editor.js')->uri(), [], null, true);

```

* I'm not sure what manifest.asset.php does, please edit my code if it's wrong
