### ISSUE TITLE
Replace `override` with `with` in `Post` View Composer

### ISSUE THREAD

**Issue by Emanuel-23** [roots/sage#2524]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Replace `override` with `with` in `Post` View Composer.

Shouldn't the default `Post` View Composer just come with a `with` method instead of a `override` to be less restrictive see:

https://github.com/roots/sage/blob/24ac51d510acf81a716e5fdd0cd0ae0b0256bdd3/app/View/Composers/Post.php#L25?

Especially because the View Composer uses the wildcard in the partials `partials.content-*` in
https://github.com/roots/sage/blob/24ac51d510acf81a716e5fdd0cd0ae0b0256bdd3/app/View/Composers/Post.php#L17
and therefore does not allow to override the i.e. title that has been defined in Post at all.
 
If you want to set the title of a partial template, say `partial.content-foo` by using a custom View Composer say `Foo` which implements the `override` method, the overriding will not have any effect.

This is because the override has already been set in `Post`

## Steps to reproduce

1. Create a View Composer with the name of your choice
2. Create a `override` method in your custom View Composer that returns a custom `title` in a template that is located in `partials/` and starts with `content-`  
3. Check if the title has been overridden in frontend

**Expected behavior:**
The title should be overridden, and should reflect the output coming from your custom View Composer (see 1.) )

**Actual behavior:**
The title comes from the `Post` View Composer.

## Versions
Sage `10.0.0-alpha.1`

## Additional information
Not really a "bug", i would say. But confusing though...

**Comment by Emanuel-23** [comment]
Any update on this?

**Comment by Log1x** [comment]
This was primarily to showcase that `override` exists and to force that each individual `content-` partial is calling a new instance of `$title`.

I'd expect to see Composer's get refactored a bit to be more in line with [Blade Composers](https://laravel.com/docs/8.x/blade#components) in Acorn soon. It's been on my mind.
