### ISSUE TITLE
[Sage 10] Path not defined

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2539]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Linter complains that `path` not defined / required in `webpack.mix.js` (https://github.com/roots/sage/blob/master/webpack.mix.js#L25).

## Steps to reproduce

1. Install sage 10 (from dev master) using `composer`
2. Open the `webpack.mix.js` file of the newly created theme in a linter-supporting editor, e.g. Atom.
3. Notice the linter error that `path` is not defined (`no-undef`).

**Expected behavior:**
No linter notices, warnings or errors should be emitted for a newly created sage 10 theme.

**Actual behavior:**
Linter error that `path` is not defined.

**Reproduces how often:**
It always reproduced when creating a new sage 10 from dev master.

## Versions
`10.0.0-beta.1: TBA`

**Comment by gsusI** [comment]
+1
