### ISSUE TITLE
Sage 9.x incompatible with Composer 2

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2568]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Sage 9.x is incompatible with Composer 2 (can't be created/installed).

## Steps to reproduce

1. Ensure that composer 2.x is used.
2. `$ composer create-project roots/sage sage`
````
Creating a "roots/sage" project at "./sage"
Installing roots/sage (9.0.9)
  - Downloading roots/sage (9.0.9)
  - Installing roots/sage (9.0.9): Extracting archive
Created project in /home/build/src/sage
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - composer/installers is locked to version v1.6.0 and an update of this package was not requested.
    - composer/installers v1.6.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - composer/installers v1.6.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - soberwp/controller 2.1.1 requires composer/installers ^1.0 -> satisfiable by composer/installers[v1.6.0].
    - soberwp/controller is locked to version 2.1.1 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
````

**Expected behavior:**
Sage 9.x project is created/installed with composer 2.x.

**Actual behavior:**
Composer 2 creation/installation of Sage 9.x project fails.

**Reproduces how often:**
Always.

## Versions
Sage 9.0.9 (latest 9.x release).

## Additional information
`composer/installers` has to be updated to a recent enough version so it supports Composer 2.x.

**Comment by strarsis** [comment]
PR ready: https://github.com/roots/sage/pull/2569

**Comment by strarsis** [comment]
@retlehs, @swalkinshaw: Please merge so `composer create-project` works correctly with sage 9.x (and composer 2).

**Comment by retlehs** [comment]
@strarsis we'll need to tag another version in order for this to work, which means #2466 should probably be handled at the same time

do you feel like making a PR for that issue as well? 😁

**Comment by strarsis** [comment]
@retlehs: Alright: https://github.com/roots/sage/pull/2572

**Comment by retlehs** [comment]
merged and tagged, thank you @strarsis 🙏
