### ISSUE TITLE
Sage 10 incompatible @php directive

### ISSUE THREAD

**Issue by eduardoarandah** [roots/sage#2574]
* [ x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x ] This request isn't a duplicate of an existing issue
* [ x ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Tried to use `@php` directive like in sage9 but didn't work

## Steps to reproduce

Example: 

```
<div class="page-navigation">
  @php
  if(function_exists('wp_pagenavi')){
    wp_pagenavi();
  }
  else{
    the_posts_navigation();
  }
  @endphp
</div>

```

**Expected behavior:** [What you expect to happen]

Display pagination from plugin `WP-PageNavi`

**Actual behavior:** [What actually happens]

Error

**Reproduces how often:** [What percentage of the time does it reproduce?]

Error on regular pages like `index.blade.php`
it doesn't throw error when doing

```
echo \Roots\view('the_view')->render();
```

## Versions

Sage 10, mac os catalina

## Additional information

I see there's a change of syntax of `@php` blade directive

https://github.com/roots/sage/blob/36937b4ceafb9b3c5b705be2ad6f75bc77a9efce/resources/views/index.blade.php#L14

Instead of using

```
@php
echo "ok";
@endphp
```

it's now 

```
@php(some_function())
```

Found it when migrating code from `sage9` templates.

What's the reasoning behind this? 
saving one line of code doesn't seem like a great gain from the cost of being incompatible with native laravel blade, sage9 and tools like blade-formatter

https://github.com/shufo/blade-formatter

May I suggest a new directive that doesn't erase `@php` directive?
like `@exec()`

**Comment by foltra** [comment]
Both the inline and multi-line forms are working for me. You didn't provide any error output so it's hard to say, might be on the plugin end. You could be using `@if` directive or  rendering the plugin output from the controller. Also, quoting blade 7.x docs:
```
While Blade provides this feature, using it frequently may be a signal that you have too much logic embedded within your template.
```

Might be the case that you cannot have both in the same template https://github.com/laravel/framework/issues/20994#issuecomment-658507263

**Comment by dawidurbanski** [comment]
This will come up more often because of issues when using both inline `@php(xxx)` and `@php xxx @endphp` in the same template.

I mentioned it already here: https://github.com/roots/sage/issues/2491 so it looks like this approach done on purpose.

**Comment by Log1x** [comment]
This was intentional (you can blame me). It may or may not get changed in a near-future version – I've brought it up for discussion to the team a few times.

**Comment by eduardoarandah** [comment]
@Log1x Please consider supporting original blade structure, it wouldn't make sense becoming incompatible with blade formatters. 

Also, I suppose there will be constant repo issues asking why their laravel code doesn't work

**Comment by dawidurbanski** [comment]
@eduardoarandah 

The original directive is supported. You can use:

```
@php
    wp_pagenavi()
@endphp
```

and it will work fine!

You may only encounter problems when you use both versions of these directives **in the same template file**. For example:

```
@php(some_function())

// and somewhere later

@php
    some_other_function() // this may brake
@endphp
```

If you want to avoid it, just stick to only one of these per one file.

Your original example could be converted to:

```
@if(function_exists('wp_pagenavi'))
    @php(wp_pagenavi())
@else
    @php(the_posts_navigation())
@endif
```

or you could replace other `@php(function())` occurrences to `@php function() @endphp` (in the same template) so you can stick with your original code.

**Comment by Log1x** [comment]
Semi-related you could just do [`{!! wp_pagenavi(['echo' => false]) !!}`](https://github.com/lesterchan/wp-pagenavi/blob/master/core.php#L31)

**Comment by MWDelaney** [comment]
You could also do the logic for `function_exists()` in a View Composer, something like this:

**app/View/Composers/App.php**
```php
...
public function pageNavi() {
  // Initialize the return variable so there are no surprises
  $return = false;

  // Check if the wp_pagenavi function exists
  if (function_exists('wp_pagenavi')) {
    // Set the return value of the function exists
    $return = wp_pagenavi(['echo' => false]);
  }

  // Always return
  return $return;
}
...
```

And then in your template, just do this:
```php
...
{!! $pageNavi !!}
...
```

This gets all the logic out of your templates and just lets you work with the output of that logic.
