### ISSUE TITLE
Sage 9.0.10 - postcss.config.js not working

### ISSUE THREAD

**Issue by wouter-85** [roots/sage#2585]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

After the latest release postcss.config.js gives an error, this

`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
`
## Steps to reproduce

1. Installed a fresh copy and and use yarn start && yarn build
2. Installed a fresh copy of version 9.0.9, this works like expected

**Expected behavior:** 
Everything for building the website works like a charm

**Actual behavior:**
The template building does not work like it should work, for example I'm unable to load custom fonts in version 9.0.10 because postcss.config.js doesn't work during development

**Reproduces how often:**
This issue occured since the latest version 9.0.10

## Versions

9.0.10

**Comment by idev-hub** [comment]
No solution yet?

**Comment by retlehs** [comment]
sage 9 is not in active development and the latest release has some issues in certain scenarios  

you can use the previous sage 9 release, or we are happy to pay for anyone's time to submit PRs for the sage 9.x branch

**Comment by salty-walty** [comment]
To anyone else hung up on this, I found a workaround. My version of this issue was not font related, but rather image related. I was trying to use a background image in my css and stumbled across the same errors. 

In looking for a solution, others were suggesting just rolling back to 9.0.9 which certainly worked. That said, I thought it would be nice to just roll back the packages that were at the root of this issue for me rather than rolling back a full version. With that, I narrowed this issue down to a few specific dev dependencies and changed them to the following versions:

`
    "postcss-loader": "~2.1.0", 
    "postcss-safe-parser": "~3.0",  
    "resolve-url-loader": "~2.3.1", 
    "url-loader": "^0.6.2",
`

After updating my package.json to have those older dev dependencies from 9.0.9, deleting my node_modules, and running a: 

`yarn && yarn start`

my version of this issue worked itself out. Hope that helps anyone else who's currently down this rabbit hole!

**Comment by strarsis** [comment]
An update to webpack 5 for sage 9.x, WIP: https://github.com/strarsis/sage/tree/webpack5
This also fixes other issues like [Object] when an image is inlined in the styles, etc.
Changes are surprisingly small for a webpack update between two major versions.

**Comment by Jacksoor** [comment]
I also had to change:
`"file-loader": "^1.1.6"`
Maybe the fix detailed [here](https://github.com/roots/sage/pull/2572#issuecomment-725446999) is enough.

**Comment by strarsis** [comment]
@Jacksoor: You may be interested in trying out this PR: https://github.com/strarsis/sage/tree/webpack5

**Comment by Jacksoor** [comment]
@strarsis Yes thank you, I managed to get your PR working by replacing my `package.json`, `yarn.lock` and all scripts in `resources/assets/build`.
BrowserSync seems more stable and StyleLint is now also working now where before I had to disable it.
Really hope Sage 10 is comming soon or they merge your PR.

**Comment by dock70** [comment]
Thank you @strarsis! I have yours PR working but I can't manage to set:

`background-image: url("..images/my-image.svg");`

Always getting:

`Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
 ModuleBuildError: Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
 Error: Can't resolve './images/my-image.svg' ´
 
 Any help?

**Comment by strarsis** [comment]
@dock70: You have to add one more `../` as the paths are now relative to the style files (which is actually more correct).

**Comment by dock70** [comment]
Thank you!! I've tried before but it compiles like:
`background-image: url(http://idddefence-mvp.test/[object Object]`

**Comment by strarsis** [comment]
@dock70: Many updates have been added to sage 9, including the sage-installer, so you can now install the sage 9 theme as usual:
https://discourse.roots.io/t/sage-9-2-please-test/20067?u=strarsis
This also fixes the `[object Object]` issue.

**Comment by greghollowell** [comment]
@salty-walty 
Downgrading dependancies did the trick for me. Nice one— thanks!

**Comment by strarsis** [comment]
@greghollowell: https://discourse.roots.io/t/sage-9-2-please-test/20067/9

**Comment by chatelp** [comment]
Thanks for your PR @strarsis. It solved most of my issues, like the other commenters. But I do get a new issue related to the upgrade from extract-text-webpack-plugin to mini-css-extract-plugin. More specifically, I get a module build error when using mini-css-extract-plugin with postcss-loader for .scss file. I posted bug reports to both projects, but I wanted to know if you had any idea where it might come from.

If I remove postcss-loader from the loaders list in the module, then it builds correctly.

```
ERROR in ./styles/main.scss
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/postcss-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss/lib/lazy-result.js:484:33)
    at LazyResult.runAsync (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss/lib/lazy-result.js:372:30)
    at async Object.loader (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss-loader/dist/index.js:87:14)
    at processResult (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/webpack/lib/NormalModule.js:676:19)
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/webpack/lib/NormalModule.js:778:5
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/vagrant/modulor-theme/public/themes/modulor/node_modules/postcss-loader/dist/index.js:96:7)
```

**Comment by strarsis** [comment]
@chatelp: What framework have you selected for Sage 9, Bootstrap/None? And what node version are you using, LTS/*?

**Comment by artshostak** [comment]
Strange that Sage 9.0.10 is currently the default included when running `composer create-project roots/sage your-theme-name` and is riddled with this many issues.

9.0.10 has Composer 2 support which is what I need to proceed after bringing up Trellis/Bedrock to the latest version. Sage 10 doesn't have routes and bundled Tailwind by default, which makes me avoid it for now. Finally got 9.0.10 running fine after @Jacksoor and @salty-walty's suggestions of selectively downgrading the packages:

```
"file-loader": "^1.1.6"
"postcss-loader": "~2.1.0",
"postcss-safe-parser": "~3.0",
"resolve-url-loader": "~2.3.1",
"url-loader": "^0.6.2",
```

Seems like there's no stable go-to version of Sage out there at the moment.

**Comment by alwaysblank** [comment]
> doesn't have routes

If you want the routes functionality, the same effect is straightforward to achieve manually: https://discourse.roots.io/t/sage-10-and-js-routing/19020/2?u=alwaysblank

> bundled Tailwind by default

There are instructions for removing Tailwind here: https://discourse.roots.io/t/sage-10-remove-completely-tailwindcss-and-jquery/20613

**Comment by artshostak** [comment]
Right @alwaysblank, I understand and have been doing that — but it does seem like a departure from days of (1) being to select your framework (or "none" as an option) and (2) getting into the habit of breaking out from a single javascript file into routes, especially if integrating something like Barba.

**Comment by QWp6t** [comment]
@artshostak We have a separate package for the js dom router.

https://www.npmjs.com/package/js-dom-router
https://github.com/roots/js-dom-router

I haven't messed with this code in 2 years so I don't remember much about its api, but you can probably review the tests to understand it.

https://github.com/roots/js-dom-router/blob/master/src/index.spec.ts

i believe you would do something like this...

```js
import { router } from 'js-dom-router'

router
  .on('about', () => /* do a thing on your about page */)
  .on('home', () => /* do a thing on your home page */)
  .ready() // <-- this means it will fire when the dom is ready
```

i also added a `.watch()` method to watch for new classes on the target element.

If you have questions about it, feel free to ask in roots discourse.

**Comment by pcampina** [comment]
Thank's man :P

> To anyone else hung up on this, I found a workaround. My version of this issue was not font related, but rather image related. I was trying to use a background image in my css and stumbled across the same errors.
> 
> In looking for a solution, others were suggesting just rolling back to 9.0.9 which certainly worked. That said, I thought it would be nice to just roll back the packages that were at the root of this issue for me rather than rolling back a full version. With that, I narrowed this issue down to a few specific dev dependencies and changed them to the following versions:
> 
> `"postcss-loader": "~2.1.0", `
> `"postcss-safe-parser": "~3.0", `
> ` "resolve-url-loader": "~2.3.1", `
> ` "url-loader": "^0.6.2",`
> 
> After updating my package.json to have those older dev dependencies from 9.0.9, deleting my node_modules, and running a:
> 
> `yarn && yarn start`
> 
> my version of this issue worked itself out. Hope that helps anyone else who's currently down this rabbit hole!
