### ISSUE TITLE
DATEBASE_URL isnt getting "masked" when sage throwing a debug message

### ISSUE THREAD

**Issue by alexbogias** [roots/sage#2601]
I tried Sage 10 and the new DATEBASE_URL .env variable. When a debug message is echoed I noticed that "DATABASE_URL" is printed without a "mask" (*) like the AUTH_KEYS. Would be better to hide username/password from printing to the world?

![image](https://user-images.githubusercontent.com/1313467/103081039-c6302680-45df-11eb-89b6-21803786b429.png)

**Comment by QWp6t** [comment]
@Log1x I think this is all in acorn, right?

**Comment by Log1x** [comment]
> @Log1x I think this is all in acorn, right?

https://github.com/roots/acorn/blob/master/src/Acorn/Exceptions/WhoopsHandler.php#L14-L31

**Comment by QWp6t** [comment]
This will be added to the next version of Acorn. Thanks for reporting it. Happy holidays!
