### ISSUE TITLE
Modern Events Calendar template rendered after </html> tag

### ISSUE THREAD

**Issue by gsusI** [roots/sage#2624]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x ] This request isn't a duplicate of an existing issue
* [x ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Viewing an event created with Modern Events Calendar Pro renders the_content after the `</html>` tag.

## Steps to reproduce

1. Enable Modern Events Calendar in a site using a sage 9 based theme
2. Create event
3. View event page

**Expected behavior:**

```
--------------------
¦    Sage header   ¦
--------------------
¦    MEC Content   ¦
--------------------
¦    Sage footer   ¦
--------------------
```

**Actual behavior:**

```
--------------------
¦    Sage header   ¦
--------------------
¦    Sage footer   ¦
¦     </html>      ¦
--------------------
¦    MEC Content   ¦
--------------------
```

**Reproduces how often:**

Consistently

## Versions

9.0.10: November 9th, 2020

## Additional information

In my theme I have created a `header.php` and `footer.php` respecting the golden rule (_silence is gold_), which I had to do to make it compatible with the Elementor plugin.

I've tried overriding the _single-mec-events.php_ and I guess I could make it work by overriding each template used by the plugin. However, this feels like a bad practice, given that I'm not planning to change anything within those templates and I want them to update along with the plugin.

Theme template:

```php
<?php
/** no direct access **/
defined('MECEXEC') or die();

/**
 * The Template for displaying all single events
 * 
 * @author Webnus <info@webnus.biz>
 * @package MEC/Templates
 * @version 1.0.0
 */
get_header('mec'); ?>

    <section id="<?php echo apply_filters('mec_single_page_html_id', 'main-content'); ?>" class="<?php echo apply_filters('mec_single_page_html_class', 'mec-container'); ?>">

        <?php do_action('mec_before_main_content'); ?>

        <?php while(have_posts()): the_post(); ?>

            <?php $MEC = MEC::instance(); echo $MEC->single(); ?>

        <?php endwhile; // end of the loop. ?>
        <?php comments_template(); ?>
    </section>

    <?php do_action('mec_after_main_content'); ?>

<?php get_footer('mec');
```

**Comment by gsusI** [comment]
Some more details here: https://discourse.roots.io/t/custom-plugin-template-rendering-after-html-overriding-template-duplicates-html-block-in-page/19972

**Comment by gsusI** [comment]
Turns out that the problem was [this snippet](https://discourse.roots.io/t/how-to-add-buddypress-support-to-sage-9/16213) I was using to make my theme compatible with BuddyPress.

Does someone know why it was creating the conflict? (would be useful to undersand it and to have it documented somewhere)

```php

/**
 * Adds BuddyPress compatibility
 */
add_filter('bp_template_include_theme_compat', function ($template) {

    if (strpos($template, "mec-events") !== false) {
        return $template;
    }

// Find any oif the templates mentioned by BP codex
    $theme_template = locate_template([
        'plugin-buddypress',
        'buddypress',
        'community',
        'generic',
        'page',
        'single',
        'singular',
        'index',
    ]);
    // Load template from theme if it exists
    if ($theme_template) {
        $data = collect(get_body_class())->reduce(function ($data, $class) {
            return apply_filters("sage/template/{$class}/data", $data);
        }, []);

        echo template($theme_template, $data);
        return get_stylesheet_directory() . '/index.php';
    }

    return $template;

}, PHP_INT_MAX, 1);

/**
 * Prepares BuddyPress classes for usage with Controller
 */
add_filter('body_class', function (array $classes) {
    if (function_exists('bp_get_the_body_class')) {
        $bp_classes = array_filter(bp_get_the_body_class());

        if (!empty($bp_classes) && is_array($bp_classes)) {
            foreach ($bp_classes as $bp_class) {
                // We need to append 'bp-' to classes like 'directory'.
                // It will help to sort the Controller Classes and avoids duplicated classes:
                // e.g. class BpDirectory for 'bp-directory-data'
                $prepend = preg_match('/bp|buddypress/i', $bp_class) ? '' : 'bp-';
                $classes[] = $prepend . $bp_class . '-data';
            }
        }
    }

    return $classes;
}, 100);

/**
 * Adds the resources/views folder as potential
 * parent of buddypress/community folder
 */
add_filter('bp_get_template_locations', function ($locations) {
    return array_merge(
        $locations,
        [
            'views/buddypress',
            'views/community',
        ]
    );
});
```

**Comment by Log1x** [comment]
Please open a discussion on https://discourse.roots.io/ (or follow the existing one there) – once docs are done we will compile a list of filters for plugins like this.

**Comment by Log1x** [comment]
try this out https://gist.github.com/Log1x/d02f35f6f9de5f1a5078a3807c6a36c2
