### ISSUE TITLE
[Sage 9+10] Safely replace/refactor translation domains

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2633]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary
The translation domain of a Sage theme is `sage`, but this is usually changed to the translation domain of the site (e.g. `company-name-site`). Just using search and replace for `'sage'` in Sage 10 results in non-translation domain string being also replaced, which results in errors (see https://discourse.roots.io/t/sage-10-target-class-assets-does-not-exist/18603/4?u=strarsis).

## Motivation
Currently one either has to manually search through all occurences of `'sage'` or replace all occurencies of `'sage'` but undo some incorrect replacements afterwards.
A refactor/safe replace feature during theme creation or a script would be very helpful.

## Additional context
Related forum discussion: https://discourse.roots.io/t/sage-10-target-class-assets-does-not-exist/18603/4?u=strarsis

**Comment by Log1x** [comment]
The current build of Sage doesn't have any manual replacements needed right now. This will be added when we get around to making a Sage 10-specific Installer.

As for Sage 9, development on our side has ceased entirely.
