### ISSUE TITLE
[Sage10] header block render 2 times when Elementor is activated

### ISSUE THREAD

**Issue by fzhantw** [roots/sage#2638]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In sage 10, index.php
"wp_head()" & "do_action('get_header');" are both called.
https://github.com/roots/sage/blob/33005e59b45ebf6139c07ec6b5751417a1d24dda/index.php#L7
https://github.com/roots/sage/blob/33005e59b45ebf6139c07ec6b5751417a1d24dda/index.php#L12
This makes some plugins (like Elementor) render header two times !

## Steps to reproduce

1. Install Sage 10 by installation steps
2. Install plugin "elementor"
3. You would find 2 `<body>` tags on every pages, and some <head> tags are inside <body></body>.

**Expected behavior:** [What you expect to happen]
The header section should only render once and should place in the reasonable DOM tree

**Actual behavior:** [What actually happens]
The header section render 2 times.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime

## Versions
Sage 10.0.0-beta.1 (dev-master)
Elementor 3.1.1

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

I think simply removing the line below would help.
`    <?php do_action('get_header'); ?>`

--

This image shows that header block render 2 times when Elementor is activated.
![image](https://user-images.githubusercontent.com/2579111/108015188-997e1580-704a-11eb-8420-c1db283b31fb.png)

**Comment by Log1x** [comment]
I assume there's a template in Elementor you need to override. I'd move this to https://discourse.roots.io/

**Comment by 0LIW3R** [comment]
Having the same problem right now. Are there any fixes 2 years later?

**Comment by bwat-dev** [comment]
Same problem with Roots Sage 10 and Elementor.
I replace the do_action('get_header') in themes/<sage>/index.php with this piece of code to prevent double header when elementor plugin is activated.
`<?php
    if (!is_plugin_active( 'elementor/elementor.php' )) {
      do_action('get_header');
    }
    ?>`

**Comment by 0LIW3R** [comment]
Hm, doesn't solve the problem for me, when I remove the get_header function the Elementor Theme Header wouldn't be loaded and if I want to edit this, I get the error "no content area found, please include the_content() in your theme" ...

**Comment by bwat-dev** [comment]
@0LIW3R  I tried again and I don't have any problem to edit page with Elementor with my change.
The error you see usually occurs when you miss the   @php(the_content()) in your page (in partials/content-single.blade.php for example)

**Comment by retlehs** [comment]
Feel free to use https://discourse.roots.io/t/sage10-incompatibility-with-elementor/22201 to discuss Elementor and Sage 10. I'm locking this issue from further comments because we don't use GH issues for support.
