### ISSUE TITLE
Call to undefined method Roots\Acorn\Assets\Asset\PhpAsset::get()

### ISSUE THREAD

**Issue by lukasz-gorski** [roots/sage#2660]
* [x] I've read the [guidelines for Contributing to Roots Projects (https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Site crash when trying to edit any page.

## Steps to reproduce

1. Install fresh Trellis / Bedrock / Sage (dev-master)
2. Try go edit any page in the admin

**Expected behavior:**

Page Edit to show.

**Actual behavior:** 

Whoops error: Call to undefined method Roots\Acorn\Assets\Asset\PhpAsset::get()

**Reproduces how often:**

100%

## Versions

Sage 10.0.0-beta.1: TBA
Latest MacOS.

## Additional information

There is no method get(), it's named "load()", need to update setup.php line 35 to:
 if ($manifest = asset('scripts/manifest.asset.php')->load()) {
from 
 if ($manifest = asset('scripts/manifest.asset.php')->get()) {

**Comment by QWp6t** [comment]
Oops! 🙈

**Comment by harry1988** [comment]
i am getting same issue 👍 

atal error: Uncaught Roots\Acorn\Assets\Contracts\ManifestNotFoundException: The manifest [D:\xampp\htdocs\wordpress/wp-content/themes/sage/public/manifest.json] cannot be found. in D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php:133 Stack trace: #0 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php(101): Roots\Acorn\Assets\Manager->getJsonManifest('D:\\xampp\\htdocs...') #1 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php(76): Roots\Acorn\Assets\Manager->resolve('theme', Array) #2 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\Acorn\Assets\AssetsServiceProvider.php(22): Roots\Acorn\Assets\Manager->manifest('theme') #3 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\illuminate\container\Container.php(885): Roots\Acorn\Assets\AssetsServiceProvider->Roots\Acorn\Assets\{closure}(Object(Roots\Acorn\Application), Array) #4 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\illuminate\container\Container.php(770): Illuminate\Container\Container->build(Object(Closure)) #5 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Illuminate\Foundation\Application.php(856): Illuminate\Container\Container->resolve('assets.manifest', Array, true) #6 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\illuminate\container\Container.php(706): Illuminate\Foundation\Application->resolve('assets.manifest', Array) #7 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Illuminate\Foundation\Application.php(841): Illuminate\Container\Container->make('assets.manifest', Array) #8 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Illuminate\Foundation\helpers.php(120): Illuminate\Foundation\Application->make('assets.manifest', Array) #9 D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\helpers.php(37): app('assets.manifest') #10 D:\xampp\htdocs\wordpress\wp-content\themes\sage\app\setup.php(26): Roots\bundle('editor') #11 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(308): App\{closure}('') #12 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #13 D:\xampp\htdocs\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #14 D:\xampp\htdocs\wordpress\wp-includes\class-wp-customize-widgets.php(879): do_action('enqueue_block_e...') #15 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(308): WP_Customize_Widgets->enqueue_scripts('') #16 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #17 D:\xampp\htdocs\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #18 D:\xampp\htdocs\wordpress\wp-admin\customize.php(123): do_action('customize_contr...') #19 {main} thrown in D:\xampp\htdocs\wordpress\wp-content\themes\sage\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php on line 133

Warning: Trying to access array offset on value of type bool in D:\xampp\htdocs\wordpress\wp-includes\class-wp-recovery-mode-email-service.php on line 367

Warning: Trying to access array offset on value of type bool in D:\xampp\htdocs\wordpress\wp-includes\class-wp-recovery-mode-email-service.php on line 368
There has been a critical error on this website. Please check your site admin email inbox for instructions.
