### ISSUE TITLE
Impossible to disable postcss-calc in production

### ISSUE THREAD

**Issue by dangelion** [roots/sage#2668]
## Description

I have to disable `postcss-calc` because in production makes wrong calc (see the reported bugs at the end). 
That library, I think, is used by cssnano.
In Sage 9 I did this adding `calc: false` in `postcss.config.js` file:

```
const cssnanoConfig = {
  preset: ['default', { discardComments: { removeAll: true }, calc: false }],
};

module.exports = ({ file, options }) => {
  return {
    parser: options.enabled.optimize ? 'postcss-safe-parser' : undefined,
    plugins: {
      autoprefixer: true,
      cssnano: options.enabled.optimize ? cssnanoConfig : false,
    },
  };
};
```

Tried also this:

```
mix
  .sass('resources/styles/app.scss', 'styles')
  .sass('resources/styles/editor.scss', 'styles')
  .options({
    postCss: [
      require('cssnano')({
        preset: ['default', {discardComments: {removeAll: true}, calc: false}],
      }),
    ],
    processCssUrls: false,
  });
```

No solutions work and give no error!
How can do that?

Or how can remove `postcss-calc` at all from Sage 10?

> Bug: cssnano -> postcss-calc compiling in production
> doesn't keep parenthesis inside some calc() with css variables

> https://github.com/postcss/postcss-calc/issues/115
https://github.com/postcss/postcss-calc/issues/107
https://github.com/postcss/postcss-calc/issues/91
https://github.com/postcss/postcss-calc/issues/77
https://github.com/postcss/postcss-calc/pull/116
https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/110
https://github.com/cssnano/cssnano/issues/628

**Comment by oxyc** [comment]
I use:

```js
mix.options({
  processCssUrls: false,
  // Causes the follow invalid optimization:
  //   calc(50% - (50vw - ((100vw - 42.125rem) / 2) * .2) + 10px)
  //   calc(50% - 50vw - (100vw - 42.125rem) / 2 * 0.2 + 10px)
  cssNano: {calc: false}
});
```

**Comment by dangelion** [comment]
@oxyc you saved me! Thanks a lot 🙏
