### ISSUE TITLE
`yarn translate:pot` failing if public folder is generated

### ISSUE THREAD

**Issue by gmutschler** [roots/sage#2672]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

There is an issue with the WP-CLI dependency, Peast (used to parse ES code). Anyhow the following error is thrown when parsing the content from `public/script/app.js`.

```
Warning: Uncaught Error in exception handling during call to Error::__tostring() in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/mck89/peast/lib/Peast/Syntax/Token.php on line 0
```

I don't believe it's a Sage issue in itself, but more a conflic between mck89/peast and the way Laravel Mix compile JS files.
Also we can get around it by temporarly removing the `public` folder, but a more robust workaround would be to ignore the `public` folder by adding the `--exclude=\"public\"` option in the yarn/npm script

## Steps to reproduce

1. Build your public folder with `yarn build` or  `yarn build:production`
2. Generate you translation file(s) with `yarn translate:pot`

**Expected behavior:** Should generate a .pot file in `resources/lang/`

**Actual behavior:** WP-CLI throw an error and the process exits with the code 255

**Reproduces how often:** 100%

## Versions

**Sage:** 10.0.0-beta.1: TBA
**OS:** macOS 11.2.3

**Comment by gmutschler** [comment]
Ok apparently, `wp i18n make-pot` doesn't handle Blade template string, had to run `wp acorn view:cache` and to add the `storage` folder to `--include` option in order to have it working.

So my final `yarn translate:pot` in `package.json` looks like this : 

```JSON
{
  ...
  "scripts": {
    ...
    "translate:pot": "wp acorn view:cache && wp i18n make-pot . ./resources/lang/sage.pot  --ignore-domain --include=\"app,resources,storage\" --exclude=\"public\"",
    ...
  },
  ...
}
```


---
#### Sidenotes:
1. Some `/* translators: */` comments are missing in `app/View/Composers/App.php` and `resources/views/partials/comments.blade.php` (as per https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#variables).
2. `wp i18n make-pot`, throw a warning about a missing singular placeholder. I don't like it, but @Automattic/_s overcomes the warning [this way](https://github.com/Automattic/_s/commit/a626d603c1ce4e5d82f625575fcb288e129874c5). It's also recommended in the [official doc](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#basic-pluralization).

**Comment by SergiArias** [comment]
Following the duplicate bug I posted, to generate the pot file in the beta-2 (where cached views were moved to wp-content/cache/acorn/views) I used the following command:

`wp acorn view:cache && wp i18n make-pot ../../ ./resources/lang/sage.pot  --ignore-domain --include=\"themes/theme_folder/app,themes/theme_folder/resources,cache/acorn/views\" --exclude=\"themes/theme_folder/public,plugins,languages,upgrade,uploads,index.php\"`

The only problem is having to update the theme_folder for every project, but it works ok.

Now is the only way to do it as plugins normally scan the theme folder only.

**Comment by StudioRATATA** [comment]
@SergiArias I've used `wp i18n` in beta1 as well. But it doesn't play well with beta2. [But the devs published documentation about translations. ](https://docs.roots.io/sage/10.x/localization/) I've tried this with my beta2 theme and it works well. I've tested it with your ` <h2>{!! __('Frequently asked questions', 'sage') !!}</h2>` line in the `app.blade.php` and it got picked up in the pot file.

**Comment by SergiArias** [comment]
@StudioRATATA why wp i18n doesn't play well in beta2? It works flawlessly for me. 

I tried also the way you recommend in the official documentation and it works except for one thing: In the "content-type" line of the pot file instead of UTF-8 it gives CHARSET. Does it happen to you as well?

Unfortunately I don't understand very well this command to propose a solution.
