### ISSUE TITLE
Sage 10: issues with Gutenberg version: 10.5.0

### ISSUE THREAD

**Issue by huubl** [roots/sage#2690]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

A clean install of Sage 10 (dev-master) with the Gutenberg plugin version: 10.5.0 breaks site. It shows the message:

`no matching template found`

## Steps to reproduce

1. composer create-project roots/sage dev-clean dev-master
2. Install and activate the Gutenberg plugin (version: 10.5.0)
3. Open the (home)page

**Expected behavior:** [What you expect to happen]

No errors.

**Actual behavior:** [What actually happens]

Breaks site.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

## Versions

dev-master branch

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by joshuafredrickson** [comment]
I see this in 10.5.1 and 10.5.2 as well. No issues with 10.4.1 and below. I wonder if this has to do with Site Editor functionality.

**Comment by retlehs** [comment]
> Gutenberg now explicitly declares that anyone running the plugin is on a block-based theme, despite whether their theme actually supports block templates.

via https://wptavern.com/gutenberg-10-5-embeds-pdfs-adds-verse-block-color-options-and-introduces-new-patterns

**Comment by joshuafredrickson** [comment]
Looks like this solves it:

`
remove_theme_support( 'block-templates' );
`

**Comment by huubl** [comment]
Thanks, that works!
