### ISSUE TITLE
Update the documentation to Sage 10

### ISSUE THREAD

**Issue by basduchambre** [roots/sage#2758]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

The current documentation is only up to v9.x. Since the master branch is now 10.x it's handy to update the documentation.

## Motivation

For future developers to catch any issues beforehand by reading the documentation in the corresponding version.

**Comment by retlehs** [comment]
thanks @basduchambre - we're tracking this over at https://github.com/roots/sage/issues/2357

the current progress can be seen at https://github.com/roots/docs/pull/249
