### ISSUE TITLE
vendor.js doesn't exist, breaking wp-admin/widgets in wordpress 5.8

### ISSUE THREAD

**Issue by eduardoarandah** [roots/sage#2774]
* [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing issue
* [x ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

/wp-admin/widgets.php doesn't render with fresh sage install 

## Steps to reproduce

1. Install wp
2. Install and compile sage 10
3. Visit widgets

**Expected behavior:** 

see widgets

**Actual behavior:** 

blank page, js stops working

**Reproduces how often:** 

100%

## Versions

wp 5.8
sage 10

## Additional information

Wordpress 5.8 makes heavy use of JS in the backend. 

When vendor doesn't exist, wordpress responds with a redirection. 

![image](https://user-images.githubusercontent.com/4065733/127600021-550d519a-8c5e-470b-98ea-f64f94d40fc9.png)

then javascript stops execution and page displays blank 

check: /wp-admin/widgets.php

![image](https://user-images.githubusercontent.com/4065733/127600131-628467e6-cb43-4871-a178-d83038a4db82.png)

## Temporary solution

**webpack.mix.js**

remove `.extract()`

**setup.php**

change this:

```
    wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), ['jquery'], null, true);
    wp_enqueue_script('sage/app.js', asset('scripts/app.js')->uri(), ['sage/vendor.js'], null, true);
    wp_add_inline_script('sage/vendor.js', asset('scripts/manifest.js')->contents(), 'before');

```

to this:

```
wp_enqueue_script('sage/app.js', asset('scripts/app.js')->uri(), ['jquery'], null, true);

```

change this:

```
    if ($manifest = asset('scripts/manifest.asset.php')->load()) {
        wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), ...array_values($manifest));
        wp_enqueue_script('sage/editor.js', asset('scripts/editor.js')->uri(), ['sage/vendor.js'], null, true);
        wp_add_inline_script('sage/vendor.js', asset('scripts/manifest.js')->contents(), 'before');
    }

```

to this:

``` 
        wp_enqueue_script('sage/editor.js', asset('scripts/editor.js')->uri(), [], null, true);

```

* I'm not sure what manifest.asset.php does, please edit my code if it's wrong

**Comment by kukac7** [comment]
i have a `vendor.js` file, but it still dies on the admin widgets page.

**Comment by noahott** [comment]
For me, the solution was just to remove "import '@wordpress/edit-post';" from the first line of editor.js

**Comment by zonay** [comment]
I fixed it by creating an empty `vendor.js` file on `/public/scripts` folder. 🥺

**Comment by aminta** [comment]
Same problem here...

**Comment by theMosaad** [comment]
Removing this line makes it makes `.extract()` work again and creates `vendor.js` on build.

```diff
mix
  .js('resources/scripts/app.js', 'scripts')
  .js('resources/scripts/customizer.js', 'scripts')
-  .blocks('resources/scripts/editor.js', 'scripts')
  .autoload({ jquery: ['$', 'window.jQuery'] })
  .extract();
```

**Comment by stephan-v** [comment]
Why not actually fix this instead of pointing people towards a pull request which may or may not get merged soon?

**Comment by retlehs** [comment]
@stephan-v as i mentioned, it's because **we're no longer pushing any more changes to the mix setup/config** and we do have our own deadlines that we are following to get things wrapped up for sage 10 right now.

**Comment by blift** [comment]
In my case that was issue with uBlock and imported url fonts... not Sage and mix assets. So maybe for someone that will be helpful :D
