### ISSUE TITLE
Sage 9 not working on Windows

### ISSUE THREAD

**Issue by kingkero** [roots/sage#2775]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The theme isn't working on Windows because of hardcoded `/` instead of using `DIRECTORY_SEPARATOR`.

## Steps to reproduce

1. Have a Windows machine
2. Try to activate a theme that uses Sage 9.
3. Errors.

**Expected behavior:** [What you expect to happen]

It works.

**Actual behavior:** [What actually happens]

It can't load autoload.php or setup files.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

## Additional information

I can provide a PR for this later today.

**Comment by retlehs** [comment]
thanks, but we only support windows through WSL
