### ISSUE TITLE
[Sage 10] "Class 'Intervention\HttpAuth\Laravel\HttpAuthServiceProvider' not found"

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2808]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
After having a Sage 10 theme created and activated the following error occurs:
````
Class 'Intervention\HttpAuth\Laravel\HttpAuthServiceProvider' not found
````

## Steps to reproduce

1. Create a new Sage 10 project (`composer create-project roots/sage your-theme-name dev-master`).
2. Run `npm install && npm run build` (`composer install` is already run by the composer installer script).
3. Activate that theme. Note the error mesage.

**Expected behavior:** No error message.

**Actual behavior:** Exception `Class 'Intervention\HttpAuth\Laravel\HttpAuthServiceProvider' not found`

**Reproduces how often:** Always.

## Versions
Current master (`10.0.0-beta.1: TBA`).
Recent Bedrock (`1.16.1: 2021-07-30`).

**Comment by Log1x** [comment]
what plugins are you running? i think it might be caused by wp-optimize

**Comment by strarsis** [comment]
Yes, after removing the plugins folder and re-running `composer` for the Bedrock site, the error went away.
IMHO the issue is that there are actually two `composer` projects: One for the Bedrock site and one for the Sage theme. 
Usually these don't interfere - but because both `composer` managed projects are loaded at the same time (and plugins are allowed to use practically anything, `composer`, bundled libraries, etc that will be used by the Bedrock `composer`), issues like these can happen sometimes. It would be nice if `composer` projects can be somehow chained/linked so `composer` knows about the other `composer` files and harmonize the dependencies.
