### ISSUE TITLE
@apply !important throws error in Sage 10.

### ISSUE THREAD

**Issue by christianmagill** [roots/sage#2843]
* [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing issue
* [x ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Using the !important designation with Tailwind's @apply throws an error in Sage 10.

## Steps to reproduce

1. Fresh Install
2. Edit global.scss to include an @apply rule with the !important designation.
`@apply font-sans !important;`
3. Attempt to build the project.

**Expected behavior:** The project should build with !important being added to the related rules per: https://tailwindcss.com/docs/functions-and-directives

**Actual behavior:** I get the following error:

```
ERROR in ./resources/styles/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected ";".
  ╷
2 │   @apply font-sans !important;
  │                    ^
  ╵
  resources/styles/common/global.scss 2:20  @import
  resources/styles/app.scss 3:9             root stylesheet
```

**Reproduces how often:** Always

## Versions

10.0.0-beta.1: October 21st, 2021
Tailwind 2.2.19, JIT

**Comment by joshuafredrickson** [comment]
In that same Tailwind link, it mentions:

> Note that if you’re using Sass/SCSS, you’ll need to use Sass’ interpolation feature to get this to work:

```
.btn {
  @apply font-bold py-2 px-4 rounded #{!important};
}
```

Looks like a Sass limitation vs a Sage-specific issue.

**Comment by christianmagill** [comment]
@joshuafredrickson, Thanks for catching that!
