### ISSUE TITLE
Embed Blocks don't work with Sage 9.0.9

### ISSUE THREAD

**Issue by aresrioja10** [roots/sage#2856]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

I'm trying to embed a YouTube video by pasting the URL in the Guttenberg editor and it doesn't work.

## Steps to reproduce

1. Paste the following URL in the Gutenberg editor: https://www.youtube.com/watch?v=3lfnR7OhZY8
2. It should load the YouTube video

**Expected behavior:** [What you expect to happen]

It should embed the Youtube Video 

**Actual behavior:** [What actually happens]

The console shows the following error:

Failed to load resource: the server responded with a status of 404 (Not Found) http://nintenduo.test/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Ftwitter.com%2FAntonioMaestre%2Fstatus%2F1463470370233724934&_locale=user
http://nintenduo.test/wp-includes/js/dist/api-fetch.min.js?ver=134e23b5f88ba06a093f9f92520a98df

{code: "rest_no_route",…}
code: "rest_no_route"
data: {status: 404}
message: "No se ha encontrado ninguna ruta que coincida con la URL y el método de la solicitud."

**Comment by KIKOmanasijev** [comment]
Do you also have any issues when trying to embed an internal link from your site? For me both external embeds, and internal link embeds don't work on Sage 10. 

`Sorry, this content could not be embedded.`
Is the error I am getting when trying to embed any page or article from my blog. Tried to achieve this with the vanilla Wordpress theme, and I am having no issues of this type there.
