### ISSUE TITLE
Unreferenced static images from /resources/images folder are not processed in bud

### ISSUE THREAD

**Issue by AltanS** [roots/sage#2863]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Since migrating from laravel mix to bud the asset building process is somewhat improved I guess and images or other static resources referenced in asset files are included automatically in the `public` folder. What I noticed however is that images located in `resources/images` which have no reference are not included.

## Steps to reproduce

1. Clone the repository
2. Install all dependencies and build requirements, fire up a dev server
3. Add an image to the `resources/images` folder
4. Load this image via the asset directive in a template
``` HTML
<img class="block w-auto h-6" src="@asset('images/company-mark.svg')" alt="company logo">
```
5. Rebuild the assets manually `yarn build`

**Expected behavior:** 
- There should now be a folder in the `public` directory for images and the `manifest.json` file should reference the actual path.

**Actual behavior:**
- The images are not processed

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Versions

HEAD

## Additional information

I looked at the old Laravel mix implementation and noticed a difference with the folders.

Line in question:
https://github.com/roots/sage/blob/master/bud.config.js#L24

changing this from `assets/images` to `resources/images` fixes the problem

**Comment by retlehs** [comment]
thanks for reporting this! would you mind submitting a PR with that fix?
