### ISSUE TITLE
Styles not compiling by default

### ISSUE THREAD

**Issue by gitgudcameron** [roots/sage#2868]
## Description

Styles not compiling by default.

## Steps to reproduce

1. Clone Sage 10 repo 
2. Run the following commands: yarn && composer Install && yarn dev && yarn build
3. Check the public folder for CSS files.

**Expected behavior:** 

The editor.css and app.css should be compiled into the "public" folder but are not by default. However, no error is displayed.

**Reproduces how often:** 
Every time.

## Additional information

- If I remove the @apply's from the global.css file and add some standard CSS, it will compile as expected.
- If I try to change the file the files to SCSS, I get the following error:
`When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option.` 
 I've tried "yarn add postcss-scss --dev" and tweaking the stylelint config file but not having any luck.

**Comment by gitgudcameron** [comment]
Silly me. https://github.com/roots/sage/issues/2869

**Comment by retlehs** [comment]
🤔  could you please shoot us the full terminal output after you attempted a `yarn build`?

**Comment by gitgudcameron** [comment]
Sure @retlehs.

This is the full terminal output without changing anything out of the box. No scss files, just .css with the tailwind @apply.

`$ bud build
[your-theme-name] › ▶  bud          Initialized timer...
[your-theme-name] › ❯  process.env.NODE_ENV production
[your-theme-name] › ❯  process.env.BABEL_ENV production
▶  building bud Initialized timer...
[your-theme-name] › …  [1/4] bootstrap api
[your-theme-name] [api] › ❯  binding bud.alias facade
[your-theme-name] › ✔  bound alias
[your-theme-name] [api] › ✔  binding bud.alias facade
[your-theme-name] [api] › ❯  binding bud.assets facade
[your-theme-name] › ✔  bound assets
[your-theme-name] [api] › ✔  binding bud.assets facade
[your-theme-name] [api] › ❯  binding bud.copy facade
[your-theme-name] › ✔  bound copy
[your-theme-name] [api] › ✔  binding bud.copy facade
[your-theme-name] [api] › ❯  binding bud.config facade
[your-theme-name] › ✔  bound config
[your-theme-name] [api] › ✔  binding bud.config facade
[your-theme-name] [api] › ❯  binding bud.webpackConfig facade
[your-theme-name] › ✔  bound webpackConfig
[your-theme-name] [api] › ✔  binding bud.webpackConfig facade
[your-theme-name] [api] › ❯  binding bud.override facade
[your-theme-name] › ✔  bound override
[your-theme-name] [api] › ✔  binding bud.override facade
[your-theme-name] [api] › ❯  binding bud.define facade
[your-theme-name] › ✔  bound define
[your-theme-name] [api] › ✔  binding bud.define facade
[your-theme-name] [api] › ❯  binding bud.devtool facade
[your-theme-name] › ✔  bound devtool
[your-theme-name] [api] › ✔  binding bud.devtool facade
[your-theme-name] [api] › ❯  binding bud.entry facade
[your-theme-name] › ✔  bound entry
[your-theme-name] [api] › ✔  binding bud.entry facade
[your-theme-name] [api] › ❯  binding bud.js facade
[your-theme-name] › ✔  bound js
[your-theme-name] [api] › ✔  binding bud.js facade
[your-theme-name] [api] › ❯  binding bud.css facade
[your-theme-name] › ✔  bound css
[your-theme-name] [api] › ✔  binding bud.css facade
[your-theme-name] [api] › ❯  binding bud.experiments facade
[your-theme-name] › ✔  bound experiments
[your-theme-name] [api] › ✔  binding bud.experiments facade
[your-theme-name] [api] › ❯  binding bud.externals facade
[your-theme-name] › ✔  bound externals
[your-theme-name] [api] › ✔  binding bud.externals facade
[your-theme-name] [api] › ❯  binding bud.hash facade
[your-theme-name] › ✔  bound hash
[your-theme-name] [api] › ✔  binding bud.hash facade
[your-theme-name] [api] › ❯  binding bud.version facade
[your-theme-name] › ✔  bound version
[your-theme-name] [api] › ✔  binding bud.version facade
[your-theme-name] [api] › ❯  binding bud.minimize facade
[your-theme-name] › ✔  bound minimize
[your-theme-name] [api] › ✔  binding bud.minimize facade
[your-theme-name] [api] › ❯  binding bud.persist facade
[your-theme-name] › ✔  bound persist
[your-theme-name] [api] › ✔  binding bud.persist facade
[your-theme-name] [api] › ❯  binding bud.provide facade
[your-theme-name] › ✔  bound provide
[your-theme-name] [api] › ✔  binding bud.provide facade
[your-theme-name] [api] › ❯  binding bud.proxy facade
[your-theme-name] › ✔  bound proxy
[your-theme-name] [api] › ✔  binding bud.proxy facade
[your-theme-name] [api] › ❯  binding bud.run facade
[your-theme-name] › ✔  bound run
[your-theme-name] [api] › ✔  binding bud.run facade
[your-theme-name] [api] › ❯  binding bud.runtime facade
[your-theme-name] › ✔  bound runtime
[your-theme-name] [api] › ✔  binding bud.runtime facade
[your-theme-name] [api] › ❯  binding bud.serve facade
[your-theme-name] › ✔  bound serve
[your-theme-name] [api] › ✔  binding bud.serve facade
[your-theme-name] [api] › ❯  binding bud.splitChunks facade
[your-theme-name] › ✔  bound splitChunks
[your-theme-name] [api] › ✔  binding bud.splitChunks facade
[your-theme-name] [api] › ❯  binding bud.vendor facade
[your-theme-name] › ✔  bound vendor
[your-theme-name] [api] › ✔  binding bud.vendor facade
[your-theme-name] [api] › ❯  binding bud.template facade
[your-theme-name] › ✔  bound template
[your-theme-name] [api] › ✔  binding bud.template facade
[your-theme-name] [api] › ❯  binding bud.watch facade
[your-theme-name] › ✔  bound watch
[your-theme-name] [api] › ✔  binding bud.watch facade
[your-theme-name] › ✔  bound use
[your-theme-name] › ✔  bound setPublicPath
[your-theme-name] › ✔  bound publicPath
[your-theme-name] › …  [2/4] bootstrap hooks
[your-theme-name] › …  [3/4] bootstrap project
[your-theme-name] › …  [4/4] bootstrap env
[your-theme-name] [env] › ❯  loading env
[your-theme-name] [env] › ⚠  no env values found
[your-theme-name] › ✔  [1/4] bootstrap api
[your-theme-name] › ✔  [2/4] bootstrap hooks
[your-theme-name] › ✔  [4/4] bootstrap env
[your-theme-name] › ✔  [3/4] bootstrap project
[your-theme-name] › …  [1/4] register project
[your-theme-name] › …  [2/4] register build
[your-theme-name] › …  [3/4] register compiler
[your-theme-name] › …  [4/4] register dependencies
[your-theme-name] › ✔  [3/4] register compiler
[your-theme-name] › ✔  [4/4] register dependencies
[your-theme-name] › ✔  [2/4] register build
[your-theme-name] [project] › ▶  building profile Initialized timer...
[your-theme-name] [project] › …  analyzing devDependencies
[your-theme-name] [project] › ✔  resolved @roots/sage ./node_modules/@roots/sage
[your-theme-name] [project] › ✔  manifest resolved @roots/sage
[your-theme-name] [project] › ✔  resolved @roots/bud-preset-wordpress ./node_modules/@roots/bud-preset-wordpress
[your-theme-name] [project] › ✔  resolved @roots/bud-eslint ./node_modules/@roots/bud-eslint
[your-theme-name] [project] › ✔  resolved @roots/bud-prettier ./node_modules/@roots/bud-prettier
[your-theme-name] [project] › ✔  resolved @roots/bud-stylelint ./node_modules/@roots/bud-stylelint
[your-theme-name] [project] › ✔  resolved @roots/bud-tailwindcss ./node_modules/@roots/bud-tailwindcss
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-preset-wordpress
[your-theme-name] [project] › ✔  required peer dependency is met @wordpress/browserslist-config@4.1.0
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-eslint
[your-theme-name] [project] › ✔  required peer dependency is met eslint@7.32.0
[your-theme-name] [project] › ✔  required peer dependency is met prettier@2.4.1
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-prettier
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-stylelint
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-tailwindcss
[your-theme-name] [project] › ✔  required peer dependency is met tailwindcss@2.2.19
[your-theme-name] [project] › ✔  resolved @roots/bud-preset-recommend ./node_modules/@roots/bud-preset-recommend
[your-theme-name] [project] › ✔  resolved @roots/bud-wordpress-externals ./node_modules/@roots/bud-wordpress-externals
[your-theme-name] [project] › ✔  resolved @roots/bud-react ./node_modules/@roots/bud-react
[your-theme-name] [project] › ✔  resolved @roots/bud-wordpress-dependencies ./node_modules/@roots/bud-wordpress-dependencies
[your-theme-name] [project] › ✔  resolved @roots/bud-wordpress-manifests ./node_modules/@roots/bud-wordpress-manifests
[your-theme-name] [project] › ✔  resolved @roots/bud-postcss ./node_modules/@roots/bud-postcss
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-preset-recommend
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-wordpress-externals
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-react
[your-theme-name] [project] › ✔  required peer dependency is met react@17.0.2
[your-theme-name] [project] › ✔  required peer dependency is met react-dom@17.0.2
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-wordpress-dependencies
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-wordpress-manifests
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-postcss
[your-theme-name] [project] › ✔  required peer dependency is met postcss@8.3.11
[your-theme-name] [project] › ✔  required peer dependency is met postcss-import@14.0.2
[your-theme-name] [project] › ✔  required peer dependency is met postcss-nested@5.0.6
[your-theme-name] [project] › ✔  required peer dependency is met postcss-preset-env@7.0.1
[your-theme-name] [project] › ✔  resolved @roots/bud-babel ./node_modules/@roots/bud-babel
[your-theme-name] [project] › ✔  resolved @roots/bud-entrypoints ./node_modules/@roots/bud-entrypoints
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-babel
[your-theme-name] [project] › ✔  manifest resolved @roots/bud-entrypoints
[your-theme-name] [project] › …  reading project configuration files
[your-theme-name] [project] › ●  located user config bud.config.js
[your-theme-name] [project] › ◼  building profile Timer run for: 61ms
[your-theme-name] › ✔  [1/4] register project
[your-theme-name] › …  [1/3] registered api
[your-theme-name] › …  [2/3] registered dashboard
[your-theme-name] › …  [3/3] registered extensions
[your-theme-name] [extensions] › ▶  instantiating built-ins Initialized timer...
[your-theme-name] [extensions] › ✔  webpack-provide-plugin instantiated
[your-theme-name] [extensions] › ✔  clean-webpack-plugin instantiated
[your-theme-name] [extensions] › ✔  copy-webpack-plugin instantiated
[your-theme-name] [extensions] › ✔  webpack-define-plugin instantiated
[your-theme-name] [extensions] › ✔  webpack-hot-module-replacement-plugin instantiated
[your-theme-name] [extensions] › ✔  ignore-emit-webpack-plugin instantiated
[your-theme-name] [extensions] › ✔  webpack-manifest-plugin instantiated
[your-theme-name] [extensions] › ✔  mini-css-extract-plugin instantiated
[your-theme-name] › ✔  [2/3] registered dashboard
[your-theme-name] › ✔  [1/3] registered api
[your-theme-name] [extensions] › ◼  instantiating built-ins Timer run for: 3ms
[your-theme-name] › ✔  [3/3] registered extensions
[your-theme-name] › …  [1/4] boot hooks
[your-theme-name] › …  [2/4] boot project
[your-theme-name] › …  [3/4] boot cache
[your-theme-name] › …  [4/4] boot extensions
[your-theme-name] [extensions] › ❯  extension injection enabled
[your-theme-name] [extensions] › …  injecting project extensions
[your-theme-name] › ✔  [1/4] boot hooks
[your-theme-name] › ✔  [2/4] boot project
[your-theme-name] [extensions] › ✔  @roots/sage resolved
[your-theme-name] [extensions] › ✔  @roots/bud-preset-wordpress resolved
[your-theme-name] [extensions] › ✔  eslint-webpack-plugin resolved
[your-theme-name] [extensions] › ✔  @roots/bud-prettier resolved
[your-theme-name] [extensions] › ✔  stylelint-webpack-plugin resolved
[your-theme-name] [extensions] › ✔  @roots/bud-tailwindcss resolved
[your-theme-name] [extensions] › ✔  @roots/bud-preset-recommend resolved
[your-theme-name] [extensions] › ✔  @roots/wordpress-externals-webpack-plugin resolved
[your-theme-name] [extensions] › ✔  @roots/bud-react resolved
[your-theme-name] [extensions] › ✔  @roots/wordpress-dependencies-webpack-plugin resolved
[your-theme-name] [extensions] › ✔  @roots/bud-wordpress-manifests resolved
[your-theme-name] [extensions] › ✔  @roots/bud-postcss resolved
[your-theme-name] [extensions] › ✔  @roots/bud-babel resolved
[your-theme-name] [extensions] › ✔  @roots/bud-entrypoints resolved
[your-theme-name] › ✔  [4/4] boot extensions
[your-theme-name] [cache] › ℹ  cache hash generated ph6oks27wmonxxzzeouv_y1acn8_
[your-theme-name] [cache] › ℹ  cache feature flag: true
[your-theme-name] [cache] › ℹ  --cache flag: true
[your-theme-name] [cache] › ❯  --cache.type flag filesystem
[your-theme-name] [api] › ❯  executing persist ["filesystem"]
[your-theme-name] [api] › ✔  cache enabled filesystem
[your-theme-name] › ✔  [3/4] boot cache
[your-theme-name] › …  [1/2] booted build
[your-theme-name] › …  [2/2] booted extensions
[your-theme-name] [extensions] › ▶  registering  Initialized timer...
[your-theme-name] › ✔  [1/2] booted build
[your-theme-name] [extensions] › ✔  registered bud.eslint eslint-webpack-plugin
[your-theme-name] [extensions] › ✔  registered bud.postcss @roots/bud-postcss
[your-theme-name] [extensions] › ✔  registered bud.babel @roots/bud-babel
[your-theme-name] [extensions] › ✔  register called webpack-provide-plugin
[your-theme-name] [extensions] › ✔  register called clean-webpack-plugin
[your-theme-name] [extensions] › ✔  register called copy-webpack-plugin
[your-theme-name] [extensions] › ✔  register called webpack-define-plugin
[your-theme-name] [extensions] › ✔  register called webpack-hot-module-replacement-plugin
[your-theme-name] [extensions] › ✔  register called ignore-emit-webpack-plugin
[your-theme-name] [extensions] › ✔  register called webpack-manifest-plugin
[your-theme-name] [extensions] › ✔  register called mini-css-extract-plugin
[your-theme-name] [extensions] › ✔  register called @roots/sage
[your-theme-name] [extensions] › ✔  register called @roots/bud-preset-wordpress
[your-theme-name] [extensions] › ✔  register called @roots/bud-prettier
[your-theme-name] [extensions] › ✔  register called stylelint-webpack-plugin
[your-theme-name] › ✔  bound tailwind
[your-theme-name] [extensions] › ✔  registered bud.tailwind @roots/bud-tailwindcss
[your-theme-name] [extensions] › ✔  register called @roots/bud-preset-recommend
[your-theme-name] [extensions] › ✔  register called @roots/wordpress-externals-webpack-plugin
[your-theme-name] [extensions] › ✔  register called @roots/bud-react
[your-theme-name] [extensions] › ✔  register called @roots/wordpress-dependencies-webpack-plugin
[your-theme-name] [extensions] › ✔  register called @roots/bud-wordpress-manifests
[your-theme-name] [extensions] › ✔  register called @roots/bud-entrypoints
[your-theme-name] [extensions] › ✔  register called eslint-webpack-plugin
[your-theme-name] [extensions] › ✔  register called @roots/bud-tailwindcss
[your-theme-name] › ✔  postcss plugin set: postcss-import
[your-theme-name] › ✔  postcss plugin set: postcss-nested
[your-theme-name] › ✔  postcss plugin set: postcss-preset-env
[your-theme-name] [extensions] › ✔  register called @roots/bud-postcss
[your-theme-name] [extensions] › ✔  register called @roots/bud-babel
[your-theme-name] [extensions] › ◼  registering  Timer run for: 11ms
[your-theme-name] [extensions] › ▶  booting      Initialized timer...
[your-theme-name] [api] › ❯  facade called: alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[your-theme-name] [api] › ❯  facade added to queue: alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[your-theme-name] [api] › ❯  facade called: provide [{"$":["jquery"],"jQuery":["jquery"]}]
[your-theme-name] [api] › ❯  facade added to queue: provide [{"$":["jquery"],"jQuery":["jquery"]}]
[your-theme-name] [api] › ❯  facade called: minimize []
[your-theme-name] [api] › ❯  facade added to queue: minimize []
[your-theme-name] [api] › ❯  facade called: hash []
[your-theme-name] [api] › ❯  facade added to queue: hash []
[your-theme-name] [api] › ❯  facade called: runtime ["single"]
[your-theme-name] [api] › ❯  facade added to queue: runtime ["single"]
[your-theme-name] › ✔  tailwindcss requirements met
[your-theme-name] › ℹ  tailwindcss to be configured using config file at [secure]/tailwindcss.config.js
[your-theme-name] [extensions] › ✔  @roots/sage booted
[your-theme-name] [extensions] › ✔  @roots/bud-tailwindcss booted
[your-theme-name] [extensions] › ✔  @roots/bud-react booted
[your-theme-name] [extensions] › ◼  booting      Timer run for: 5ms
[your-theme-name] › ✔  [2/2] booted extensions
[your-theme-name] › ◼  building bud Timer run for: 886ms
[your-theme-name] [build] › runner ✔  framework ready
[your-theme-name] [build] › ▶  process user configs Initialized timer...
[your-theme-name] [build] › ❯  processing [secure]/bud.config.js
[your-theme-name] [build] › …  importing module [secure]/bud.config.js
[your-theme-name] [build] › …  calling user config [secure]/bud.config.js
[your-theme-name] [api] › ❯  facade called: entry [{"app":["scripts/app.js","styles/app.scss"],"editor":["scripts/editor.js","styles/editor.scss"],"customizer":"scripts/customizer.js"}]
[your-theme-name] [api] › ❯  facade added to queue: entry [{"app":["scripts/app.js","styles/app.scss"],"editor":["scripts/editor.js","styles/editor.scss"],"customizer":"scripts/customizer.js"}]
[your-theme-name] [api] › ❯  facade called: assets [["resources/images"]]
[your-theme-name] [api] › ❯  facade added to queue: assets [["resources/images"]]
[your-theme-name] [api] › ❯  facade called: watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[your-theme-name] [api] › ❯  facade added to queue: watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[your-theme-name] [api] › ❯  facade called: proxy [{"target":"http://template.loc"}]
[your-theme-name] [api] › ❯  facade added to queue: proxy [{"target":"http://template.loc"}]
[your-theme-name] [api] › …  Executing 9 enqueued functions
[your-theme-name] [api] › ❯  executing alias [{"@fonts":"./resources/fonts","@images":"[secure]/resources/images","@scripts":"[secure]/resources/scripts","@styles":"[secure]/resources/styles"}]
[your-theme-name] [api] › ✔  alias @fonts ./resources/fonts
[your-theme-name] [api] › ✔  alias @images ./resources/images
[your-theme-name] [api] › ✔  alias @scripts ./resources/scripts
[your-theme-name] [api] › ✔  alias @styles ./resources/styles
[your-theme-name] [api] › ❯  executing provide [{"$":["jquery"],"jQuery":["jquery"]}]
[your-theme-name] [api] › ❯  executing minimize none
[your-theme-name] [api] › ❯  executing hash none
[your-theme-name] [api] › ✔  file hashing enabled
[your-theme-name] [api] › ❯  executing runtime ["single"]
[your-theme-name] [api] › ❯  executing entry [{"app":["scripts/app.js","styles/app.scss"],"editor":["scripts/editor.js","styles/editor.scss"],"customizer":"scripts/customizer.js"}]
[your-theme-name] [api] › ❯  executing assets [["resources/images"]]
[your-theme-name] [api] › ❯  executing watch [["tailwind.config.js","resources/views/*.blade.php","app/View/**/*.php"]]
[your-theme-name] [api] › ✔  watch files added tailwind.config.js, resources/views/*.blade.php, app/View/**/*.php
[your-theme-name] [api] › ❯  skipping watch files production mode is set
[your-theme-name] [api] › ❯  executing proxy [{"target":"http://template.loc"}]
[your-theme-name] [build] › ◼  process user configs Timer run for: 16ms
[your-theme-name] [api] › ❯  executing run [[]]
[your-theme-name] › ❯  event.build.make.promise api calls
[your-theme-name] › ℹ  glob search ["scripts/app.js","styles/app.scss"]
[your-theme-name] › ℹ  glob directory [secure]/resources
[your-theme-name] › ℹ  glob results ["scripts/app.js"]
[your-theme-name] [api] › ✔  entrypoints added app {"import":["scripts/app.js"]}
[your-theme-name] › ℹ  glob search ["scripts/editor.js","styles/editor.scss"]
[your-theme-name] › ℹ  glob directory [secure]/resources
[your-theme-name] › ℹ  glob results ["scripts/editor.js"]
[your-theme-name] [api] › ✔  entrypoints added editor {"import":["scripts/editor.js"]}
[your-theme-name] › ℹ  glob search ["scripts/customizer.js"]
[your-theme-name] › ℹ  glob directory [secure]/resources
[your-theme-name] › ℹ  glob results ["scripts/customizer.js"]
[your-theme-name] [api] › ✔  entrypoints added customizer {"import":["scripts/customizer.js"]}
[your-theme-name] [extensions] › ▶  extensions.make Initialized timer...
[your-theme-name] [extensions] › ✔  webpack-provide-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  clean-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ❯  copy-webpack-plugin will not be used in the compilation
[your-theme-name] [extensions] › ❯  webpack-define-plugin will not be used in the compilation
[your-theme-name] [extensions] › ❯  webpack-hot-module-replacement-plugin will not be used in the compilation
[your-theme-name] [extensions] › ✔  ignore-emit-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  webpack-manifest-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  mini-css-extract-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  eslint-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  stylelint-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  @roots/wordpress-externals-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  @roots/wordpress-dependencies-webpack-plugin will be used in the compilation
[your-theme-name] [extensions] › ✔  @roots/bud-wordpress-manifests will be used in the compilation
[your-theme-name] [extensions] › ✔  @roots/bud-entrypoints will be used in the compilation
[your-theme-name] [extensions] › ◼  extensions.make Timer run for: 26ms
[your-theme-name] [build] › ⚠  build.make: excluding experiments value is undefined
[your-theme-name] [build] › ⚠  build.make: excluding externals value is undefined
[your-theme-name] [build] › ⚠  build.make: excluding profile value is undefined
[your-theme-name] [build] › ⚠  build.make: excluding stats value is undefined
[your-theme-name] [build] › ⚠  build.make: excluding watch value is undefined
[your-theme-name] [build] › ⚠  build.make: excluding watchOptions value is undefined
[your-theme-name] [project] › ✔  writing profile to disk ./.budfiles/bud/profile.json
[your-theme-name] [build] › ℹ  writing webpack dump to disk ./.budfiles/bud/webpack.config.js
[your-theme-name] › ℹ  using config from parent compiler
[your-theme-name] [dashboard] › ✔  rendering dashboard
[your-theme-name] › ◼  bud          Timer run for: 1.34s`
