### ISSUE TITLE
Failed to load resource: unsupported URL

### ISSUE THREAD

**Issue by fowlercraig** [roots/sage#2871]
- Fresh install of Sage 10 with Bud
- Running on DevKinsta (basically Docker)
- yarn dev
- go to http://localhost:3000

CSS and JS assets aren't loading. Looking at the source, it appears that the asset urls are being output as
```
<script src="localhost:3000/wp-content/themes/sage-652b7ae24ca422d61503483adfb9518d27696b26/public/runtime.a5b3e3.js" id="app/0-js"></script>
<script src="localhost:3000/wp-content/themes/sage-652b7ae24ca422d61503483adfb9518d27696b26/public/app.c27b30.js" id="app/1-js"></script>
```
while in previous versions before roots/bud, they were output as
```
<script src="//localhost:3000/wp-content/themes/sage-652b7ae24ca422d61503483adfb9518d27696b26/public/runtime.a5b3e3.js" id="app/0-js"></script>
<script src="//localhost:3000/wp-content/themes/sage-652b7ae24ca422d61503483adfb9518d27696b26/public/app.c27b30.js" id="app/1-js"></script>
```

Tested on the laravel mix version of Sage and everything works as it should.

**Comment by jasaldivara** [comment]
I have the same issue, but i'm not using DevKinsta nor Docker.

Stylesheets are not loading on the live preview from `yarn dev` on http://localhost:3000/

A workaround I found is adding two slashes to the end of the proxy/targer URI on bud.config.js, so I changed from this:

```
.proxy({target: 'http://localhost/~username/website'});
```
to this:

```
.proxy({target: 'http://localhost/~username/website//'});
```

And now my stylesheets are loading ok on the live preview.
