### ISSUE TITLE
Fatal error Uncaught Exception

### ISSUE THREAD

**Issue by GarikHG** [roots/sage#2875]
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

[Description of the issue]

Fatal error: Uncaught Exception: The /current/web/app/themes/sage-10/public directory must be present. in /current/web/app/themes/sage-10/vendor/roots/acorn/src/Roots/Acorn/Application.php:124 Stack trace: 
#0 /current/web/app/themes/sage-10/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(206): Roots\Acorn\Application->usePaths(Array)
#1 /current/web/app/themes/sage-10/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(181): Roots\Acorn\Bootloader->app() 
#2 /current/web/wp/wp-includes/class-wp-hook.php(303): Roots\Acorn\Bootloader->__invoke('') #3 /current/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#4 /current/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#5 /current/web/wp/wp-settings.php(556): do_action('after_setup_the...') 
#6 /current/web/wp-config.php(9): require_once('/srv/www/re in /current/web/app/themes/sage-10/vendor/roots/acorn/src/Roots/Acorn/Application.php on line 124

## Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by retlehs** [comment]
instead of deciding to not read or fill out the issue template, please use it next time, since you would have already seen this.

dupe #2852
