### ISSUE TITLE
yarn bud error = command not found

### ISSUE THREAD

**Issue by DexIlaganDev** [roots/sage#2881]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### out of ideas

![image](https://user-images.githubusercontent.com/78647498/145222792-1b7644ac-bbaa-40c6-8495-a9e1fe38ff2d.png)

### Steps To Reproduce

1. install through cmd yarn add @roots/bud --dev
2. $ yarn bud --help
or any bud command just throws error command not found

### Expected Behavior

Expecting to show bud commands

### Actual Behavior

nothings just shows bud command not found

### Relevant Log Output

```shell
error Command "bud" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Versions

latest @root/bud

**Comment by retlehs** [comment]
> install through cmd yarn add @roots/bud --dev

😕 

bud is already installed with sage, why are you running this command? i'm closing this issue since it's a personal support request that should be posted on https://discourse.roots.io/

**Comment by DexIlaganDev** [comment]
thanks for the reply!

I needed to run these, I was just following the docs but when I run these builds, bud is not found.

Build commands
yarn dev — Compile assets when file changes are made, start Browsersync session
yarn build — Compile assets for production

**Comment by retlehs** [comment]
@DexIlaganDev 👉 https://discourse.roots.io/
