### ISSUE TITLE
Bug: When change blog info name, the console show error : TypeError: $ is not a function 

### ISSUE THREAD

**Issue by hieu0nguyen** [roots/sage#2893]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
In WP 5.8.2, the blog title does not change when I change it in theme customize.

#### What have you tried?
When I change blog name in WP customize theme, the blog title not change.

#### Possible solutions
I think jQuery is not loaded with $ variable. Show in customizer.js file, I was changed from $ to jQuery and It worked.

### Steps To Reproduce

1.
1.
1.

### Expected Behavior

The blog title will change when I change it in theme customize dashboard.
jQuery variable $ work in cutomizer.js file.

### Actual Behavior

jQuery $ not work.
Brower's console show: TypeError: $ is not a function 

### Versions

HEAD

**Comment by retlehs** [comment]
thanks for the report! time for us to decide if we'll keep the [customizer starter and convert it to vanilla JS](https://github.com/roots/sage/blob/d1d9dc03bf236335987ae0b9e681005ee4203ae5/resources/scripts/customizer.js), or just drop it entirely
