### ISSUE TITLE
Bug: yarn dev: Resources not loading when Wordpress site is not on the root directory

### ISSUE THREAD

**Issue by jasaldivara** [roots/sage#2894]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

I was having some issues with a previous version of sage 10 dev, so I updated my git repository to the latest commit on main branch: `d1d9dc0`. After doing `git checkout` I ran `composer install` and `yarn`. Then, the only change I made to the code from origin/main was setting the proxy URL on `bud.config.js` to reflect the URL of my development site, which is not on the root directory of the server:

```
.proxy('http://localhost/~user/website');
```

When I run `yarn dev` I see a output like this:

```

./public

bud ✔ app.js                                                                                 ✘ min       297.53 kB
bud ✔ editor.js                                                                              ✘ min       289.43 kB
bud ✔ customizer.js                                                                          ✘ min       261.46 kB

… compiled in 799ms using webpack v5.65.0

◉ 200 [dev] http://localhost:3000
◉ 200 [proxy] http://localhost

⠧ waiting for changes... 🆀 to exit

```

When I open the dev URL on a web browser, I see my website without any stylesheets applied. On the browser's dev tools console I see some warnings about not found resources:

```
GET http://localhost:3000/~user/website/wp-includes/css/dist/block-library/style.min.css?ver=5.8.2 net::ERR_ABORTED 404 (Not Found)

GET http://localhost:3000/~user/website/wp-content/themes/my-theme/public/app.js net::ERR_ABORTED 404 (Not Found)

GET http://localhost:3000/~user/website/wp-includes/js/wp-embed.min.js?ver=5.8.2 net::ERR_ABORTED 404 (Not Found)
```

When I try to open the URL of the stylesheet on a browser tab, there is a 404 "not found" error, but if I remove the path to the site from the URL: `http://localhost:3000/wp-includes/css/dist/block-library/style.min.css?ver=5.8.2`, the stylesheet loads fine.

I think bud should remove the site path when generating the URLS to the CSS and JS resources.

### Steps To Reproduce

1. `git clone git@github.com:roots/sage.git theme-name`
1. `cd theme-name`
1. `composer install`
2. `yarn`
3. Edit `bud.config.js` to chagne th proxy URL to something like `http://localhost/~user/website` when te website is installed on that directory.
4. `yarn dev`
5. Open `http://localhost:3000` on web browser
6. scripts and stylesheets not loading

### Expected Behavior

Stylesheets should be loading on developer preview. Bud should be removing site path from resources URL.

### Actual Behavior

Resources are not loading because it's URLs look like `http://localhost:3000/~user/website/wp-includes/css/dist/block-library/style.min.css?ver=5.8.2` instead of `http://localhost:3000/wp-includes/css/dist/block-library/style.min.css?ver=5.8.2`

### Relevant Log Output

```shell
./public

bud ✔ app.js                                                                                 ✘ min       297.53 kB
bud ✔ editor.js                                                                              ✘ min       289.43 kB
bud ✔ customizer.js                                                                          ✘ min       261.46 kB

… compiled in 799ms using webpack v5.65.0

◉ 200 [dev] http://localhost:3000
◉ 200 [proxy] http://localhost

⠧ waiting for changes... 🆀 to exit
```

### Versions

Latest commit from 'main' branch: `d1d9dc0`. OS: Fedora Linux 35.

**Comment by blift** [comment]
Change .proxy url to your **localhost** domain name

this:
.proxy('http://localhost/~user/website');

to:
.proxy('http://your-local-domain-name.test');

**Comment by jasaldivara** [comment]
Thank you @blift 

I did that, and now it's working ok. Scripts and style sheets are loading correctly.

Now the only issue is a warning message on dev tools console about source map:

```

DevTools failed to load source map: Could not load content for http://localhost/~user/website/wp-content/themes/my-theme/public/overlay.web-component.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

```

**Comment by blift** [comment]
No problem mate, could you change the label or close the issue? Thanks

**Comment by jasaldivara** [comment]
Reopening because some issues came back after updating to Sage 10 beta 2:

Now, when I open `http://localhost:3000` on my web browser, it shows me the contents of the root directory of my web server (`http://localhost`) instead of my wordpress site. So now I have to open `http://localhost:3000/~user/website` to view my wordpress development site, which is not _that_ bad, but also have another more anoying problem:

When I make changes to my stylesheets, the new styles doesn't get live-updated on `http://localhost:3000/~user/website`, so I have to manually reload the page. I'm seeing these messages on the developer tools console:

```
GET http://localhost:3000/~user/app.9fccffba8e8fdc7ec5ae.hot-update.json 404 (Not Found)
[HMR] Cannot find update (Full reload needed)
[HMR] (Probably because of restarting the server)
```

So the page is trying to load hot-update.json on `/~user/` but it's not present in that directory. Instead it should be loading it from the root directory, as: `http://localhost:3000/app.9fccffba8e8fdc7ec5ae.hot-update.json`, which is where the file Is present:

```
{"c":["app"],"r":[],"m":[]}
```

**Comment by retlehs** [comment]
@jasaldivara could you please start a topic over at https://discourse.roots.io/ for support?
