### ISSUE TITLE
Bug: Bud HMR not working as expected outside of front page

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2920]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

From a `yarn dev` session, updates made to assets (at least stylesheets) aren't applied to the proxy session correctly unless you're on the home page

### Steps To Reproduce

1. `yarn dev`
1. Visit http://localhost:3000/sample-page/
1. 404 on the hot update json file

### Expected Behavior

1. Hot update json file shouldn't 404 outside of the front page
2. Updates to assets should be applied in the Bud proxy session

### Actual Behavior

```
Failed to load resource: the server responded with a status of 404 (Not Found)

:3000/sample-page/app.34c442a9dc0b3adc14e3.hot-update.json:1 
```

### Versions

10.0.0-beta.2

**Comment by retlehs** [comment]
fixed as of bud v5.1.0 (#2952) with the latest acorn (#2953)

**Comment by zchlm** [comment]
@retlehs I'm having this issue in a new Sage project v10.1.3

**Comment by retlehs** [comment]
@zchlm prob need to bump to bud 5.7.2
