### ISSUE TITLE
Bug: Wordpress uploaded images do not show on `yarn dev` (10.0.0-beta2)

### ISSUE THREAD

**Issue by SergiArias** [roots/sage#2937]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Images uploaded to wordpress can be seen in the proxy address or after `yarn build`. I do not see the images when in `yarn dev`, as they are shown as broken. The theme images aren't affected.

I am using the wordpress function `wp_get_attachment_image()` which uses all thumbnails in srcset and it is using relative paths.

When opening the image link, instead of the image a small white square is shown.

I am using Laravel Valet as local server.

![image](https://user-images.githubusercontent.com/13618783/148440048-f4bf33ef-ee57-4946-a756-1461d93c19f8.png)

![image](https://user-images.githubusercontent.com/13618783/148440137-188854e8-bded-4952-8f33-56e62a74ede2.png)

### Steps To Reproduce

1. Upload image to Wordpress page (I used acf field)
2. In the view, use `{!! wp_get_attachment_image($image['id'], 'full', null, ['class' => '']) !!}`
3. run `yarn dev`

### Expected Behavior

Images shouldn't appear as broken

### Actual Behavior

Images appear as broken, but not on proxy.

### Versions

10.0.0-beta2

**Comment by retlehs** [comment]
looks like this is a bug with soil's relative url's + bud and not an issue with sage itself

i'd suggest disabling the relative url's module for now

**Comment by SergiArias** [comment]
@retlehs Thanks!! :)

Do I close this bug and report it in bud?

**Comment by retlehs** [comment]
i think this might be fixed as of bud v5.2.0
