### ISSUE TITLE
Bug: resolve the exact path of bundles

### ISSUE THREAD

**Issue by dongnguyenvie** [roots/sage#2940]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
The code splitting is not working in production. when i try to chunk file. it in dev env. but when build for prod. it's not work. because the path is wrong
#### What have you tried?
I try to set public path
`.setPublicPath('wp-content/themes/my-theme/public/')`
then I use `yarn build`
then I replace public path in "entrypoints.json" manually. it work in prod

### Steps To Reproduce

1. code splitting and import into app.js 
2. yarn build
3. http://domain/ 

### Expected Behavior

Resolve correct path of bundle

### Actual Behavior

![image](https://user-images.githubusercontent.com/42445585/148822040-d9a0f481-7756-43a7-a404-6fcd47f7c2aa.png)

### Relevant Log Output

```shell
(index):633 GET http://xxxxx.test/94.46e9e8.js net::ERR_ABORTED 404 (Not Found)
u.l @ (index):633
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
(index):633 Uncaught (in promise) ChunkLoadError: Loading chunk 94 failed.
(error: http://xxxxx.test/94.46e9e8.js)
    at Object.u.f.j ((index):633:2188)
    at (index):633:866
    at Array.reduce (<anonymous>)
    at Function.u.e ((index):633:831)
    at Object.675 (app.104bdb.js:1:261)
    at u ((index):633:138)
    at n (app.104bdb.js:1:1068)
    at app.104bdb.js:1:1078
    at n ((index):633:2651)
    at app.104bdb.js:1:64
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
Promise.then (async)
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
(index):633 GET http://xxxxx.test/951.ba9c7b.js net::ERR_ABORTED 404 (Not Found)
u.l @ (index):633
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
(index):633 Uncaught (in promise) ChunkLoadError: Loading chunk 951 failed.
(error: http://xxxxx.test/951.ba9c7b.js)
    at Object.u.f.j ((index):633:2188)
    at (index):633:866
    at Array.reduce (<anonymous>)
    at Function.u.e ((index):633:831)
    at Object.675 (app.104bdb.js:1:319)
    at u ((index):633:138)
    at n (app.104bdb.js:1:1068)
    at app.104bdb.js:1:1078
    at n ((index):633:2651)
    at app.104bdb.js:1:64
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
Promise.then (async)
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
(index):633 GET http://xxxxx.test/791.2a2363.js net::ERR_ABORTED 404 (Not Found)
u.l @ (index):633
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
(index):633 Uncaught (in promise) ChunkLoadError: Loading chunk 791 failed.
(error: http://xxxxx.test/791.2a2363.js)
    at Object.u.f.j ((index):633:2188)
    at (index):633:866
    at Array.reduce (<anonymous>)
    at Function.u.e ((index):633:831)
    at Object.675 (app.104bdb.js:1:289)
    at u ((index):633:138)
    at n (app.104bdb.js:1:1068)
    at app.104bdb.js:1:1078
    at n ((index):633:2651)
    at app.104bdb.js:1:64
u.f.j @ (index):633
(anonymous) @ (index):633
u.e @ (index):633
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
Promise.then (async)
675 @ app.104bdb.js:1
u @ (index):633
n @ app.104bdb.js:1
(anonymous) @ app.104bdb.js:1
n @ (index):633
(anonymous) @ app.104bdb.js:1
```

### Versions

mac catalina 10.15.7

**Comment by retlehs** [comment]
:+1: thanks for the report! this is resolved in the upcoming bud release

**Comment by retlehs** [comment]
fixed as of bud v5.1.0 (#2952) with the latest acorn (#2953)

**Comment by flmuel** [comment]
@retlehs Hey :)
I think I have the same problem with the latest Sage and Bud version.
I dynamically export React components like so:
```js
export default {
  Button: async () => await import(/* webpackChunkName: "Button" */ './index'),
}
```
and register it via React Habitat (https://github.com/DeloitteDigitalAPAC/react-habitat). Loading the chunks also works "out-of-the-box" on Dev. On Production, like here in the ticket, I have the problem that the files are always loaded from the current URL path.

The "setPublicPath" method defined in the commits is deprecated and also does not give a desired result.

It would be awesome if you could finally help me out here....

PS: React Habitat is a very nice framework for rendering React components partially on your website

**Comment by retlehs** [comment]
@flmuel could you please either post on roots discourse for support or file a new bug report with a reduced test case/a repo that we can look at?
