### ISSUE TITLE
Bug: Problem with minify images - infinity loop

### ISSUE THREAD

**Issue by grzesiek1owline** [roots/sage#2955]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

**I use ZORIN OS (Debian -> Ubuntu -> ZORIN)
NODE 16.13.1**

#### What's wrong?

I tested Sage10 today. I download latest version form main branch.
I have two questions and one issue.

**Question 1:**
How to config now some tools example `@svg` directive or acf defaults? I must create config directory?

**Question 2:**
How to config  `wp_enqueue_script` now? Example code which i used od sage 10 beta versions:
```
    if (JQUERY) {
        wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), ['jquery'], null, true);
    } else {
        wp_dequeue_script('jquery');
        wp_enqueue_script('sage/vendor.js', asset('scripts/vendor.js')->uri(), array(), null, true);
    }
```
How now i can do this?

-------------------------------------------------------------------------------------------------------------

**Problem 1**
I wanted to change the theme of my current website to the Sage10 theme.
I added many images (100+) to resource/images and now command `npm run dev` doesnt work correctly.
A loop appears while BUD optimizes the images all the time.

Example:
https://gifyu.com/image/Sb8tF

If I have 5 images is the same error.
When i have 0 images everything is ok.

#### What have you tried?

I changed public path in bud.config.js from `/app/themes/theme_name/public/` to `/wp-content/themes/theme_name/public/` and add serve to bud config.

### Steps To Reproduce

1. Download Sage 10 beta-4
2. composer install
3. copy many images to resources/images
4.  yarn build / npm run build
5. yarn dev / npm run dev

### Expected Behavior

Optimize and copy images to public path

### Actual Behavior

Infiinity Loop

### Versions

10.0.0-beta.4

**Comment by retlehs** [comment]
the new bundle function hasn't been documented fully yet, but take a look at the source along with https://discourse.roots.io/t/using-ajax-wp-localize-script-with-roots-bundle-in-sage-10/21762/3 / https://github.com/roots/docs/issues/319

> I added many images (100+) to resource/images and now command npm run dev doesnt work correctly.
> A loop appears while BUD optimizes the images all the time.

weird, bud shouldn't be optimizing images out of the box :eyes: you mentioned you're on beta 4, but beta 3 isn't even released yet

can you please post on https://discourse.roots.io/ for support, or do a proper bug report on the bud repo? github issues aren't for support or questions - just bug reports
