### ISSUE TITLE
Bug: Missing `i18n` tasks/scripts

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2957]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
The `i18n` related tasks/scripts are missing.

#### What have you tried?
I tried to invoke the `i18n` related tasks/scripts (e.g. `yarn translate:pot`), but the tasks/scripts weren't found.
I also looked for them in the `package.json` and searched for a similar functionality in the new build tool (`bud`) that may replace it. Also searched for these `i18n` related tasks/scripts in the Sage 10 repository.

#### What insights have you gained?
The `i18n` related tasks/scripts were removed by this still recent PR: 
https://github.com/roots/sage/pull/2643/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L20-L22

#### Possible solutions
Re-add the `i18n` related tasks/scripts.
Add the `i18n` functionality to `bud` (only if this really would make sense).

#### Temporary workarounds
Manually copy and re-add these `i18n` related tasks/scripts from the commit prior to the PR that removed these tasks/scripts.
```json
{
  [...]
  "scripts": {
    [...]
    "translate": "npm run translate:pot && npm run translate:js",
    "translate:pot": "wp i18n make-pot . ./resources/lang/sage.pot --ignore-domain --include=\"app,resources\"",
    "translate:js": "wp i18n make-json ./resources/lang --pretty-print"
  },
  [...]
}
````

### Steps To Reproduce

1. Create a Sage 10 theme from latest commit.
2. Install all dependencies.
3. Invoke the `i18n` related tasks/scripts, e.g. `yarn translate:pot` or `npm run translate:pot`.
Note that the tasks/scripts don't exist.
Optionally inspect the `package.json` `scripts` field.

### Expected Behavior

The `i18n` related tasks/scripts can be invoked to generate `POT`/`MO` files.

### Actual Behavior

The `i18n` related tasks/scripts don't exist (anymore).

### Relevant Log Output

```shell
yarn translate:pot
yarn run v1.22.17
error Command "translate:pot" not found.
```

### Versions

WSL 2 (Ubuntu 20.04.3 LTS on Windows 10 x64)

**Comment by retlehs** [comment]
:+1: those scripts were accidentally removed when bud was merged

a PR would be appreciated to get those re-added! 

ref #2672

**Comment by strarsis** [comment]
@retlehs: https://github.com/roots/sage/pull/2958
