### ISSUE TITLE
[Sage 10] Bug: Primary sidebar not displayed

### ISSUE THREAD

**Issue by strarsis** [roots/sage#2960]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
The primary sidebar isn't rendered on any page.
Sidebar section part (currently in `index.blade.php`):
```blade.php
@section('sidebar')
  @include('sections.sidebar')
@endsection
````

#### What have you tried?
- Ensuring the primary sidebar widget area indeed contains widgets.
- Adding something to the sidebar section itself.
- Clearing the acorn cache (`wp acorn optimize:clear`).

#### What insights have you gained?
The sidebar section never appears in the markup.
Moving the sidebar section part from `index.blade.php` over to `page.blade.php` finally resulted in it being shown.

#### Possible solutions
Move the sidebar section part from `index.blade.php` to `page.blade.php` would make the sidebar appear on all pages.
However, I am not sure whether this fixes an issue I introduced into the theme by modifying it or by some strange Gutenberg/widget constellation.

#### Temporary workarounds
Move sidebar section part from `index.blade.php` over to `page.blade.php`.

### Steps To Reproduce

1. Create a Sage 10 project (latest commit) (`composer create-project roots/sage sage10 dev-main`).
2. Ensure all theme build + runtime dependencies are installed (`yarn install`; `composer install` if necessary).
3. Build the theme to prevent any issues (`yarn build`).
4. Activate the theme.
5. Ensure the primary sidebar widget area contains something.
6. Open frontend, check front-page and other pages. Note that the primary sidebar doesn't appear in the markup of any page.

### Expected Behavior

Primary sidebar is shown on all pages.

### Actual Behavior

Primary sidebar isn't shown on any page.

### Versions

Remove `config` and `bootstrap` directories ([#2839](https://github.com/roots/sage/pull/2839))

**Comment by retlehs** [comment]
hey @strarsis this is intentional - the sidebar is included for posts out of the box but not for pages

if you'd like to add support for the sidebar on pages, add it directly to your theme w/ whatever conditionals etc. you'd need
