### ISSUE TITLE
[Sage 10]: Partial incompatibility with Elementor

### ISSUE THREAD

**Issue by FelipeVa** [roots/sage#2965]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Recently, I noticed that there’s maybe an incompatibility with Elementor/Pro when I use sage 10. If I go to _Dashboard → Templates → Theme Builder_, it’ll throw a blank page with the next text: `* Error: Undefined array key "data"*.`

I already contacted Elementor support, and they told me to switch themes. When I switched to the default one, the error just disappeared. I thought possibly was my theme, so, I installed fresh Sage 10 theme, then the problem appeared again.

#### What have you tried?
I tried re-installed Elementor, and rollback their versions, but nothing worked.
#### Possible solutions
None.
#### Temporary workarounds
Using a different theme.

### Steps To Reproduce

1. Set up a local dev env using roots or a default WordPress installation.
2. Install Elementor
3. Install a new instance of Sage 10
4. Go to _Dashboard → Templates → Theme Builder_

### Expected Behavior

Display an Elementor builder that allows you to create custom templates for archives, pages, etc...

### Actual Behavior

Throws a blank screen with the following message: `* Error: Undefined array key "data"*.`

### Versions

HEAD, macOS Monterrey 12.1

**Comment by holaontiveros** [comment]
Where you able to figure something out? just run into the same issue and tried a few things but I wasn't able to pin point anything wrong.

For testing purposes I tried:

* Remove composers
* dd() on the index.php, app.blade.php
* Add something to the body class from functions

Nothing in the theme appears to be affecting the loading of the theme build view, but something on it breaks the load.

**Comment by FelipeVa** [comment]
@holaontiveros it's an error related to Elementor plugin.

Go to the folder where your Elementor plugin is installed, and then to `core->common->modules->ajax`, then open `module.php` and go to the line **171**, and replace it with this:

```php
$results = call_user_func( $this->ajax_actions[ $action_data['action'] ]['callback'], $action_data['data'] ?? [], $this );
```

**Comment by Saggre** [comment]
@holaontiveros @FelipeVa This can also be "solved" by disabling Acorn's error handler:

`add_filter('acorn/throw_error_exception', '__return_false');`
