### ISSUE TITLE
Feature Request: Disable error logging completly

### ISSUE THREAD

**Issue by simplenotezy** [roots/sage#2982]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

I'd like to know how we can disable the error logging functionality completely - no errors are sent to Sentry.io logging service, and I suspect it's the custom error handler logic implemented. Using 2.0.0-alpha.0.

https://discourse.roots.io/t/disable-error-logging-feature-completly/22099

#### Why are we doing this?
Because error logging requirements should be up to the developer

#### What use cases does it support?
More flexibility for the developers

#### What is the expected outcome?
Better error handling

**Comment by Log1x** [comment]
You can do this by dumping Acorn config via the [directory structure docs](https://docs.roots.io/acorn/2.x/directory-structure/#wp-cli-commands) and setting `debug` to `false` in `config/app.php`
