### ISSUE TITLE
wp_login_form() with localhost:3000

### ISSUE THREAD

**Issue by aksld** [roots/sage#3001]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

I'm using simple `wp_login_form()` without args.
When submitting the form, i'm redirected to the proxy URL.

#### What have you tried?

Test the form in fresh install.

### Steps To Reproduce

1. Use wp_login_form()
2. Submit the form with real credentials.

### Expected Behavior

After submission I would like to stay on the URL localhost:3000 because otherwise it is impossible to be considered as a user connected to localhost.

### Actual Behavior

Redirected to the proxy URL.

### Versions

Last

**Comment by retlehs** [comment]
are you using a VM for local dev? is this the same as https://github.com/roots/docs/issues/383#issuecomment-1061177942? it's a bud issue that i moved into the docs repo for now, because i believe this is just a server configuration issue with your local dev env

**Comment by aksld** [comment]
I think you're right.
Maybe I need to add something to my lando conf but i don't know what.

In my bud config, i have :

`.proxy('http://myproject.lndo.site')`

But this is not the place for that. if by chance someone has info for lando with sage 10 :)

**Comment by retlehs** [comment]
should be resolved with newer versions of bud
