### ISSUE TITLE
"align-wide" theme feature not working

### ISSUE THREAD

**Issue by finex** [roots/sage#3007]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
**alignwide** and **alignfull** are not shown.

#### What have you tried?
I've debugged until ```block-editor.php``` where the variable seems to be correctly set.

#### What insights have you gained?
Nothing useful.

### Steps To Reproduce

1) Install Wordpress
2) Create a new Sage (10.x) theme following the default documentation
3) Create a post/page and look at the image alignment options: wide and full size are missing even if ```add_theme_support('align-wide');``` is enabled on ```setup.php``` file.

### Expected Behavior

**alignwide** and **alignfull** should be visible.

### Actual Behavior

**alignwide** and **alignfull** are not shown.

### Versions

10.1.1

**Comment by alwaysblank** [comment]
Do you see the expected behavior if you switch to a different theme, i.e. Twenty Twenty-One?

**Comment by retlehs** [comment]
thanks for the report! see #3008 - you'll have to configure this setting in `theme.json` now

**Comment by finex** [comment]
Thank you, I've just come back to github just to say that (I've discovered by my own)... but it looks a known bug. The ```setup.php``` and the docs should be updated.
