### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fabianwurk** [roots/sage#3014]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

I'm yarn installing the following javascript carousel package from: https://pawelgrzybek.github.io/siema/#installation and its failing if include is placed in any other view above **app.blade.php** eg. **content-page.blade.php**

I have also tried this with a different javascript package called embla carousel: https://www.embla-carousel.com/get-started/module/ - and similar thing happens when @include is placed anywhere above app.blade. 

I have tried with fresh install of bud sage this morning and also bedrock with acorn installed. 

### Steps To Reproduce

Install javascript carousel package from: https://pawelgrzybek.github.io/siema/#installation and my **app.js** is as follows. 

```
import {domReady} from '@roots/sage/client';
import Siema from 'siema';

/**
 * app.main
 */
const main = async (err) => {
  if (err) {
    // handle hmr errors
    console.error(err);
  }
};

// fire up Siema Carousel
const mySiema = new Siema({
  selector: '.siema',
});
```

All installs correctly, and if I add the blade include ...

`@include('partials.sliders.siema')`

```
<div class="siema">
  <div>Hi, I'm slide 1</div>
  <div>Hi, I'm slide 2</div>
  <div>Hi, I'm slide 3</div>
</div>
```

to **app.blade.php**: 

```
@include('sections.header')

  <main id="main" class="main">
    @yield('content')
  </main>

  @include('partials.sliders.siema')

  @hasSection('sidebar')
    <aside class="sidebar">
      @yield('sidebar')
    </aside>
  @endif

@include('sections.footer')
```

the carousel works as expected with no issues or errors. 

But if I try to move the blade include into any other view eg.

partials > **content-page.blade**:

```
@php(the_content())

@include('partials.sliders.siema')

{!! wp_link_pages(['echo' => 0, 'before' => '<nav class="page-nav"><p>' . __('Pages:', 'sage'), 'after' => '</p></nav>']) !!}
```
then it stops working and throws an error in console:

`Uncaught Error: Something wrong with your selector 😭`

### Expected Behavior

Carousel should load as its does if loaded into app.blade.php view. Any other view above app.blade doesn't work and throws console error.

### Actual Behavior

Carousel doesn't work and throws console error if include is place anywhere above app.blade.php:

`Uncaught Error: Something wrong with your selector 😭`

### Relevant Log Output

```shell
app.b4cc08.js:1 Uncaught Error: Something wrong with your selector 😭
    at new e (app.b4cc08.js:1:2010)
    at Object.683 (app.b4cc08.js:1:535)
    at t ((index):615:134)
    at t (app.b4cc08.js:1:13546)
    at app.b4cc08.js:1:13556
    at n ((index):615:1038)
    at app.b4cc08.js:1:51
e @ app.b4cc08.js:1
683 @ app.b4cc08.js:1
t @ (index):615
t @ app.b4cc08.js:1
(anonymous) @ app.b4cc08.js:1
n @ (index):615
(anonymous) @ app.b4cc08.js:1
```

### Versions

Sage 10.1.2. Bedrock 1.19.2. MacOS BigSur 11.6.2

**Comment by retlehs** [comment]
hi @fabianwurk 👋  

i'm not seeing a bug in sage based on this report, which looks like a support request. per our guidelines, please only use this issue tracker to report bugs in sage

come visit us at https://discourse.roots.io/ for support or questions
