### ISSUE TITLE
Bug: unregisterBlockStyle not working

### ISSUE THREAD

**Issue by peXed** [roots/sage#3030]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
unregisterBlockStyle seems to not work in the current version of sage.

#### What have you tried?
remove some block styles as shown in the editor.js.

### Steps To Reproduce

Use the following code in the editor.js

```
import {domReady} from '@roots/sage/client';
import {registerBlockStyle, unregisterBlockStyle} from '@wordpress/blocks';


/**
 * editor.main
 */
const main = (err) => {
  if (err) {
    // handle hmr errors
    console.error(err);
  }

  unregisterBlockStyle('core/button', 'outline');

  unregisterBlockStyle('core/separator', 'wide');
  unregisterBlockStyle('core/separator', 'dots');

};

/**
 * Initialize
 *
 * @see https://webpack.js.org/api/hot-module-replacement
 */
domReady(main);
import.meta.webpackHot?.accept(main);
```

### Expected Behavior

It should remove the outline style from the buttons and the wide and dots style from the separator.

### Actual Behavior

Alle three block styles are still show in the editor.

### Versions

10.1.6

**Comment by letsbuildafire** [comment]
Seems to perhaps be a race issue with the built in block scripts, I don't think it's specifically an issue with acorn/bud/sage. https://github.com/WordPress/gutenberg/issues/40202

Tried updating `setup.php` as per the suggestion there, but no luck.
```php
add_action(
    'enqueue_block_editor_assets',
    function () {
        bundle('editor')->enqueueCss('all', ['wp-edit-blocks']);
        bundle('editor')->enqueueJs(true, [
            'wp-blocks',
            'wp-i18n',
            'wp-element',
            'wp-components',
            'wp-editor',
            'wp-dom-ready',
            'wp-edit-post'
        ]);
    },
    100
);
```

So I tried a using a timeout like mentioned higher in that issue in `editor.js` which correctly unregistered the built-in styles.
```js
setTimeout(() => {
  unregisterBlockStyle('core/button', ['default', 'fill', 'outline']);
}, 100);
```

**Comment by letsbuildafire** [comment]
I did also try modifying `domReady` provided by `@roots/sage/client` to closer mimic the Wordpress function like so
```ts
const domReady: domReady = onReady => {
  window.requestAnimationFrame(function check() {
    document.readyState === 'complete' || document.readyState === 'interactive'
      ? onReady()
      : window.requestAnimationFrame(check);
  });
};
```

which also seems to work without any timeouts
```js
domReady((error) => {
  if (error) {
    // handle hmr errors
    console.error(error);
  }

  registerBlockStyle('core/button', {
    name: 'primary',
    label: __('Primary', 'sage'),
    isDefault: true,
  });

  unregisterBlockStyle('core/button', ['default', 'fill', 'outline']);
});
```

**Comment by oxyc** [comment]
You can also use:

```js
window._wpLoadBlockEditor.then(() => {
  unregisterBlockStyle(...);
});
```

**Comment by EHLOVader** [comment]
I was able to call `wp.domReady` to make this work. 

Was there a reason not to use the WordPress provided `domReady` or was there a significant difference in their function? 

```js
wp.domReady(function() {unregisterBlockStyle('core/button', 'outline')});
```

**Comment by unscripted** [comment]
I experienced the same issue. Using the example @peXed shared, changing `domReady(main);` to `wp.domReady(main);` resolved this issue for me.
