### ISSUE TITLE
Feature Request: Override plugin file in sage wordpress

### ISSUE THREAD

**Issue by ahmedmymail** [roots/sage#3038]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

I am trying to override plugin file located in path/filename.html.php by sage theme ,

I have moved the file under themedirectory/path/filename.html.php but that did not show anything The sage version used is 10

DO anyone has an idea about that? Thanks

**Comment by retlehs** [comment]
hi there, please make a topic on https://discourse.roots.io/ with some more details for support
