### ISSUE TITLE
Bug: issue installing blade-icons on staging

### ISSUE THREAD

**Issue by nikitasol** [roots/sage#3085]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Installing balde-icons breaks staging env

#### What have you tried?
Reinstalling acorn, reprovision, redploying, reinstalling blade-icons

### Steps To Reproduce

1. Follow steps to install blade-icons as per sage docs (I installed inside bedrock where Acorn (2.1.2) is installed) -> provision staging (local and staging are both on php 8.1 in case it's relevant)
1. Provision fails (log attached)
1. SSH into staging try manual composer install -> breaks env until blade-icons are removed

### Expected Behavior

As on local with no issues

### Actual Behavior

Staging gets broken with no possibility to redeploy or wp @staging acorn commands until blade-icons are removed.

### Relevant Log Output

```shell
Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read any of the environment file(s) at [/srv/www/the-test.com/releases/20220908144855/.env]. in /srv/www/the-test.com/releases/20220908144855/vendor/vlucas/phpdotenv/src/Store/FileStore.php:68
Stack trace:
#0 /srv/www/the-test.com/releases/20220908144855/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Store\FileStore->read()
#1 /srv/www/the-test.com/releases/20220908144855/config/application.php(38): Dotenv\Dotenv->load()
#2 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277) : eval()'d code(7): require_once('/srv/www/the-te...')
#3 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277): eval()
#4 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1235): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#7 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#8 phar:///usr/bin/wp/php/boot-phar.php(11): include('phar:///usr/bin...')
#9 /usr/bin/wp(4): include('phar:///usr/bin...')
#10 {main}
  thrown in /srv/www/the-test.com/releases/20220908144855/vendor/vlucas/phpdotenv/src/Store/FileStore.php on line 68
```

### Versions

10.2.0

**Comment by retlehs** [comment]
Howdy! This issue tracker is meant for bug reports and not support requests. Please head on over to https://discourse.roots.io/ and make a topic for support.

FWIW, we have no issues using the `blade-icons` package on any environment, including https://roots.io/
