### ISSUE TITLE
Bug: Tailwind text size class not working when `theme.json` generation is enabled

### ISSUE THREAD

**Issue by kukac7** [roots/sage#3092]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

ignored talwindcss font-size classes.

### Steps To Reproduce

install latest sage.
i write the `text-2xl`.
build.
no class is generated.

### Expected Behavior

bigger text.

### Actual Behavior

nothing, no `text-2xl` class.

### Versions

sage 10.3.0
node 18.7.0
npm 8.19.1

edit:

if i commented the `theme.json` generals from the `bud.config.mjs` file, it will be fine.

**Comment by retlehs** [comment]
Confirmed this is a bug, thank you for the report!

**Comment by retlehs** [comment]
The `theme.json` generator is generating invalid CSS right now:

```css
.text-2xl font-size{line-height:2rem}
```

We'll get this fixed in Bud and push out a new release soon

**Comment by retlehs** [comment]
This is fixed with Bud v6.4.5

https://github.com/roots/bud/releases/tag/v6.4.5

I’ll get it bumped and put out a new Sage release tomorrow
