### ISSUE TITLE
Bug: "Removing Tailwind CSS" gives build error

### ISSUE THREAD

**Issue by maximilliangeorge** [roots/sage#3113]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

I've followed the steps under [Removing Tailwind CSS](https://roots.io/sage/docs/css-frameworks/) to remove Tailwind and use vanilla CSS.

However, upon completing the steps my build fails with `Cannot read properties of undefined (reading 'config')`. The documentation is likely out of date.

#### What have you tried?

It should be noted that I am using npm and not yarn. In the first step I used `npm uninstall @roots/bud-tailwindcss` instead of `yarn remove @roots/bud-tailwindcss`. Other than that, I've done what the guide says.

#### What insights have you gained?

None.

#### Possible solutions

None.

#### Temporary workarounds

None.

### Steps To Reproduce

1. Create a fresh sage theme using compose.
1. Install and activate Acorn using as a Wordpress plugin.
1. Build theme, verify that CSS compilation works as expected.
2. Remove Tailwind as per the guide linked above.
3. Try to rebuild, get the error.

### Expected Behavior

Should compile successfully without Tailwind after removing Tailwind as per the guide.

### Actual Behavior

Build fails with `Cannot read properties of undefined (reading 'config')`

### Relevant Log Output

```shell
✘  sage ./public [355b60293243b6655eb2]
│
├─ ✘ error
│  Cannot read properties of undefined (reading 'config')
│
│
├─ ✘ error
│  Cannot read properties of undefined (reading 'config')
│
│
├─ entrypoints
│ ├─ app
│ │ ├─ js/runtime.06fab3.js     1.05 kB
│ │ ├─ js/259.7edc5d.js       314 bytes
│ │ └─ js/app.ccc03f.js         6.63 kB
│ └─ editor
│   ├─ js/runtime.06fab3.js     1.05 kB
│   ├─ js/259.7edc5d.js       314 bytes
│   └─ js/editor.ab6756.js      6.74 kB
│
│
└─ compiled 12 modules in 425ms
```

### Versions

v10.4.0

**Comment by retlehs** [comment]
I'm unable to reproduce this following the steps from the docs

Please create a topic on https://discourse.roots.io/ if you'd like to try to get further support
