### ISSUE TITLE
Bug: Sage on windows does not map folders correct to blade templates

### ISSUE THREAD

**Issue by MonocodeJosePedro** [roots/sage#3118]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

When I add a View Composer for a page blade template in a subfolder pages, it does not get mapped and does not find the variables that should be passed.

Folder structure

├── app
│   ├── View
│   │   ├── Components
│   │   ├── Composers
│   │   │   ├── pages
│   │   │   │   ├── Test.php
├── resources
│   ├── views
│   │   ├── pages
│   │   │   ├── test.blade.php

#### What have you tried?

Changes both folder names and namespace to be "pages" instead of "Pages".

#### What insights have you gained?

This seems to only be a windows issue, as it works on Linux and MacOs.

#### Possible solutions

Not found one yet.

#### Temporary workarounds

Move the View Composer to View/Composers instead of View/Composers/Pages and move the page template to views instead of views/pages

### Steps To Reproduce

1. Setup sage project with version 10.3.1 on Windows 11
2. Add folder structure as provided and pass variable "buttonDTO".
3. Try and dump "buttonDTO" in test.blade.php

### Expected Behavior

That the template blade renders with the provided variables

### Actual Behavior

<img width="647" alt="image" src="https://user-images.githubusercontent.com/121229930/215492601-621fbf10-cc59-4a87-8c18-acfc95ca1a5d.png">

### Versions

10.3.1

**Comment by retlehs** [comment]
1. WSL is a requirement to use Sage on Windows 
2. You must follow PSR-4, see https://roots.io/sage/docs/composers/

Please use Roots Discourse for further support requests
