### ISSUE TITLE
❤️ Feature Request: static analysis of blade templates

### ISSUE THREAD

**Issue by chrillep** [roots/sage#3139]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

* analyse blade templates for errors. 
* add as composer script
* add to github workflow

refs:
* https://discourse.roots.io/t/feat-req-use-bladestan-for-linting-of-blade-templates/25461
* https://laravel-news.com/bladestan
* https://tomasvotruba.com/blog/introducing-bladestan-phpstan-analysis-of-blade-templates/
* https://github.com/tomasVotruba/bladestan

### Motivation
static analysis finds bugs you or linters dont

#### Why are we doing this?
need better code :)

#### What use cases does it support?
all templates

#### What is the expected outcome?
better code, less bugs

#### Potential conflicts / foreseeable issues
needs php 8.1

**Comment by eaCe** [comment]
That would be great. 
I tried to test bladestan, it seems like bladestan can't find or compile the blade files.
