### ISSUE TITLE
Hot reload not working (Redirecting to base URL when front page is set)

### ISSUE THREAD

**Issue by philippschmid** [roots/sage#3148]
### Version

10

### What did you expect to happen?

Since I mainly work on styles and layouts this is crucial to me. The expected behaviour is a page reload whenever I change a scss file, this does not work anymore once the Wordpress front page is set as a static page.

### What actually happens?

When attempting to open page in dev mode over port 3000, it will automatically redirect to base URL (localhost)
The page does not reload anymore. It has to be reloaded manually. 

### Steps to reproduce

Download and install sage 10 and set front page to a static page
Start dev mode via yarn dev

### System info

Docker, macOS Version 12.3 (21E230), happens also on Linux

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Head over to https://discourse.roots.io/ for support requests
