### ISSUE TITLE
Unable to use @import on css files

### ISSUE THREAD

**Issue by ThomasPof** [roots/sage#3151]
### Version

10.7.0

### What did you expect to happen?

I expect to be able to import other .css files in app.css or editor.css

### What actually happens?

Nothing is imported. No error in yarn console

### Steps to reproduce

- Install a fresh sage 10.7.0
- create a styles folder, for instance `common`. And create a file `typo.css` (or whatever)
- add some css rules in this file
- build with **yarn dev** or **yarn build**

Nothing in imported

### Please confirm this isn't a support request.

No

**Comment by retlehs** [comment]
1. Create `styles/example.css`
2. Edit `app.css`:

```css
@import "example.css";

@tailwind base;
@tailwind components;
@tailwind utilities;
```

Confirmed this is working ✅ 

Head on over to https://discourse.roots.io/ if you need further support
