### ISSUE TITLE
[sage 9] page-template not working on wordpress 6.4

### ISSUE THREAD

**Issue by patipan-off** [roots/sage#3158]
### Version

9.0.9

### What did you expect to happen?

[sage 9] template-custom not working on wordpress 6.4

### What actually happens?

![Screenshot 2566-11-13 at 23 08 25](https://github.com/roots/sage/assets/59647561/f8f7d081-0fa4-4874-9760-03109e3b6c37)

### Steps to reproduce

sage 9.0.9 with wordpress 6.4

### Please confirm this isn't a support request.

No

**Comment by ksholander** [comment]
I think this may be an issue with WP 6.4.x. Check out this thread: https://core.trac.wordpress.org/ticket/60025
