### ISSUE TITLE
Sage 9 + Wordpress 6.4 and 6.4.1 create broken Gutenberg layout

### ISSUE THREAD

**Issue by JoshuaVB** [roots/sage#3160]
### Version

9.0.9

### What did you expect to happen?

Normal gutenberg styles to appear

### What actually happens?

Broken gutenberg styles appear

![Screenshot 2023-11-29 003126](https://github.com/roots/sage/assets/8481960/2d39be84-72e0-4120-b88b-56c20195e022)

### Steps to reproduce

1. Have a Sage 9.0.9 theme active with WP Core 6.4 or 6.4.1 present
2. Go to any page or post and edit it via Gutenberg.

Reverting to WP Core 6.3.2 or lower fixes the issue.

### Please confirm this isn't a support request.

Yes

**Comment by andrewmarino** [comment]
Ran into the same issue, this fixed it in my case since my Sage 9 themes do not have a theme.json file in them.

```php
/**
 * Satisfy WP check for theme.json without this file being present.
 *
 * @since 6.3
 * @link https://github.com/roots/sage/issues/3143
 */
add_filter('theme_file_path', function ($path, $file) {
    if ($file === 'theme.json') {
        return false;
    }

    return $path;
}, 0, 2);
```

**Comment by JoshuaVB** [comment]
@andrewmarino Amazing, thank you so much! Added this to functions.php and it worked like a charm.

**Comment by josialoos** [comment]
works perfectly thanks so much ❤️️
