### ISSUE TITLE
Seems eslint --fix doesn't apply prettier changes

### ISSUE THREAD

**Issue by cawa-93** [roots/sage#3170]
### Version

10.7.0

### What did you expect to happen?

I applied the linters and formatting configuration to the project as specified in the [documentation](https://roots.io/sage/docs/adding-linting/#adding-eslint-prettier-and-stylelint).

However, I notice something strange. In the `.prettierrc:` is `"semi": true`. However, when I run the eslint` on `console.log('')`, it does not show errors in this place and does not correct the syntax. 

### What actually happens?

Eslint ignore semicolon rule. 

### Steps to reproduce

1. Clone Sage repo
2. Follow the [documentation](https://roots.io/sage/docs/adding-linting/#adding-eslint-prettier-and-stylelint) and add lintets into project.
3. Install `eslint` by `yarn add eslint -D`.
4. Open `resources/scripts/editor.js` and remove all semicolons.
5. Run lint `yarn run lint:js` 

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Please use https://discourse.roots.io/ for support requests

Also take a look at https://bud.js.org/extensions/bud-eslint if you're looking for the config for having ESLint fix errors
