### ISSUE TITLE
Tailwind logical properties classes does not work as expected

### ISSUE THREAD

**Issue by alaa-alshamy** [roots/sage#3191]
### Version

v10.8.2

### What did you expect to happen?

When I use for example `ms-1` css class, tailwind should use `margin-inline-start`, like following:

```
.ms-1 {
    margin-inline-start: 0.25rem;
}
```

### What actually happens?

It actullay use `margin-left`, like following:

```
.ms-1 {
    margin-left: 0.25rem;
}
```

### Steps to reproduce

Just create a new sage theme and use one of the logical properties classes for example `ms-1`, none of them working as expected

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Dupe https://github.com/roots/bud/issues/2597
