### ISSUE TITLE
Keep license comments in SCSS files

### ISSUE THREAD

**Issue by diego-betto** [roots/sage#3197]
### Version

6.20.0

### What did you expect to happen?

Keep license comments within SCSS/CSS files beginning with `/*!`.

### What actually happens?

Comments are removed

### Steps to reproduce

- Add a comment inside a SCSS file using `/*!` format
- Run `yarn build`

### System info

Ubuntu 24

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Please head over to Roots Discourse for support requests
