### ISSUE TITLE
style.css changes overidden by bootstrap.css? 

### ISSUE THREAD

**Issue by NickTomlin** [roots/sage#321]
Hi All, 

First off, roots rocks! I've been using 1140 starkers as a base theme (i'm a newbie WP designer, slowly getting into this framework stuff) but roots is an excellent alternative. 

My problem is this: 

I wanted to change the default font to Times New Roman for a client, but I'm not versed in the ways of LESS yet, so I added: 

```
body, p {
  font-family: TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif;
}
```

to: css/style.css 

Unfortunately, it seems that my styles are being overidden by bootstrap.css when I check things out in firefox. 

What is the easiest way to change the default font? Is there a way I can just use style.css, or do I need a crash course in LESS? 

Thanks,
Nick

**Comment by abhijitbcob** [comment]
> The styles are being overridden because styles.css is called BEFORE bootstrap.css, so bootstrap styles will override them, if they have the same specificity. (I agree that it might be a bit confusing, as the style.css has a space to put your styles. But I think this comes from the original HTML5 Boilerplate style file, which, in Roots, is now combined with bootstrap css...)
> 
> A simple solution would be to put your styles in **app.css**, which is called AFTER bootstrap.css. That's were wordpress specific styles reside.

thanks man
