### ISSUE TITLE
Gravity Forms Not Displaying When There's Conditional Logic

### ISSUE THREAD

**Issue by iChris** [roots/sage#324]
(First time posting on GitHub so forgive me if I'm doing something wrong or don't have enough information)

It seems that when I enable conditional logic in a a Gravity Forms, a display:none gets added to the form and isn't removed as it should be.

You can see the page where it doesn't load [here](http://yxe.ssktn.com/contact/)

[See this support article on Gravity Forms Support site for what I mean](http://www.gravityhelp.com/question/why-is-there-a-style-attribute-of-displaynone-being-added-my-form-isnt-showing-up/)

Roots is calling wp_footer so I know that's not the issue.

Thanks!

**Comment by Epic720** [comment]
Still having this issue as well. I removed the css attribute of display:none but there are further consequential issues with conditional login not working now.

**Comment by retlehs** [comment]
latest roots master? i'm assuming that jquery is in the footer when it should be in the header in this case. open up `lib/scripts.php` and [change last arg](https://github.com/roots/roots/blob/master/lib/scripts.php#L49) on the enqueue for jquery from `true` to `false`

if you still need help please post on our discourse.
