### ISSUE TITLE
<?php if( is_home() ) : ?> Conditionals Not Working

### ISSUE THREAD

**Issue by expertpixels** [roots/sage#435]
Hey all,

Sorry to post regarding this but i am trying to use some simple conditionals that work fine on other templates, but are not working with the roots theme.

These are the conditionals i am trying to use:

<?php if( is_home() ) : ?>

<?php if( is_front_page() ) : ?>

I mainly need the "is_home" to work.. I am guessing that the roots activation / cleanup process is effecting this somehow.. ive deleted the front-page.php file and am using the index.php / loop.php as my main template files..

Any help on this would be great.

Regards, Darren

**Comment by patforg** [comment]
I had the issue in the `page-header.php` template.

Issued a `wp_reset_query();` at the top of the file and it fixed the problem.  (hopefully won't cause other issues)
