### ISSUE TITLE
500 internal server error after activation

### ISSUE THREAD

**Issue by ncic** [roots/sage#475]
hi
i was trying to install roots theme and i pressed save changes in the activation dialog and now i can't access neither the admin or the site. i get the server error 500.
not sure whats happening but maybe it has something to do with my wp being installed in a subfolder. unfortunately I'm not so good with the code stuff, i was trying to learn by installing roots. can someone help me out?
site: http://narancicgrafika.com/ncic/
I'm using wordpress 3.4

thanks

**Comment by oscar-g** [comment]
Here is a line from the error log 

`[Wed Jan 06 09:42:22 2016] [error] [client (retracted)] PHP Parse error:  syntax error, unexpected '[' in /var/www/wordpress/wp-content/themes/sage-8.4.0/functions.php on line 12`
