### ISSUE TITLE
custom page templates missing from dropdown in WP 3.4.1

### ISSUE THREAD

**Issue by edanweis** [roots/sage#520]
Hi, 
My custom page templates do not appear in the Template dropdown list in WP 3.4.1. Eg: page-custom-test.php in the /roots folder with this at top:

<?php
/*
Template Name: Custom
*/
get_header(); ?>

I have logged in/out, switched themes, re-uploaded files, double-checked php files, nothing works. I cannot select custom pages. This seems to be a common problem http://wordpress.org/support/topic/custom-page-template-in-edit-page-dropdown-list) but none of these solutions work for me. Any further suggestions?

Edan

**Comment by alexkerber** [comment]
I got the same problem … template-custom.php is there but sometimes I'm loosing the option to select any template. I starts removing pages and change things and finally it's back but randomly it happens again :( Ideas?
