### ISSUE TITLE
Vertical menu using Twitter Bootstrap accordion

### ISSUE THREAD

**Issue by RobertBouten** [roots/sage#529]
Hi, sorry if I post this in the wrong place. Just started finding my way around here......

Recently I started using Twitter Bootstrap together with Wordpress. Now I would like to make an accordion menu using the collapse feature. Does the roots theme has some way of generating all the classes, data-toggle, id's etc needed for the twitter bootstrap accordion in wp_nav_menu or something??

**Comment by pointclear** [comment]
Thanks Foxaii. Much appreciated!
