### ISSUE TITLE
Header & Footer deprecated notice

### ISSUE THREAD

**Issue by Geczy** [roots/sage#610]
> Notice: Theme without header.php is <strong>deprecated</strong> since version 3.0 with no alternative available. Please include a header.php template in your theme.
> 
> Theme without footer.php is <strong>deprecated</strong> since version 3.0 with no alternative available. Please include a footer.php template in your theme.

Believe this is replicated by doing get_header()

**Comment by mtx-z** [comment]
I removed "notice" verbose level from output using a mu-plugin. 
Create `/wp-content/mu-plugins/verbose.php`

Containing: 
`error_reporting(E_ALL ^ E_NOTICE); //all except notice`

In `wp-config.php` add 
`error_reporting(E_ERROR | E_WARNING | E_PARSE); //report only error, warning, parse errors
`

Please also see my [Sage9-Woocommerce-Integration](https://github.com/mtx-z/Sage9-Woocommerce-Integration).
[Source](https://wordpress.stackexchange.com/questions/103040/control-verbosity-level-of-wp-debug) that have some useful links also.
