### ISSUE TITLE
wp_localize_script not working

### ISSUE THREAD

**Issue by robsonfgjunior** [roots/sage#965]
I want to pass variables to my javascript, so I'm trying to use wp_localize_script passing an object to 'roots_scripts', the name of the main script file minified js after grunt does its magic.

my code looks like this:

``` php
function pass_variables_to_javascript() {

     wp_localize_script(
        'roots_scripts', // The name of our minifed script file
        'my_javascript_object',
        array(
            'key1' => 'value 1',
            'key2' => 'value 2',
            'key3' => 'value 3'
        )
    );

}
add_action('wp_enqueue_scripts', 'pass_variables_to_javascript');
```

And my javascript looks like:

``` Javascript
jQuery(document).ready(function($){
    console.log(my_javascript_object);
}
```

But all I get is `Uncaught ReferenceError: my_javascript_object is not defined`

Am I doing something wrong?
Thanks in advance

**Comment by AzadRpi** [comment]
It helps me too..

Thanks a lot @Foxaii
